### ISSUE TITLE
config:set encloses values with apostrophes when using a Dockerfile

### ISSUE THREAD

**Issue by marcbachmann** [progrium/dokku#1002]
All string config values get enclosed by apostrophes.

e.g. `dokku config:set NODE_ENV=production`
Generates the config `export NODE_ENV='production'`
in the files `/home/dokku/app/ENV` and `/dokku/app/DOCKERFILE_ENV_FILE`

The problem only occurs when using a custom Dockerfile in the root directory of the pushed repo.

I believe setting environment variables like that won't work in docker:
`docker run -e NODE_ENV='production'`

They needs to be written as:
`docker run -e 'NODE_ENV=production'`

**Comment by mahnunchik** [comment]
I confirm this behavior.
All environment variables are enclosed by single quote.

dokku: master 70e1e5d14dc79907ae7b8afd28d6b88f5b7c7efd
Custom Dockerfile

**Comment by michaelshobbs** [comment]
Hrm. We have a test for this.... Are you seeing behavior in your app that would indicate these are not getting injected correctly?

**Comment by mahnunchik** [comment]
Yep!

I think simplest test will be:
```bash
dokku config:set TEST_VAR=foobar
```

```bash
#!/bin/bash

echo $TEST_VAR
```
expected: foobar
actual: 'foobar'

**Comment by josegonzalez** [comment]
@michaelshobbs are you testing a Dockerfile app in that test?

**Comment by michaelshobbs** [comment]
Yes but its naive. I'll sort it out.

https://github.com/progrium/dokku/blob/70e1e5d14dc79907ae7b8afd28d6b88f5b7c7efd/tests/unit/config.bats#L60-L66
