### ISSUE TITLE
Rails 4.1.9 deploy failed on dokku (ruby 2.2.0)

### ISSUE THREAD

**Issue by ProGM** [progrium/dokku#1007]
I'm trying to deploy my rails 4.1.9 application on dokku (on my vagrant local machine).
It seems like it fails to load ruby 2.2.0 buildpack from heroku:

```shell
$ git push dokku development:master
Counting objects: 14705, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (5737/5737), done.
Writing objects: 100% (14705/14705), 106.62 MiB | 14.83 MiB/s, done.
Total 14705 (delta 9709), reused 13094 (delta 8547)
-----> Cleaning up...
-----> Building rails from buildstep...
-----> Adding BUILD_ENV to build environment...
-----> Ruby app detected
-----> Compiling Ruby/Rails
       !
       !     An error occurred while installing Ruby ruby-2.2.0
       !     For supported Ruby versions see https://devcenter.heroku.com/articles/ruby-support#supported-runtimes
       !     Note: Only the most recent version of Ruby 2.1 is supported on Cedar-14
       !     Command: 'set -o pipefail; curl --fail --retry 3 --retry-delay 1 --connect-timeout 30 --max-time 30 https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/cedar-14/ruby-2.2.0.tgz -s -o - | tar zxf - ' failed unexpectedly:
       !
       !     gzip: stdin: invalid compressed data--crc error
       !
       !     gzip: stdin: invalid compressed data--length error
       !     tar: Unexpected EOF in archive
       !     tar: Unexpected EOF in archive
       !     tar: Error is not recoverable: exiting now
       !
To dokku@dokku.me:rails
 ! [remote rejected] development -> master (pre-receive hook declined)
error: failed to push some refs to 'dokku@dokku.me:rails'
```

**Comment by michaelshobbs** [comment]
How are you specifying your ruby version and which one are you requesting?

**Comment by ProGM** [comment]
My ruby version is specified in the Gemfile:

```ruby
source 'https://rubygems.org'

# Specify a particular version of Ruby
# (Ref.: https://devcenter.heroku.com/articles/ruby-versions#selecting-a-version-of-ruby)
ruby '2.2.0'

gem 'rails', '~> 4.1'
...
```
 I'm requesting 2.2.0.

**Comment by michaelshobbs** [comment]
Check out the troubleshooting docs and try to run the `curl` command without `tar` to verify you can download the ruby package. If you can, then try running the deploy again. Might just be transient.

**Comment by michaelshobbs** [comment]
Docs http://progrium.viewdocs.io/dokku/troubleshooting

**Comment by ProGM** [comment]
I tried to `curl` and it seems to work, then I tried to run:
```shell
$ curl https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/cedar-14/ruby-2.2.0.tgz -o ruby-2.2.0.tgz
$ tar tzf ruby-2.2.0.tgz
```

And it seems to work well.

The I tried:

```shell
$ curl --fail --retry 3 --retry-delay 1 --connect-timeout 30 --max-time 30 https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/cedar-14/ruby-2.2.0.tgz -s -o - | tar zxf - 
```

And I get:

```shell
tar: Skipping to next header

gzip: stdin: invalid compressed data--format violated
tar: Child died with signal 13
tar: Error is not recoverable: exiting now
```

**Comment by josegonzalez** [comment]
@ProGM how long did the initial curl command take? Maybe your time to download is longer than 30 seconds.

**Comment by michaelshobbs** [comment]
It's unclear really what is happening here. You may want to open an issue against the BUILDPACK repo itself.

**Comment by josegonzalez** [comment]
If you try omitting the `--max-time` option, what happens?

**Comment by michaelshobbs** [comment]
Ah yes. I completely missed the missing args in the first test.

**Comment by ProGM** [comment]
Removing `--max-time` it seems to work. Why there is such a parameter?

How can I remove it from building process?

**Comment by michaelshobbs** [comment]
I suppose to prevent deployments from hanging too long. I believe you can set CURL_TIMEOUT to something higher than 30 to control this curl command.

**Comment by josegonzalez** [comment]
I think the problem here may just be slow network. If you are having timeout issues, raise your `CURL_TIMEOUT` env var to however many seconds that request takes (maybe 120 seconds?) and then you might avoid the issue.
