### ISSUE TITLE
! [remote rejected] master -> master (pre-receive hook declined)

### ISSUE THREAD

**Issue by alfetopito** [progrium/dokku#1011]
As indicated by the [troubleshooting page](http://progrium.viewdocs.io/dokku/troubleshooting), here is the [gist](https://gist.github.com/alfetopito/8888693b3bc5ee442e8f).

Got this right after a regular push, which worked fine until now.

Running Ubuntu 14.04 x64 on AWS EC2 t2.micro instance.
Python 3.4.2 Dajngo app running a gunicorn instance, nothing more.

**Comment by michaelshobbs** [comment]
Hrm. The call to `git clone` failed.
https://gist.github.com/alfetopito/8888693b3bc5ee442e8f#file-dokku-trace-log-L555-L556

Disk space? Might try running that as the `dokku` user without `-q` to see the error.

@josegonzalez this brings up a common troubleshooting issue in that we silence a lot of useful output similar to this `git clone -q` case. it would be nice to route that to stderr and then collect that into a deployment log somewhere.....(i'm not entirely certain this is feasible with bash...)

**Comment by alfetopito** [comment]
@michaelshobbs So it seems.
Checked the file system and nothing unusual until I noticed that `/tmp` was full. 
I didnt want to manually clean it, so rebooted to see what would happen.
Turns out it worked.

But that is no permanent solution. Maybe the deploy script should clean up the /tmp afterwards?
Or maybe not. Usually I think it shouldn't be a problem, but in this AWS case there is little tmp space.

Anyway, I have a temporary fix, but I'll leave this open for you @michaelshobbs, @josegonzalez or whoever is responsible to decide.

**Comment by michaelshobbs** [comment]
It would be interesting to know what was filling up the space there. A t2.micro doesn't have much in the way of disk in the first place.

**Comment by josegonzalez** [comment]
We don't write to /tmp, so without knowing what the contents of it were, I can't really offer any advice.

@michaelshobbs I think we can route the output using something like [`chronic`](https://joeyh.name/code/moreutils/). Thoughts?

**Comment by michaelshobbs** [comment]
We do write to /tmp when we clone the git repo. I'll check out chronic again but I don't know about adding another dependency.

**Comment by josegonzalez** [comment]
hmmm. Don't think the deploy should do the clean up, since it can fail and then it wouldn't be cleaned up. Do we name the directories differently during each deploy? If so, we can delete old ones via a cron task.

**Comment by michaelshobbs** [comment]
I'm mobile right now but we should clean up after ourselves. Not sure if we are or not.

**Comment by michaelshobbs** [comment]
We clean up after ourselves in the git plugin. Just not when installing dokku. :cry: 

https://github.com/progrium/dokku/blob/53f9974f6f905de5ec99163cc691f2493e6048e3/Makefile#L74-L76

**Comment by josegonzalez** [comment]
I'm closing. I've never seen this issue in prod, so it makes me think something else was the issue. Don't know what was in your `/tmp` so no way of attempting to debug.

Please comment if you see this issue again.
