### ISSUE TITLE
Cannot create container with more than 127 parents

### ISSUE THREAD

**Issue by sebastiaandegeus** [progrium/dokku#1014]
When I try to rebuild an app I get this error: 
What does it mean and how to fix it?

```
time="2015-03-02T17:57:06+01:00" level="fatal" msg="Error response from daemon: Cannot create container with more than 127 parents"
```

**Comment by michaelshobbs** [comment]
Related to https://github.com/docker/docker/issues/7095

**Comment by sebastiaandegeus** [comment]
```
$ docker info
```

```
Containers: 5
Images: 259
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: <unknown>
 Dirs: 269
Execution Driver: native-0.2
Kernel Version: 3.13.0-44-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 2
Total Memory: 1.955 GiB
Name: dokku
ID: 7W27:4RHQ:LNUE:6MXS:6ZZP:EMMQ:G22C:AKHQ:JXZD:KSI4:T2K2:4NWP
WARNING: No swap limit support
```

**Comment by michaelshobbs** [comment]
I guess that didn't relate in the way I intended. I believe the current layer limit of aufs is 127.

**Comment by sebastiaandegeus** [comment]
What is the official way of handling this? 

Right now I cleaned it up by: ```docker rmi $(docker images -aq)``` But that generates so many errors:

```
Error response from daemon: Conflict, cannot delete f35aba9b44a2 because the running container 03f5e10a904c is using it, stop it and use -f to force
```

But it enables me to run the rebuild of an app again.

**Comment by michaelshobbs** [comment]
`dokku cleanup` would sort out the removal of dependent containers and subsequent images. If give that a try. Honestly I haven't run into this yet.

**Comment by sebastiaandegeus** [comment]
Would it be best practice to run  `dokku cleanup` in a cron?

**Comment by michaelshobbs** [comment]
I don't think so? It gets run prior to every deployment. Perhaps we could run it prior to rebuild. For clarity, what command are you running to rebuild your app(s)?

**Comment by vincentfretin** [comment]
A image uses less than 20 layers generally. Each time you use dokku config:set which calls dokku deploy, it creates a new layer in your image. If you do that more than 100 times, then you can get to the 127 layers limit. In this case, you need to rebuild your application to go below 20. You can see the layers with "docker images --tree"
Executing dokku cleanup will not resolve your problem here.

**Comment by sebastiaandegeus** [comment]
Interesting. 

To rebuild an app we run `dokku rebuild my_app_name`

@vincentfretin  We have multiple apps running on the system so it could be possible that we ran the `dokku config:set` command a lot of times. 

Are we supposed to run `dokku rebuild my_app_name` every time after `dokku config:set`?

**Comment by vincentfretin** [comment]
@sebastiaandegeus I meant "dokku config:set myapp" will add a layer only for your dokku/myapp image, so the fact you have multiple apps is not an issue.

> Are we supposed to run dokku rebuild my_app_name every time after dokku config:set?
No

Do you use buildpacks or a Dockerfile?
What "docker images --tree" gives you? You should normally see if your image has lots of layers.

**Comment by sebastiaandegeus** [comment]
I know but we probably ran the config:set command multiple times per app without doing a push after.

We have apps running the standard `ruby on rails` buildpack and apps that run the heroku php buildpack (wordpress).

I cannot access the network right now so I will check `docker images --tree` tomorrow.

**Comment by sebastiaandegeus** [comment]
The gist of the result:
https://gist.github.com/sebastiaandegeus/cc0b46fede008c071081

**Comment by vincentfretin** [comment]
Wahou, your dokku/vakmedianet-missethoreca-rails:latest image has really lots of layer, but your progrium/buildstep:latest is even worse. What did you do with your progrium/buildstep:latest image?
To see the details of each layer to investigate which files create a new layer:
docker history --no-trunc progrium/buildstep:latest

If you have some sort of script to do an apt-get upgrade of your buildstep image, don't do it, best to rebuild your image completely.

**Comment by vincentfretin** [comment]
If you do 
docker pull progrium/buildstep:latest
to retrieve the latest progrium/buildstep:latest from Docker Hub
this should fix your error, but you should investigate why your image is like this. The progrium/buildstep:latest should actually never change. You just rebuild it from time to time, or do a pull to have security patches, that's all.

**Comment by sebastiaandegeus** [comment]
`docker history --no-trunc progrium/buildstep:latest`
https://gist.github.com/sebastiaandegeus/d8f54f83a27d6d162550

`docker history --no-trunc progrium/buildstep:latest`
https://gist.github.com/sebastiaandegeus/59b54caa7f54ef73883b

**Comment by vincentfretin** [comment]
There is some weird things about supervisord, do you use a specific dokku plugin?

**Comment by sebastiaandegeus** [comment]
I have a suspicion it is related to puppet somehow. I think it's either puppet or a cron. Something that comes around again and again.

`dokku`
https://gist.github.com/sebastiaandegeus/e55bcf8f416b2e6c6779

**Comment by sebastiaandegeus** [comment]
My colleague told me about supervisord. It's used as an alternative to upstart on the server. To keep everything in the Procfile running. Maybe that causes to creation of endless layers?

**Comment by sebastiaandegeus** [comment]
Apparently we use this plugin: https://github.com/statianzo/dokku-supervisord

**Comment by vincentfretin** [comment]
Well, look no further, this plugin is your problem. https://github.com/statianzo/dokku-supervisord/blob/master/post-release I shouldn't do all that in a post-release hook, but probably better in a post-build-buildstep hook with latest dokku version or post-build if you have an older version.
Try to rename post-release to post-build-buildstep in your /var/lib/dokku/plugins/dokku-supervisord directory. Please contact the maintainer of the plugin, create an issue or PR there.

**Comment by sebastiaandegeus** [comment]
An update on this. I changed the `post-release` to `post-build-buildstep` but that didn't really solve our problem. 

`docker history progrium/buildstep:latest`
https://gist.github.com/sebastiaandegeus/c302d18a704fd8a01cb5 

We still need to investigate more why this is run every 5 minutes.

**Comment by josegonzalez** [comment]
Cron?

**Comment by michaelshobbs** [comment]
Wow! @sebastiaandegeus something is definitely not right there.

**Comment by sebastiaandegeus** [comment]
There are no crontabs. `/var/spool/cron/crontabs` is empty. 

I have some more investigation to do. I'm thinking puppet, automatic updates or the dokku-supervisord plugin. I will do some testing to figure out what is causing it.

**Comment by michaelshobbs** [comment]
Maybe sudo logs could help?

**Comment by vincentfretin** [comment]
I think this is it:
https://github.com/statianzo/dokku-supervisord/blob/41300fefe35bfd97b0fd8a067984a19caa98989a/install
Do you have a cron with "dokku plugin-install" or a "make install" from a dokku git repo?

And FYI, apt-get clean is useless because apt-get is already configured to clean the download packages. You should use "rm -rf /var/lib/apt/lists/*" instead of apt-get clean 
here https://github.com/statianzo/dokku-supervisord/blob/41300fefe35bfd97b0fd8a067984a19caa98989a/install#L6 and here https://github.com/statianzo/dokku-supervisord/blob/41300fefe35bfd97b0fd8a067984a19caa98989a/post-release#L72

This is the /var/lib/apt/lists/* files that takes 10Mo on a layer each time.

cc @statianzo the author of the plugin. You should rename the file post-release to post-build-buildstep, see discussion above.

**Comment by sebastiaandegeus** [comment]
There is no cron. 

Right now I'm 99% sure the problem is the `dokku-supervisord` plugin. 

I will remove it for now and keep monitoring our dokku server.

**Comment by statianzo** [comment]
Pushed v0.4.0 of dokku-supervisord with the pluginhook rename.

**Comment by sebastiaandegeus** [comment]
@statianzo Renaming the hook did not solve the problems for us. So maybe it needs some more reviewing.

**Comment by statianzo** [comment]
Switched to doing `rm -rf /var/lib/apt/lists/*` as @vincentfretin suggested.

**Comment by michaelshobbs** [comment]
It seems like there isn't anything for dokku to do here. Please feel free to re-open if there is disagreement.

**Comment by sebastiaandegeus** [comment]
Agreed.

**Comment by statianzo** [comment]
If you find that it does link back to the supervisord plugin, open an issue there.
