### ISSUE TITLE
Dokku won't start apps on reboot

### ISSUE THREAD

**Issue by dubcanada** [progrium/dokku#1015]
Hello

My Dokku doesn't seem to be restarting apps on reboot. If I modify the dokku-redeploy.conf in the /etc/init to read

    description "Dokku app redeploy service"

    start on filesystem and started docker # <-- CHANGE THIS LINE

    script
      sleep 2 # give docker some time
      sudo -i -u dokku /usr/local/bin/dokku ps:restartall
    end script

Everything works fine. But the original `start on (started docker)` doesn't seem to work for me. I am on EC2, not sure if that matters or not.

**Comment by josegonzalez** [comment]
What operating system are you on?

**Comment by dubcanada** [comment]
Ubuntu 14.04.2 LTS

**Comment by michaelshobbs** [comment]
Should we expect a PR making this change? Not sure where we landed here...

**Comment by dubcanada** [comment]
Also don't know, maybe it's just me? Or maybe it is everyone. On my servers, this is the case.

**Comment by josegonzalez** [comment]
Is there any output in syslog with the existing setup?

I'm okay with making this a pr. Can you dig up some some docs or an example showing your version to be the case? I just want external confirmation.

**Comment by marvinroger** [comment]
The [Docker docs](https://docs.docker.com/articles/host_integration/) shows `start on filesystem and started docker` for upstart.
