### ISSUE TITLE
Installation on EC2 Ubuntu 14.04 is completely broken

### ISSUE THREAD

**Issue by Suor** [progrium/dokku#1016]
I started by doing this twice (why the heck twice?):
```bash
wget -qO- https://raw.github.com/progrium/dokku/v0.3.15/bootstrap.sh | sudo DOKKU_TAG=v0.3.15 bash
```
Then tried `cd /root/dokku && make dokku-installer` and, first, it's obviously permission denied and, second, there is no such dir as `/root/dokku/`. There is, however, `/home/ubuntu/dokku`, so I guessed it I should have installed it as a root user so I did:
```bash
sudo su
wget -qO- https://raw.github.com/progrium/dokku/v0.3.15/bootstrap.sh | sudo DOKKU_TAG=v0.3.15 bash
cd /root/dokku && make dokku-installer
```

It worked, I went to installer page. Where I can see public key, instance ip in HOSTNAME field and a phrase "Your app URLs will look like: http://52....1:<app-port>", which doesn't correlates with anything in the docs, they say only about subdomains, not ports. I clicked "Finish Setup" anyway and added remote:
```bash
git remote add dokku dokku@stargeo-dokku:new
```
I made a record in `~/.ssh/config` to make it work:
```
Host stargeo-dokku
  HostName ec2-52-..-..-..1.us-west-2.compute.amazonaws.com
  User dokku
  IdentityFile /../stargeo.pem
  IdentitiesOnly yes
```
So I get:
```bash
$ git push dokku master
Permission denied (publickey).
...
```
I went to a server and saw this garbage in `/home/dokku/.ssh/authorized_keys`:
```
command="FINGERPRINT=c5:...:01 NAME=admin `cat /home/dokku/.sshcommand` $SSH_ORIGINAL_COMMAND",no-agent-forwarding,no-user-rc,no-X11-forwarding,no-port-forwarding no-port-forwarding,no-agent-forwarding,no-X11-forwarding,command="echo 'Please login as the user \"ubuntu\" rather than the user \"root\".';echo;sleep 10" ssh-rsa AAAA.......................(public key)......................aF stargeo
```
I removed all the junk before `ssh-rsa` and now I can `ssh stargeo-dokku` but:
```
$ git push dokku master
fatal: 'new' does not appear to be a git repository
fatal: Could not read from remote repository.
```

At this point I gave up.

**Comment by michaelshobbs** [comment]
So....the "garbage" is the beginning of the glue that make dokku work. You'll want that back...

Additionally this path in `~/.ssh/config` seems suspect.
```
  IdentityFile /../stargeo.pem
```
If you run `ls /../stargeo.pem` on the host your are running `git push` on, does that really exist?

Can you confirm the public key side of `stargeo.pem` matches what is in `/home/dokku/.ssh/authorized_keys`?

You can also now use `apt-get` to install dokku. @josegonzalez do we have docs on this somewhere?

**Comment by michaelshobbs** [comment]
@josegonzalez any idea where this bit in `~/.ssh/authorized_keys` is coming from?

```
command="echo 'Please login as the user \"ubuntu\" rather than the user \"root\".';echo;sleep 10" 
```

**Comment by josegonzalez** [comment]
It sounds like he tried to run sshcommand with the root user and it threw an error because the default ssh user on ec2 is ubuntu.

**Comment by abrkn** [comment]
:-1:

**Comment by abrkn** [comment]
Solution:

To install on EC2 Ubuntu:

``# Before the install
`$ sudo bash
$ export HOME=/root
$ cd ~/.ssh
$ mv authorized_keys authorized_keys.bak
$ cp /home/ubuntu/.ssh/authorized_keys .

$ wget -qO- https://raw.github.com/progrium/dokku/v0.3.15/bootstrap.sh | sudo DOKKU_TAG=v0.3.15 bash
$ wget -qO- https://raw.github.com/progrium/dokku/v0.3.15/bootstrap.sh | sudo DOKKU_TAG=v0.3.15 bash

$ cd /root/dokku && make dokku-installer

# Now go complete the web setup

# Restore ssh keys
$ cd ~/.ssh
$ mv -f authorized_keys.bak authorized_keys
```

**Comment by michaelshobbs** [comment]
Why do you need to run `bootstrap.sh` twice?

**Comment by Suor** [comment]
Thanks, @abrkn. It worked with slight addition. `/home/dokku/.ssh/authorized_keys` contained 2 lines:
```
ssh-rsa AAAA......................aF stargeo
command="FINGERPRINT=c5:d9:e0:5d:a2:26:1c:5e:4b:f7:66:e0:73:0e:df:01 NAME=admin `cat /home/dokku/.sshcommand` $SSH_ORIGINAL_COMMAND",no-agent-forwarding,no-user-rc,no-X11-forwarding,no-port-forwarding ssh-rsa AAAA................................aF stargeo

```

I needed to remove first to make things work.

**Comment by michaelshobbs** [comment]
So this seems to be an issue with which key is being used and how EC2 keys are generated? (i.e. the public key is only on the instance and not on the client)

The installer pre-populates the pubkey field with the first line of `/root/.ssh/authorized_keys` which I am assuming is not there on the EC2 platform. (default user being ubuntu) So I think you could have gotten around this by pasting in the pubkey side of the EC2 generate key found in `/home/ubuntu/.ssh/authorized_keys`. Does that make sense or am I missing something?

**Comment by Suor** [comment]
There are 2 major issues:

1. `wget ... | sudo bash` tries to install to current user home dir, not `/root/`. Next line in installation docs however assumes that you got installed dokku to `/root/dokku/`.

2. `/root/.ssh/authorized_keys` contain a key, but it also contains a command:
    ```bash
    no-port-forwarding,no-agent-forwarding,no-X11-forwarding,
    command="echo 'Please login as the user \"ubuntu\" rather than the user \"root\".';echo;sleep 10"
    ```
    So dokku gobbles up it.

And lesser ones:

3. Nginx config is not created unless I specify hostname from the start. It's not documented anywhere how to set it up later.

4. Static files in repo go into container and thus can't be served by nginx, which is outside of it.

**Comment by Suor** [comment]
P.S. lesser.1 is actually documented here http://progrium.viewdocs.io/dokku/nginx, so only one scenario remains unfullfilled, where I don't want vhosts, but want nginx.

P.P.S. lesser.2 has been brought up and up for months: #437, #512, #112, #372, #638. So it would be nice to have some official way to do that.

**Comment by michaelshobbs** [comment]
What is the prescribed method to do this on Heroku?

**Comment by Suor** [comment]
You mean static? For python - serve it with whitenoise python lib, which kind of works, but not a best way to serve static.

**Comment by michaelshobbs** [comment]
I mean in production you would serve static with a CDN of some sort, right? In a test env, having Python serve it up is fine. Serving static files is sort of out of the primary scope of dokku I think.

It should be noted that I don't speak for progrium. Just my 2 cents on the topic.

**Comment by Suor** [comment]
I don't know where it comes from, but serving static from your host in production is totally fine and sometimes better than CDN: think like city/country website, you probably don't want your users to go to some overseas CDN for jquery. Also, CDNs are not that fast actually and they require more setup effort.

While you use single host for app, which is primary use case for dokku as I understand it, single host for static will work flawlessly.

**Comment by joshco** [comment]
@abrkn's solution worked for me on EC2.  One difference I noticed when running his soln was that the web gui textarea for the ssh key only contained the ssh key.  When I had run it off the stock instructions (which failed), the textarea had the ssh command stuff in there as well.  The failure was that I kept getting ssh publickey denied when trying to ssh to the dokku@dokku host,

**Comment by josegonzalez** [comment]
@joshco what do you mean by:

- stock instructions
- the" ssh command stuff"

Just asking so we can get the process smoothed out by for future users

**Comment by joshco** [comment]
Stock Instructions == just following exactly what it said at 
> http://progrium.viewdocs.io/dokku/installation
Those docs could be more helpful if it clarifies what user you are supposed to run it as, and that it will assume /root/dokku

ssh command stuff == the first part of the line containing stuff like
> command="FINGERPRINT=c5:...:01 NAME=admin `cat /home/dokku/.sshcommand`

**Comment by josegonzalez** [comment]
@joshco we never said to run the `command=` stuff, can you clarify where you got that?

**Comment by joshco** [comment]
What I meant was that in the web configuration UI, there is a textarea that is for the SSH key. It was prepopulated both with the command string and the key the first time I did it (when it ultimately didnt work)
When I used @abrkn 's solution, the textarea was prepopulated only with the SSH key.
The command stuff ultimately ended up in ~dokker/.ssh/authorized_keys even though it wasn't in the UI.
I don't know if this is relevant, but it seemed odd and perhaps helpful in your troubleshooting so I am reporting it.

**Comment by josegonzalez** [comment]
Can you send me a link to the instructions you followed for an EC2 installation? That seems like an extremely odd outcome, and I sort of think you tried uploading a key via sshcommand but got the command to run incorrect.

**Comment by joshco** [comment]
I just followed what was on http://progrium.viewdocs.io/dokku/installation
Then I tried @abrkn 's answer which worked. I believe I started with a fresh EC2 instance, but I was flailing around, so it is possible I did something unusual.

**Comment by joshco** [comment]
This may be explain what I saw and be helpful to you.  In a fresh EC2 instance, the authorized_keys file for root is populated with **amazon's own** command=
>no-port-forwarding,no-agent-forwarding,no-X11-forwarding,command="echo 'Please login as the user \"ubuntu\" rather than the user \"root\".';echo;sleep 10" ssh-rsa AAAAB3............

Maybe the dokku install script isn't handling this.  That command= should come out.

**Comment by josegonzalez** [comment]
Oh it's definitely not. Totally forgot about that with EC2, as I chef out everything in my own infrastructure. So we have a bug in the dokku-installer. I can fix that :)

**Comment by craigbeck** [comment]
+1 same issues following install on local Ubuntu 14.10 machine.

https://github.com/progrium/dokku/blob/v0.3.15/bootstrap.sh#L21 assumes that this will switch to `/root` as the `sudo` user home directory, but it doesn't i.e. it still uses my user home directory.

https://github.com/progrium/dokku/blob/v0.3.15/Makefile#L121 assumes the above script changed the directory to `/root/dokku`, but it didn't (`dokku` dir was created in user's `HOME`) so the `dokku-installer` target fails.

There's a lack of documentation for what to do with the web install UI after that (I pieced it together once, but still not sure if it is all correct yet)

**Comment by josegonzalez** [comment]
You need to run the script as sudo, which is how it's documented. You almost certainly skipped that.

**Comment by craigbeck** [comment]
Hey @josegonzalez, no i didn't skip that. I copied and pasted the command into the terminal from the docs. Only the `bootstrap.sh` file is run with `sudo` via the pipe from `wget`.

Even when run via `sudo` the script does not checkout the repo in the location expected by the `Makefile` which expects it to be under `/root/dokku` (per your commit https://github.com/progrium/dokku/commit/a2d1d8c0653b60d9bbe2cadecb93197b19b3051d). If the intent is that all the commands at http://progrium.viewdocs.io/dokku/installation be run as a script the docs don't say that, and even still under sudo it will still fail as `cd ~` does not chagne the directory to `/root`

```sh
cbeck@cbeck-desktop:~$ sudo bash
root@cbeck-desktop:~# cd /root/dokku/
root@cbeck-desktop:/root/dokku# sudo echo ${HOME}
/home/cbeck
root@cbeck-desktop:/root/dokku# cd ~
root@cbeck-desktop:~# pwd
/home/cbeck
```

I'm guessing this was tested by using `sudo su` as that will switch to the `root` user and change the meaning of `~`

```sh
cbeck@cbeck-desktop:~$ sudo su
[sudo] password for cbeck: 
root@cbeck-desktop:/home/cbeck# echo ${HOME}
/root
root@cbeck-desktop:/home/cbeck# cd ~
root@cbeck-desktop:~# pwd
/root
```

**Comment by joshco** [comment]
+1  sudo doesnt update the HOME env var.
using sudo -i will

**Comment by josegonzalez** [comment]
Installation is now performed - by default - from debian packages. Closed by #1058.

**Comment by omin** [comment]
I'm getting this on a freshly installed Ubuntu 16.04.2 LTS

**Comment by joshmanders** [comment]
@omin please open a new issue with all the info in the issue template requests.
