### ISSUE TITLE
No nice way to push 12-factor apps

### ISSUE THREAD

**Issue by Suor** [progrium/dokku#1019]
12-factor app needs configuration specified separately from repo. There is now `dokku config:set`, but you can't make config before first push. So a workflow now is like that:

1. Make push, it says happily that all got deployed (even if there is no container running). 
2. ssh into server (yuck)
3. run `dokku config:set app ...`.
4. run `dokku ps:rebuild app`

I thought 12-factor app is the way you are supposed to go with dokku. Looks like this part needs more love.

**Comment by michaelshobbs** [comment]
This is not correct. 

1. `dokku apps:create app-name` (or `ssh dokku@host apps:create app-name`
2. `dokku config:set app-name var=value` (or similar ssh command from above)
3. `git push dokku@host:app-name master`
4. Profit :smile:

**Comment by Suor** [comment]
This needs to be more clear in the docs. Maybe a snippet "Deploying 12-factor apps".

It would be even cooler if it didn't require me to type ssh, host, app-name each time and derive it somehow from `git remote -v`. But that's a separate thing.

**Comment by Suor** [comment]
It's cool that there is a way, though :)

**Comment by michaelshobbs** [comment]
Check out the dokku client in contrib/

Also feel free to PR the docs from your experience.

**Comment by josegonzalez** [comment]
There are docs on several clients, including the slightly official one in `/contrib`.

**Comment by josegonzalez** [comment]
Closing as everything here is documented. If you'd like to contribute to the docs, make a pr to the `docs/` dir :)
