### ISSUE TITLE
No errors reported on failed builds

### ISSUE THREAD

**Issue by Suor** [progrium/dokku#1020]
When I push first time my app surely won't work cause I have not set configs yet (see #1019), still it says it deployed it and gives me an url. Url doesn't work, there is no even docker container running!

The other scenario - if I made a mistake like haven't checked in changed requirements file, so my app throws ImportErrors, web process doesn't start, still no reported errors. Worse is that when I log into server there is no place to look for error logs. I need to rerun parts of buildpack to get to the actual errors.

**Comment by michaelshobbs** [comment]
This is because dokku by default just spins up a container with your app. If you set up zero downtime deploys, then dokku will present an error. 

You can get your app logs with `dokku logs app-name`.

**Comment by michaelshobbs** [comment]
Perhaps we could always do a generic check even if zero downtime is not configured to see if the container hangs around for at least x number of seconds?

**Comment by Suor** [comment]
Generic check would be nice. Also, outputting errors would be nice, so that I won't need to query for logs.

OK, `dokku logs app-name` should be added to http://progrium.viewdocs.io/dokku/troubleshooting.

Also, where do web process errors go? I send them to STDOUT, but then they seem to just get ignored. Nothing in `dokku logs app-name`.

**Comment by Suor** [comment]
Also, `dokku logs app-name` doesn't help if something is broken in the middle of buildpack.

**Comment by michaelshobbs** [comment]
The builder output does go to stdout.

**Comment by josegonzalez** [comment]
@michaelshobbs The container will stop if there are errors in the app, so maybe we just check if the container is running?

**Comment by michaelshobbs** [comment]
Yeah that's what I was thinking.
