### ISSUE TITLE
Unable to destroy app. Permission Denied (Cache Folder)

### ISSUE THREAD

**Issue by nbhasin2** [progrium/dokku#1023]
I have a node app on one of my subdomain and for some reason I cannot destroy it. 

Please have a look at the logs below and it will give you an idea of whats going on. 

https://gist.github.com/nbhasin2/c97eaba14fd21123cf80

**Comment by michaelshobbs** [comment]
Looks like something else interacted with docker perhaps. In any case, you can run `dokku apps:destroy <app>`, ignore the errors and then `sudo rm -rf /home/dokku/<app>` to finish the clean up process.

**Comment by nbhasin2** [comment]
Seems like sudo rm -rf /home/dokku/<app> did the trick.
