### ISSUE TITLE
dokku config:set should restart the app, not rebuild it

### ISSUE THREAD

**Issue by paralin** [progrium/dokku#1024]
... at least in most situations. The user should have to issue a rebuild command to rebuild their app, imo.

**Comment by josegonzalez** [comment]
Mind making a PR for that? I think it might be that our `ps:build` is what adds env vars to the container, hence why we rebuild.

**Comment by michaelshobbs** [comment]
We do call `ps:restart` on `config:set`.

https://github.com/progrium/dokku/blob/2922a95ff61c5518761252cc8fc6020613a121e7/plugins/config/commands#L45

**Comment by paralin** [comment]
My apologies, I forgot I had switched to dokku-alt.

https://github.com/dokku-alt/dokku-alt/issues/216
