### ISSUE TITLE
missing newline in newly deployed rails app /app/.env

### ISSUE THREAD

**Issue by gcohen55** [progrium/dokku#1025]
After a new rails app deployment via git, the generated /app/.env file is missing a newline and ends up looking like this:

````
docker exec -t -i 3299 cat /app/.env
export CURL_CONNECT_TIMEOUT=5
export CURL_TIMEOUT=30 export DATABASE_URL='postgres://root:asdfasdf@172.17.42.1:49155/db'
export REDIS_IP=172.17.0.18
export REDIS_PORT=6379
export REDIS_URL=redis://172.17.0.18:6379
````
I've tried adding an extra newline to ~dokku/ENV and that didn't help, /BUT/ throwing a leading newline in ~dokku/<APP>/ENV, is a workaround.

@josegonzalez asked me to open this issue on #dokku

**Comment by michaelshobbs** [comment]
How are you setting `DATABASE_URL` and `REDIS_*`?

**Comment by josegonzalez** [comment]
He had them set via plugins. The odd thing is that I had him unset the DATABASE_URL and re-set it, and he *still* had that error. I think it might be how the env vars are concated into the `.env` file.

**Comment by michaelshobbs** [comment]
Yeah I was able to recreate the issue using the ruby example app. I'm going to sort out a fix and include this in our test suite.
