### ISSUE TITLE
How will docker swarm, machine, compose relate to/change dokku?

### ISSUE THREAD

**Issue by miraculixx** [progrium/dokku#1033]
Just came across this: http://blog.docker.com/2015/02/orchestrating-docker-with-machine-swarm-and-compose/

Any insights on how dokku will be influenced by, should integrate these components?

[Me thinks dokku + swarm + shipyard would be a great combination, so would machine + dokku]

**Comment by josegonzalez** [comment]
Compose is what was formerly fig. We'd love to have native fig support - or at least a good plugin for it - and I think the big blocker is the fact that we currently only support single-container applications.

Re: machine, it seems like that's just automating the installation of docker. It could definitely simplify our installation instructions in some respects, but would require more work on the part of the user. I can see that being useful for larger installations geared towards HA, but I don't see any immediate reason to include it in dokku in any meaningful way. Maybe I'm misunderstanding here.

Re: swarm, it could be interesting in HA setups. You could test your image on a staging dokku box, promote that - via a plugin - to a prod setup, and then have another plugin that pushes that image to your swarm cluster somehow. I think it could be a good workflow for users looking at how to transition to docker for a traditional setup or replicating heroku. I don't know that we should have official support for it, and am not sure what it would even look like, but I do think there is an opportunity here for enterprising folk to build out a a great solution.

This is more of a general discussion, so closing, but feel free to ping us on irc if you think I'm off base. I'm excited about some of the stuff they are releasing, and think it'll be great for the community, though I do think our general path isn't going to be swayed one way or another by them.
