### ISSUE TITLE
error during  installation

### ISSUE THREAD

**Issue by partus** [progrium/dokku#1034]
.....
.......
apt-get install -qq -y lxc-docker
sleep 2 # give docker a moment i guess
Start building buildstep

gzip: stdin: unexpected end of file
FATA[0416] Error: Untar exit status 1 unexpected EOF    
make: *** [stack] Error 1

lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.2 LTS
Release:	14.04
Codename:	trusty

tar --version 
tar (GNU tar) 1.27.1

**Comment by michaelshobbs** [comment]
Transient or networking issue? Have you tried again?

**Comment by partus** [comment]
there must not be network problems. yes, several times

**Comment by josegonzalez** [comment]
@partus can you try the instructions [here](https://gist.github.com/josegonzalez/834b9e585b752e5b95f4) for installation?

**Comment by partus** [comment]
@josegonzalez without root privileges there was permission error to access /etc/apt/sources.list.d/docker.list
with root privileges  it went without errors , thank you.

**Comment by josegonzalez** [comment]
Gotcha, so now everything works?

**Comment by partus** [comment]
yes

**Comment by josegonzalez** [comment]
Cool, closing. Our knew installation method will be via debian packages, so we can get around the need for a makefile installation that may fail. Thanks for checking!

**Comment by chrisRidgers** [comment]
I'm aware this is closed and the approach is different, but I've run into the same error trying to install Dokku with Vagrant.

Shall I create a separate issue?

**Comment by josegonzalez** [comment]
Sure, please open a new issue and document exactly what you're doing.
