### ISSUE TITLE
better logging of startup errors

### ISSUE THREAD

**Issue by joshco** [progrium/dokku#1044]
I'm working with rails.  It seems that for app startup errors, dokku logs doesnt return anything, and browsing to the app gets the 502 bad gateway as the container is not running.

To troubleshoot a rails startup error, I needed to 
> dokku run appname bash
> rails s

to see error output.
Is there a convenient place to find this information?

**Comment by josegonzalez** [comment]
@michaelshobbs This should probably be partially taken care of by #1038 but I don't there is a test to cover it. Can you confirm/deny that we validate whether an app starts up?

Re: figuring out why debugging why it might not have started, @michaelshobbs I can add a bit of instructions on running `/start web` under "why didn't my container start" in the troubleshooting docs. Anything you think this might otherwise be missing to close?

**Comment by joshco** [comment]
According to the git push, the app was started, but browsing to it gets a 502.
It must have started and then crashed.  For example, my DATABASE_URL was not set.

**Comment by josegonzalez** [comment]
@joshco I guess what I'm asking is if you are running dokku master branch or not. If not, can you verify that you don't get an error message when running your app on master?

**Comment by joshco** [comment]
Ah.  I installed dokku with:

> wget -qO- https://raw.github.com/progrium/dokku/v0.3.15/bootstrap.sh | sudo DOKKU_TAG=v0.3.15 bash

as it says on the documentation pages.
What would the syntax be to do that from master?
I'll give it a shot on a fresh instance

**Comment by josegonzalez** [comment]
Try the following:

```
wget -qO- https://raw.github.com/progrium/dokku/master/bootstrap.sh | sudo bash
```

**Comment by joshco** [comment]
Ok, that's better.  The git output is below.  
````
remote:        -----> Discovering process types
remote:        Procfile declares types -> web
remote: -----> Releasing sample...
remote: -----> Deploying sample...
remote: -----> Running pre-flight checks
remote:        CHECKS file not found in container: running simple container check...
remote: -----> Waiting for 35 seconds ...
remote: App container failed to start!!
remote: /usr/local/bin/dokku: line 49: 16092 Killed                  dokku deploy "$APP"
To dokku@d2.splitatom.com:sample
 ! [remote rejected] dokku -> master (pre-receive hook declined)
error: failed to push some refs to 'dokku@d2.splitatom.com:sample'
````
Is there a place where I can see the error log for what happened?

**Comment by michaelshobbs** [comment]
My be good to dump `dokku logs <app>` output on both successful and failed deployments.

**Comment by michaelshobbs** [comment]
@joshco to your question, you'll need to run `docker ps -a` and find the container ID for `/start web`. The run `docker logs <container_id>`. Additionally I have a PR coming that will dump this to stdout on deploy.

**Comment by joshco** [comment]
I updated to master last night.  Yes, I see these errors, and the CHECKS are helpful.
