### ISSUE TITLE
! [remote rejected] master -> master (pre-receive hook declined) -- with submodule

### ISSUE THREAD

**Issue by alfetopito** [progrium/dokku#1045]
Hey guys, it's me again.

I already opened a ticket of this kind and the problem was solved (#1011).

This time, the situation is slightly different. New machine (Ubuntu 14.04x64 on EC2 t2.micro), same setup, except the project now contains a private submodule.

I did as suggested, adding the deploy key to dokku user:

```shell
$ ssh -T git@bitbucket.com
authenticated via a deploy key.


You can use git or hg to connect to Bitbucket. Shell access is disabled.

This deploy key has read access to the following repositories:
...
```

But still wasn't able to push the app. Here is the trace log -> https://gist.github.com/alfetopito/15268db996be21afbc57

Ideas?

**Comment by michaelshobbs** [comment]
Looks like `git submodule update --init --recursive` failed...

https://gist.github.com/alfetopito/15268db996be21afbc57#file-dokku-trace-log-L556-L557

**Comment by alfetopito** [comment]
Yep. I was looking into that, manually run this command inside the temp cloned folder:

```shell
/tmp/tmp.hBjohXA5HU$ git submodule update --init --recursive                                                                                                              
Cloning into 'myapp/mysubmodule'...
The authenticity of host 'bitbucket.org (131.103.20.168)' can't be established.
RSA key fingerprint is 97:8c:1b:f2:6f:14:6b:5c:3b:ec:aa:46:46:74:7c:40.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'bitbucket.org,131.103.20.168' (RSA) to the list of known hosts.
remote: Counting objects: 148, done.
remote: Compressing objects: 100% (145/145), done.
remote: Total 148 (delta 80), reused 0 (delta 0)
Receiving objects: 100% (148/148), 62.21 KiB | 0 bytes/s, done.
Resolving deltas: 100% (80/80), done.
Checking connectivity... done.
Submodule path 'myapp/mysubmodule: checked out 'a05f8e460162553c106ab1e59a30f2683cf952a8'
```

And this time it worked.

The weird thing is, I did run `ssh-keyscan -t rsa bitbucket.org >> ~/.ssh/known_hosts` to add bitbucket remote key, but only after running manually it worked...

Well, works now, tks.

**Comment by michaelshobbs** [comment]
@alfetopito you might check into using https://github.com/cedricziel/dokku-hostkeys-plugin to avoid having to do the manual step.

**Comment by alfetopito** [comment]
:+1: @michaelshobbs cool! I'll look into that
