### ISSUE TITLE
Rebuild fails when app has persistent storage

### ISSUE THREAD

**Issue by iamso** [progrium/dokku#1046]
When trying to run `ps:rebuild` on an app that has perstistent storage (let's say `-v /var/www/appname/data:/app/data`, either using dokku-persistent-storage, dokku-docker-options or dokku-volume) it fails with the following error:
```
rm: cannot remove '/app/data': Device or resource busy
```

Thanks for looking into that.

**Comment by michaelshobbs** [comment]
This should probably be logged against the plugin(s) repo(s) if it isn't already.

**Comment by michaelshobbs** [comment]
I believe this fixed it. You probably need to upgrade your plugin?

dyson/dokku-persistent-storage#12

**Comment by iamso** [comment]
Ok, so it's definitely a plugin issue. Dokku-volume also got an update and is now working, so I switchted to that one.

The only one, that didn't get an update, is dokku-docker-options, the one I was using before.
