### ISSUE TITLE
Nginx 111: Connection refused errors 

### ISSUE THREAD

**Issue by Epigene** [progrium/dokku#1050]
Dokku apps became unresponsive today, request ending up in 
`502 Bad Gateway`
Seems like an nginx configuration problem.
Ended up remaking a digital ocean droplet, but the issue persists.

Sample /var/log/nginx/error.log output
```
2015/03/23 10:49:01 [error] 1212#0: *9 connect() failed (111: Connection refused) while connecting to upstream, client: 11.118.65.13, server: domain.com, request: "GET /favicon.ico HTTP/1.1", upstream: "http://127.0.0.1:5000/favicon.ico", host: "domain.com"
```

nginx -t #=> all OK

sample nginx.conf in application folder
```
upstream domain.com { server 127.0.0.1:5000; }

server {
  listen      [::]:80; #IPv6 compatibility
  listen      80;
  server_name domain.com;
  location    / {
    proxy_pass  http://domain.com;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header X-Request-Start $msec;
  }
}
```
As far as I can tell, my DNS settings are fine.

I recently added nginx-alt to my plugin list, could that be causing this? (Suspecting this, I deleted the directory in plugins and reinstalled plugins, did not fix anything)

Interestingly, I deployed a test node app to node.apps.domain.com to see if that would perhaps work, but requests there do not even reach nginx.

Any help would be great,
Thanks!

**Comment by josegonzalez** [comment]
A few qs:

- Is nginx running?
- Can you gist your actual nginx.conf from the app? You can omit the name, but everything else is important
- Gist `docker ps -a`
- Deploy logs?
- What version of dokku are you running, and how did you install it?

**Comment by Epigene** [comment]
I believe nginx is running - if it were not I'd be getting the same "webpage does not exist" on both app URLs

The nginx.conf is precisely as it is in the app sans the real domain.

docker ps -a gist https://gist.github.com/Epigene/6b4fa2eeb901133a4673

Rails app deploy gist https://gist.github.com/Epigene/62bee007acdcbb3e3c7d
Node app deploy gist https://gist.github.com/Epigene/2adfe58fe6e7cd15dc18

Running Dokku v0.3.15, installed by setting up the pre-made dokku image on a droplet on Digital Ocean.

**Comment by Sacristan** [comment]
Nginx is running for sure

**Comment by michaelshobbs** [comment]
I'm almost certain we don't have the correct upstream information here. 

Can we get the output from `docker inspect --format='{{ .NetworkSettings }}' <container_id>` and the nginx config for both apps/running containers? Also, getting a `dokku ps:rebuildall` with DOKKU_TRACE on might be helpful as well.

**Comment by Epigene** [comment]
docker inspect --format='{{ .NetworkSettings }}' rails app #=>
`map[GlobalIPv6Address: IPPrefixLen:16 LinkLocalIPv6Address:fe80::42:acff:fe11:18 Ports:map[] Gateway:172.17.42.1 GlobalIPv6PrefixLen:0 IPAddress:172.17.0.24 IPv6Gateway: LinkLocalIPv6PrefixLen:64 MacAddress:02:42:ac:11:00:18 PortMapping:<nil> Bridge:docker0]`

docker inspect --format='{{ .NetworkSettings }}' node app #=>
`map[Gateway:172.17.42.1 GlobalIPv6Address: IPPrefixLen:16 LinkLocalIPv6Address:fe80::42:acff:fe11:29 Ports:map[] PortMapping:<nil> Bridge:docker0 GlobalIPv6PrefixLen:0 IPAddress:172.17.0.41 IPv6Gateway: LinkLocalIPv6PrefixLen:64 MacAddress:02:42:ac:11:00:29]`

Rails app nginx.conf (in /home/dokku/domain.com)
```
upstream domain.com { server 127.0.0.1:5000; }

server {
  listen      [::]:80; #IPv6 compatibility
  listen      80;
  server_name domain.com;
  location    / {
    proxy_pass  http://domain.com;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header X-Request-Start $msec;
  }
}
```

Node app nginx.conf
```
upstream node { server 127.0.0.1:5000; }

server {
  listen      [::]:80; #IPv6 compatibility
  listen      80;
  server_name node.apps.creative.gs;
  location    / {
    proxy_pass  http://node;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header X-Request-Start $msec;
  }
}
```

How do I get all the trace? It is way too long. Tried piping output into a file, but it only saves the app deployment lines like `^[[1G-----> Cleaning up...` and not the trace-y lines starting with "+"

**Comment by Epigene** [comment]
I should add that deleting the /home/dokku/VHOST file thus reverting to IP:PORT based lookup works as can be seen at http://apps.creative.gs:49158/

**Comment by Jeewes** [comment]
I think I have similar problem. I'm also using Digital Oceans Dokku (3.1.5) image.

I can access my application by running `curl 172.17.0.127:5000` on the host machine. Found that ip from __/home/dokku/app_name/nginx.conf:__
```
upstream app_name { server 172.17.0.127:5000; }
server {
  listen      [::]:80;
  listen      80;
  server_name app_name.mydomain.io ;
  ...
  }
  include /home/dokku/app_name/nginx.conf.d/*.conf;
}
```
When I try to access the application with the `app_name.mydomain.io` I get __502 Bad Gateway__.

Seems like Nginx does not "find" the application correctly. Could this be related to [IPv6 and docker](http://progrium.viewdocs.io/dokku/getting-started/install/digitalocean) (just a wild guess).

**Comment by michaelshobbs** [comment]
@Jeewes I don't think your issue is the same one. if you don't mind, please open a new issue. thanks.

**Comment by michaelshobbs** [comment]
@Epigene yeah it seems we're not extracting your container ip correctly. can you provide the original contents of `/home/dokku/VHOST`?

Thanks.

**Comment by Epigene** [comment]
@michaelshobbs sorry, I have probably deleted and recreated the `/home/dokku/VHOST` file a dozen times while tinkering with this problem, no way to tell what was in it originally.

However, I believe it must have contained the single line
`apps.creative.gs`, our dokku subdomain which points to Digital Ocean droplet at 82.196.9.147, as do `*.apps.creative.gs`

Maybe file permission issue on this file?

**Comment by Epigene** [comment]
In a last-ditch attempt to see if I can fix this, I made a fresh Digital Ocean dokku image droplet and did not run upgrade, just went straight to setting up node.utils.creative.gs and it works!

I can only surmise that something in code changes during upgrade breaks dokku, or was I supposed not to upgrade in the first place? And I am sure I opted for not changing nginx settings when it prompted.

I could save a working image and do the breaking upgrade if that would be helpful for debugging.
If not we can close this with a lesson learned: "If it works, create a backup image and do not change anything" :smile:

**Comment by Sacristan** [comment]
So another case of - "If it works - dont touch it" ?

**Comment by Epigene** [comment]
Plus nginx-alt plugin, it's the real culprit!

**Comment by michaelshobbs** [comment]
Ah! I missed the fact you had a different nginx plugin.

**Comment by michaelshobbs** [comment]
So I have a working fork of [nginx-alt](https://github.com/expa/dokku-nginx-alt) that works with the latest dokku. I just haven't had a chance to get a PR up for it.

**Comment by Epigene** [comment]
I'll keep an eye out for it then. For now I am making custom nginx settings work with the default nginx.conf.template file. Escaping all them dollar signs is tedious though :rabbit:

**Comment by michaelshobbs** [comment]
PR opened https://github.com/mikexstudios/dokku-nginx-alt/pull/20
