### ISSUE TITLE
Typos in docs

### ISSUE THREAD

**Issue by Epigene** [progrium/dokku#1052]
At http://progrium.viewdocs.io/dokku/nginx there is a paragraph containing "The template is manually uploaded this template file and must it owned by".

Not sure what is meant by it, surely typos present.

**Comment by michaelshobbs** [comment]
@josegonzalez is to blame? not sure what you were intending good sir. :smile:

https://github.com/progrium/dokku/commit/3d6727a1b865a7de8075d06b4f17b96e569584ee
