### ISSUE TITLE
support alternate dockerfiles

### ISSUE THREAD

**Issue by mmerickel** [progrium/dokku#1053]
Docker 1.5 has the ability to specify the dockerfile to use in `docker build`. It'd be great if we could override the default file via an environment setting like "dokku config:set myapp DOCKERFILE=Dockerfile.docs" or add it to the `.env` file.

**Comment by michaelshobbs** [comment]
Sounds like a good idea to me :smile:

**Comment by mmerickel** [comment]
I was gonna add a PR for this. I have a quick convention question though. Is there a reason for the `DOKKU_DOCKERFILE_PORT` versus using simply `DOCKERFILE_PORT`? I think it'd be better to just use `DOCKERFILE_PORT` and check first if it's already set to avoid overwriting it.

**Comment by michaelshobbs** [comment]
We had some issue with internal env variables getting overwritten because they were to ambiguous. Hence, the convention to prepend `DOKKU_`.

**Comment by josegonzalez** [comment]
@mmerickel bump :)

**Comment by mmerickel** [comment]
It looks to me like this is solved by the docker-options build-phase plugin.
