### ISSUE TITLE
Rails rake db:migrate issues due to $VERSION conflict

### ISSUE THREAD

**Issue by joejwright** [progrium/dokku#1066]
Herokuish seems to be adding a VERSION environment variable that is conflicting with Rails migrations. New app containers have a VERSION environment variable of 0.2.0. This only happens when the container entry point is herokuish, i.e /exec or /start.

Rails migrations use a VERSION env variable to specify a migration to be run. Since the rails migrator is essentially seeing VERSION=0 it is reverting all migrations on the database.

This can be a serious issue on a production database since it will wipe out all migrations until if gets to an empty database or irreversible migration.

**Comment by michaelshobbs** [comment]
@joejwright I believe this will probably need to logged over at https://github.com/progrium/buildstep.

@progrium can you comment on this at all?

**Comment by progrium** [comment]
Wow. Definitely log an issue with Herokuish.

**Comment by sibsfinx** [comment]
```
This can be a serious issue on a production database since it will wipe out all migrations until if gets to an empty database or irreversible migration.
```
Yeah, this is why I haven't slept last night :sleepy: 
Until it's fixed we can only run migrations manually like `dokku run <app> rake db:migrate:up VERSION=<version>`

**Comment by josegonzalez** [comment]
@progrium ^

**Comment by josegonzalez** [comment]
@joejwright can you test with the new version of herokuish?

**Comment by joejwright** [comment]
@josegonzalez Looks good to me. I forked buildstep to point it at the herokuish 0.3.0 binary then rebuilt the buildstep image. I'm seeing the new HEROKUISH_VERSION env var instead of the VERSION env var and migrations are completing successfully.

The fork is here in case anyone wants to use it to rebuild buildstep: https://github.com/joejwright/buildstep.

**Comment by joshco** [comment]
+1000 I've been struggling with this for the past 2 days.  Talk about tough to debug (my migrations were reverting too.  All my tables got dropped :)
My hackaround was to put this in my app's env file 
````
export VERSION=
```

**Comment by joejwright** [comment]
@joshco I tried that initially but it didn't work for me. The migrations kept reverting anyway. Hit me up if you need help building a new buildstep image.

**Comment by joshco** [comment]
@joejwright Hmm I put that in the app specific ENV, then rebuilt the image.
Since then, I've taken your forked buildstep and am using the new herokuish and I see the new env var.

**Comment by michaelshobbs** [comment]
Closing as the upstream issue has been fixed.
