### ISSUE TITLE
npm version in package.json ignored

### ISSUE THREAD

**Issue by danhawkes** [progrium/dokku#1069]
I've got a `package.json` with the following:

    "engines": {
      "node": "^0.10.0",
      "npm": "2.x"
    },

When deploying, it looks like the wrong version is used:

      -----> Requested node range: ^0.10.0
      -----> Resolved node version: 0.10.38
      -----> Downloading and installing node
      -----> Exporting config vars to environment
      -----> Installing dependencies
             npm WARN engine imagemin@3.1.0: wanted: {"node":">=0.10.0","npm":">=2.1.5"} (current: {"node":"0.10.38","npm":"1.4.28"})

The [buildpack](https://github.com/heroku/heroku-buildpack-nodejs) claims to support npm version specification, so any ideas why it's not working here?

**Comment by MatthewMueller** [comment]
I actually *just* tried this and it worked, what version of dokku are you running? also can you try running it with `node 0.11.x` or `node 0.12.x`

**Comment by MatthewMueller** [comment]
should look like this:

![image](https://cldup.com/5YPrjVq_Rk.png)

**Comment by danhawkes** [comment]
Thanks for the quick response.
Am running `v0.3.16` from the current digitalocean image. Also tried upgrading to `0.12.x` with no change in outcome.

**Comment by michaelshobbs** [comment]
To clarify, when you say "the wrong version is used", you are referring to the version of npm, yes?

Is node 0.10.x with npm 2.x a valid configuration? (I'm not a node eng in case that wasn't clear :smile:)

**Comment by michaelshobbs** [comment]
I'm seeing the same behavior using this buildpack url `https://github.com/heroku/heroku-buildpack-nodejs#v63`

**Comment by danhawkes** [comment]
Yes, the wrong version of npm. No idea WRT node 0.10.x compatibiliy with npm 2.x, but regardless I've tried node 0.12.x (and it resolves to 0.12.0), so presumably that's not the issue.

**Comment by danhawkes** [comment]
Right, so you think the buildpack is obsolete? How does dokku retrieve it?

**Comment by michaelshobbs** [comment]
Using the latest buildpack, seems to resolve this. YMMV.

Add a file named `.env` to the root of your repo with the following contents. This will force dokku to download the latest buildpack. Give it a shot and let us know.

```
export BUILDPACK_URL=https://github.com/heroku/heroku-buildpack-nodejs
```

**Comment by danhawkes** [comment]
Yes, that seems to have done it! Much appreciated.
