### ISSUE TITLE
Smarter CHECKS

### ISSUE THREAD

**Issue by matthewmueller** [progrium/dokku#1070]
I'd like to precompile my app before actually starting up the server, so my `Procfile` may look something like this:

```
web: make build && make start
```

Which will take longer than 35 seconds. I could update the timeout, but that would be a guess and I'd have to keep updating it as the app grows. 

It'd be nice to either wait until the command fully finishes, or if that's not possible, curl before releasing to make sure that you are not getting a "Bad Gateway" error from nginx.

**Comment by michaelshobbs** [comment]
I wrote a plugin to do this in the pre-deploy phase. I believe there is another out there as well.

https://github.com/michaelshobbs/dokku-app-predeploy-tasks

**Comment by michaelshobbs** [comment]
Also this is in process. https://github.com/progrium/dokku/pull/1056 

Feel free to chime in there as well.

**Comment by michaelshobbs** [comment]
Closed in favor of #1056
