### ISSUE TITLE
Install application vi 'git pull'

### ISSUE THREAD

**Issue by jwarzech** [progrium/dokku#1073]
Is there a way to deploy an application with dokku from running a script on the deployment server using a 'git pull' command rather than pushing to the remote?

**Comment by michaelshobbs** [comment]
I use a chef recipe that pulls from github to a 'staging' directory and then `git push` into the local dokku instance. Nothing that will `git pull` directly into dokku

**Comment by michaelshobbs** [comment]
Feel free to re-open if you have any further comments on this.
