### ISSUE TITLE
Upgrading from 0.3.13

### ISSUE THREAD

**Issue by jeremiahrhall** [progrium/dokku#1078]
If I follow the upgrade process on the wiki:

    cd ~/dokku
    git pull --tags origin master
    sudo make install

I get the following on the final `sudo make install`:

    wget -qO /usr/local/bin/sshcommand https://raw.github.com/progrium/sshcommand/master/sshcommand
    chmod +x /usr/local/bin/sshcommand
    sshcommand create dokku /usr/local/bin/dokku
    User 'dokku' already exists

And it hangs on that last output until I Ctrl+C out of it.

I took a look at the makefile and I don't see an alternate command here. Is there a different process for upgrading that's not documented?

**Comment by michaelshobbs** [comment]
@josegonzalez you've been in the upgrade/install process more recently. thoughts here?

**Comment by josegonzalez** [comment]
Installation is now performed - by default - from debian packages. Upgrading is now performed via apt-get, so this issue isn't a relevant issue anymore - and the upgrade path from source to apt is just as easy. Closed by #1058.
