### ISSUE TITLE
Possible issue with dokku on a server with a non standard ssh port

### ISSUE THREAD

**Issue by eddywashere** [progrium/dokku#1086]
Is there anything I need to do to get dokku working on a non standard ssh port?

I am getting the following error when doing `git push dokku master`:

```
Permission denied (publickey).
fatal: Could not read from remote repository.
```

I'm not using the standard ssh port 22, I've changed my ssh config to point to the right ssh port (figured it was similar to vagrant). I see in the dokku user authorized keys that my ssh pub key exists and is correct.

**Comment by eddywashere** [comment]
I'm on ubuntu 14.04, on a Rackspace Cloud Server.

**Comment by josegonzalez** [comment]
How did you install dokku?

**Comment by eddywashere** [comment]
With a user with root permissions I used `wget -qO- https://raw.github.com/progrium/dokku/v0.3.16/bootstrap.sh | sudo DOKKU_TAG=v0.3.16 bash`

Then I did the make installer for the web part of the installation.

**Comment by eddywashere** [comment]
My bad. It turns out that my chef setup locked down openssh access to the server to a specific user and group. I allowed access for that user and it's all good now. Thanks!
