### ISSUE TITLE
Remote Rejected when Pushing to Digitalocean

### ISSUE THREAD

**Issue by louisscruz** [progrium/dokku#1092]
I am trying to push my yo angular-fullstack MEAN app to Digitalocean with Dokku. I've followed the documentation on Digitalocean's site, but I get the following error when pushing:

    git push dokku master
    Counting objects: 965, done.
    Delta compression using up to 8 threads.
    Compressing objects: 100% (945/945), done.
    Writing objects: 100% (965/965), 242.54 KiB | 0 bytes/s, done.
    Total 965 (delta 668), reused 0 (delta 0)
    To dokku@xxxxxxxx.com:xxxxxxxx.com
    ! [remote rejected] master -> master (pre-receive hook declined)
    error: failed to push some refs to 'dokku@xxxxxxxx.com:xxxxxxxx.com'

I set up my droplet using the one click Dokku image, and it's running on Ubuntu 14.04. My droplet has 1GB ram.

**Comment by louisscruz** [comment]
I've fixed this, but I'm not entirely sure how. I checked git status, and it showed that there was an untracked folder. When I resolved that issue, it went through the build step.

**Comment by michaelshobbs** [comment]
In order to root cause, this you'd need to run a deploy in the broken configuration with `DOKKU_TRACE` on. (i.e. `dokku trace on` then deploy)
