### ISSUE TITLE
help encourage PR to heroku to use official base image

### ISSUE THREAD

**Issue by progrium** [progrium/dokku#1094]
https://github.com/heroku/stack-images/pull/15

Maybe some upvotes on this very simple PR will help it get merged. I've been told they *want* the community to use them, so this will let us do that. 

Biggest reason is that [progrium/cedarish](https://github.com/progrium/cedarish) (used by Herokuish/Buildstep/Deis/Flynn/etc) is now just mirroring a script in their repository. They also now have a Dockerfile in their repo that's published on Docker Hub, so this PR let's us use that instead of maintaining a separate community cedarish project. Which means Dokku would be based on a more or less "official" base image from Heroku. It also means security updates and other changes to Heroku will be reflected in Dokku and others much faster.

**Comment by michaelshobbs** [comment]
upvoted!

**Comment by progrium** [comment]
HOT DAMN. It worked. Thanks!

**Comment by josegonzalez** [comment]
Now we just need an updated buildstep release that I can make a debian package out of...

**Comment by progrium** [comment]
Use Herokuish!

On Tue, Apr 7, 2015 at 12:09 PM, Jose Diaz-Gonzalez <
notifications@github.com> wrote:

> Now we just need an updated buildstep release that I can make a debian
> package out of...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/progrium/dokku/issues/1094#issuecomment-90649374>.
>



-- 
Jeff Lindsay
http://progrium.com
