### ISSUE TITLE
gzip responses

### ISSUE THREAD

**Issue by krokhale** [progrium/dokku#1095]
I have installed the regular DO droplet with dokku and a got a few apps running with SSL. Have made no configuration changes manually, just followed the readme. No changes made to nginx config or touched anything.

I am facing an odd issue, my expressjs app has gzip compression enabled and if i deploy the app on heroku i do get gzipped responses. But on Dokku i am not getting gzipped responses. 

What am i missing?

**Comment by krokhale** [comment]
Read a bit more, added the conf template http block, 

    gzip on;
   gzip_static on;
   gzip_disable msie6;
   gzip_vary on;
   gzip_comp_level  4;
   gzip_min_length  256;
   gzip_buffers 16 8k;
   gzip_http_version 1.1;
   gzip_proxied     expired no-cache no-store private auth;
   gzip_types       text/css text/javascript text/xml text/plain text/x-component application/javascript    application/x-javascript application/json application/xml  application/rss+xml font/truetype application/x-font-ttf font/opentype application/vnd.ms-fontobject image/svg+xml;



Restarted app and nginx, verified the new conf file has the overridden settings, still no gzip.

**Comment by krokhale** [comment]
Ah well figured it out, a dumb config issue, though i feel that gzip could be enabled by default in the default config file, majority of the folks would want gzip by default.

**Comment by michaelshobbs** [comment]
:+1:

**Comment by michaelshobbs** [comment]
@krokhale Mind putting up a PR for this?

**Comment by krokhale** [comment]
Sure, just created one. Let me know if any questions.

**Comment by john-doherty** [comment]
@krokhale I'm having a similar issue [so](https://stackoverflow.com/questions/57425833/how-do-you-enabled-gzip-for-nginx-within-a-dokku-instance), what was the config issue?

**Comment by krokhale** [comment]
@john-doherty There are two ways of going about this. 1) Update the dokku config itself and add a custom nginx config. Though this is an old issue, not sure if they have enabled it by default now. And the way i use now is by enabling gzip on my express server itself. Look up gzip and express js, you will find a bunch of stuff.

**Comment by josegonzalez** [comment]
@john-doherty please do not bump a 4 year old issue.

Also, I just read the stackoverflow link. You're running an ancient version of Dokku, and your doc link also points to an even older version of the docs. Please upgrade and then refer to the nginx docs for the latest version.

Thanks @krokhale for responding in the interim.
