### ISSUE TITLE
memory_limit for PHP application

### ISSUE THREAD

**Issue by tcdev0** [progrium/dokku#1098]
I'm trying to set up a PHP application using Symfony with Sylius. If i execute any symfony command i get the following output.

``` bash
  $ PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted 
  (tried to allocate 10931 bytes) in ...
```
After that i created a custom conf for the web process to increase the memory limit 

``` bash
  php_value[memory_limit] = 256M
```
and updated Procfile

``` bash
 web: bin/heroku-php-apache2 -F fpm_custom.conf web/
```
redeployed the app

``` bash
  ...  
  =====> sylius container output:
       DOCUMENT_ROOT changed to 'web/'
       Using PHP-FPM configuration include 'fpm_custom.conf'
       2 processes at 256MB memory limit.
       Starting php-fpm...
  ...
```

checking the value

``` bash
  $ dokku run sylius php -ini | grep memory_limit
```

outputs 128M, nothing changed

``` bash
  $ memory_limit => 128M => 128M
```

What can i do ?

thanks

**Comment by michaelshobbs** [comment]
I'm almost certain the solution is in the php buildpack. You'll want to have a look there to see how memory is set. I had a similar issue with the Java buildpack and it turned out I just needed to an ENV variable to override Heroku's memory setting logic.

**Comment by tcdev0** [comment]
Setting ENV variables had no effect for me. CLI and Web still outputs default value.

If i include a custom php.ini with a modified 

``` bash
  memory_limit = 256M
```

changing the Procfile to 

``` bash
  web: vendor/bin/heroku-php-apache2 -i php_custom.ini
```

the value is present , checked with phpinfo() page.


Running php commands on the CLI works with 
``` bash
  $ dokku run sylius php -d memory_limit=256M app/console sylius:install
```

For a permanent memory value i forked the heroku php buildpack and manipulated the memory_limit in

``` bash
  conf/php/php.ini   
```

and run my project with this forked buildpack. So executing 

``` bash
  $ dokku run sylius php -ini | grep memory_limit
```
outputs the correct value

``` bash
 memory_limit => 256M => 256M
```

**Comment by josegonzalez** [comment]
Sounds like a bug in the buildpack, not for us. I know we handle env vars properly. Thanks for doing research though, hopefully this helps someone!

**Comment by praveenaj** [comment]
@tcdev0 try this: http://stackoverflow.com/questions/32127554/dokku-digital-ocean-client-max-body-size-node-js
