### ISSUE TITLE
Ghost servers

### ISSUE THREAD

**Issue by krokhale** [progrium/dokku#1099]
I faced a rather frustrating issue just now:

1) I use a cloud database that get initialized when a server starts up and has callbacks on certain conditions so that it can modify the database in the cloud.

2) So basically if there are two servers up with the same codebase, a callback will be executed twice. We don't want that to happen.

3) In my time tinkering and testing a production app, i noticed that callbacks were being executed twice. I Listed out the apps and containers in dokku, they showed just one container and app running.

4) Finally i had to restart the DO droplet, and then everything went back to normal.

Any idea why this would happen and how can i diagnose it next time? 

Also, yes Procfile contains just one web instance.

**Comment by josegonzalez** [comment]
Were you running it locally?

**Comment by krokhale** [comment]
Ah, now that would have too easy! :) . Yes i was running a local server too, but it clearly had a different DB url and environment. Unfortunately i won't have the time to explore it further, i am just going to write a test for it and research more if it happens again in future or if someone else files a similar issue.

**Comment by josegonzalez** [comment]
Cool, if you figure something out, let me know!
