### ISSUE TITLE
Application-level configuration is not taken into use anymore

### ISSUE THREAD

**Issue by kblcuk** [progrium/dokku#1101]
I think [check-deploy](https://github.com/progrium/dokku/blob/master/plugins/checks/check-deploy#L49) misses the following at line 49:

`[[ -f "$DOKKU_ROOT/$APP/ENV" ]] && source $DOKKU_ROOT/$APP/ENV`

That line used to be there in 0.3.15, but went missing during some cleanup, I guess?

**Comment by josegonzalez** [comment]
Good call. Mind making a pr? /cc @michaelshobbs

**Comment by kblcuk** [comment]
Done.
