### ISSUE TITLE
What is the best way to deploy from TravisCI?

### ISSUE THREAD

**Issue by eddiejaoude** [progrium/dokku#1104]
Ideally I do not want to have an *encrypted* **pem** file to my server in my repo so that TravisCI can deploy.

Is there another way with a token specific to an App on Dokku?

**Comment by josegonzalez** [comment]
Have a webhook on your server that does the push for you? Thats the only other way I can think of.

**Comment by eddiejaoude** [comment]
Wow that was a fast close... :gun: #triggerhappy :bangbang: 

:wink:

**Comment by josegonzalez** [comment]
I closed the issue because an answer was provided and this doesn't really have to do with dokku - either as a feature request or a bug. Not trigger happy, and still free to comment on it :)

**Comment by eddiejaoude** [comment]
Anyone else who has a similar situation, I will try & be helpful by sharing what I find... Initially I have come across http://dploy.io which looks promising.

**Comment by josegonzalez** [comment]
Note: ^ solution is similar to giving your pem key to travisci, you're just giving access to another party :)

**Comment by eddiejaoude** [comment]
> Note: ^ solution is similar to giving your pem key to travisci, you're just giving access to another party :)

Thanks for feedback. This is true, however for Travis it needs to be in the public repo (albeit encrypted).

I am on the fence about each solution & still searching for a better one.

**Comment by michaelshobbs** [comment]
I use AWS ops works and provide a deploy key when I define the app. There is a dokku deploy chef cookbook floating around somewhere. I'll try to find the link and drop it here.
