### ISSUE TITLE
Error when pushing/deploying a tag

### ISSUE THREAD

**Issue by eddiejaoude** [progrium/dokku#1105]
Error when pushing/deploying a tag:

```sh
...
-----> Shutting down old container in 60 seconds
=====> Application deployed:
       http://ci.dashboardhub.io

error: Trying to write non-commit object 9f0cebfd408ce17d0b7bc203e182def9f4e99fc9 to branch refs/heads/master
To dokku@alpha.dashboardhub:ci
 ! [remote rejected] build-develop-330 -> master (failed to write)
error: failed to push some refs to 'dokku@alpha.dashboardhub:ci'
```

**Comment by eddiejaoude** [comment]
I forgot to add... however, it still deploys successfully.

**Comment by josegonzalez** [comment]
How are you pushing tags?

**Comment by eddiejaoude** [comment]
Sorry I should have included that.

Same way I push a branch:
```
git push dokku-ci build-develop-330:master -f 
```

**Comment by josegonzalez** [comment]
So build-develop-330 is a tag? What happens if you push a tag? Or the commit that the tag points to?

**Comment by eddiejaoude** [comment]
Yes `build-develop-330` is a tag, when I push a tag it still deploys but displays the error below:.

```
To dokku@alpha.dashboardhub:ci
 ! [remote rejected] build-develop-330 -> master (failed to write)
error: failed to push some refs to 'dokku@alpha.dashboardhub:ci'
```

**Comment by eddiejaoude** [comment]
Pushing a branch is fine `git push dokku-ci dokku-deployments:master -f`

```sh
...
=====> Application deployed:
       http://ci.dashboardhub.io

To dokku@46.101.46.10:ci
   3808a5d..0485d09  dokku-deployments -> master
```

**Comment by michaelshobbs** [comment]
Can you gist a deploy of a tag with tracing on? (i.e. on the dokku box, run `dokku trace on` then push your tag)

**Comment by eddiejaoude** [comment]
Sure. I notice I am pushing with an IP in my git config (while waiting for dins to propagate), not sure how that could cause a difference between a **branch** & a **tag** deploy though?

```
[remote "dokku-ci"]
	url = dokku@46.101.46.10:ci
	fetch = +refs/heads/*:refs/remotes/dokku/*
```

Trace Gist https://gist.github.com/eddiejaoude/22d06934abf96adab18a

**Comment by josegonzalez** [comment]
Relevant [comment](http://stackoverflow.com/a/4061542).

**Comment by eddiejaoude** [comment]
@josegonzalez yes that seemed to work. I will have another play in the morning & do more reading around the subject.

Thanks :+1: 

Note: It might be worth added a brief example/overview to the docs about that.
