### ISSUE TITLE
Dokku and docker images

### ISSUE THREAD

**Issue by krokhale** [progrium/dokku#1108]
I feel like i am missing something really trivial here:

1) I am trying to get this going: https://github.com/gitlabhq/gitlabhq

2) Docker has a great image for this which is: https://github.com/sameersbn/docker-gitlab , and just fetching that image and then:

    docker run --name='gitlab' -it --rm \
    -e 'GITLAB_PORT=10080' -e 'GITLAB_SSH_PORT=10022' \
    -p 10022:22 -p 10080:80 \
    -v /var/run/docker.sock:/run/docker.sock \
    -v $(which docker):/bin/docker \
    sameersbn/gitlab:7.9.2

gets it all running.

3) I am able to run that image independently just using docker itself and access it on my IP address:port just as the image is supposed to work.

4) But how do i get that image to run in a dokku app? I read the docs, there's something about run to be passed as docker options, but am not quite sure what exactly should i pass to docker options:  

    http://progrium.viewdocs.io/dokku/docker-options

Thanks!

**Comment by jlachowski** [comment]
From my understanding the docker-options provide a way to add additional options when running a dokku app and not a separate docker image. So for this to work in your case, you would have to provide gitlabhq as a dokku app (e.g. using the someersbn docekr file) and then set the additional options from 2) via docker-options plugin.

**Comment by josegonzalez** [comment]
Basically what @jlachowski said. If you want to deploy an app via a got repo with a dockerfile, you can do that, but otherwise dokku does not support exactly what you are trying to do.

**Comment by joshco** [comment]
This would be super helpful.  Doesnt dokku start building the container based on some baseline docker? (ubuntu?).
If so, I'd like to replace that with another docker image as a baseline.
My current example is a django app that uses datascience libraries like scikit-learn, numpy, scipy, etc.  These are way too complicated installationwise to put in a django requirements file, or even to use the docker apt plugin.  I don't want to have to wait for all of those installations to be done when I send a new git repo of my app.

i tried looking through the source to find where we pull the base docker image from, but can't  can you tell me where that is?

**Comment by michaelshobbs** [comment]
@joshco I'm not fully understanding what you're looking for here. You can definitely now run any Dockerfile in dokku with any docker options. Is there something else you're specifically trying to do?

**Comment by michaelshobbs** [comment]
I posted this on IRC too but for completeness here.

One can set `$DOKKU_IMAGE` to override the build container's image OR one could replace the `progrium/buildstep` (this will change in the next major release to `gliderlabs/herokuish`) image with their own.  I do the latter for my own scipy/numpy/etc project.

**Comment by joshco** [comment]
I'm confused.  I think I'm close, but not sure what to do.  Can you share an example of how you are doing it?

here's the Dockerfile I included with my app:
````
FROM kaggle/python:latest

RUN curl -L -k https://github.com/gliderlabs/herokuish/releases/download/v0.3.0/herokuish_0.3.0_linux_x86_64.tgz -L |tar -xzC /bin

# install herokuish supported buildpacks and entrypoints
RUN /bin/herokuish buildpack install \
	&& ln -s /bin/herokuish /build \
	&& ln -s /bin/herokuish /start \
	&& ln -s /bin/herokuish /exec

````

here's the error I'm getting

````
remote: App container failed to start!!
remote: =====> pymysample container output:
remote:        cat: /app/Procfile: No such file or directory
remote: =====> end pymysample container output
remote: /usr/local/bin/dokku: line 49:  2679 Killed
````

**Comment by michaelshobbs** [comment]
Looks like it's trying to use a Procfile that's not there. I don't have enough information to tell you what is going on. 

A deployment with DOKKU_TRACE on might help.

**Comment by joshco** [comment]
Here's the build output with trace.   It seems like it isn't copying my app into the docker image
https://gist.github.com/joshco/3834495d9fd87772ce01

Heres the app
https://github.com/joshco/pymysample

**Comment by michaelshobbs** [comment]
@joshco it's doing a dockerfile deployment. If an app repo ships with a `Dockerfile` and no `$BUILDPACK_URL`, dokku will attempt a dockerfile deployment. (This is now documented in #1232; just submitted.)

If you include a `.env` file with `$BUILDPACK_URL` set, you should be good to go.
