### ISSUE TITLE
Setting Environment Variables

### ISSUE THREAD

**Issue by littleStudent** [progrium/dokku#1109]
It seems like setting the environment config is broken:
'dokku config <app>' returns different results than 'dokku run <app> printenv'

add:
switching to version 3.13 seems to fix the problem

**Comment by josegonzalez** [comment]
- What version are you running?
- How did you install dokku?
- How did you switch to a different version?
- What was the output of `dokku config APP`?
- What was the output of `dokku run APP printenv`?

**Comment by littleStudent** [comment]
* dokku v0.3.16
* i am running dokku for some time now, dont really remember how i installed it. 
* i updated by pulling the master `git pull --tags origin master` and running `sudo make install`. Process like on the upgrading page.

I did `dokku config:set APP VARIABLE=VALUE` and with `dokku config APP` the output was correct. So dokku was aware of the variable change i just did. But sadly my app used the old value. 
I ran `dokku run APP printenv` which returned that old value.

**Comment by josegonzalez** [comment]
Are you running on digital ocean?

**Comment by littleStudent** [comment]
yes i am

**Comment by josegonzalez** [comment]
I'll test this later, but I'm pretty sure this isn't possible.

**Comment by michaelshobbs** [comment]
I'm a little confused here. In the original issue you say switching to 3.13 seems to fix the issue. Is this not resolved then?

**Comment by littleStudent** [comment]
with version 3.16 i have this issue
with version 3.13 i do not have this issue

sorry for the confusion, thats what i meant.

**Comment by michaelshobbs** [comment]
For clarification, what buildpack are you using?

**Comment by michaelshobbs** [comment]
Using the nodejs buildpack this seems to work on master

```
root@dokku:~/dokku# dokku config node-js-app
=====> node-js-app config vars
testing: true
root@dokku:~/dokku# dokku run node-js-app printenv | grep testing
testing=true
```

**Comment by littleStudent** [comment]
I did some more testing.
I can change arbitrary variables like your example with `testing`, but:

I am trying to change the MONGO_URL variable, which is initially set from the mongodb plugin.
It seems like i cannot change this variable in dokku 3.16. But it does work in 3.13.

Could this be a possible case?

**Comment by michaelshobbs** [comment]
It would seem that this (https://github.com/jeffutter/dokku-mongodb-plugin/blob/8bd0fcb4848727303f48a409bc784b86503816f5/pre-release) would get run after your `config:set` and overwrite your change, no?

**Comment by michaelshobbs** [comment]
I'm very certain this behavior is as expected. Feel free to open an issue with the mongodb plugin project to confirm. Closing for now but feel free to re-open if my findings are incorrect.

```
root@dokku:~/dokku# dokku run node-js-app printenv | grep MONGO_URL
MONGO_URL=mongodb://node-js-app:VVhsN3U0dlNvNEhVZ3g4UkphaElLTzdNRXhnclV0UmtyRUx0NFpsa3VnZz0K@172.17.0.60:27017/node-js-app-production
root@dokku:~/dokku# dokku config:set node-js-app MONGO_URL=crap
-----> Setting config vars
       MONGO_URL: crap
-----> Restarting app node-js-app
-----> Releasing node-js-app ...

-----> node-js-app linked to jeffutter/mongodb:latest container
-----> Deploying node-js-app ...
-----> Running pre-flight checks
       CHECKS file not found in container: running simple container check...
-----> Waiting for 35 seconds ...
-----> Default container check successful!
=====> node-js-app container output:
       > node-js-sample@0.1.0 start /app
       > node index.js
       Node app is running at localhost:5000
=====> end node-js-app container output
-----> Running post-deploy
-----> Configuring node-js-app.dokku.me...
-----> Creating http nginx.conf
-----> Running nginx-pre-reload
       Reloading nginx
-----> Shutting down old container in 60 seconds
=====> Application deployed:
       http://node-js-app.dokku.me

root@dokku:~/dokku# dokku run node-js-app printenv | grep MONGO_URL
MONGO_URL=mongodb://node-js-app:VVhsN3U0dlNvNEhVZ3g4UkphaElLTzdNRXhnclV0UmtyRUx0NFpsa3VnZz0K@172.17.0.60:27017/node-js-app-production
```

**Comment by littleStudent** [comment]
You are right.
The interesting thing is that with dokku versions <= 3.13 the issue is not present.
So dokku stores the environment variables itself. And `dokku config APP` does not return the real variables but those stored in dokku?

I will ask the mongodb-plugin guys. Thx for clarification.

**Comment by michaelshobbs** [comment]
I'm not sure why or how this behaved differently in v0.3.13. 

For clarification, config vars are stored in `/home/dokku/APP/ENV` on the dokku host and subsequently placed in `/app/.profile.d/01-app-env.sh` as seen here: https://github.com/progrium/dokku/blob/aee2d9ca64f9f7a9ac94684635c67da63e94b6e7/plugins/00_dokku-standard/commands#L67

Depending on your version of buildstep, `dokku run APP bash` either initializes a shell with `/exec` in the image which runs this code: https://github.com/progrium/buildstep/blob/2014-12-16/builder/builder#L47-L49

or if you build from scratch or use the docker hub image (i think) herokuish will execute this similar function: https://github.com/gliderlabs/herokuish/blob/1d75eba54272ad81a31f1463fdfc5222885569e0/include/procfile.bash#L53-L64
