### ISSUE TITLE
Linode Dokku Stackscript not working.

### ISSUE THREAD

**Issue by nicksergeant** [progrium/dokku#1110]
Following the instructions for using the stackscript, I do get the email `Dokku Linode instance must be restarted`. After properly changing the kernel and `Xenity Distro`, I rebooted the server, but nothing happened. After about an hour I still hadn't received the "Installation is complete" email.

My guess is that Linode is not re-running the Stackscript on reboot.

Any ideas?

**Comment by josegonzalez** [comment]
I just pushed a few changes to the stackscript to sync up with the one in our repository, can you check it out and let us know if it worked?

**Comment by nicksergeant** [comment]
Yup, will do. Also, this might also be a Linode problem. As soon as I switched kernels, I was no longer able to SSH into the machine (though I believe I did at one point).

I have a ticket into Linode for this issue, but I'll spin up a new Linode w/ the updated Stackscript and report back.

**Comment by nicksergeant** [comment]
Same issues, it seems. Rebuilt with the Stackscript, got the restart email, SSHd into the server and here's the tail of `stackscript.log`:

```
Searching for GRUB installation directory ... found: /boot/grub
Searching for default file ... found: /boot/grub/default
Testing for an existing GRUB menu.lst file ... found: /boot/grub/menu.lst
Searching for splash image ... none found, skipping ...
Found kernel: /boot/vmlinuz-3.13.0-49-generic
Replacing config file /run/grub/menu.lst with new version
Updating /boot/grub/menu.lst ... done

=> 04/14 17:46:02 Sending notification email to nick@nicksergeant.com of required restart
```

**Comment by nicksergeant** [comment]
Here's the end of `setup_linode.txt`:

```
Processing manual pages under /usr/local/share/man...
1 man subdirectory contained newer manual pages.
66 manual pages were added.
0 stray cats were added.
150 old database entries were purged.
Adding user `dokku' ...
Adding new group `dokku' (1000) ...
Adding new user `dokku' (1000) with group `dokku' ...
Creating home directory `/home/dokku' ...
Copying files from `/etc/skel' ...
docker:x:999:
hostname: Name or service not known
dpkg: error processing package dokku (--configure):
 subprocess installed post-installation script returned error exit status 1
Setting up aufs-tools (1:3.2+20130722-1.1) ...
Setting up manpages-dev (3.54-1ubuntu1) ...
Processing triggers for libc-bin (2.19-0ubuntu6.3) ...
Errors were encountered while processing:
 dokku
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by nicksergeant** [comment]
FWIW, `dokku` does return the help, so it appears that it _might_ have been installed successfully...

**Comment by nicksergeant** [comment]
Yeah, some other issues:

```
root@dokku:~# dokku version
sudo: unable to resolve host dokku.nicksergeant.com
cat: /home/dokku/VERSION: No such file or directory
Unable to determine dokku's version
You have new mail in /var/mail/root
root@dokku:~# ls /home
dokku
root@dokku:~# ls /home/dokku
HOSTNAME
root@dokku:~# hostname
dokku.nicksergeant.com
```

**Comment by josegonzalez** [comment]
Hmm, it's been a while since I used linode - I mostly wrote that stackscript as we were having issues with certain users flailing over each other due to the xenify stuff - so I'll have to take a look tonight.

From your logs, It looks like `dokku plugins-install` is failing for you, somewhere [here](https://github.com/progrium/dokku/blob/master/debian/postinst#L15). Very odd, as the only place we call `hostname` that would be relevant is [here](https://github.com/progrium/dokku/blob/master/plugins/00_dokku-standard/install#L5).

**Comment by nicksergeant** [comment]
I've got a bunch of hostname errors. I did not actually have this hostname setup in DNS before I deployed, so I'm going to retry w/ DNS properly setup.

**Comment by nicksergeant** [comment]
After rebuilding w/ proper DNS, it seems everything was installed properly. Closing. Thanks!
