### ISSUE TITLE
Dokku errors if bin/release script not present

### ISSUE THREAD

**Issue by dbp** [progrium/dokku#1112]
According to the [documentation](https://devcenter.heroku.com/articles/buildpack-api#bin-release), the `bin/release` script is optional, and should only be run if present. But dokku errors out if it's not present. The error looks like:

```
remote: /build/compile.sh: line 73: /tmp/buildpacks/custom/bin/release: No such file or directory
```

See mietek/haskell-on-heroku#51 for more details.

**Comment by josegonzalez** [comment]
@progrium

**Comment by michaelshobbs** [comment]
@dbp i definitely see this issue using the latest buildstep release. However, master is now using herokuish. Can you build buildstep from master and see if the issue persists?

i.e.
```
docker rmi progrium/buildstep
BUILD_STACK=true make -e stack
```

You'll need to remove any containers that rely on `progrium/buildstep` first.

**Comment by dbp** [comment]
@michaelshobbs That looks like it is fixed - thanks for figuring that out! Do you know when that'll get out as a release? I have a fork of the mentioned buildpack that has a dummy `bin/release` file, but it'd be nice not to have that.

**Comment by michaelshobbs** [comment]
@progrium can we get a `buildstep` release cut?

**Comment by seanhess** [comment]
I'm interested in this as well!

**Comment by progrium** [comment]
I thought a PR was being made to use Herokuish directly.

On Thu, Apr 23, 2015 at 9:57 PM, Sean Hess <notifications@github.com> wrote:

> I'm interested in this as well!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/progrium/dokku/issues/1112#issuecomment-95700737>.
>



-- 
Jeff Lindsay
http://progrium.com

**Comment by josegonzalez** [comment]
@progrium tests fail and we'd want to release against a versioned build to ease our own debugging.

**Comment by michaelshobbs** [comment]
@progrium @josegonzalez 
where did we end up on the whole versioned herokish build thing?

**Comment by mietek** [comment]
What’s the status of this issue?

**Comment by josegonzalez** [comment]
We've switched to herokuish, so this can be closed. Please comment if you still see this as an issue in the latest version of dokku :)
