### ISSUE TITLE
SSL for all apps not working in 0.3.17

### ISSUE THREAD

**Issue by sglebs** [progrium/dokku#1114]
Hi,

   I successfully installed 0.3.17 on an Ubuntu 14.04 at Digital Ocean and deployed the Hello World app in Node. Then I tried to enable SSL for all apps at once (it is a STAGING box) as follows:

- generated self-signed certificate following http://www.akadia.com/services/ssh_test_certificate.html
- ssh root@104.131.71.99 "mkdir /home/dokku/tls; chown dokku.dokku /home/dokku/tls"
- scp server.key root@104.131.71.99:/home/dokku/tls
- scp server.crt root@104.131.71.99:/home/dokku/tls
- ssh root@104.131.71.99 "chown dokku.dokku /home/dokku/tls/*"
- on the server: vi /etc/nginx/conf.d/dokku.conf and uncommented these two lines (removed the #):
  ssl_certificate /home/dokku/tls/server.crt;
  ssl_certificate_key /home/dokku/tls/server.key;

  I restarted nginx and https still does not work.

  So, I tried to enabled SLL just for this app:

* tar cvf server.tar server.key server.crt 
* ssh dokku@104.131.71.99 nginx:import-ssl < server.tar node-js-sample

   I restarted nginx and https works for this app.

   I'd like to enable https self-signed by default for all my apps, just like Heroku does out-of-they-box, without having to nginx:import-ssl . Is it possible?

   Did I miss any detail or is it a bug with 0.3.17?

Thanks!

**Comment by michaelshobbs** [comment]
For site-wide ssl, I believe the CN of the cert must match a domain associated with your app. 
in some fashion at least. (i.e.*.domain.com)

Would be good to see the generated nginx.conf from the app when using site-wide ssl.

**Comment by sglebs** [comment]
Right now I have the certs in both places: /home/dokku/tls (manually copied by me) and in /home/dokku/node-js-sample/tls (I presume that inserted by nginx:import-ssl), because of the way I run the steps above.

Here's the conf:

```conf
root@dokku-staging:/home/dokku/node-js-sample# cat nginx.conf 
server {
  listen      [::]:80;
  listen      80;
  server_name BetDev;
  return 301 https://BetDev$request_uri;
}

server {
  listen      [::]:443 ssl spdy;
  listen      443 ssl spdy;
  server_name BetDev;
  ssl_certificate     /home/dokku/node-js-sample/tls/server.crt;
  ssl_certificate_key /home/dokku/node-js-sample/tls/server.key;

  keepalive_timeout   70;
  add_header          Alternate-Protocol  443:npn-spdy/2;
  location    / {
    proxy_pass  http://node-js-sample;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection upgrade;
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header X-Request-Start $msec;
  }
  include /home/dokku/node-js-sample/nginx.conf.d/*.conf;
}
server {
  listen      [::]:80;
  listen      80;
  server_name node-js-sample.dokku.fui.ai ;
  location    / {
    proxy_pass  http://node-js-sample;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection upgrade;
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header X-Request-Start $msec;
  }
  include /home/dokku/node-js-sample/nginx.conf.d/*.conf;
}
upstream node-js-sample { server 172.17.0.29:5000; }
```

**Comment by michaelshobbs** [comment]
Ok so you don't want both. Go ahead and remove the app-level one to simplify troubleshooting. Then make sure the CN of the site-wide self-signed cert is either `node-js-sample.dokku.fui.ai` or more correctly `*.dokku.fui.ai`. Then you should be good to go barring any bugs of course.
