### ISSUE TITLE
ENV var SSL_CERT_FILE breaks build

### ISSUE THREAD

**Issue by joshco** [progrium/dokku#1115]
If the app ENV has a SSL_CERT_FILE present, this screws up the build.
It seems to interfere with curl
I initially had the variable set to a cacert.pem inside my app tree.  I changed it to a file on the host system (outside docker/dokku) thinking that might help, but it doesnt.
Only removing SSL_CERT_FILE app ENV var makes it work again.

````
-----> Cleaning up...
-----> Building vwf from buildstep...
-----> Adding BUILD_ENV to build environment...
-----> Ruby app detected
/tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/shell_helpers.rb:49:in `run!': Command: 'set -o pipefail; curl --fail --retry 3 --retry-delay 1 --connect-timeout 5 --max-time 30 https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/bundler-1.6.3.tgz -s -o - | tar zxf - ' failed unexpectedly: (LanguagePack::Fetcher::FetchError)

gzip: stdin: unexpected end of file
````

**Comment by michaelshobbs** [comment]
This seems related. http://stackoverflow.com/questions/9564940/who-reads-the-value-of-envssl-cert-file
More detail here: http://stackoverflow.com/questions/14286265/how-to-use-ssl-cert-file-for-openssl-windows-openssl-1-0-1c

As this ENV var is quite generic and used by system libs such as OpenSSL, I would (obviously) advise against using it. 

Closing as this seems unactionable. Please feel free to re-open if necessary.

**Comment by joshco** [comment]
I can workaround, OK to close.

This variable is used to specify a specific set of ca certs.  I've used it for two reasons
1) higher security by ensuring a clean set of certs rather than depending on the what's on the OS or hosting platform (heroku et al)
2) Enabling an app to work properly when doing SSL connections where the OS or hosting platform doesnt have a correctly configured cert file.  (This is common on Windows*)

Setting this var like I did in my app worked fine on heroku.  Something unusual must be going on with dokku.  Perhaps the fact that we're setting ENV vars during the build process *outside the container* when the vars apply *to the inside of the container*.  So, an in-container path might not resolve.  However, the host system path approach also should have worked.

*yup, I doubt anyone would try to do dokku on windows, but it means my app configuration cant be the same across platform and I lose reason 1

**Comment by michaelshobbs** [comment]
Oh I see. Your intent actually is to override a system-level var. That wasn't immediately clear to me. I think your assessment about when we source in vars is spot on. 

We could potentially filter what we source outside of the container...?

**Comment by andyjeffries** [comment]
I've just been bitten by this too! Maybe it should output a warning if you use config:set with this setting name? Given that it seems to really break things...

**Comment by josegonzalez** [comment]
@andyjeffries there is a potentially infinite number of settings you can set that would conflict with something, so I don't think thats the best solution.

Can you add a troubleshooting entry for this?
