### ISSUE TITLE
executable file not found in $PATH"

### ISSUE THREAD

**Issue by mapreal19** [progrium/dokku#1116]
I'm having the following error when trying to create a database container.

Command: 

    dokku postgresql:create my_app

Error: 

    time="2015-04-17T17:53:23Z" level=fatal msg="Error response from daemon: Cannot start container 8d5ef4aee040437215abe7384063b5f7e7f6766710cd0fbfacc891c17c654f91: [8] System error: exec: \"exit\": executable file not found in $PATH" 

Any idea of what could be wrong?

**Comment by josegonzalez** [comment]
Do you have more log output than that? Can you run that command with `dokku trace on`/

**Comment by mapreal19** [comment]
Sure. Here it is: https://gist.github.com/mapreal19/07b1d277c25db5fa2fa0

**Comment by mapreal19** [comment]
Updating the postgresql plugin solved the issue. Thanks!
