### ISSUE TITLE
How to use Blackfire - part of heroku php build pack 

### ISSUE THREAD

**Issue by eddiejaoude** [progrium/dokku#1122]
Is it possible to use Blackfire on Dokku?

It is part of the Heroku build pack for PHP https://github.com/heroku/heroku-buildpack-php/blob/0adff36b9d648a3f836271fb7a6dc7eafff74356/conf/php/conf.d/ext-blackfire.ini

**Comment by josegonzalez** [comment]
It should be, is there something that isn't working?

**Comment by eddiejaoude** [comment]
I am not sure where to start?

On **Heroku** it says just to use `heroku addons:add blackfire` but I appreciate it is not exactly the same for **Dokku**. 

From the [dokku plugins docs](http://progrium.viewdocs.io/dokku/plugins) it talks about cloning a repo.

Any advice is appreciated.

**Comment by josegonzalez** [comment]
Seems like you'll need to run the agent inside of your container [like so](https://blackfire.io/getting-started). You can use a plugin like supervisord to run another agent in your container alongside your app.

**Comment by eddiejaoude** [comment]
Great, I will have a play. Thanks for quick response! :+1:
