### ISSUE TITLE
Updates for plugin conventions

### ISSUE THREAD

**Issue by patrickjahns** [progrium/dokku#1127]
I did a search, but haven`t found anything regarding this matter.

Currently I feel that plugins are lacking the following information
- Version
- Author
- Url for source

I have seen the idea of creating a common plugin repository - in light of that I propose to add guidelines for writing plugins, that include these 3 informations.

My current idea is to require VERSION, AUTHOR, URL files in the plugins. Eventually also a NAME file

Additionally it would be great if the plugins command could also display more information. Including the current Version number of the plugin to keep track if it is up 2 date or not.

**Comment by josegonzalez** [comment]
@progrium

**Comment by patrickjahns** [comment]
In light of creating a plugin database had had a couple more thoughts about this today. 

I am not sure what the current plan for offering "official tested" plugins is, but here are my thoughts:
- it would be great to have one place where plugins are listed and downloadable
For this I propose creating a seperate repository (dokku-plugins) with each 3rd party plugin being a submodule in git.
This way we could maintain a repository easily and if a user wants to add their plugin, they can create a PR with their repository as submodule
(See the pelican template repo for an example https://github.com/getpelican/pelican-themes)

To ease up plugin maintainance it would be great if dokku fetches a list of available plugins with their version (maybe a single file inside the dokku-plugins repository that includes lines like NAME:VERSION:AUTHOR (`:` being examplatory - maybe use different delimiter?) 

Then dokku would be able to compare local installed versions if the ones in the repository and eventually offer to update via a certain command.

doku plugins could look something like this
```
dokku plugins:list
====> Enabled plugins
Name                   Version                   Author (url?)
...                           
====> Available plugins 
Name                   Version                   Author (url?)
.... 
```

`dokku plugins:enable <plugin>`
This will fetch the plugins from git and install the requested one

`dokku plugins:update <plugin>`
To update a plugin

`dokku plugins:disable`
To disable a certain plugin

Is this feasible or do you have another idea for the plugin index in mind?

**Comment by patrickjahns** [comment]
A good releasepoint for the new plugin system would be if we already start to rename the pluginhooks in favor for herokuish (see #1128). If that change already breaks current plugins, a good start would be then to define the new plugin structure with appropiate hooks, required files and so on. 

And at the same time we could publish the plugin repository displaying example plugins

**Comment by progrium** [comment]
Work has been started on mostly this. Search my github account for plugn.
Would love contributions there as it will likely be used by Dokku in the
future.

On Tuesday, April 21, 2015, Patrick Jahns <notifications@github.com> wrote:

> A good releasepoint for the new plugin system would be if we already start
> to rename the pluginhooks in favor for herokuish (see #1128
> <https://github.com/progrium/dokku/pull/1128>). If that change already
> breaks current plugins, a good start would be then to define the new plugin
> structure with appropiate hooks, required files and so on.
>
> And at the same time we could publish the plugin repository displaying
> example plugins
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/progrium/dokku/issues/1127#issuecomment-94793738>.
>


-- 
Jeff Lindsay
http://progrium.com

**Comment by patrickjahns** [comment]
Can you elaborate more on what needs to be done with plugn and in order to get it compatible with dokku. As well as how can we build a guideline for developing the new pluggins integrating some of the lessons learned from dokku and other projects

**Comment by josegonzalez** [comment]
Closing as #1228 should take care of this in our upcoming 0.4.0 release :)
