### ISSUE TITLE
Deploying Basic Rails App to Dokku- Can't Find Build Pack

### ISSUE THREAD

**Issue by santoshsankar** [progrium/dokku#1130]
Hi- I am trying to get a Dokku Droplet on Digital Ocean and followed [this] (https://www.digitalocean.com/community/tutorials/how-to-use-the-digitalocean-dokku-application) tutorial.

I receive the below error:

```
santoshs-mbp:muddypawsite santoshsankar$ git push dokku master
Counting objects: 99, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (82/82), done.
Writing objects: 100% (99/99), 239.10 KiB | 0 bytes/s, done.
Total 99 (delta 6), reused 0 (delta 0)
-----> Cleaning up...
-----> Building muddypawlabs.com from buildstep...
-----> Adding BUILD_ENV to build environment...
-----> Unable to select a buildpack
To dokku@muddypawlabs.com:muddypawlabs.com
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'dokku@muddypawlabs.com:muddypawlabs.com'
```

I tried following [this] (https://www.digitalocean.com/community/tutorials/how-to-use-the-dokku-one-click-digitalocean-image-to-run-a-ruby-on-rails-app) but also had no luck

I'm new to Dokku and still ramping up on Rails so any insight would be valuable.

**Comment by michaelshobbs** [comment]
The buildpack system uses a somewhat naive approach to detecting you repo's language. For example the ruby buildpack just looks for a Gemfile.

See here: https://github.com/heroku/heroku-buildpack-ruby/blob/master/bin/detect#L5

I'm guessing you don't have one? (Surprising actually) So you can include one in your repo or tell dokku which buildpack you'd like to use by following this: http://progrium.viewdocs.io/dokku/application-deployment (Specifying a custom buildpack section)

If you still run into issues follow the troubleshooting guide (http://progrium.viewdocs.io/dokku/troubleshooting) and post a gist of your deployment with dokku trace on.

**Comment by santoshsankar** [comment]
Thank you!

Despite only being a page with an image on it, I have a Gemfile-- odd that it wasn't picked up. I have a .env to tell dokku which buildpack to pick up. Here is the gist with dokku trace on.

https://gist.github.com/santoshsankar/05b79639da248e69d66f#file-gistfile1-sh

It appears there is something wrong with nginx?

**Comment by michaelshobbs** [comment]
It seems as though you set BUILDPACK_URL to be the static buildpack? You'll want to use the url for the ruby buildpack I would think.

**Comment by santoshsankar** [comment]
I changed it to BUILDPACK_URL=https://github.com/heroku/heroku-buildpack-ruby.git and the Ruby app is detected but there is still a fail.

https://gist.github.com/santoshsankar/6828862e7c0cb171998b

**Comment by michaelshobbs** [comment]
It would you are suffering from https://github.com/gliderlabs/herokuish/issues/19 which is fixed in master by this https://github.com/gliderlabs/herokuish/pull/27.

You'll want to create your buildstep image from master. 

as root:
```
dokku --force apps:destroy <your_app_name>
dokku cleanup
docker rmi progrium/buildstep
cd /path/to/dokku/repo
BUILD_STACK=true make -e stack
```

Then deploy your app again.

**Comment by santoshsankar** [comment]
Hi Michael,

I performed the steps you suggested on the DO server as root and continue
to get an error. Please see this gist:
https://gist.github.com/santoshsankar/44b6a7047b4fdcaa67e8

On Tue, Apr 21, 2015 at 1:33 PM, Michael Hobbs <notifications@github.com>
wrote:

> It would you are suffering from gliderlabs/herokuish#19
> <https://github.com/gliderlabs/herokuish/issues/19> which is fixed in
> master by this gliderlabs/herokuish#27
> <https://github.com/gliderlabs/herokuish/pull/27>.
>
> You'll want to create your buildstep image from master.
>
> as root:
>
> dokku --force apps:destroy <your_app_name>
> dokku cleanup
> docker rmi progrium/buildstep
> cd /path/to/dokku/repo
> BUILD_STACK=true make -e stack
>
> Then deploy your app again.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/progrium/dokku/issues/1130#issuecomment-94880844>.
>



-- 
Santosh Sankar
santoshsankar@gmail.com | (410) 340-9288
www.santoshsankar.com

Penn State IFC/Panhellenic Dance Marathon | www.thon.org

**Comment by joshco** [comment]
If your rails app is just a static page, is it in a public git repo? Then we can clone the app and repo the problem.

**Comment by michaelshobbs** [comment]
@santoshsankar deploying this static rails app work on the release for me. https://github.com/michaelshobbs/static_rails_app_dokku (forked from @joshco. thank you :smile:)

**Comment by josegonzalez** [comment]
@santoshsankar bump :)

**Comment by santoshsankar** [comment]
Hi! Sorry, been traveling. I am going to give it another go this week

Santosh Sankar
santoshsankar@gmail.com | (410) 340-9288
http://www.santoshsankar.com

**Comment by josegonzalez** [comment]
Closing as there hasn't been any response in a few months.
