### ISSUE TITLE
Unable to retrieve IP

### ISSUE THREAD

**Issue by jagrutireddymulagundla** [progrium/dokku#1132]
We have followed all the steps on the following link: http://progrium.viewdocs.io/dokku/dns. But when we get to retrieving IP, it does not retrieve any IP.

host test.myserver.example.tld
host xyzzy.myserver.example.tld

**Comment by josegonzalez** [comment]
Thats an example of the command you are supposed to run. What exactly are you trying to do?

**Comment by jagrutireddymulagundla** [comment]
ok. We are trying to implement Dokku within a load balancer. In the example above what is test and xyzzy? Are those applications?

**Comment by josegonzalez** [comment]
Yes, those are applications.

**Comment by jagrutireddymulagundla** [comment]
Should those application be running in order to return the IP? For example i have an nginx image so can i use nginx in place of test?

**Comment by josegonzalez** [comment]
Can you go on our irc room? It's linked to in the readme, we'll be able to help you much better there.

Closing as this is asking for support rather than a bug/feature request.
