### ISSUE TITLE
starting containers on demand (opon request)

### ISSUE THREAD

**Issue by patrickjahns** [progrium/dokku#1134]
As mentioned in #1118 here is another idea: 

Also I am curious if it would be possible to create containers that dynamically start on requests and stop after some idle time again. 

A possible solution for this could be to have a lightweight go server component, that listens on a certain port for requests. If nginx can`t reach any upstream source, this server would be available, the request would arrive. The go server would check if a container is already running, just drop the connection. If it is not running, check if it is being provisioned, if not, start provisioning and wait for X seconds before dropping the connection so that nginx would switch to the running container upstream.

@joshco 
You wrote about load based scaling and modifying nginx - can you share a bit more here what your thoughts are

**Comment by josegonzalez** [comment]
This sounds like a good candidate for a plugin and not dokku core. On-demand containers seems like something we'd get wrong most of the time or cause headaches for users (why did my request time out if my container is running?).
