### ISSUE TITLE
Vagrant Install Error

### ISSUE THREAD

**Issue by chrisRidgers** [progrium/dokku#1139]
Problem installing similar to https://github.com/progrium/dokku/issues/1034

Steps taken:

```bash
git clone https://github.com/progrium/dokku
cd dokku
vagrant up
```

Proceeds to build until error.  Thoughts?

**Comment by josegonzalez** [comment]
Can you paste the errors you get? If I run exactly those steps, I get a working dokku install.

**Comment by chrisRidgers** [comment]
==> dokku: make -e stack
==> dokku: make[1]: Entering directory `/root/dokku'
==> dokku: Start building buildstep
==> dokku:
==> dokku: gzip:
==> dokku: stdin: unexpected end of file
==> dokku: time="2015-04-22T22:03:02Z" level=fatal msg="Error response from daemon: Untar exit status 1 unexpected EOF"
==> dokku: make[1]: Leaving directory `/root/dokku'
==> dokku: make[1]: *** [stack] Error 1
==> dokku: make: *** [dependencies] Error 2
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

I'm currently re running the install, but it's been hanging at the start building build step section for around 20 mins now.

If it kicks out the same error again I'll find the log it mentions.

Running on OS X Yosemite 10.10.2

**Comment by chrisRidgers** [comment]
Second build succeeded.

The machines up, but I wouldn't say its working:

Attempting to git push an application results in 

git push staging master
ssh: connect to host dokku.me port 2222: Connection refused
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

In /etc/hosts I have:

10.0.0.2    dokku.me

And in ~/.ssh/config

Host dokku.me
    Port 2222

From the web interface I enabled checked the 'use virtual host naming box' and changed the domain name to 'staging'.

The remote for my repo is:

dokku@dokku.me:staging

**Comment by chrisRidgers** [comment]
/home/dokku/VHOST and /home/dokku/HOSTNAME both contain 'staging'

and my ssh key has been added twice to /home/dokku/.ssh/authorized_keys
once through the web interface, and once using

cat ~/.ssh/id_rsa.pub | make vagrant-acl-add

Not sure what else to add.

**Comment by josegonzalez** [comment]
Can you do the following:

```shell
vagrant destroy -f
vagrant up
```

And gist the *entire* log output for me? https://gist.github.com.

**Comment by chrisRidgers** [comment]
At the risk of sounding like a complete imbecile...

Which log would you like, and would you like it prior to running those commands or after?

**Comment by josegonzalez** [comment]
The output of `vagrant up`.

**Comment by chrisRidgers** [comment]
Currently in work, I'll post that gist once I'm back home.

**Comment by chrisRidgers** [comment]
https://gist.github.com/chrisRidgers/6eeec0f03b9774b6a730

Here's that gist for you.  I'll hold off on doing anything with the install so you've got a clean install for me to try stuff on.

**Comment by josegonzalez** [comment]
Is that the entire output? And is this install buggy?

**Comment by chrisRidgers** [comment]
haven't tested this one yet, Ill go through the web interface again if you like?  Any recommend settings for me to test?

**Comment by josegonzalez** [comment]
Nope, just whatever you'd normally do. I think you just had a bum vagrant run, maybe a network issue :)

**Comment by chrisRidgers** [comment]
Set the hostname to staging, enabled virtual host naming.

pushing the git project to dokku@dokku.me:staging results in 

git push staging
ssh: connect to host dokku.me port 2222: Connection refused
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by josegonzalez** [comment]
Did you set `dokku.me` in your hosts file?

**Comment by chrisRidgers** [comment]
10.0.0.2    dokku.me

(got me through to web interface, but now when i try to connect i get a safari cannot connect to web server error)

**Comment by josegonzalez** [comment]
What is the output of `vagrant ssh-config`? Sounds like maybe it just doesn't see the vagrant box because the ip or port are wrong (can happen if you have multiple vagrant vms or a weird network).

**Comment by chrisRidgers** [comment]
ah here we go.  somethings up.

The provider for this Vagrant-managed machine is reporting that it
is not yet ready for SSH. Depending on your provider this can carry
different meanings. Make sure your machine is created and running and
try again. Additionally, check the output of `vagrant status` to verify
that the machine is in the state that you expect. If you continue to
get this error message, please view the documentation for the provider
you're using.

And vagrant status displays:

Current machine states:

empty                     not created (virtualbox)
dokku                     running (virtualbox)
dokku-deb                 not created (virtualbox)
build                     not created (virtualbox)

This environment represents multiple VMs. The VMs are all listed
above with their current state. For more information about a specific
VM, run `vagrant status NAME`.

**Comment by josegonzalez** [comment]
`vagrant ssh-config dokku`

**Comment by chrisRidgers** [comment]
Host dokku
  HostName 127.0.0.1
  User vagrant
  Port 2222
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile /Users/Chris/dokku/.vagrant/machines/dokku/virtualbox/private_key
  IdentitiesOnly yes
  LogLevel FATAL
  ForwardAgent yes

**Comment by chrisRidgers** [comment]
And in case your next question is, what's in ~/.ssh/config:

Host dokku.me
	Port 2222

**Comment by josegonzalez** [comment]
We're on irc if you can go there, it's probably easier to debug that way :)

**Comment by chrisRidgers** [comment]
I can but not tonight, I've got work in the morning.

**Comment by josegonzalez** [comment]
Sure, I idle as `savant` there :)

**Comment by warden1975** [comment]
Just attempting to add to this issue instead of creating new one, could you also help me, I'm stuck with this:
```
==> dokku: Fetched 1,985 kB in 46s (42.6 kB/s)
==> dokku: Reading package lists...
==> dokku: apt-get install -qq -y lxc-docker
==> dokku: sleep 2 # give docker a moment i guess
==> dokku: apt-get install -qq -y help2man
==> dokku: apt-get install -qq -y man-db
==> dokku: make -e stack
==> dokku: make[1]: Entering directory `/root/dokku'
==> dokku: Start building buildstep
```

**Comment by warden1975** [comment]
Okay, since I posted, it continued now...

**Comment by chrisRidgers** [comment]
If you run into the issue after buildstep has finished, try switching your port in .ssh/config to 22 (rather than 2222).

With help from jose we realised that the docs were wrong -- not sure if they've been fixed yet.

**Comment by chrisRidgers** [comment]
Ran into this error again last night :P

Good times.
