### ISSUE TITLE
Where CHECKS file should be storred?

### ISSUE THREAD

**Issue by iofjuupasli** [progrium/dokku#1143]
Here is my Dockerfile

```
FROM node
COPY . /usr/src/app
WORKDIR /usr/src/app
RUN npm install
RUN npm run buildProd
WORKDIR /usr/src/app/backend
ENV NODE_ENV production
CMD [ "node", "app.js" ]
EXPOSE 80
EXPOSE 443
```

I have `CHECKS` in `.` folder (`/usr/src/app` in container). Also I tried to place it in `./backend` as it's workdir in the end.

But dokku still says me

```
CHECKS file not found in container
```

I found this line in sources https://github.com/progrium/dokku/blob/master/plugins/checks/check-deploy#L68 . Does it mean that I should copy `CHECKS` to `/app` in container?

**Comment by 3onyc** [comment]
Dokku fetches the file from `/app/CHECKS` yes, so you'd have to `ADD` it there, or however you want to add it.

**Comment by josegonzalez** [comment]
What @3onyc said :)

**Comment by michaelshobbs** [comment]
This brings up a good point. We should document the Dockerfile 'nuances'. We sort of assume a buildstep style directory structure.

**Comment by iofjuupasli** [comment]
Thank you, @3onyc 
@michaelshobbs agree about documenting it. Now it's almost impossible to guess where this file should be stored without source code.
Is using `/app` common for docker?
If not, is there a way to use workdir to find CHECKS (in docker in general)? Or maybe env var, that contains path to root of project folder?

**Comment by michaelshobbs** [comment]
It's the Heroku pattern and hence our pattern. :smile:

**Comment by 3onyc** [comment]
I agree with @iofjuupasli that it would be nice if `<WORKDIR>/CHECKS` is used if present.

**Comment by joshco** [comment]
The WORKDIR would be unavailable to apps that are pushed with git.
Checking in the WORKDIR could happen, though we'd need to be clear on what happens if both are present.  Choose app first then fall back to workdir?

My sense is that this is extra complexity that might be unneeded with better documentation.

**Comment by joshco** [comment]
Also, it's likely to lead to confusion problems where someone is wondering why the CHECKS arent being honored, when the reality is that they dont realize there is a CHECKS file in the app dir that is overriding the one in the WORKDIR

**Comment by 3onyc** [comment]
`WORKDIR` being unavailable in buildstep apps isn't a problem if we check the type of app, and only check for it in dockerfile type apps.

And when `WORKDIR` isn't present in a dockerfile app, fall back to  `/app/CHECKS`.

This would add complexity, however dockerfile apps are quite different from buildstep ones, the question is whether it's worth it in this case.

**Comment by joshco** [comment]
What are we gaining by doing this?  avoiding the ADD command in the docker file?
I kinda feel that since CHECKS is an infrastructure thing (dokku) rather than an app thing, the explicit step makes sense.

**Comment by iofjuupasli** [comment]
Usually I expect that tools will use current workdir, if they need some specific files for running.
So I don't copy `package.json` to `/home/username/npm/package.json` every time I running `npm install`. And to work with git, I shouldn't copy project to `/git/repository`.
On the other hand, I can't see problems with use `/app` only.
The main thing is that it should be documented.

**Comment by ypadlyak** [comment]
What would be the Dockerfile command?

**Comment by michaelshobbs** [comment]
`ADD ./CHECKS /app`

**Comment by n2liquid** [comment]
I've read the documentation and this whole thread, tried 3 things, none worked, and I still have no clue where that file should go or what to add to the Dockerfile.

First I've tried adding it to the repository root, not noticing the "For dockerfile-based deploys, the file must be in /app/CHECKS within the container" note on the documentation.

Then I've moved the file into the `<repo root>/app/CHECKS`. Still no success. So I searched the web, found this thread, obviously agreed with everyone who said checking the repository root as well would be a really good idea, moved `CHECKS` back to the repository root and tried adding `ADD ./CHECKS /app` to the Dockerfile, but it still doesn't work.

Does anyone know why the `ADD` command produced no errors, but had no effect either?

Also, this thread is from 2015. How come the documentation doesn't even mention the Dockerfile needs to be changed and what goes there exactly?

**Comment by josegonzalez** [comment]
Hi @n2liquid!

As you stated, this thread is about 2 years old. Please don't resurrect old issues like this, you're notifying a bunch of people who probably had this issue solved or don't use Dokku anymore.

As you mentioned, you missed the note in the documentation as to where it needs to be added. Sounds like the documentation is correct here and you just weren't paying attention. Your tone at the end of the comment isn't appreciated.

Please open a separate issue with all the information we ask for so that we can help you debug the problem you are having, and hopefully clarify the documentation further.
