### ISSUE TITLE
ps:restartall not a valid replacement for deploy:all

### ISSUE THREAD

**Issue by Benjamin-Dobell** [progrium/dokku#1154]
Loosely related to https://github.com/progrium/dokku/issues/82 etc.

```deploy:all``` is marked as deprecated and just calls out to ```ps:restartall```, however as far as I can tell ```deploy:all``` (i.e. the old implementation that literally called deploy for each app) was necessary functionality.

```ps:restartall``` doesn't setup $APP/IP and $APP/PORT etc.

In my case, I've just tried to upgrade from ```v0.3.9-33-gf1bfb3e```. __Ramblings:__ *My fifth attempt actually - as pretty much anything that could have broken, has broken e.g DOCKER_OPTIONS has become DOCKER_OPTIONS_$PHASE and been officially integrated, so I had to copy my files manually. The old dokku-logging-supervisord plugin I had installed forks processes infinitely against the new buildstep etc. To be fair, these are/were all third-party plugins, but it does highlight the need to stabilise the plugin API etc. (I think my dokku-graduate plugin may have broken as well).*

Anyway, this particular issue seems to be with Dokku itself, as opposed to a plugin. Upon upgrading all my containers were shut down - fair enough. But they didn't start back up (3 of 8 did...?). This is when I attempted to perform:

    sudo dokku deploy:all

Which didn't work, but yet specifically calling:

    sudo dokku deploy <app>

for ~~each app~~ some apps allows them to deploy (*well, sort of - the docker containers haven't had their ports exposed/mapped, still looking into that*).

Anyway, ```dokku ps:restartall``` wasn't sufficient because it doesn't create $APP/IP etc. Which in my case don't exist at all because that file wasn't around in ```v0.3.9-33-gf1bfb3e```.

It would seem to me that ```deploy:all``` should stick around (and in its previous form, where it actually deploys) - unless I'm totally missing something (very possible).

**Comment by michaelshobbs** [comment]
Hmm, interesting. 

`dokku ps:restartall`:(https://github.com/progrium/dokku/blob/713a8d4f312d03f3c7ef0a7dc0c08eeaab917150/plugins/ps/commands#L92-L97)

calls `dokku ps:restart`: (https://github.com/progrium/dokku/blob/713a8d4f312d03f3c7ef0a7dc0c08eeaab917150/plugins/ps/commands#L82-L90)
 on all apps that have been deployed. (i.e. have a CONTAINER file) 

which then calls `release_and_deploy()`: https://github.com/progrium/dokku/blob/713a8d4f312d03f3c7ef0a7dc0c08eeaab917150/plugins/ps/commands#L5-L24 
that runs `dokku release $APP` and `dokku deploy $APP`

This will subsequently yield running apps and the aforementioned $APP/IP etc.

```
root@dokku:~/dokku# dokku apps
=====> My Apps
node-js-app
static-rails-app

root@dokku:~/dokku# dokku ps:stop node-js-app
Stopping node-js-app ...
root@dokku:~/dokku# dokku ps:stop static-rails-app
Stopping static-rails-app ...

root@dokku:~/dokku# docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

root@dokku:~/dokku# rm /home/dokku/*/IP
root@dokku:~/dokku# ls -l /home/dokku/*/IP
ls: cannot access /home/dokku/*/IP: No such file or directory

root@dokku:~/dokku# dokku ps:restartall
-----> Releasing node-js-app ...
-----> Deploying node-js-app ...
...
=====> Application deployed:
       http://node-js-app.dokku.me

-----> Releasing static-rails-app ...
-----> Deploying static-rails-app ...
...
=====> Application deployed:
       http://static-rails-app.dokku.me

root@dokku:~/dokku# docker ps
CONTAINER ID        IMAGE                           COMMAND             CREATED             STATUS              PORTS               NAMES
9735cdc18946        dokku/static-rails-app:latest   "/start web"        3 minutes ago       Up 3 minutes                            agitated_ptolemy
b3ede1fba432        dokku/node-js-app:latest        "/start web"        4 minutes ago       Up 4 minutes                            dreamy_hypatia

root@dokku:~/dokku# ls -l /home/dokku/*/IP
-rw-r--r-- 1 dokku dokku 12 Apr 29 17:47 /home/dokku/node-js-app/IP
-rw-r--r-- 1 dokku dokku 12 Apr 29 17:48 /home/dokku/static-rails-app/IP
```

Point being that `deploy:all` and `ps:restartall` are actually doing the same thing and I can't replicate the issue. Any additional info is welcome.

**Comment by Benjamin-Dobell** [comment]
Okay, I've found the real problem. It's related.

I killed all the docker containers than ran:

```
$ sudo dokku ps:restartall
-----> Releasing analytics ...
-----> Injecting Logging Supervisor ...
supervisor is already installed (skipping apt-get update/install)
-----> Deploying analytics ...
-----> Running pre-flight checks
-----> Running post-deploy
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   131    0   104  100    27    186     48 --:--:-- --:--:-- --:--:--   187
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    17  100    17    0     0     45      0 --:--:-- --:--:-- --:--:--    45
-----> Configuring analytics.snaploader.com...
-----> Configuring analytics.snaploaderdev.com...
DOKKU_APP_LISTEN_PORT: 5000
DOKKU_APP_LISTEN_IP: 172.17.0.170
-----> Creating http nginx.conf
-----> Running nginx-pre-reload
       Reloading nginx
nginx: [emerg] host not found in upstream "renet-monitor" in /home/dokku/renet-monitor/nginx.conf:6
nginx: configuration file /etc/nginx/nginx.conf test failed
```

Which results in:

```
$ sudo docker ps
CONTAINER ID        IMAGE                    COMMAND             CREATED             STATUS              PORTS               NAMES
```

Where renet-monitor's nginx.conf looks like:

```
server {
  listen      [::]:80;
  listen      80;
  server_name renet-monitor.snaploader.com ;
  location    / {
    proxy_pass  http://renet-monitor;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection upgrade;
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header X-Request-Start $msec;
  }
  include /home/dokku/renet-monitor/nginx.conf.d/*.conf;
}
```

It is missing an upstream definition. After debugging this because DOKKU_APP_LISTEN_IP is undefined due to /home/dokku/renet-monitor/IP not existing - hence my original assessment.

Calling ```dokku deploy renet-monitor``` actually does resolve the problem (for this particular app anyway).

__The real issue__ is that $APP/IP, $APP/PORT etc. are populated for one app, then that app is deployed, then we repeat for the next app. However, the nginx config is left in a bad state so ```ps:restartall``` fail to deploy and bails out. As such it would seem we need to generate all these files first in one go, before actually deploying any instances.


Strangely, at the moment most my $APP/IP files have the same value, ```5000```, in them... probably which my containers port binding isn't working. I'll continue looking into that, it's quite possibly related.

**Comment by michaelshobbs** [comment]
What version are you on?

**Comment by Benjamin-Dobell** [comment]
```
$ dokku version
v0.3.17-55-g713a8d4
```

**Comment by Benjamin-Dobell** [comment]
Oh, to clarify the:

```
DOKKU_APP_LISTEN_PORT: 5000
DOKKU_APP_LISTEN_IP: 172.17.0.170
```

was some logging I added. Everything else is stock ```v0.3.17-55-g713a8d4```

**Comment by michaelshobbs** [comment]
Oh I see, validate_nginx is bombing on the nginx config for `renet-monitor` when deploying `analytics`. The question is how did the `renet-monitor` nginx config get hosed....

Now that you have them both working, does a `ps:restartall` work for you?

**Comment by josegonzalez** [comment]
It got hosed on reboot, the nginx conf was invalid. We need to generate them all *before* reloading/restarting nginx.

**Comment by michaelshobbs** [comment]
But how did it get hosed on reboot? Also :+1: on validate & restart after all configs are built.

**Comment by josegonzalez** [comment]
Docker doesnt persist the bound ports when it starts up again, so containers get new ones.

**Comment by michaelshobbs** [comment]
But `nginx -t` would have passed, no?

**Comment by josegonzalez** [comment]
Oh hmm probably right. How *did* they get hosed?

**Comment by Benjamin-Dobell** [comment]
They're not *hosed* in-so-far as they are old. I've just attempted to update from an old version of dokku, where nginx.conf didn't have (or require) an upstream definition (or $APP/IP files).

**Comment by Benjamin-Dobell** [comment]
Wait no, that can't be right, well not entirely. upstream was already required.

I must have ```nginx:build-config``` ran at some stage (which would have stripped upstream due to $APP/IP not existing)  when I realised my containers (the few that started) ports weren't binding. ```ps:restartall``` does seem a bit fragile in its current form.

I'm still going to have to look into what is going on with the port binding. I've got snapshots of this server (it's a non-production environment). So I'm going to roll-back and nail-down this upgrade process exactly before I do it in production.

**Comment by Benjamin-Dobell** [comment]
Alright, so the reason my ports weren't being exposed is because I have a VHOST file, basically I didn't realise the behaviour had changed to use internal IP addresses for upstream instead of ports (as was made the case in https://github.com/progrium/dokku/commit/948d7902f22c60dd9ba952306f8a6d75a7efe729) when a VHOST file is specified.

Of course I should have just been able to visit any of my apps URLs and I would have seen they were accessible... *but*, they weren't. For some reason nginx was in some wacky state where it kept taking me to default host (nginx default webpage). I tried restarting nginx, but my apps still weren't accessible. I noticed when I stopped nginx its worker processes kept running. So I killed those manually then started nginx again and everything was then accessible as it should be.

Heading to bed now. But when I get up I'm going to rollback my server and run through the upgrade process again keeping in mind what I've learnt and hopefully report back specifically what is breaking during the upgrade.

**Comment by Benjamin-Dobell** [comment]
Alright, finally got around to running the upgrade again from scratch. Something funky is definitely happening.

After the upgrade only 3 of my 8/9 containers are running. So I try ```dokku ps:restartall``` and one of my apps fails on pre-flight checks (and ps:restartall bails out). Specifically tracked it down to the ```PORT``` env var not being specified (which causes my app to fail because it doesn't have a port to bind to).

Then, the really peculiar thing is if I then run ```dokku ps:restart renet-monitor``` (the app that failed), the app boots up just fine.

So, then I try run ```dokku ps:restartall``` again (because a few apps still weren't running yet), then *BAM!* The exact same error with ```PORT``` being undefined for ```renet-monitor``` again.

I've put up an annotated gist that contains the exact commands I entered:
https://gist.github.com/Benjamin-Dobell/47ed874bacd00172183c

**Comment by josegonzalez** [comment]
What version are you upgrading from?

**Comment by Benjamin-Dobell** [comment]
@josegonzalez It's all in the gist:

```
$ dokku version
v0.3.9-33-gf1bfb3e
```

**Comment by josegonzalez** [comment]
Can you gist some specs on your apps? Which buildpacks, config files, etc.?

**Comment by Benjamin-Dobell** [comment]
Is there something specifically that you're after. There's 8 apps but every one of them is ruby. I think some of them have multiple buildpacks. However, the one that failed above (```renet-monitor```) is just ruby:

```
$ cat buildpack_version 
v129
$ cat buildpack_ruby_version 
ruby-2.1.2
``` 

However, I just ran ```ps:restartall`` again, and it proceeded past ```renet-monitor``` only to fail on another app, ```tiles```. Again plain ruby, has the exact same build-pack and ruby version (out of date ruby is actually my primary reason for updating dokku/buildstep). Both apps are actually among the simplest of the apps deployed, just simple Sinatra apps.

With regards to the ```renet-monitor``` failures, It's almost like there is some sort of obscure race condition happening within docker itself. Like there is a possibility the processes are launched before the environment (specifically env vars) have been set.

Oh, I put some logging in dokku before the most recent ```ps:restartall``` where ```renet-monitor``` started but ```tiles``` failed; ```tiles``` was executed like:

```
docker run -d -e PORT=5000  -v /var/log/dokku/tiles:/var/log/app --env-file=/home/dokku/tiles/DOCKERFILE_ENV_FILE dokku/tiles 
```

But, I can't look at the logs, I go:

```
$ sudo docker logs `cat /home/dokku/tiles/CONTAINER`
/bin/bash: /start: Permission denied
```

Inspecting the container shows a blank log file path :confused:
https://gist.github.com/Benjamin-Dobell/ec48a9b06c7133bc101f



I'm really lost as to how everything gets so broken. This is reproducible though, I just roll-back my snapshot and repeat the process and I end up in the same spot.


I can probably rebuild my apps, and *hopefully* they launch then. However, this is UAT, I'm trying to come up with a bullet-proof 100% understood upgrade-path so I can do this in production with minimal downtime.

**Comment by Benjamin-Dobell** [comment]
Wait, hrm...

I just realised, the command I logged that launched the ```tiles``` docker container, it doesn't have a /start command. How strange.

**Comment by michaelshobbs** [comment]
Is there a Dockerfile in that repo?

**Comment by Benjamin-Dobell** [comment]
No, just a Ruby Procfile like all the other apps I'm running. I'm going to insert a bit more logging in dokku and see why ```START_CMD``` ends up blank.

**Comment by Benjamin-Dobell** [comment]
Alright, for ```tiles``:

```
sudo docker run --entrypoint="/bin/bash" --rm "dokku/tiles" -c "[[ -f /exec ]]"
```

This returns 1. Presumably because tiles was built with an *old* buildstep, it has ```/start``` and no ```/exec```.

So it would seem this particular functionality of dokku is tightly coupled with a particular buildstep version. Is that intended?

**Comment by josegonzalez** [comment]
Does an upgrade not rebuild buildstep? I know when you do deb-based installs, it pulls the absolute latest buildstep code and rebuilds the docker image for it.

**Comment by Benjamin-Dobell** [comment]
@josegonzalez I saw buildstep pull down and I believe it updates the base Dokku docker image, however it doesn't rebuild the apps. I assumed this was an intentional choice in order to minimise down-time when upgrading.

By the way guys, thank you so much for your help so far, and of course for Dokku itself. It's an awesome piece of kit!

Only time I've had problems with Dokku is when it comes to upgrading (in the past and now). Last time I just more or less muddled around rebuilding, deploying, upgrading plugins etc. until I got things working. However, this time I'm trying to be a bit more analytical about the process in hope I can identify the pain points and hopefully improve the experience for others.

**Comment by josegonzalez** [comment]
Maybe our upgrade instructions should have a `ps:rebuildall` instead of `ps:restartall`?

**Comment by Benjamin-Dobell** [comment]
I imagine tightly coupled breaking changes between the containers and Dokku don't happen too often.

However, I guess now that Dokku is coming down from apt-get you'd want to automate the rebuilding (rather than requiring a user action at all). Otherwise, users will go to update their whole system and perhaps their dokku apps will suddenly fail to boot.

**Comment by josegonzalez** [comment]
Probably worth placing in [here](https://github.com/progrium/dokku/blob/master/debian/postinst) under both `abort-upgrade` and `configure`?

**Comment by Benjamin-Dobell** [comment]
I think there might be more to it actually...

My apps are rebuilding now I'll report back shortly. However, I believe there is a potential issue regarding Ubuntu deb packages no longer being available if you update the docker base image.

**Comment by josegonzalez** [comment]
What do you mean?

**Comment by Benjamin-Dobell** [comment]
Woh, unrelated, apparently ```PORT``` for lots of my apps at the moment. They just weren't failing pre-checks like ```renet-monitor``` was. Although I still think it's some sort of weird race condition, because ```renet-monitor```'s ```PORT``` was defined and it's up and running just fine.

> What do you mean?

I have a real-world example because I ran into it a couple of days ago with my last update attempt (I mostly got things working in the end but wasn't sure exactly what I did due to all the messing around).

Anyway, one of my apps has a dependency on [libavcodec.53](https://launchpad.net/ubuntu/trusty/amd64/libavcodec53/6:0.8.7-1ubuntu2), which *was* available in the Ubuntu 14.04 package repository. However, it's now marked as *deleted*.

I could deploy all I wanted and deploy and rebuild my app just fine using the old buildstep version. However, when I updated buildstep is must have pulled down the latest 14.04 repository, where ```libavcodec53``` no longer exists (instead there's only ```libavcodec54```).

Of course this proved to be a royal pain in the arse so I had to rebuild my native code libraries to utilise ```libavcodec54``` instead of ```libavcodec53``` so that I could deploy them to the updated Dokku (with the updated buildstep docker image). But the point is that my app was 100% stable and safely redeployable *until* I updated buildstep *and* rebuilt - which is precisely what we're talking about automating.

If we automate that then people may have the same problem as before (except it's even more confusing), whereby all they did was update Dokku and suddenly their containers went down and aren't coming back up.

Ideally I think it would be best to *not* rebuild people's apps automatically, as you're changing the underlying system, and their app may suddenly break. So rebuilding should be an explicit task. But then again, updating Dokku from apt-get also shouldn't cause their containers to go down and not come back up.

The best solution I can think of is simply to ensure Dokku is not tightly coupled with a particular buildstep container version. That means two things:

1. We can't make assumptions about files like ```/exec``` existing, we need an abstraction/API.
2. When the abstraction/API inevitably does need to change to support new functionality, then you'll need to release a *different* dokku package (so that system updates don't ever pull down breaking changes). e.g. ```dokku2```, ```dokku3``` etc.

That's a lot of work, but unfortunately I think it's the only truly safe way to handle the situation.

**Comment by josegonzalez** [comment]
Buildstep is unfortunately not versioned, so I can't be like "we need at least X version" or similar (which would help with our own versioning). I'm curious to see where we broke bc between 0.3.9 and 0.3.17 (we've been pretty good about that) regarding `/exec` existing.

**Comment by Benjamin-Dobell** [comment]
I'm not at all very familiar with how buildstep, cedarish etc. work. Is it possible to tie each Dokku version to a particular commit in buildstep?

**Comment by josegonzalez** [comment]
Probably. Not sure how that would help you in this case though.

**Comment by Benjamin-Dobell** [comment]
Oh, I'm pretty screwed for now... I've come to accept that :stuck_out_tongue: The fact a package can be completely removed from a repository seems pretty crazy to me, ah well.

I'm more thinking long-term; just a way to formalise any tight coupling between dokku and buildstep, so dokku doesn't ever end up with a version of buildstep it's incompatible with etc.

Rebuilding the apps did at least resolve the ```/exec``` issue. I've now got the dependency problem I described (which is not really anything to do with Dokku, so that's fine). However, in addition to that I've still got this really obscure ```PORT``` env var undefined issue in most of my apps. This actually looks more like a weird Docker issue than anything else, but I'll keep digging.

So I guess the only confirmed "Dokku issue" at this point is that there was a breaking change with regards to the assumption that ```/exec``` should exist in buildstep based containers. Which we've established can be fixed with a rebuild, so "resolving the issue" might be as simple as making a note in the documentation.

**Comment by Benjamin-Dobell** [comment]
Hmm, I have no idea how to debug this ```PORT``` issue, whenever I push a new app with some logging it seems to resolve the problem.

Is ```ps:rebuildall``` different in any significant ways than pushing a new build (deploying)?

**Comment by michaelshobbs** [comment]
`ps:rebuildall` just pushes the git repo on the dokku server back through the build/deploy process for all known apps.

**Comment by Benjamin-Dobell** [comment]
Ugh, finally found out why my apps are complaining about undefined $PORT variables:

```
[supervisord]
logfile=/var/log/app/supervisor.log
loglevel=info
nodaemon=true

[program:web]
command=/exec bundle exec rackup -p $PORT
process_name:%(program_name)s
numprocs=1
autostart=true
autorestart=true
stopsignal=TERM
redirect_stderr=true
stdout_logfile=/var/log/app/genghis.%(program_name)s.%(process_num)02d.log
```

The supervisord plugin is trying to setup the processes in my Procfile, but the problem is the user of ```$PORT```. It should already be substituted for 5000 at this point, or we should call through to a shell, because supervisord does not perform shell expansion on ```$PORT```.

Some of my apps work because they don't directly use the ```$PORT``` variable in this command, instead they run shell scripts that then use the ```$PORT``` variable, where shell variable expansion works just fine.

**Comment by michaelshobbs** [comment]
I just use a different variable name. (ex. `$NODE_PORT`)

**Comment by Benjamin-Dobell** [comment]
@michaelshobbs It's not new to Dokku, I do specifically want to use ```$PORT```. The issue is dokku-logging-supervisord (which I updated along with Dokku) changed its syntax from:

```/exec sh -c "${COMMAND}"```

to:

```/exec ${COMMAND}```

The latter is incorrect.

**Comment by michaelshobbs** [comment]
Yeah I was involved in that testing. Something changed in buildstep that seemed to necessitate this change...

**Comment by Benjamin-Dobell** [comment]
Yeah, I see the commit:
https://github.com/sehrope/dokku-logging-supervisord/commit/70f5ea273ec6dc5d2f809315fed6985779ecd913

Including "sh -c" works for me though. Although I do definitely know that something in that commit was necessary, because without updating I encountered the endless forking problem - took me a good while to work out what was happening.

**Comment by Benjamin-Dobell** [comment]
It's probably worth noting that dokku-supervisord calls out to a shell, and that plugin does seem to be well maintained (recent commits) - never used it though:
https://github.com/statianzo/dokku-supervisord/blob/master/post-build-buildstep#L46

**Comment by Benjamin-Dobell** [comment]
Just in case anyone runs into similar problems, my final upgrade process was exactly the following:

```
sudo su

cd /var/lib/dokku/plugins

# Remove docker-options, because it's now part of Dokku
rm -rf docker-options

# Unnecessary plugin
rm -rf dokku-rebuild

# Need to update dokku-logging-supervisord or it will cause in infinite loop with the latest buildstep/cedar
# Using a fork because Procfile ENV variable expansion is broken on master, also have
# one other tweak regarding log naming so the logs play nice with services like papertrail
cd dokku-logging-supervisord
git remote set-url origin https://github.com/glassechidna/dokku-logging-supervisord.git
git fetch origin
git reset --hard origin/master
cd ..

# Can't remember why exactly, but needed to update dokku-apt, again forked to meet out needs
cd dokku-apt
git remote set-url origin https://github.com/glassechidna/dokku-apt.git
git fetch origin
git reset --hard origin/master
cd ..

# Latest docker-options has a DOCKER_OPTIONS file for each phase (we want RUN & DEPLOY)
sudo -u dokku bash
cd /home/dokku
for D in *; do
  if [ -d "${D}" ]; then
    pushd "${D}"
    if [ -f "DOCKER_OPTIONS" ]; then
      mv DOCKER_OPTIONS DOCKER_OPTIONS_RUN
      cp DOCKER_OPTIONS_RUN DOCKER_OPTIONS_DEPLOY
    fi
    popd
  fi
done
exit

# Update Dokku
cd /root/dokku/
git pull --tags origin master
make install

# dokku ps:rebuildall won't work straight away because each app depends on every other
# app having a valid nginx.conf before it will launch. When one app fails, ps:rebuildall
# just gives up, so we manually fix the nginx.conf of each app (even though only the last
# app will end up deploying correctly)

cd /home/dokku
for D in *; do
  if [ -d "${D}" ]; then
    dokku deploy ${D}
  fi
done

# Now we have valid nginx.conf for all apps, we need to rebuild the apps using latest
# buildstep and launch them.
dokku ps:rebuildall

# Not sure why but orphaned nginx worker processes stick around when dokku restarted
# nginx. We need to specifically kill them:
# NOTE: Perhaps I ran ```sudo service start nginx``` instead of init.d and that causes
# problems... but I can't remember.

/etc/init.d/nginx stop
ps aux | grep nginx | cut -d " " -f 2 | xargs kill -kill
/etc/init.d/nginx start

docker ps

##
# Then manually kill any stray containers with:
# docker stop <container-id>
##

exit
```


There were a few little hiccups I ran into, nginx.conf issues etc. However, I'll close this issue (as it's pretty large) - if there's anything specific that came from this issue I guess someone can create a new issue about it in particular.

**Comment by Benjamin-Dobell** [comment]
NOTE: Whilst the process above upgraded dokku, it did not update my buildstep docker image - or install from a deb package like the documentation indicated it would, see issue https://github.com/progrium/dokku/issues/1165
