### ISSUE TITLE
dokku misbehaves for unknown command if plugin installed; exits 0

### ISSUE THREAD

**Issue by fwolfst** [progrium/dokku#1156]
In a bare install, if I run a valid command, it displays output and exits with 0 (normally).
(assume `dokku-remote` is an alias for `ssh dokku@....`)

```
➜  ~  dokku-remote apps; echo $?
=====> My Apps
ruby-sample
0
```

If I give an invalid command dokku helps me with message and exit code.

```
➜  ~  dokku-remote appsitypo; echo $?
 !    `appsi` is not a dokku command.
 !    See `dokku help` for a list of available commands.
1
```

Now if I install a plugin (I think it is same for all plugins, but not sure, otherwise I should file an issue against the respective plugin(s))

```
cd /var/lib/dokku/plugins
git clone https://github.com/Kloadut/dokku-pg-plugin postgresql
dokku plugins-install
```

the situation changes for worse:

```
➜  ~  dokku-remote apps; echo $? 
=====> My Apps
ruby-sample
0
➜  ~  dokku-remote appsitypo; echo $?
0
```

I have not needed that yet, but it might be pretty annoying for scripting-stuff-situations.

**Comment by josegonzalez** [comment]
Can you check if that plugin uses `DOKKU_NOT_IMPLEMENTED_EXIT `? If not, then that would fix the [issue](http://progrium.viewdocs.io/dokku/development/plugin-creation)

**Comment by fwolfst** [comment]
Thanks, good pointer. I will move over to the plugin repo and create issue and PR there. Have fun.
