### ISSUE TITLE
nginx-vhost should separate access.log and error.log by $APP

### ISSUE THREAD

**Issue by fwolfst** [progrium/dokku#1158]
Hey guys,
really happy with my dokku experience, but I'd like an addition to the nginx(-vhost) plugin:

Provide separate access (and maybe error.log) per app-instance, e.g. in
https://github.com/progrium/dokku/blob/master/plugins/nginx-vhosts/templates/nginx.conf.template#L5

    access_log /var/log/nginx/$APP.log;
    error_log /var/log/nginx/$APP.log;

or

    access_log /var/log/nginx/$APP/access.log
Obviously same changes in the ssl-template.

**Comment by josegonzalez** [comment]
Mind writing a PR? In my mind, something like this would work:

```
access_log /var/log/nginx/{$APP}-access.log;
error_log /var/log/nginx/{$APP}-access.log;
```

@michaelshobbs any thoughts?

**Comment by fwolfst** [comment]
@josegonzalez I fear not being able to set up and properly test dokku development right now - too much work on the horizon and have no dev setup there, yet (although to play around I likely just have to clone a VM :) ...).

**Comment by josegonzalez** [comment]
`vagrant up` can get you a local dev setup...

It's so that we know it's a variable. It's part of our [bash rules](https://github.com/progrium/bashstyle).

**Comment by michaelshobbs** [comment]
Sending `error_log` to the same file as access is problematic for anything that will want to parse the logs. Also just seems like a bad idea. Sending it to its own app error log, though, seems reasonable.

i.e.
```
access_log /var/log/nginx/{$APP}-access.log;
error_log /var/log/nginx/{$APP}-error.log;
```

**Comment by fwolfst** [comment]
@miYeah I never meant to send it to the same file.
I won't have the time to create a tested PR this week, but will come back to it.

**Comment by longhotsummer** [comment]
This hasn't been applied to `nginx.ssl.conf.template` :(
