### ISSUE TITLE
Install deb package without using web installer?

### ISSUE THREAD

**Issue by 3onyc** [progrium/dokku#1161]
I'm installing Dokku using the deb package, but looking at the source it seems I can't bypass the web installer (Have it not initialise/run). Am I overlooking something or is this not yet implemented?

**Comment by josegonzalez** [comment]
The [web installer](https://github.com/progrium/dokku/blob/master/contrib/dokku-installer.rb#L38):

- Writes out or removes a `VHOST` file
- Writes out a `HOSTNAME` file
- Calls `sshcommand acl-add dokku admin` with your key on stdin
- Removes the dokku-installer nginx conf and removes its init file.

You could do all of that to bypass a web installer. If you want to disable it straightaway, thats not implemented, though I would consider a pull request that created `/etc/default/dokku` with some env var to disable it.

**Comment by 3onyc** [comment]
Is there any reason why this is done using a web interface? as the same could be accomplished through a prompt during installation, which would also remove the dependency on ruby.

Not sure what we could do if we want to bypass the prompts, I don't know what the idiomatic Debian packaging way of handling that is.

**Comment by josegonzalez** [comment]
It's done using the web interface as its more user friendly for the common user of dokku (seriously).

If you'd like to modify the debian package to prompt for this information, sure, but doing so probably means you want an automated way to do this, in which case a defaults file is the way to go...

**Comment by 3onyc** [comment]
It would be for just the Debian package yes, and a config option could be added to disable the web-based config.

As far as I can tell [debconf](http://www.fifi.org/doc/debconf-doc/tutorial.html) would be the idiomatic way of handling this.

Values can be set before install, and can be prompted for during install.

What do you think? If it sounds like the right way to go, I'll look into it.

**Comment by josegonzalez** [comment]
Go for it

**Comment by josegonzalez** [comment]
Closed by #1171.
