### ISSUE TITLE
Nginx conf not being configured, nginx gateway error. DigitalOcean, node.js app.

### ISSUE THREAD

**Issue by MaxYari** [progrium/dokku#1164]
Hello there, i'm new to dokku and nginx. After some minot problems with SSH keys i was able to push local git master to remote dokku (DigotalOcean's droplet), dokku finished app's deployment succesfully, but i was unable to enter my app, getting nginx `504  gateway time-out` or `502 bad gateway`. I found `nginx.conf` in `~/etc/nginx/` and `cat nginx.conf` showed pretty suspicious results. 
Here's my `nginx.conf`:
https://gist.github.com/MaxYari/07d4d0dbf37641e94596
And it seems that it was pretty much the same before i even pushed app.

And here's output of  dokku that I was able to copy from console:
https://gist.github.com/MaxYari/caef124c17dac7d56fd2

dokku version is 0.3.17
I'm deploying node.js app on express+mongoose+socket.io+some other stuff that anyway listens on the same server port:
```
var port = process.env.PORT || 4242;
server.listen(port);
```

As i understand dokku somehow determines app type and configures nginx.conf accordingly. Therefore here something gone wrong? Or am i need to manually configure nginx somehow?

**Comment by MaxYari** [comment]
Oops, just after posting it i figured out that nginx.conf for app is located in `home/dokku/MyApp/nginx.conf` and here its contains 
```
server {
  listen      [::]:80;
  listen      80;
  server_name MyApp.MyApp.net ;
  location    / {
    proxy_pass  http://MyApp;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection upgrade;
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header X-Request-Start $msec;
  }
  include /home/dokku/MyApp/nginx.conf.d/*.conf;
}
upstream MyApp { server 172.*x*.0.9:5000; }
```
Which looks much more promising. Again i'm new to nginx, so wuld you mind to give me advise what to do next? Wat is those ports 80 (in listen) and 5000 (in upstream) and how must they corelate to port which my server in node code listens.
Also am i need to link this `conf` somewhere manually or am i need to just edit something? (gateway error's still here obviously)

**Comment by MaxYari** [comment]
Ok i figured out that it seel that i need to symlink this `nginx.conf` in `home/dokku/MyApp/nginx.conf` to  folder to ~/etc/nginx/sites-enabled, done it, called it just MyApp.Another problem occured, wjile trying to reload nginx with `nginx -s reload` i recieved `[emerg] duplicate upstream "MyApp" in /etc/nginx/sites-enabled/MyApp:18` the reson of which i can not quite grasp at this moment.

**Comment by nickdb93** [comment]
I'm having this issue with a basic Rails 4 application both on Google Compute Engine as well as DigitalOcean. Any suggestions?

**Comment by josegonzalez** [comment]
@nickdb93 can you file a different issue? You just commented on a several month old issue without any information tying you to this one (which was user error).
