### ISSUE TITLE
$NOSSL_SERVER_NAME is not defined when creating a `nginx.conf.template`

### ISSUE THREAD

**Issue by jadlr** [progrium/dokku#1169]
using 0.3.17:

I created a `ngnix.conf.template` in my app dir in order to raise the `client_max_body_size` 

It looks like this:

```
server {
  listen      [::]:80;
  listen      80;
  server_name $NOSSL_SERVER_NAME;
  return 301 https://$SSL_SERVER_NAME\$request_uri;
}

server {
  listen      [::]:443 ssl spdy;
  listen      443 ssl spdy;
  server_name $SSL_SERVER_NAME;
$SSL_DIRECTIVES

  client_max_body_size 20M;
  keepalive_timeout   70;
  add_header          Alternate-Protocol  443:npn-spdy/2;
  location    / {
    proxy_pass  http://$APP;
    proxy_http_version 1.1;
    proxy_set_header Upgrade \$http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host \$http_host;
    proxy_set_header X-Forwarded-Proto \$scheme;
    proxy_set_header X-Forwarded-For \$remote_addr;
    proxy_set_header X-Forwarded-Port \$server_port;
    proxy_set_header X-Request-Start \$msec;
  }
  include $DOKKU_ROOT/$APP/nginx.conf.d/*.conf;
}
```

the generated output looks like this:

```
server {
  listen      [::]:80;
  listen      80;
  server_name  ;
  return 301 https://myapp.mydomain.com$request_uri;
}

server {
  listen      [::]:443 ssl spdy;
  listen      443 ssl spdy;
  server_name myapp.mydomain.com;
  ssl_certificate     /home/dokku/myapp/tls/server.crt;
  ssl_certificate_key /home/dokku/myapp/tls/server.key;

  client_max_body_size 20M;
  keepalive_timeout   70;
  add_header          Alternate-Protocol  443:npn-spdy/2;
  location    / {
    proxy_pass  http://myapp;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection upgrade;
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header X-Request-Start $msec;
  }
  include /home/dokku/myapp/nginx.conf.d/*.conf;
}
upstream myapp { server 172.17.0.97:5000; }
```

note the empty `server_name  ;` in the non-ssl part of the conf. It seems that  $NOSSL_SERVER_NAME is not defined.

**Comment by michaelshobbs** [comment]
What is/are the CN(s) in your cert and what are the domains for the deployed app in question? Can you also provide a gist of a deploy with `dokku trace on`?

**Comment by jadlr** [comment]
I cannot give you the real domain name since this is the project of a client of mine.

but the common name for the cert is: `*.mydomain.com`

I renamed the original domain to mydomain.com in the gist, plus i renamed the app from the real name to myapp. Also I removed all displays of env vars. 

https://gist.github.com/jadlr/0bb1ff97385fd19f2420

**Comment by michaelshobbs** [comment]
These lines are problematic:
https://gist.github.com/jadlr/0bb1ff97385fd19f2420#file-dokku_trace-txt-L2256
https://gist.github.com/jadlr/0bb1ff97385fd19f2420#file-dokku_trace-txt-L2296

@jadlr can you check out #1172 and let me know if it solves your issue?

**Comment by jadlr** [comment]
thanks @michaelshobbs I'll test this as soon as possible.

**Comment by jadlr** [comment]
since I did not want to update to master I just edit that one line. 

This didn't fix the issue

**Comment by michaelshobbs** [comment]
Can you provide a new deploy gist with this change?

**Comment by jadlr** [comment]
here you go: https://gist.github.com/jadlr/52524a0891da693ce129

**Comment by michaelshobbs** [comment]
Does it work without the custom nginx template?

**Comment by jadlr** [comment]
Yes, I just tried. Without the template both server names are correctly set

**Comment by michaelshobbs** [comment]
Alright. Let me take another look when I get in the office.

**Comment by jadlr** [comment]
Great, thanks a ton for your help!

**Comment by michaelshobbs** [comment]
I see what's happening now. Not too long ago the processing of SSL config was refactored (see #1008) but I don't think custom config was ever tested. I'll remedy this and include a test for custom nginx config.

**Comment by michaelshobbs** [comment]
@jadlr updated #1172

**Comment by jadlr** [comment]
:+1: thanks

**Comment by josegonzalez** [comment]
@jadlr does that work?

**Comment by jadlr** [comment]
Do you guys have a system that you can test this on? Our customer is already using the deployed system and I would rather not risk a downtime.

**Comment by michaelshobbs** [comment]
I've written a few tests that seem to pass. However, it would be great to test out with your config specifically. Do you have a test environment perhaps? 

Sidenote: How did you end up getting this working, just modified the built-in template or perhaps a plugin?

**Comment by jadlr** [comment]
I'll try to test this today. It works because I only use the SSL part of the custom config

**Comment by jadlr** [comment]
I checked out `1169_mh-fix-empty-nonssl-vhosts` and used the exact same template I posted above and the server_name in the nossl part is still not set

**Comment by jadlr** [comment]
here's the gist: https://gist.github.com/jadlr/0938cf6a9177aba7760d

**Comment by michaelshobbs** [comment]
Wait. This looks like you have defined a wildcard SSL and an app SSL. Is that intentional?

**Comment by michaelshobbs** [comment]
Also it seems the version of code you have and the version of code i have differ....

I had removed this line (errantly) `dokku_log_info1 'Overriding default nginx.conf with detected nginx.conf.template'`but it seems to still be running in your env.

**Comment by jadlr** [comment]
I have only defined ssl for one app. The certificate is a wildcard cert, though.

I did a git checkout of the branch you mentioned on the dokku folder. Is there anything else i need to do in order to update/change the code?

**Comment by michaelshobbs** [comment]
Ah crud. Yeah I just misread the gist. I see the app-level cert now. 
https://gist.github.com/jadlr/0938cf6a9177aba7760d#file-dokku_trace3-txt-L2359

So regarding updating from a branch. You want to ensure you have the latest version of the branch checked out. (commit: c5337cf6a2efcdc06233f9a3e5d9bf0ca8b7d868)

Then you'll want to run `make copyfiles` from that directory. You can confirm all is up-to-date by, in the same directory, running `diff plugins/nginx-vhosts/commands /var/lib/dokku/plugins/nginx-vhosts/commands`.

**Comment by jadlr** [comment]
Ok, sorry. I didn't know about the make part.

I tried to deploy the app with the properly upgraded branch, but now I'm being asked for the password to the dokku user when it tries to reload the nginx config. Do you know what could have caused this?

**Comment by michaelshobbs** [comment]
Hrm. I didn't change anything wrt that. We do require the following sudoers config that gets installed when you run `dokku plugins-install`. Maybe try running that again?

```
# cat /etc/sudoers.d/dokku-nginx
%dokku ALL=(ALL) NOPASSWD:/etc/init.d/nginx reload, /usr/sbin/nginx -t
```

**Comment by jadlr** [comment]
Ok, that did the trick!

Everything seems to work as expected! `nginx.conf` looks good.

Thank you so much for your help.

**Comment by michaelshobbs** [comment]
:+1:
