### ISSUE TITLE
Where is web installer?

### ISSUE THREAD

**Issue by harshjv** [progrium/dokku#1170]
After successfully installing **dokku**, documentation says, visit server IP, and follow web installer. But when i visit the IP, it just displays **Welcome to nginx on Debian!** page.

I ran this command for **dokku** installation.

    wget -qO- https://raw.github.com/progrium/dokku/v0.3.17/bootstrap.sh | sudo DOKKU_TAG=v0.3.17 bash

![screen shot 2015-05-05 at 5 16 31 pm](https://cloud.githubusercontent.com/assets/2311316/7471934/823899e6-f34a-11e4-8af2-8f5e10a6919e.png)

What happened to web installer?

**Comment by harshjv** [comment]
Okay, i got it.

Searched through source, and found this.

    if [ ! -f "/home/dokku/HOSTNAME" ]; then
      echo "\nTo avoid cli-based dokku configuration, use the web installer"
      echo "Debian-based installs should have this running and available"
      echo "on port 80. You can also install it via the following commands:"
      echo ""
      echo "  cd /root/dokku"
      echo "  sudo make dokku-installer\n"
    fi

So i ran following command in `dokku` directory, and got it working.

    sudo make dokku-installer

Thanks :)

**Comment by sekjun9878** [comment]
I also had this issue, which was fixed by running the command manually (thanks!). But really, shouldn't this have been done automatically like the message says?

**Comment by harshjv** [comment]
Yes, it should be included in `make install` because the documentation says that.

**Comment by josegonzalez** [comment]
Closing as there is an open PR.

**Comment by sahilshekhawat** [comment]
Did anyone updated docs? I cannot find it anywhere.
