### ISSUE TITLE
Exposed commands over SSH using sshcommand

### ISSUE THREAD

**Issue by monkey-H** [progrium/dokku#1174]
How do you achieve “Exposed commands over SSH using sshcommand” ？

**Comment by josegonzalez** [comment]
What do you mean

**Comment by monkey-H** [comment]
![](http://i1066.photobucket.com/albums/u407/5681713/octopress/sshd_zpspxi2f2st.png)
It seems that every time user push an app, dokku uses commands in /home/dokku/.sshcommand to deploy the app. I know that when I install dokku, dokku create a user by `sshcommand create dokku /usr/local/bin/dokku`. And sshcommand `echo "$COMMAND" > "$USERHOME/.sshcommand"`. But, when does dokku call .sshcommand? I can only see that when I run sshd in debug model, but I donnot know when dokku achieve this in source code.

**Comment by michaelshobbs** [comment]
I think this is love what you're asking..:

If you look at the Makefile under the sshcommand target, you'll find `sshcommand create dokku /usr/local/bin/dokku`

This command creates the dokku user (I think) and sets their default ssh command (similar to their shell but only over ssh) to the dokku script. Then you have to use `sshcommand acl-add dokku <key-name> to authorize an ssh key to connect and execute the default script/command. Check out the sshcommand repo for more details. https://github.com/progrium/sshcommand

**Comment by monkey-H** [comment]
I also think that I have to use `sshcommand acl-add dokku` to authorize an ssh key to connect and execute the default command. 
```
acl-add) # sshcommand acl-add <user> <identifier>
    if [[ $# -ne 3 ]]; then
      echo "Usage : sshcommand acl-add user identifier"
      exit -1
    fi
    USER="$2"; NAME="$3"

    getent passwd $USER > /dev/null || false
    USERHOME=$(sh -c "echo ~$USER")

    KEY=$(cat)
    FINGERPRINT=$(ssh-keygen -lf /dev/stdin <<< $(echo $KEY) | awk '{print $2}')
    KEY_PREFIX="command=\"FINGERPRINT=$FINGERPRINT NAME=$NAME \`cat $USERHOME/.sshcommand\` \$SSH_ORIGINAL_COMMAND\",no-agent-forwarding,no-user-rc,no-X11-forwarding,no-port-forwarding"
    echo "$KEY_PREFIX $KEY" >> "$USERHOME/.ssh/authorized_keys"
    echo $FINGERPRINT
    ;;
```
In the end, dokku echo $key_prefix $key into authorized_keys, but I cannot find it in authorized_keys.

**Comment by monkey-H** [comment]
Sorry, my mistake. The authorized_keys is in $USERHOME/.ssh/authorized_keys. I find it in wrong filepath. 
Thank you ~

**Comment by michaelshobbs** [comment]
Looks like we're good here? Feel free to re-open if necessary.
