### ISSUE TITLE
docker-options volcabulary

### ISSUE THREAD

**Issue by matthewmueller** [progrium/dokku#1181]
Just dealt with a lot of confusion around thinking the `run` phase was referring to `docker run` and I wasn't sure why my options weren't being applied.

Maybe we can clarify that or change it to `exec`? Though the mismatch between `dokku run` and `exec` kind of sucks. Open to ideas.

Also instead of phases, does `stages` make more sense? I wasn't really sure what you meant by phases at first. Seemed scifi-y

Not a big deal either way, just voicing some thoughts :-)

**Comment by michaelshobbs** [comment]
Can you further describe the issue you ran into that the language contributed to?

My thoughts and some clarification:
The `run` phase language is supposed to line up with the `dokku run` command. `dokku run` literally does `docker run <app_image> <command>`. Hence the `run` phase. I agree `exec` feels sloppy as it seems to imply a `docker exec` which is very different from a `docker run`. 

Regarding phase vs stage. Meh? Perhaps stage implies a more connected hierarchy where phase does not necessarily. I don't personally have strong opinions either way. I look forward to that pull request. :smiley: 

Anybody else, please feel free to chime in here.

**Comment by matthewmueller** [comment]
@michaelshobbs Yah, I think you make a good point about `docker exec`. Where I ran into confusion is that they all (run, build, deploy) use `docker run` in some form.

Maybe it's just documenting what stage does what and I think some sort of logging during the deploy pipeline would be useful, perhaps... `===> Running "deploy" phase`, and maybe `===> Running docker options: ...`.

**Comment by matthewmueller** [comment]
closing for now
