### ISSUE TITLE
libpoppler.so.28: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by naveed-ahmad** [progrium/dokku#1182]
I'm getting "cannot open shared object file" when I ran `pdftohtml` in my dokku container.

dokku run app_name  pdftohtml 

=> `/app/bin/pdftohtml: error while loading shared libraries: libpoppler.so.28: cannot open shared object file: No such file or directory`
 
pdftohtml is provided by `poppler-utils` package which is installed in container. 

Interesting fact is I can ran pdftohtml  on Ubuntu vm without any issue, both vm and dokku container has `poplar-utils` package. 

VM version

lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.1 LTS
Release:	14.04
Codename:	trusty

Dokku container's vm versions

dokku run app_name lsb_release -a 

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.2 LTS
Release:	14.04
Codename:	trusty

So both has almost same version. 

Anyone has a clue to help me fix this issue?

**Comment by michaelshobbs** [comment]
Where did `/app/bin/pdftohtml` come from? Unless you statically linked that binary, it is going to expect the same libraries in place in the docker image as on the host system. 

The deb package depends on a few libraries. The least of which is `libpoppler44`. I doubt that's installed in your image.

```
# apt-cache depends poppler-utils
poppler-utils
  Depends: libc6
  Depends: libcairo2
  Depends: libfreetype6
  Depends: liblcms2-2
  Depends: libpoppler44
  Depends: libstdc++6
...
```

You can try using the [dokku-apt plugin](https://github.com/F4-Group/dokku-apt) and installing the `poppler-utils` package. That will probably solve your issue.

**Comment by naveed-ahmad** [comment]
@michaelshobbs  thanks for quick reply.  And I've already installed `poppler-utils` package using `dokku-apt` plugin.

`/app/bin/pdftohtml` came from which `dokku run paper_pusher which pdftohtml` :) 

and `libpoppler44` is installed in container.


```
dokku run app_name apt-cache depends poppler-utils
poppler-utils
  Depends: libc6
  Depends: libcairo2
  Depends: libfreetype6
  Depends: liblcms2-2
  Depends: libpoppler44
  Depends: libstdc++6
  Conflicts: <pdftohtml>
  Breaks: <xpdf-utils>
  Replaces: <pdftohtml>
    poppler-utils
  Replaces: <xpdf-reader>
  Replaces: <xpdf-utils>
```

````
dokku run app_name  dpkg --get-selections | grep  libpoppler44
libpoppler44:amd64				install

````

**Comment by josegonzalez** [comment]
How did you install pdftohtml ?

**Comment by naveed-ahmad** [comment]
Using [Dokku Apt](https://github.com/F4-Group/dokku-apt) plugin.

Simply created  `apt-packages` file in root of project. And put bunch of extra packages I need for my project. `poppler-utils` is one of them.

**Comment by michaelshobbs** [comment]
Seems to work for me. See below. Main difference is that I don't see `/app/bin/pdftohtml`. Not sure where that is coming from.

```
root@dokku:~/dokku# dokku run node-js-app which pdftohtml
/usr/bin/pdftohtml
```

```
root@dokku:~/dokku# dokku run node-js-app pdftohtml
pdftohtml version 0.24.5
Copyright 2005-2013 The Poppler Developers - http://poppler.freedesktop.org
Copyright 1999-2003 Gueorgui Ovtcharov and Rainer Dorsch
Copyright 1996-2011 Glyph & Cog, LLC

Usage: pdftohtml [options] <PDF-file> [<html-file> <xml-file>]
  -f <int>              : first page to convert
  -l <int>              : last page to convert
  -q                    : don't print any messages or errors
  -h                    : print usage information
  -help                 : print usage information
  -p                    : exchange .pdf links by .html
  -c                    : generate complex document
  -s                    : generate single document that includes all pages
  -i                    : ignore images
  -noframes             : generate no frames
  -stdout               : use standard output
  -zoom <fp>            : zoom the pdf document (default 1.5)
  -xml                  : output for XML post-processing
  -hidden               : output hidden text
  -nomerge              : do not merge paragraphs
  -enc <string>         : output text encoding name
  -fmt <string>         : image file format for Splash output (png or jpg)
  -v                    : print copyright and version info
  -opw <string>         : owner password (for encrypted files)
  -upw <string>         : user password (for encrypted files)
  -nodrm                : override document DRM settings
  -wbt <fp>             : word break threshold (default 10 percent)
  -fontfullname         : outputs font full name
```

**Comment by josegonzalez** [comment]
@naveed-ahmad did you maybe commit a `pdftohtml` binary to your repository?

**Comment by michaelshobbs** [comment]
@naveed-ahmad bump

**Comment by naveed-ahmad** [comment]
Sorry for late response. @josegonzalez  I don't think so, I've used [pdftohtmlr]  (https://github.com/kitplummer/pdftohtmlr) gem in my rails app. And [pdftohtmlr]  (https://github.com/kitplummer/pdftohtmlr) don't have `pdftohtml` binary, nor I've committed binary in project. 

FYI: I'm using digital ocean for hosting the application, and I've installed `dokku` manually.

**Comment by michaelshobbs** [comment]
@naveed-ahmad I think we're confused because in the original comment, you included
>
`/app/bin/pdftohtml:...`

It seems something attempted to execute `pdftohtml` in `/app/bin`. Where did that come from?

**Comment by josegonzalez** [comment]
Does this app have a `Dockerfile` by any chance?

**Comment by naveed-ahmad** [comment]
@michaelshobbs  You were right. Yeah there is `pdftohtml` binary in `/bin` directory of application.

Issue solved. Thanks you guys :)
