### ISSUE TITLE
Redirecting to port 5000

### ISSUE THREAD

**Issue by alexbeletsky** [progrium/dokku#1184]
Running the static application based on [heroku-buildpack-nginx](https://github.com/alexbeletsky/heroku-buildpack-nginx), I've got a strange error.

Once I hit the URL, which doesn't exist, or one without trailing slash, I got redirect to port 5000.

It is very simple to reproduce [here](http://socialsearch.likeastore.com/), just open the link and then `/anything` and it will be redirected to `:5000/anything`. All is good then I have a trailing slash.

Where does this port `5000` comes from? Is this something `dokku` does or it's container's `ngingx.conf` issue? Any clues are really appreciated.

Dokku version `v0.3.7`.

**Comment by josegonzalez** [comment]
Probably https://github.com/alexbeletsky/heroku-buildpack-nginx/blob/master/config/nginx.conf.erb#L66

**Comment by alexbeletsky** [comment]
@josegonzalez thanks a lot. I've tried to remove that, it became a little better, but still not solved.

Now, if I hit `/anything` I got 404, as expected. But, if I hit `/pricing` (the folder does exist), it's redirecting to `:5000/pricing` again.

**Comment by josegonzalez** [comment]
I'd recommend using the php buildpack for static files, since its quite simple to setup and is an official buildpack. Should work just fine for this use case. I think the redirect issues are caused by your buildpack. Sorry I can't help anymore, hopefully you figured this out in the meantime.
