### ISSUE TITLE
Wildcard domain always added to app

### ISSUE THREAD

**Issue by sampettersson** [progrium/dokku#1185]
I have this issue where *.domain.com always get added to a newly pushed app when using a VHOST, why is this happening?

Have tried multiple ways of removing it, manually removing it from VHOST doesn't seem to work, using the dokku command doesn't do anything. How do I get rid of it?

There is an SSL certificate for *.domain.com in /home/dokku/tls, may this be causing the issue?

**Comment by michaelshobbs** [comment]
What do you mean by always added to a newly deployed app? Can you provide nginx config output from deploys and a gist of the deploy with dokku trace on?

**Comment by sampettersson** [comment]
This seems to happen when I add a domain to an app, lets say I add hello.domain.com to the app hello, automatically the domain *.domain.com get's added for some reason.

Tried to get an output but i got loads of these for some reason:
`shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory`

**Comment by michaelshobbs** [comment]
So I'm not following exactly what's happening. Some config examples would probably help.

Those shell-init errors are because your current working directory has been removed.

**Comment by michaelshobbs** [comment]
@sampettersson ping

Can you define what you mean by the *.domain.com domain gets 'added' to the app? How are you observing this behavior? From `dokku urls app` or in nginx config or something else?

**Comment by vincentfretin** [comment]
I had the same behaviour as @sampettersson.
Step to reproduce, define a wildcard certificate for *.domain.com in /home/dokku/tls
and deploy an app for another domain, say myapp.example.com. 

    git remote add deploy dokku@domain.com:myapp.example.com
    git push deploy master

and you have by default a VHOST with
*.domain.com
myapp.example.com

The generated nginx.conf of course doesn't work at all.

When you have a /home/dokku/tls folder, all deployed apps will be automatically in https and it extract the common name from the certificate. If you want to fix it, you need to generate an auto-signed certificate for myapp.example.com in /home/dokku/myapp.example.com/tls

    mkdir /home/dokku/myapp.example.com/tls
    cd /home/dokku/myapp.example.com/tls
    openssl req -new -x509 -days 365 -nodes -out server.crt -keyout server.key

@sampettersson Is it the same case?

**Comment by michaelshobbs** [comment]
Using the `tests/unit/server_ssl_wildcard.tar` SSL cert bundle, I was unable to reproduce this. Here's what I did.

```
# mkdir -p /home/dokku/tls
# tar xf tests/unit/server_ssl_wildcard.tar -C /home/dokku/tls
# chown -R dokku:dokku /home/dokku/tls
# chmod -R 600 /home/dokku/tls/*

# openssl x509 -in /home/dokku/tls/server.crt -noout -subject | tr '/' '\n' | grep CN= | cut -c4-
*.dokku.me

# cat /home/dokku/VHOST
dokku.me

# git push dokku@dokku.me:node-js-app.example.com master
....
-----> Running post-deploy
-----> Creating new /home/dokku/node-js-app.example.com/VHOST...
-----> Configuring node-js-app.example.com...
-----> Creating http nginx.conf
-----> Running nginx-pre-reload
       Reloading nginx
=====> Application deployed:
       http://node-js-app.example.com

# cat /home/dokku/node-js-app.example.com/VHOST
node-js-app.example.com

# cat /home/dokku/node-js-app.example.com/nginx.conf
server {
  listen      [::]:80;
  listen      80;
  server_name node-js-app.example.com ;
  location    / {
    proxy_pass  http://node-js-app.example.com;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection upgrade;
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header X-Request-Start $msec;
  }
  include /home/dokku/node-js-app.example.com/nginx.conf.d/*.conf;
}
upstream node-js-app.example.com { server 172.17.0.40:5000; }
```

This seems like the expected behavior but not the behavior you guys are seeing, correct? What did I miss in my repro steps?

**Comment by vincentfretin** [comment]
You seem to have the good steps indeed, but it's not the behavior I see.

Here what I have, I replaced my domains by dokku.me and example.com.

    openssl x509 -in /home/dokku/tls/server.crt -noout -subject | tr '/' '\n' | grep CN= | cut -c4-
    *.dokku.me
    cat /home/dokku/VHOST 
    dokku.me

The generated nginx.conf is in https

    root@dokku.me:~# cat /home/dokku/myapp.example.com/VHOST 
    myapp.example.com
    *.dokku.me

    root@dokku.me:~# cat /home/dokku/myapp.example.com/nginx.conf 
    server {
      listen      [::]:80;
      listen      80;
      server_name *.dokku.me;
      return 301 https://*.dokku.me$request_uri;
     }
    
     server {
      listen      [::]:443 ssl spdy;
      listen      443 ssl spdy;
      server_name *.dokku.me;
    
    
      keepalive_timeout   70;
      add_header          Alternate-Protocol  443:npn-spdy/2;
      location    / {
        proxy_pass  http://myapp.example.com;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection upgrade;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-Request-Start $msec;
      }
      include /home/dokku/myapp.example.com/nginx.conf.d/*.conf;
    }
    server {
      listen      [::]:80;
      listen      80;
      server_name myapp.example.com ;
      location    / {
        proxy_pass  http://myapp.example.com;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection upgrade;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-Request-Start $msec;
      }
      include /home/dokku/myapp.example.com/nginx.conf.d/*.conf;
    }
    upstream myapp.example.com { server 172.17.2.166:5000; }

**Comment by vincentfretin** [comment]
I think the difference is the certificate, I have this:

    openssl x509 -in /home/dokku/tls/server.crt -noout -text | grep --after-context=1 '509v3 Subject Alternative Name:' | tail -n 1 | sed -e "s/[[:space:]]*DNS://g"  | tr ',' '\n'
    *.dokku.me
    dokku.me

https://github.com/progrium/dokku/blob/c5337cf6a2efcdc06233f9a3e5d9bf0ca8b7d868/plugins/nginx-vhosts/commands#L75

**Comment by vincentfretin** [comment]
This is a RapidSSL wildcard from GeoTrust.

**Comment by michaelshobbs** [comment]
Alrighty I see it now. I was able to reproduce it with the `server_ssl_sans.tar` bundle in `/home/dokku/tls`.

**Comment by michaelshobbs** [comment]
@josegonzalez @vincentfretin @lmars 

What do we expect the behavior to be if we have a wildcard ssl with one domain name and deploy an app with a completely unrelated domain name?

**Comment by vincentfretin** [comment]
For me, the behavior should be the behavior you described in your test, deploy without ssl.

**Comment by josegonzalez** [comment]
Deploy without ssl.

**Comment by lmars** [comment]
I'd say without ssl too

**Comment by michaelshobbs** [comment]
I'm not clear on how we would make this happen....Right now we do something like this:

```
[[ -z "$(egrep "^test\.dokku\.me$" /home/dokku/node-js-app.example.com/VHOST)" ]] && echo "test.dokku.me" >> /home/dokku/node-js-app.example.com/VHOST
```

Because we assume that a wildcard SSL installation means that all apps deployed on this dokku instance would fall under that domain....I think this may just need some documentation to clarify when to use a wildcard and when not to? Or do we want to handle the case of an unrelated app domain running in a wildcard dokku installation? Does that make sense? Thoughts?

**Comment by josegonzalez** [comment]
Yeah this is a bit complex. Maybe we want to revisit how we do domain handling in 0.4.0?

**Comment by joshco** [comment]
"Or do we want to handle the case of an unrelated app domain running in a wildcard dokku installation? "
If I understand this correctly, I do this.
My main dokku domain is *.dokku.mydomain.com.  That's what is in dokku/VHOST
Among the apps I have hosted, one is SSL enabled with it's product domain. *.product.com

**Comment by josegonzalez** [comment]
If your app that has `product.com` as its domain is named `product`, should we also have `product.dokku.mydomain.com`?

Can we conditionally include an ssl cert for a given domain?

**Comment by joshco** [comment]
Upon creating the app, if the app name is 'product' then product.dokku.mydomain.com should work (and it does for http)
However, if the dokku app name is something other than 'product' I'm not sure I see the need to do that.  Seems like what your suggesting is to apply a heuristic based on the domain information in the ssl cert to provision a domain that isn't actually in the cert.

**Comment by josegonzalez** [comment]
@joshco there is a wildcard cert on the server for the dokku installation. We don't currently have a way to say "only respond to this domain", which is why `APP.dokku.mydomain.com` would always work.

However, applying an ssl cert to a specific domain is a bit trickier - and as I understand it, you're trying to get `example.com` as well as `example.dokku.mydomain.com` working under ssl. Handling that is what we're discussing I think, and I understand why it wouldn't work so great.

**Comment by michaelshobbs** [comment]
@josegonzalez I don't think there is any need to have `product.dokku.mydomain.com` and `product.com` on the same app via automagic. If you want that, name your app `product` and add `product.com` as a domain.

Still not clear on what we want to do here though.

**Comment by josegonzalez** [comment]
@michaelshobbs We should probably have a discussion on google hangouts or something to sort this one out.

**Comment by joshco** [comment]
@michaelshobbs or, regardless of what your app name is, if you want product.com added just add it as a domain.

**Comment by michaelshobbs** [comment]
@joshco of course, that works as well

**Comment by michaelshobbs** [comment]
@josegonzalez when do you want to chat?

**Comment by michaelshobbs** [comment]
@sampettersson to clarify an answer to your original question, yes, the wildcard cert in `/home/dokku/tls` is causing the behavior.

**Comment by michaelshobbs** [comment]
@vincentfretin @sampettersson we seem to have two issues here.

I believe we have two issues here. 

1. @sampettersson is seeing *.domain.com (literally) end up in the URLS and nginx config
2. @vincentfretin is seeing that all CNs/SANs of a server-wide SSL cert get added to deployed apps.

The first is a bug that can be fixed. The second I think is an unsupported configuration. We assume that a server-wide SSL cert is intended to secure all deployed apps. Therefore if you want to deploy `app.example.com` when you have a server-wide SSL cert with `*.domain.com`, you must move the SSL cert to the app-level for all apps being deployed under `.domain.com`.

**Comment by josegonzalez** [comment]
I'm fine with that outcome, @michaelshobbs .

**Comment by vincentfretin** [comment]
@michaelshobbs No no, it's the same number 1 issue I have. I'm seeing the SAN *.domain.com literally in the URLS and nginx config. I don't have number 2 issue at all, where did you understand that?. :)

**Comment by michaelshobbs** [comment]
@vincentfretin hahahaha ok. i completely misunderstood then. let me sort out the original issue. sorry for the confusion

**Comment by michaelshobbs** [comment]
@vincentfretin what is the CN of your example cert then?

**Comment by vincentfretin** [comment]
@michaelshobbs Sorry for the late response. The CN of my certificate was *.dokku.me
and SAN was *.dokku.me and dokku.me

I tested your change, it works great. Thanks!
