### ISSUE TITLE
docker-options plugin in master completely broken via ssh

### ISSUE THREAD

**Issue by vincentfretin** [progrium/dokku#1187]
With dokku master,
with the following commands on my machine:

    ssh dokku@domain apps:create $APP
    APP=myapp
    VHOST=$APP
    ssh dokku@domain docker-options:add $APP deploy "-v /home/dokku/$APP/.volumes/var:/app/var"
    ssh dokku@domain docker-options:add $APP deploy "-e SERVICE_CHECK_HTTP=/"           
    ssh dokku@domain docker-options:add $APP deploy "-e SERVICE_CHECK_INTERVAL=10s"  
    ssh dokku@domain docker-options:add $APP deploy "--name $VHOST"

On the server, I get:

    $ cat /home/dokku/myapp/DOCKER_OPTIONS_DEPLOY
    --name
    -v

If I do the same command (dokku docker-options:add ...) directly on the server, the file is good.

With https://github.com/dyson/dokku-docker-options.git it worked great via ssh, except I had to specify -name instead of --name.

**Comment by vincentfretin** [comment]
This is actually the "deploy" phase I want, and not "run". Anyway, it's the same problem.

**Comment by michaelshobbs** [comment]
I think this is similar behavior to the config plugin when passing arguments with spaces over ssh. Basically you need to escape the quotes. See `tests/unit/docker-options.bats`. @josegonzalez does that sound right?

https://github.com/progrium/dokku/blob/7dd52ef1fc9af277128549dfa48e295d93c49b74/tests/unit/docker-options.bats#L153-L162

**Comment by josegonzalez** [comment]
I'd say so. We don't do any extra special handling of quotes, and since our docker-options plugin is just an import of @dyson's, I don't see how it would have stopped working.

**Comment by vincentfretin** [comment]
If I do:

    ssh dokku@domain docker-options:add $APP deploy \"-e SERVICE_CHECK_INTERVAL=10s\"

indeed it works. But it doesn't work without escaping:

    ssh dokku@domain docker-options:add $APP deploy "-e SERVICE_CHECK_INTERVAL=10s"

and it worked with @dyson's

I think I found the issue in add_passed_docker_option, you do:

    local passed_option_string=$2

it should get all remaining params, not only $2.

**Comment by vincentfretin** [comment]
see the original code: https://github.com/dyson/dokku-docker-options/blob/master/commands#L10

**Comment by josegonzalez** [comment]
Gotcha. We used his [refactored branch](https://github.com/dyson/dokku-docker-options/tree/dokku-merge), hence the difference. Mind making a pr to fix this?

**Comment by michaelshobbs** [comment]
Doh! This is an easy one. I whipped up a quick PR. @vincentfretin have a look. #1193
