### ISSUE TITLE
SSL documentation is misleading

### ISSUE THREAD

**Issue by sglebs** [progrium/dokku#1194]
At http://progrium.viewdocs.io/dokku/nginx it says:

PER APP

To enable TLS connection to to one of your applications, copy or symlink the .crt and .key files into the application's /home/dokku/:app/tls folder (create this folder if it doesn't exist) as server.crt and server.key respectively.

Redeployment of the application will be needed to apply TLS configuration. Once it is redeployed, the application will be accessible by https:// (redirection from http:// is applied as well).

However, at #1114 you can see I had to use 

ssh dokku@104.131.71.99 nginx:import-ssl < server.tar myapp

Can the documentation please be updated so that the correct steps for per-app https are listed? Thanks!

**Comment by josegonzalez** [comment]
@sglebs pull requests for documentation changes are more than welcome.

**Comment by sglebs** [comment]
I would be glad to fix the docs but I have not been able to figure out the right steps. I mean, I am trying to do the same thing for multiple domains, but it fails:

tar cvf ~/Downloads/dokku-staging-certificates.tar ~/Downloads/*.cert ~/Downloads/*.key

dokku mqm$ ssh dokku@104.131.71.94 nginx:import-ssl < ~/Downloads/dokku-staging-certificates.tar core-server-staging
tar: /Users/mqm/Downloads/._27817776_staging.core.namoromobile.com.cert
Removing leading `/' from member names
Users/mqm/Downloads/27817776_staging.core.namoromobile.com.cert
/Users/mqm/Downloads/._30459181_get.v1.staging.core.namoromobile.com.cert
Users/mqm/Downloads/30459181_get.v1.staging.core.namoromobile.com.cert
/Users/mqm/Downloads/._3795813_get.staging.core.namoroon.com.cert
Users/mqm/Downloads/3795813_get.staging.core.namoroon.com.cert
/Users/mqm/Downloads/._48373792_get.v1.staging.core.namoroon.com.cert
Users/mqm/Downloads/48373792_get.v1.staging.core.namoroon.com.cert
/Users/mqm/Downloads/._67223910_v1.staging.core.namoroon.com.cert
Users/mqm/Downloads/67223910_v1.staging.core.namoroon.com.cert
/Users/mqm/Downloads/._84123428_staging.core.namoroon.com.cert
Users/mqm/Downloads/84123428_staging.core.namoroon.com.cert
/Users/mqm/Downloads/._9243972_v1.staging.core.namoromobile.com.cert
Users/mqm/Downloads/9243972_v1.staging.core.namoromobile.com.cert
/Users/mqm/Downloads/._9737983_get.staging.core.namoromobile.com.cert
Users/mqm/Downloads/9737983_get.staging.core.namoromobile.com.cert
/Users/mqm/Downloads/._27817776_staging.core.namoromobile.com.key
Users/mqm/Downloads/27817776_staging.core.namoromobile.com.key
/Users/mqm/Downloads/._30459181_get.v1.staging.core.namoromobile.com.key
Users/mqm/Downloads/30459181_get.v1.staging.core.namoromobile.com.key
/Users/mqm/Downloads/._3795813_get.staging.core.namoroon.com.key
Users/mqm/Downloads/3795813_get.staging.core.namoroon.com.key
/Users/mqm/Downloads/._48373792_get.v1.staging.core.namoroon.com.key
Users/mqm/Downloads/48373792_get.v1.staging.core.namoroon.com.key
/Users/mqm/Downloads/._67223910_v1.staging.core.namoroon.com.key
Users/mqm/Downloads/67223910_v1.staging.core.namoroon.com.key
/Users/mqm/Downloads/._84123428_staging.core.namoroon.com.key
Users/mqm/Downloads/84123428_staging.core.namoroon.com.key
/Users/mqm/Downloads/._9243972_v1.staging.core.namoromobile.com.key
Users/mqm/Downloads/9243972_v1.staging.core.namoromobile.com.key
/Users/mqm/Downloads/._9737983_get.staging.core.namoromobile.com.key
Users/mqm/Downloads/9737983_get.staging.core.namoromobile.com.key
Tar archive missing server.crt

Does anybody know how to make SSL work for an app with multiple domains? I was only able to make it work for a single domain. Maybe a workaround is to tar one by one, but that would be very tedious.

Ideas?

**Comment by sglebs** [comment]
Doing manually for each key/cert pair worked (tar each pair, etc). PITA. Should I document it this way?

**Comment by sglebs** [comment]
I made the doc change in this pull request: https://github.com/progrium/dokku/pull/1201
(sorry I was not able to make a pull request just with the doc change - an old vmware fix also survived)
