### ISSUE TITLE
nginx:import-ssl should be able to import multiple pairs at once

### ISSUE THREAD

**Issue by sglebs** [progrium/dokku#1195]
In #1194 we show how we tried to import multiple cert/key pairs but the process fails.

Can we facilitate importing multiple ones - preferable in a single tar - to facilitate the workflow for apps with multiple domains?

Thanks!

**Comment by michaelshobbs** [comment]
@sglebs any thoughts on how this should look from a UX perspective?

**Comment by josegonzalez** [comment]
SSL imports were made more resilient in #1344 and are being overhauled in #1414. I'm going to close this as I think the best case is to provide a good `certs` plugin that can be used in a scripted manner and provide examples of it.
