### ISSUE TITLE
Second GO app fails to run on Dokku

### ISSUE THREAD

**Issue by ekkapob** [progrium/dokku#1197]
The first Go app on Dokku runs smoothly. But when pushing the second Go app which is **identical** to the first one, its subdomain.domain.com couldn't be accessed. Chrome shows the common bad URL request message "This webpage is not available - ERR_NAME_NOT_RESOLVED"

I am using godep following this tutorial (http://www.mircozeiss.com/host-your-golang-app-on-digital-ocean) and only update Procfile to have different project's folder name.

Here is the simple Go app I pushed for the first(works very well) and the second(seems server not running). Please share your thoughts.

main.go
```
package main

import (
	"fmt"
	"log"
	"net/http"
	"os"
)

func handler(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello...")
}

func main() {
	port := os.Getenv("PORT")
	http.HandleFunc("/", handler)

	log.Println("Starting web server on", port)
	if err := http.ListenAndServe(":"+port, nil); err != nil {
		log.Fatal("ListenAndServe:", err)
	}
}
```

**Comment by michaelshobbs** [comment]
Sounds like either DNS or DNS caching. Make sure the hostname is in DNS, you can `dig` your new hostname, flush your machine DNS cache and restart Chrome. (It has its own DNS cache)

**Comment by ekkapob** [comment]
If the flushing cache means this (http://osxdaily.com/2014/11/20/flush-dns-cache-mac-os-x), I've already done it. Not work. For the "dig" to hostname, I am not sure how to check them as both of them show some information with "dig".

Here are the two identical Go app I pushed to dokku. Could you please help analyze them?
1. http://pkgsociety.bytelingo.com/
2. http://testdock.bytelingo.com/

**Comment by josegonzalez** [comment]
You need to have a dns entry for your testdock app.

```
jose@mactaku:~  $ dig pkgsociety.bytelingo.com

; <<>> DiG 9.8.3-P1 <<>> pkgsociety.bytelingo.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 37854
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;pkgsociety.bytelingo.com.	IN	A

;; ANSWER SECTION:
pkgsociety.bytelingo.com. 1799	IN	A	128.199.64.185

;; Query time: 310 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Tue May 19 10:51:28 2015
;; MSG SIZE  rcvd: 58

jose@mactaku:~  $ dig testdock.bytelingo.com

; <<>> DiG 9.8.3-P1 <<>> testdock.bytelingo.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 11755
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;testdock.bytelingo.com.		IN	A

;; AUTHORITY SECTION:
bytelingo.com.		1799	IN	SOA	ns1.digitalocean.com. hostmaster.bytelingo.com. 1431831792 10800 3600 604800 1800

;; Query time: 172 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Tue May 19 10:51:35 2015
;; MSG SIZE  rcvd: 104

jose@mactaku:~  $
```

**Comment by ekkapob** [comment]
Solved! Added A Record for the second. Thank you so much @josegonzalez @michaelshobbs
