### ISSUE TITLE
ps:stop / ps:start leaves zombie docker containers

### ISSUE THREAD

**Issue by sglebs** [progrium/dokku#1199]
If you ps:stop and then ps:start your app, you will see hat there will be garbage docker containers left, even after a few minutes pass:

```
root@namoro-staging:~# docker ps -a | grep Exited
d38f7e7c8a2b        dokku/wwwbattycode:latest                  "/bin/bash -c 'mkdir   11 minutes ago      Exited (0) 11 minutes ago                         goofy_engelbart             
54793d163f8c        dokku/wwwbattycode:latest                  "/bin/bash -c 'mkdir   11 minutes ago      Exited (0) 11 minutes ago                         insane_brown                
598cd3f81146        dokku/wwwnamoro:latest                     "/bin/bash -c 'mkdir   12 minutes ago      Exited (0) 12 minutes ago                         hopeful_ptolemy             
d9fd6505c7a1        dokku/wwwnamoro:latest                     "/bin/bash -c 'mkdir   12 minutes ago      Exited (0) 12 minutes ago                         stoic_lumiere               
d379ad09be88        dokku/wwwnamoro:latest                     "/start web"           16 hours ago        Exited (137) 13 minutes ago                       hungry_yonath               
9d8500556e4a        dokku/wwwbattycode:latest                  "/start web"           16 hours ago        Exited (143) 13 minutes ago                       kickass_meitner             

```

I find myself having to play "Garbage Collector" once in a while:

```
docker ps -a | grep 'Exited' | awk '{print $1}' | xargs --no-run-if-empty docker rm
```

I am running 0.3.17 (because 0.3.18 does not even install).

**Comment by sglebs** [comment]
There are some tips at https://github.com/docker/docker/issues/479

**Comment by sglebs** [comment]
Also https://github.com/docker/docker/pull/1589

**Comment by michaelshobbs** [comment]
We run `dokku cleanup` when an app is deployed to rm exited containers. You can run that manually if the exited containers are causing issues between deployments.

https://github.com/progrium/dokku/blob/b6b8f4ddc1d7485cac1b37b3147c8747063d07c5/dokku#L167-L174

**Comment by michaelshobbs** [comment]
@sglebs can you confirm running `dokku cleanup` "solves" this issue? if not, what behavior are you expecting?

**Comment by michaelshobbs** [comment]
@sglebs ping

**Comment by michaelshobbs** [comment]
No response from OP. Closing.

**Comment by freddi301** [comment]
@michaelshobbs i have same issue, `dokku cleanup` does not solve if i keep the app running.
To make `dokku cleanup` work i need to stop the app

**Comment by josegonzalez** [comment]
@freddi301 please do not comment on years old issues. `dokku cleanup` works as advertised, and only removes not-running containers.
