### ISSUE TITLE
dokku package keeps upgrading

### ISSUE THREAD

**Issue by Flink** [progrium/dokku#1208]
I’ve just upgraded a source install to a package based one and now everytime I do an aptitude full-upgrade, dokku will upgrade itself but the package is already at the latest version (0.3.18). So I think it’s a bug but did anyone encountered it?

I’m using ubuntu 14.04 LTS.

**Comment by josegonzalez** [comment]
That's odd. How did you originally install, and what version was it originally?

**Comment by Flink** [comment]
I originally installed via source (git checkout) and it was at the 0.3.17 version. I then installed the packages like it was a new installation. Installation went well, my plugins and conf is still there and all is working but the package wants to upgrade to the same version (0.3.18) everytime now.

**Comment by michaelshobbs** [comment]
@josegonzalez any more thoughts here?

**Comment by josegonzalez** [comment]
I can definitely replicate it, but it's odd that the package isn't marked as up to date. Here is the control file we create:

```
Package: dokku
Version: 0.3.19
Section: base
Priority: optional
Architecture: amd64
Depends: locales, git, make, curl, software-properties-common, lxc-docker (>= 1.4.0), gcc, python-software-properties, man-db, buildstep, sshcommand, pluginhook
Pre-Depends: nginx, dnsutils, ruby, ruby-dev, rubygem-rack, rubygem-rack-protection, rubygem-sinatra, rubygem-tilt, apparmor, cgroup-lite
Provides: dokku
Maintainer: Jose Diaz-Gonzalez <dokku@josediazgonzalez.com>
Description: Docker powered mini-Heroku in around 100 lines of Bash
```

Anyone have any ideas?

**Comment by alessio** [comment]
The repository is buggy and generates faulty Packages files: https://packagecloud.io/dokku/dokku/ubuntu/dists/trusty/main/binary-amd64/Packages

I've seen some comments here, seems that packagecloud.io's staff got it sorted for them: 
https://gitlab.com/gitlab-org/omnibus-gitlab/issues/404

**Comment by alessio** [comment]
Needless to say that this affects my servers too.

**Comment by alessio** [comment]
One could use ```apt-mark hold dokku``` to mitigate the problem and keep the control over the upgrades

**Comment by josegonzalez** [comment]
Fixed on packagecloud's end. They removed `installed-size: 0` from our package and that seems to work.

To get the fix:

```
apt-get clean
apt-get update
apt-get upgrade
```
