### ISSUE TITLE
Dokku Upgrade Process Fails

### ISSUE THREAD

**Issue by remy-actual** [progrium/dokku#1209]
Upgrading from Digital Ocean Image install dokku 0.3.14 to 0.3.18 -- Ubuntu 14.04 Droplet
 
From the docs:
```
cd ~/dokku   
git pull --tags origin master

# continue to install from source
sudo DOKKU_BRANCH=master make install
```
result: 
```
...
dokku plugins-install
make: *** [plugins] Error 1
```

Removed all non-core plugins from /var/lib/dokku/plugins; repeat process:
same error.
```
$git checkout v0.3.18
$sudo DOKKU_BRANCH=master make install
```
same error.  

From https://github.com/progrium/dokku/issues/1165#issue-72814626:
> However, this does not perform an upgrade to a deb-based installation - it also doesn't actually update your progium/buildstep docker image. The correct command seems to be:
>  `sudo make install-from-deb`

Result:
```
Preparing to unpack .../dokku_0.3.18_amd64.deb ...
Error: keyfile '/root/.ssh/id_rsa.pub' not found.
       you can enter a new keyfile path when you restart the installation.
dpkg: error processing archive /var/cache/apt/archives/dokku_0.3.18_amd64.deb (--unpack):
 subprocess new pre-installation script returned error exit status 1
E: Sub-process /usr/bin/dpkg returned an error code (1)
make: *** [install-from-deb] Error 100
```

From https://github.com/progrium/dokku/issues/1203#issuecomment-104536917: 

> Re-running the installation should prompt you again, allowing you to change that path.

Re-running `sudo make install-from-deb` does not result in a prompt. :disappointed: Result is same Error 100 again. 

Regardless, I have public keys stored in `~/.ssh/authorized_keys` files for both root and dokku users, not in individual .pub files -- is it now a requirement for public keys to be stored individually? 

Private key files are of course on my local dev machine, not on the server. 

So what's the current procedure for updating a live production server? 

For the record: 
```
$cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.2 LTS"
$uname -a
Linux dokku.rootandflow.com 3.13.0-43-generic #72-Ubuntu SMP Mon Dec 8 19:35:06 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

Let me know if you require any additional info.

**Comment by 3onyc** [comment]
I suspect the Debian package is outdated, in the meantime you can change the keyfile path using:

```bash
echo "dokku dokku/key_file string /path/to/keyfile" | debconf-set-selections
```

After that you should no longer get the "keyfile ... not found" error.

---

If you still get an error on `dokku plugins-install` try running it in trace mode:

```bash
DOKKU_TRACE=1 dokku plugins-install
```

The output of that should tell you more about what's going on.

---

@josegonzalez Was packagecloud updated after the preinst fix?

**Comment by remy-actual** [comment]
I resolved the plugins-install issue. 
[Events Logger](https://github.com/alessio/dokku-events) plugin was interfering with plugins-install. 
Shouldn't have installed it in the first place -- I missed the version restriction >=0.3.13 in the docs. 
`$sudo DOKKU_BRANCH=master make install` completed successfully after removing it from the plugins directory. 
echo command in your reply @3onyc resolved the keyfile issue; `$sudo make install-from-deb` resolved successfully:
```
$root@dokku:~/dokku# dpkg -l | grep 'dokku'
ii    dokku    0.3.18    amd64    Docker powered mini-Heroku in around 100 lines of Bash
```
