### ISSUE TITLE
Advanced Installation Dokku v0.3.18 - connection error

### ISSUE THREAD

**Issue by pearlymaccha** [progrium/dokku#1211]
Hello!
I installed Dokku v0.3.18 on Ubuntu 14.04 LTS. I follow the Advanced Installation, this command:
# wget -qO- https://raw.github.com/progrium/dokku/master/bootstrap.sh | sudo DOKKU_BRANCH=master bash

Then I got the output below:
![03 configuring dokku](https://cloud.githubusercontent.com/assets/6280032/7834854/de36123c-049d-11e5-906a-c18c7ecad0ff.PNG)

After choosing Yes, Ubuntu went down or connection error. So I go to proxmox's IP Address to start the Ubuntu (I use Proxmox). But I can't access Proxmox's Web GUI. I go to https://myipaddress:8006 but can't connect to Proxmox.

Can someone tell me how to fix this? Is v0.3.18 failed or what so I can't access Proxmox's Web GUI after install Dokku Advanced Installation? Thank you.

**Comment by joshco** [comment]
I also ran into a similar problem the other day while installing dokku.The install got to the above screen (asking about the web interface).  I hit Yes, and then it just went right on doing it's install.  It never stopped and waited.

Is it trying to do some magic and opening up the web browser?

What I was expecting was for it to accept the Yes, then pause and print information with what URL to connect my browser to.   It should then wait for me to tell it that I am finished before proceeding.  Eg, "Hit return when finished with web installer"

**Comment by josegonzalez** [comment]
@3onyc peep

**Comment by 3onyc** [comment]
@pearlymaccha If I understand correctly, your VM host machine became inaccessible after trying to install Dokku on a VM? 

If so it seems unlikely they are related and that both happening at the same time is a coincidence, Dokku can't access the host machine in any way or form.

If the Dokku install succeeded you should be able to access the web config at `http://<server IP>` though.

---

@joshco After installation finishes the config can be accessed at `http://<server IP>`, printing the URL during installation is a good idea though (#1213).

**Comment by joshco** [comment]
Hmm.  I took a guess and tried to browse to that, but I got the nginx home page, not the dokku installer

**Comment by pearlymaccha** [comment]
I didn't get this message: "Hit return when finished with web installer". When I came back, my VM was stop running, and I couldn't access the web GUI. 
And I also can't access the web config at http://<server ip> or https://<server ip>.
Well, I think I failed at installing Dokku (v0.3.18). I should try again, then. Thank yu so much for your information, all 😊

**Comment by 3onyc** [comment]
@pearlymaccha There isn't a "Hit return when finished with web installer" prompt, so it's correct you didn't get that.

As for the VM being stopped during installation, that doesn't sound like something Dokku causes, so indeed, please try again, and if you have any other issues, feel free to open another ticket.
