### ISSUE TITLE
Rails file upload issue (temp file missing)

### ISSUE THREAD

**Issue by Perpherior** [progrium/dokku#1215]
My current project require to upload a large txt file(100k - 20M) by using sidekiq worker and paperclip. I don't wanna store the original file in anywhere, either S3 or locally. Therefore I decide to use sidekiq to handle the process of storing content inside original txt file into database. 
So far everything is ok locally. But on the dokku server,  sidekiq raises an error
```
Errno::ENOENT: No such file or directory - /tmp/RackMultipart20150604-161-8h054n.txt
```
(file path is directly read through params[:file].path)
I thought this is because before the worker starts, tmp file has already been removed or it even doesn't be created.
Could anyone help me?

**Comment by joshco** [comment]
How are you managing your process/workers?  With dokku native or something like supervisord?
If dokku, i think the different processes are in different containers. So you may need to use a plugin to mount persistnet storage across both so you can deal with the tempfile.

**Comment by Perpherior** [comment]
I'm using https://github.com/bigboxsoftware/dokku-sidekiq to manage it. So I think this is not because of different containers.

**Comment by joshco** [comment]
Are you sure?   The top of the readme says:
https://github.com/bigboxsoftware/dokku-sidekiq#sidekiq-plugin-for-dokku
> Adds a post-deploy hook to Dokku to automatically deploy a container running a Sidekiq worker

**Comment by Perpherior** [comment]
hmm, not be quite sure. But actually I don't wanna store the original file locally. After file uploads to server side, I think I should be able to access the temp file until rails remove it. 
And even if using persistence plugin, the server does nothing about saving the file, which means the worker still cannot find the file, doesn't it? 
Or do u mean I need to save the file locally and then remove it after worker done?

**Comment by Perpherior** [comment]
@joshco I think you are right. So what I need to do is store tempfile in mounted folder? But how to remove it after sidekiq worker done?  use another worker (because it is outside of the container)?

**Comment by joshco** [comment]
I think if you are using the mounted folder, your worker job couldn't you just call File.delete('/tmp/RackMultipart20150604-161-8h054n.txt') once you have imported it into the database?

**Comment by michaelshobbs** [comment]
@Perpherior did this work for you? is there anything else to do here?

**Comment by Perpherior** [comment]
Thanks @joshco.
@michaelshobbs yes, this approach works. And sorry for my late reply. I'll close the issue

**Comment by michaelshobbs** [comment]
Glad you got it sorted out.
