### ISSUE TITLE
How does program find files stored on the server?

### ISSUE THREAD

**Issue by windweller** [progrium/dokku#1221]
Hi, I have a backend that relies on Apple Push Notification `.pem` files! Since they are small, I don't want to put them on Amazon S3. About a year ago, I found an article or issue that talks about how to hook up dokku (or maybe docker)'s virtual directory with an actual server space. I cannot find that article anymore!  Can anyone shed some light on it?

**Comment by joshco** [comment]
you want docker volumes
> https://docs.docker.com/userguide/dockervolumes/

You can use them with dokku by setting docker options (-v is for volumes) or you can use dokku volumes plugin
> https://github.com/ohardy/dokku-volume

**Comment by windweller** [comment]
For some weird reason I found dokku volume impossible to understand/use.

`    volume:add         <app> <container_path>                        Mount a folder in <app> at <container_path>`

instruction says: `This plugin mount container_path to a generated folder in /home/dokku/.o_volume`

I found it somewhat confusing. Is this linking a container path with the actual server path? I put down a server path like this: `dokku volume:add xxx ~/apn_file`, but all it gave me is: `/home/dokku/.o_volume/data/8cad3d62-d227-409d-bd93-e7427eae2465:/root/apn_file` (if I type `dokku volume:list xxx`)

I still don't know where to put my apn files, and how should my server define relative path for it.

**Comment by michaelshobbs** [comment]
Check out this doc for some context. http://progrium.viewdocs.io/dokku/docker-options

Specifically the syntax: 
```
dokku docker-options:add myapp deploy "-v /host/path:/container/path"
```
So in your example your file is in `/root/apn_file`.

**Comment by windweller** [comment]
So even if I use dokku volume plugin, I still need to use docker-options??

**Comment by josegonzalez** [comment]
Both would work, but the docker-options stuff is just "built-into" dokku.

**Comment by michaelshobbs** [comment]
@windweller I was just referencing that doc because I thought it more clearly defined how the directory mapping between container and host behaved. i.e. `/host/path:/container/path`.

As @josegonzalez said, you can use either.

**Comment by windweller** [comment]
Thank you! I'm probably just going to use Docker option because i can't get dokku volume to work (reasons are stated above). Dokku volume doesn't seem to be linking two folders

**Comment by joshco** [comment]
You don't need to use both, one or the other
Allen, I am with you that the dokku volume plugin is incomprehensible.  it
should have a to/from path just like docker -v
I'd just go with docker options -v


On Fri, Jun 12, 2015 at 1:37 PM, Michael Hobbs <notifications@github.com>
wrote:

> @windweller <https://github.com/windweller> I was just referencing that
> doc because I thought it more clearly defined how the directory mapping
> between container and host behaved. i.e. /host/path:/container/path.
>
> As @josegonzalez <https://github.com/josegonzalez> said, you can use
> either.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/progrium/dokku/issues/1221#issuecomment-111569918>.
>



-- 

*Josh Co*hen  joshco@gmail.com | @joshco | LinkedIn
<http://linkedin.com/in/joshrcohen/> | GitHub <https://github.com/joshco>
  | OSDI opensupporter.org <http://opensupporter.org/>
"If [OSDI <http://opensupporter.org/>] succeeds, it could usher in the next
chapter in political technology." - Washington Post <http://wapo.st/1hYXX7O>

In the LGBT community, Domestic Abuse is the friendly-fire equivalent of
bullying, sexual assault, discrimination, Religion based bigotry  and other
types of  subjugation.

Let's stop it. Please help
<https://www.crowdrise.com/avpchamps-friends/fundraiser/joshcohen2>

**Comment by windweller** [comment]
Yeah! That's what I'm gonna go with! Thanks for looking into dokku volume! Closing it for now unless someone can offer more insight on how that plugin works
