### ISSUE TITLE
 Cannot create container with more than 127 parents

### ISSUE THREAD

**Issue by amitadpsl** [progrium/dokku#1222]
I have build an image and when i try to create a container of it i get the following error

Cannot create container with more than 127 parents

PLease help

**Comment by michaelshobbs** [comment]
A quick google search yields these related issues. 

#1014
docker/docker#7095

**Comment by amitadpsl** [comment]
dokku cleanup does not work for me. Is there any other way i can do it?

Containers: 0
Images: 126
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 133
 Dirperm1 Supported: false
Execution Driver: native-0.2
Kernel Version: 3.13.0-24-generic
Operating System: Ubuntu 14.04 LTS
CPUs: 4
Total Memory: 7.733 GiB
Name: PTL2310-1
ID: 2Z7Q:CNBU:DRN6:YSN2:YBG6:Q26W:CRYR:7QPC:ITMV:TIQE:ZHVH:ETOQ
WARNING: No swap limit support

**Comment by michaelshobbs** [comment]
I think you'll need to flatten your image. Is this a dokku deployment? Using a Dockerfile? Can you share the Dockerfile?

**Comment by michaelshobbs** [comment]
@amitadpsl ping

**Comment by amitadpsl** [comment]
Hi 

i am using a dockerfile to create the image. i will send the docker file soon

r

**Comment by josegonzalez** [comment]
Closing due to lack of response. This is also certainly not related to dokku, and likely user error in applying changes to the docker image.

**Comment by fiatjaf** [comment]
Not using any Dockerfile, just Heroku-like buildpacks and Procfiles. This happens with one dokku app, but not others running on the same instance. The app which is showing the error was running without issues for the last 6 months, until I added a new one, totally unrelated, dokku app. This new app runs without problem. I use no dokku plugins at all.

**Comment by fiatjaf** [comment]
Destroying the app and recreating it solved the problem.
