### ISSUE TITLE
Dokku Setup v0.3.18

### ISSUE THREAD

**Issue by pearlymaccha** [progrium/dokku#1229]
Hello, I still confuse what I should really write in Dokku Setup. What I should write in Public Key and Hostname box? And what's the example of app-name and app-port? Can I edit the Public Key and Hostname? Thank you

![04 dokku setup](https://cloud.githubusercontent.com/assets/6280032/8143447/0e58ed18-11d7-11e5-892c-185e0e365e91.png)

**Comment by joshco** [comment]
The public key is your SSH public key that you want to use to access the dokku host via SSH.

The hostname is the hostname that you want to use to access applications on dokku with a browser.
It's the public name of the system such as mydokkusystem.com or the IP addr (in your case 172.16.41.9, but don't use an IP addr if possible, use a name)

IMHO the optimal thing to do is to use a wildcard DNS name.  Eg create two DNS records

1. mydokkusystem.com A or CNAME pointing to <IP or public name of system>  in your case 172.161.41.9
2. *.mydokkusystem.com A or CNAME pointing to the same thing as above

This will enable you to access any app on the dokku system with app.mydokkusystem.

**Comment by pearlymaccha** [comment]
Can you give me an example if I use IP Addr? What port should I use? Is it 80?

**Comment by joshco** [comment]
you dont specify a port.  Just the IPaddr like in your screenshot.  Dokku will automatically set the port per app.

**Comment by pearlymaccha** [comment]
Do you know where I'm able to edit or change the Hostname box?

**Comment by joshco** [comment]
Is the hostname edit field not editable?  it should be

**Comment by pearlymaccha** [comment]
Actually I fill the hostname with DNS which is not able yet. So when I open it, the webpage is not available. Can I have your solution?

**Comment by joshco** [comment]
If your DNS is not ready, just use the IP address. 
Then later on, you can change the configuration to use the hostname when u are ready

**Comment by pearlymaccha** [comment]
Ok, I got it. Thank you very much for your help @joshco

**Comment by joshco** [comment]
Your welcome, good luck
