### ISSUE TITLE
Paperclip AWS uploading issue

### ISSUE THREAD

**Issue by gekong** [progrium/dokku#1230]
Hi I have an app that I is working on heroku and I am trying to make it work on dokku but I am having issues with uploading large files. Smaller files less than 100k works perfectly it sends it to S3 crops its no problem.

**Comment by gekong** [comment]
with sudo docker inspect I already have tmp folders added
    "Volumes": {
        "/app/public/system": "/home/uploadpixaller",
        "/app/tmp": "/home/tmppixaller"
    },
    "VolumesRW": {
        "/app/public/system": true,
        "/app/tmp": true
    }

I have already added temp files

**Comment by joshco** [comment]
if you are getting a max file upload size exceeded you need to adjust your nginx configuration
look for the client_max_body_size directive

**Comment by gekong** [comment]
@joshco Thanks for the very quick response, yes I do have this error on my-app-error.log should I just add this directive in my /home/dokku/myapp/nginx.conf.template?

**Comment by joshco** [comment]
i put mine in the /etc/nginx/nginx.conf file, so all of my apps have it.  I would guess it would work on a per app basis

**Comment by gekong** [comment]
@joshco Thanks. Yep it and it does work on a per app basis as well. Thanks again.
