### ISSUE TITLE
Docker steps are not cached

### ISSUE THREAD

**Issue by yngndrw** [progrium/dokku#1231]
When using Dockerfiles, each build step is not cached. This looks to be by design:
https://github.com/progrium/dokku/commit/9a71fff3f1e599e4148b9562b092c7388018add1

Is there a way of allowing the occasional forcing of fresh builds without disabling caching for every build step ?

My particular use-case is shown here, where the package restore is rather slow and mostly the same each time:
https://github.com/aspnet/aspnet-docker/issues/59

Maybe Dokku could include a http proxy for this kind of thing ? Or a cache volume could be attached automatically ?

**Comment by michaelshobbs** [comment]
While there is not currently a way to control Dockerfile build cache, we would welcome a PR. 

With regards to a cache volume, you can accomplish this by using the built-in docker-options plugin. Check out the docs for usage examples.

**Comment by michaelshobbs** [comment]
@Flink ping

**Comment by Flink** [comment]
Maybe we could control to cache (or not) on a build with an ENV var per app?
Something like this:
```
dokku config:set my_docker_app DOKKU_DOCKERFILE_CACHE_BUILD=false
```
With a default value set to `true` maybe?

**Comment by michaelshobbs** [comment]
Works for me

**Comment by Flink** [comment]
Ok I’ll give it a try soon :)

**Comment by michaelshobbs** [comment]
@Flink i had some time this morning and put together a PR. #1232

**Comment by Flink** [comment]
Ok greak, I’ll have look :)

**Comment by yngndrw** [comment]
Wow, that was quick. I blinked and missed it.

Thanks for the speedy turn-around guys, that change should be perfect for my use case.
