### ISSUE TITLE
Add SSH key creation to installation instructions

### ISSUE THREAD

**Issue by Stormcore** [progrium/dokku#1235]
It must be visible on the ReadMe page that user MUST run
sudo ssh-keygen -t rsa -b 4096 -C "your_email@example.com"

otherwise installation will be broken with no any ability to repair (Should note that too)

**Comment by josegonzalez** [comment]
It is presumed that you will upload your ssh key via sshcommand. This is documented several places. Users who do not know how to generate an ssh key in the first place are not our target audience, and as such I am closing this as wontfix. Sorry.
