### ISSUE TITLE
cgroup-lite dependency prevents installation on Debian

### ISSUE THREAD

**Issue by ChimeraCoder** [progrium/dokku#1236]
`cgroup-lite` was added as a dependency with #978, but this package is not available on Debian, which provides only `cgroup-bin`. As a result, `0.3.15` is the most recent version of Dokku that can be installed on Debian.

I believe that simply replacing `cgroup-lite` with `cgroup-bin` should fix the issue on both systems; this is why the [official Docker package uses the latter](https://github.com/docker/docker/issues/2990#issuecomment-29666967).

Related: #976.

**Comment by josegonzalez** [comment]
I was going to fix this but it seems like the `cgroup-bin` and `lxc` packages [are not compatible](https://github.com/docker/docker/pull/3085). At the moment, we do not support debian as an install target, though #1076 may help users who want to install onto debian-based systems.
