### ISSUE TITLE
Script on creation

### ISSUE THREAD

**Issue by geekuillaume** [progrium/dokku#1238]
Is it possible set a script to executeon each app creation ?

This script should be able to access the name of the new app and modify the ENV.

#### Explication:
I use a continuous integration system that push every new branch on a new app on the server but still need to create a database user and ENV before pushing my code.

It would be awesome to put this in a script that execute automatically on app creation.

Thanks !
Guillaume Besson

**Comment by michaelshobbs** [comment]
Check out the plugins and pluginhook sections of the docs.

**Comment by geekuillaume** [comment]
Exactly what I needed ! Thanks a lot :)

**Comment by michaelshobbs** [comment]
No problem. If you end up writing your own plugin, feel free to add it to the list.
