### ISSUE TITLE
sh: 1: gulp: not found

### ISSUE THREAD

**Issue by olalonde** [progrium/dokku#1239]
I'm getting an error with my Node.js' app start script:

```json
  "scripts": {
    "start": "./node_modules/.bin/gulp serve"
  }
```

```bash
-----> Caching node_modules directory for future builds
-----> Cleaning up node-gyp and npm artifacts
-----> No Procfile found; Adding npm start to new Procfile
-----> Building runtime environment
-----> Discovering process types
       Procfile declares types -> web
-----> Releasing testapp...
-----> Deploying testapp...
-----> Running pre-flight checks
       For more efficient zero downtime deployments, create a file CHECKS.
       See http://progrium.viewdocs.io/dokku/checks-examples.md for examples
       CHECKS file not found in container: Running simple container check...
-----> Waiting for 35 seconds ...
remote: App container failed to start!!
=====> testapp container output:
       > TestApp@0.0.0 start /app
       > gulp serve
       sh: 1: gulp: not found
       npm ERR! TestApp@0.0.0 start: `gulp serve`
```

Why is gulp not being found? It is specified in my devDependencies and is present in `./node_modules/.bin`. I don't have a Procfile. I have a `Dockerfile.dev` which I use for local development.

**Comment by olalonde** [comment]
Is it possible to `run /bin/bash` in the container dokku uses to troubleshoot this issue?

**Comment by olalonde** [comment]
I just ran `docker run --rm -i -t dokku/gamblebit /bin/bash` and it seems dokku isn't installing any of the `devDependencies`.

**Comment by olalonde** [comment]
Related: https://github.com/progrium/dokku/issues/464

Seems devDependencies are not installed by default. Need to set NODE_ENV to development.

**Comment by olalonde** [comment]
Well, I just tried that and it won't install devDependencies either.

**Comment by michaelshobbs** [comment]
So if you do a `dokku run <myapp> ls -l /app/node_modules/.bin/`, you don't see `gulp`? Checking one of my `gulp` apps, we put gulp in the `dependencies` section and not `devDependencies`. 

If you are running your app via `gulp serve`, then I would just move `gulp` to `dependencies`.

**Comment by olalonde** [comment]
Fixed by adding gulp to dependencies instead of devDependencies.

**Comment by DenisIzmaylov** [comment]
It's actual for me. I have gulp in `dependencies`:
```
    "gulp": "^3.9.0",
```
But when I try to do `dokku run out-service.git ls -l /app/node_modules` it outputs:
```bash
ls: cannot access /app/node_modules: No such file or directory
```
But `dokku run out-service.git ls -l /app` displays me my project directory.

**Comment by olalonde** [comment]
@DenisIzmaylov looks like you should open a new issue!
