### ISSUE TITLE
502 Bad Gateway when starting a Spring Boot App

### ISSUE THREAD

**Issue by glawson6** [progrium/dokku#1240]
The app is started and running on port 5000.

**Comment by josegonzalez** [comment]
What happens when you do `docker ps`? Is the container started?

**Comment by glawson6** [comment]
Yes, the container is started. I got around the error by restarting nginx.

**Comment by josegonzalez** [comment]
Thats odd, nginx should reload on container deploy. Have you been able to replicate the issue since?

**Comment by glawson6** [comment]
The issue has popped up before, I knew to restart nginx and it went away. 


     On Tuesday, June 23, 2015 9:44 PM, Jose Diaz-Gonzalez <notifications@github.com> wrote:
   

 Thats odd, nginx should reload on container deploy. Have you been able to replicate the issue since?—

**Comment by josegonzalez** [comment]
If you could get us verbose log output when this issue occurs again, that would be great. Sounds like maybe nginx isn't reloading properly, which seems unlikely, but *shrug*.

**Comment by glawson6** [comment]
Ok, No problem. Who do ask about the MYSQL Dokku plugin?
 


     On Wednesday, June 24, 2015 2:36 PM, Jose Diaz-Gonzalez <notifications@github.com> wrote:
   

 If you could get us verbose log output when this issue occurs again, that would be great. Sounds like maybe nginx isn't reloading properly, which seems unlikely, but shrug.—

**Comment by josegonzalez** [comment]
The maintainer of that plugin. Dokku doesn't provide any datastorage plugins by default. Are you using dokku-alt by any chance?

**Comment by michaelshobbs** [comment]
Is there anything left to do here? @josegonzalez shall we close?

**Comment by glawson6** [comment]
Yes 


     On Monday, July 27, 2015 12:42 PM, Michael Hobbs <notifications@github.com> wrote:
   

 Is there anything left to do here? @josegonzalez shall we close?—

**Comment by michaelshobbs** [comment]
@glawson6 yes to what?

**Comment by glawson6** [comment]
Yes close.
 


     On Monday, July 27, 2015 12:58 PM, Michael Hobbs <notifications@github.com> wrote:
   

 @glawson6 yes to what?—
