### ISSUE TITLE
`sshcommand acl-add dokku ` is not idempotent

### ISSUE THREAD

**Issue by olalonde** [progrium/dokku#1241]
If you add the same key multiple times, it will keep creating entries in `.ssh/authorized_keys`. I suppose that is rarely the expected behaviour so it would be nice to add a quick check to make sure the key doesn't already exist.

**Comment by michaelshobbs** [comment]
This should probably be logged against https://github.com/progrium/sshcommand

**Comment by olalonde** [comment]
Ok thanks, I created an issue there https://github.com/progrium/sshcommand/issues/14
