### ISSUE TITLE
Error uploading to git remote

### ISSUE THREAD

**Issue by kennetham** [progrium/dokku#1242]
Hi I have succssfully deployed Dokku, but I can't seem to deploy using the `git remote dokku dokku@domain....` command. It either return a `Enter password` field or it tells me the git repository doesn't have the rights to do so.

I tried to `cat id_rsa.pub | ssh...` but what should I input for ssh. Because if I were to do a ssh dokku@<hostname> it would fail as well because there isn't such a user. I am running on an Azure Ubuntu VM.

Please advise.

**Comment by michaelshobbs** [comment]
You'll need to pipe the contents of the public key side of the ssh key you'll be using for deployments into [sshcommand](https://github.com/progrium/sshcommand), not ssh. 

Example 
```
echo "contents of public key" | sshcommand acl-add dokku deploy
```

**Comment by kennetham** [comment]
@michaelshobbs may i clarify, so I need to download sshcommand, and then from my machine, do I need to `cat ~/.ssh/id_rsa.pub | ssh username@hostvmserver sshcommand acl-add dokku deploy` or the example you provided would suffice?

Besides, the installation of sshcommand should be run as a bash file `./sshcommand`?

This might be what I need since I have been getting issues with Dokku. Besides, I have pasted the public key on http://<ip>:2000 but it didn't reflect though.

**Comment by michaelshobbs** [comment]
sshcommand is installed with dokku

**Comment by michaelshobbs** [comment]
Also check what is in `/home/dokku/.ssh/authorized_keys`

**Comment by kennetham** [comment]
Alright I'll check that. So within my VM, I would need to docker ssh into dokku? My Ubuntu VM authorized_keys is empty though.

**Comment by michaelshobbs** [comment]
Not in docker, just the docker host.

**Comment by kennetham** [comment]
That is my Host VM? Yup it was empty. Even after setting the public key in `http://ip:2000`

**Comment by kennetham** [comment]
I got this error.

/usr/local/bin/sshcommand: line 55: /home/dokku/.ssh/authorized_keys: Permission denied

**Comment by michaelshobbs** [comment]
Run it as root

**Comment by kennetham** [comment]
It's still prompting me for a password when I tried doing this `git remote add dokku dokku@<host_vm>.cloudapp.net:nodejsapp`.

I have successfully added it as you have recommended. Am I missing a step? I have followed the guide as it is.

**Comment by michaelshobbs** [comment]
The issue is that `/home/dokku/.ssh/authorized_keys` is empty. You'll need to get that sshcommand command to work. Feel free to share the command you ran and the output.

**Comment by kennetham** [comment]
root@testvm:/home/user1# echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDFsIWXoXnwt+aOq+rKHmVs0eQXO3IJEjTCx1ORkIy8E+dMhfdkqlJdbs9zZ8/Pxpn3HvIMbIo6/Nl8o22fvVKuA/DzzOcdyyDoIAWBA/MO9ghscOKOHnLl5O7KFYRzkPzxBaxfrHWxsgQLH+5CC8hH6zeVmPV5ysEgEaEY3th9CyAyWMtaUyd7yt/HZzJCjliFiK4lzKM6ZS96tTcsMPkN44XRws887VcgTStMcICVgREFie9y0Fr8NMX+uM9A/0w6h7V344JScYmNrZ9ryCjLUlrdlrQhbPmZnTx1xTEvb0i64AUbr3jDW7uifvFn6b2qV9ipO2ZIDyzzE9rQFxgx testvm@vm1sea.local" | sshcommand acl-add dokku deploy
cd:10:fe:93:73:d2:4f:31:5b:e9:8b:76:aa:2b:8f:9d

**Comment by michaelshobbs** [comment]
And what's in `/home/dokku/.ssh/authorized_keys`? Looks like that command completed. Make sure you're checking the `dokku` user's `.ssh` directory.

**Comment by kennetham** [comment]
authorized_keys unfortunately resulted in an empty file. I manually entered it in as followed

```text
"ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDFsIWXoXnwt+aOq+rKHmVs0eQXO3IJEjTCx1ORkIy8E+dMhfdkqlJdbs9zZ8/Pxpn3HvIMbIo6/Nl8o22fvVKuA/DzzOcdyyDoIAWBA/MO9ghscOKOHnLl5O7KFYRzkPzxBaxfrHWxsgQLH+5CC8hH6zeVmPV5ysEgEaEY3th9CyAyWMtaUyd7yt/HZzJCjliFiK4lzKM6ZS96tTcsMPkN44XRws887VcgTStMcICVgREFie9y0Fr8NMX+uM9A/0w6h7V344JScYmNrZ9ryCjLUlrdlrQhbPmZnTx1xTEvb0i64AUbr3jDW7uifvFn6b2qV9ipO2ZIDyzzE9rQFxgx testvm@vm1sea.local"
```

But I am still getting a password request upon `git push dokku master` command

**Comment by michaelshobbs** [comment]
Unfortunately for this issue, sshcommand doesn't just pass the pubkey through. It adds additional necessary ssh options. Not sure what's going on here for you. How was this vm provisioned?

**Comment by kennetham** [comment]
I provisioned an Ubuntu 14.04LTS on Windows Azure. Did the same commands, run it through the same setup as on Github. No idea what's wrong though

**Comment by michaelshobbs** [comment]
Here's what that file should look like. (From my test environment)
```
root@dokku:~# cat /home/dokku/.ssh/authorized_keys
command="FINGERPRINT=06:df:22:54:26:92:d4:ac:76:91:b1:3f:51:26:01:f3 NAME=test `cat /home/dokku/.sshcommand` $SSH_ORIGINAL_COMMAND",no-agent-forwarding,no-user-rc,no-X11-forwarding,no-port-forwarding ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDd7hKztLrPo3VlVn5I5EXZ3RQf/Kxtux+YoOQ7sL/i+iAncdCA3oscEQFxW564NAe8pEazJ/u4TFRuv3KQ5rlxs0mo/I2GPZqwJdahW/x60vinF+ilwUQpLiZO5qIqh1d1WHYKG0lkwBe+cIHjnPTL2yKSnlh3LIkPYXQNzLuKYnzYc16JoCfIYtl1/C+k/7Km/0Uyo0sBFkZB+ireXr2wQIjgoaoLVQyXKbDtBJplQkFRDvFVMYzaho05aNYxYFkw0sdLT1eYxB9SDoiQjDqinyp09IrOOPSyEvhJXhPrEqCloSXIWNwdDFzEESOkKSDdtP/vZ/v96gqEoRUHUrFt root@dokku
```

From this command:
```
root@dokku:~# history  | grep sshcommand
  234  echo "AAAAB3NzaC1yc2EAAAADAQABAAABAQDd7hKztLrPo3VlVn5I5EXZ3RQf/Kxtux+YoOQ7sL/i+iAncdCA3oscEQFxW564NAe8pEazJ/u4TFRuv3KQ5rlxs0mo/I2GPZqwJdahW/x60vinF+ilwUQpLiZO5qIqh1d1WHYKG0lkwBe+cIHjnPTL2yKSnlh3LIkPYXQNzLuKYnzYc16JoCfIYtl1/C+k/7Km/0Uyo0sBFkZB+ireXr2wQIjgoaoLVQyXKbDtBJplQkFRDvFVMYzaho05aNYxYFkw0sdLT1eYxB9SDoiQjDqinyp09IrOOPSyEvhJXhPrEqCloSXIWNwdDFzEESOkKSDdtP/vZ/v96gqEoRUHUrFt root@dokku" | sshcommand acl-add dokku test
```

Out of curiosity, what is in `/home/dokku/.sshcommand`?

**Comment by kennetham** [comment]
Could I manually enter that in? I tried the sshcommand method but authorized_keys is always empty.

**Comment by michaelshobbs** [comment]
Sure you could. I'm concerned there is something else going on however.

**Comment by kennetham** [comment]
I see. Give me a moment while I pull the `/home/dokku/.sshcommand` I just reloaded my VM environment

**Comment by kennetham** [comment]
`/usr/local/bin/dokku` this is inside of `/home/dokku/.sshcommand`

**Comment by kennetham** [comment]
`authorized_keys` is now showing what you have just showed me above. But I am not sure why I can't deploy the Heroku Node JS App sample. It keeps requesting for password

**Comment by michaelshobbs** [comment]
It's simple ssh config at this point. You'll need to load the private key into the ssh-agent on the host you're pushing from or add config to your local `.ssh/config`

**Comment by michaelshobbs** [comment]
Most important is telling ssh which private key to use for your dokku host.

**Comment by michaelshobbs** [comment]
Example 
```
Host vm1sea
  User dokku
  Hostname <ip>
  Port 22
  IdentityFile /path/to/private/key/file
```

**Comment by kennetham** [comment]
Allow me to clarify, the host that I am pushing from is directly from my machine which has both my public and private key configured under `.ssh` with a wildcard access in `config` so basically everything is passed. I think maybe I need to specifically identify it then which key to use. I missed that again.

I'll try that later. Thank you for the tips.

**Comment by kennetham** [comment]
By the way @michaelshobbs before all that, do I need to go through this step of creating a user and all?
`https://github.com/dokku-alt/dokku-alt/tree/master/gitreceive`

**Comment by michaelshobbs** [comment]
To be clear, this the dokku project and not dokku-alt. So I don't know what is done during their installation process. However, using our installation, a `dokku` user is created for you.

**Comment by kennetham** [comment]
Ah that's right, what am I thinking. I was looking at `dokku-alt` gitreceive module. Cool, I'll set up the ssh config and try again.

**Comment by kennetham** [comment]
@michaelshobbs yes I forgot to setup `.ssh/config`. It is working now. However I am not able to actually view the page. It says the host does not exist. It has successfully been deployed.

**Comment by michaelshobbs** [comment]
Sound like a DNS issue?

**Comment by kennetham** [comment]
No idea. Might be. Trying to see what's wrong with it.

**Comment by kennetham** [comment]
I found this error while installing.
`modprobe: FATAL: Module aufs not found.`

**Comment by michaelshobbs** [comment]
That's just output from when we check if that module already exists. If not we grab it and install it. 

You wouldn't have gotten deployed if that was really an issue.

**Comment by michaelshobbs** [comment]
@kennetham did you verify that your DNS is setup correctly? what error are you seeing now and when doing what operation?

**Comment by kennetham** [comment]
Yup I verified that DNS is setup correctly. It's pointing to the nameservers and all. Besides, I also checked `/home/dokku/HOSTNAME` and `/home/dokku/VHOST`, the DNS is inside. I `dig` and `nslookup` no problem as well.

Upon deployment, git tells me it has successfully been pulled, then dokku says it's successfully deployed to the link provided. However when I access the URL, it just showed the usual page when you don't have internet connection or the page just doesn't exist, it's a error to connect anywhere page.

**Comment by michaelshobbs** [comment]
So that makes no sense. Do you get the dokku server IP when you `dig` the hostname of the URL that dokku spits out at the end of deployment?

**Comment by kennetham** [comment]
Yup I got the dokku server. I am running on Windows Azure VM, so the DNS that I am provisioned with is configured to the IP address which is the server running dokku. Yup that's correct, dokku spits out the server IP with the hostname of the url after deployment.

**Comment by michaelshobbs** [comment]
The error page you are describing is definitely DNS related. Maybe it's a local DNS cache issue. Fyi chrome caches on top of the system cache. Restarting chrome generally clears it. Let us know what you find out.

**Comment by kennetham** [comment]
Yup sounds like. I will try that out. I have a quick question on top of that. Dokku itself runs like Heroku, so which means to say, to deploy my project, it is exactly like Heroku? How about the buildpacks and databases? How do those come into play? For instance, if I want to spin off a Ruby / Node.js / Python web project with probably database backend such as Redis / MongoDB / RethinkDB etc, how do I configure them within Dokku? I don't see much of those in the documentation.

**Comment by michaelshobbs** [comment]
Dokku uses the exact same BUILDPACK code as Heroku. Obviously there is no managed infrastructure with dokku. That's up to you. So you can either run your own data stores and inject config variables into your app with `dokku config:set` or use a plugin. You can find more info about available plugins in the docs.

**Comment by kennetham** [comment]
I see, that's awesome. So if I use say a plugin, following the instructions to deploy, all I need to do is to configure my deployment to link to that plugin installed right? Do I need to do any like manual dokku command to link it?

**Comment by michaelshobbs** [comment]
Go ahead and contact the plugin maintainer for implementation specifics.

**Comment by kennetham** [comment]
Got you. I will get back to you on the DNS issue.

**Comment by kennetham** [comment]
There is an error downloading and installing v0.3.19.
`E: Version '0.3.19' for 'dokku' was not found`

**Comment by michaelshobbs** [comment]
An issue is already open for that. #1247 @josegonzalez will resolve shortly

**Comment by kennetham** [comment]
@michaelshobbs got that. thanks for following up

**Comment by josegonzalez** [comment]
Fixed the 0.3.19 issue.

**Comment by kennetham** [comment]
Hi @michaelshobbs I have reinstalled v0.3.19 but the DNS is still the issue. I have successfully deployed Heroku Node.js app but I can't get it to point to my domain. Are there any settings that I need to set?

**Comment by kennetham** [comment]
weird enough, it pointed not to the subdomain, but the main domain instead. `nussky.cloudapp.net` instead of `nodejsapp.nussky.cloudapp.net`. Why is this so?

**Comment by joshco** [comment]
Did you create a wildcard DNS record?  Make sure you have DNS records for
nussky.cloudapp.net AND *.nussky.cloudapp.net


On Thu, Jun 25, 2015 at 10:28 AM, Kenneth Ham <notifications@github.com>
wrote:

> weird enough, it pointed not to the subdomain, but the main domain
> instead. nussky.cloudapp.net instead of nodejsapp.nussky.cloudapp.net.
> Why is this so?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/progrium/dokku/issues/1242#issuecomment-115276002>.
>



-- 

*Josh Co*hen  joshco@gmail.com | @joshco | LinkedIn
<http://linkedin.com/in/joshrcohen/> | GitHub <https://github.com/joshco>
  | OSDI opensupporter.org <http://opensupporter.org/>
"If [OSDI <http://opensupporter.org/>] succeeds, it could usher in the next
chapter in political technology." - Washington Post <http://wapo.st/1hYXX7O>

In the LGBT community, Domestic Abuse is the friendly-fire equivalent of
bullying, sexual assault, discrimination, Religion based bigotry  and other
types of  subjugation.

Let's stop it. Please help
<https://www.crowdrise.com/avpchamps-friends/fundraiser/joshcohen2>

**Comment by kennetham** [comment]
@joshco I am actually checking now on Azure how to set that up

**Comment by michaelshobbs** [comment]
@kennetham in case you missed these

http://progrium.viewdocs.io/dokku/dns
http://progrium.viewdocs.io/dokku/application-deployment (see deploying to subdomains)

**Comment by kennetham** [comment]
Thanks @michaelshobbs for walking me through the errors. It's a DNS issue and it's fixed. I'm getting a new domain to test out tomorrow. As of now, all is fixed. I just need to figure how to link databases to the app.

**Comment by michaelshobbs** [comment]
:+1:
