### ISSUE TITLE
Getting "E: Version '0.3.19' for 'dokku' was not found" with a fresh install of Dokku

### ISSUE THREAD

**Issue by harley** [progrium/dokku#1247]
0.3.19 was just released so I'm guessing there's a bug somewhere. This is my first time trying Dokku out

Installing without setting DOKKU_TAG defaults to 0.3.18 and get the same error as indicated in #1196 

Ubuntu 14.04.2 LTS (GNU/Linux 3.13.0-53-generic x86_64) on EC2

`sudo DOKKU_TAG=v0.3.17 bash bootstrap.sh` works fine

**Comment by hzhu** [comment]
Same issue on Ubuntu 14.04.2 LTS (GNU/Linux 3.13.0-48-generic x86_64) EC2 when running `sudo DOKKU_TAG=v0.3.18 bash bootstrap.sh`

    Error: keyfile '/root/.ssh/id_rsa.pub' not found.
    you can enter a new keyfile path when you restart the installation.
    dpkg: error processing archive /var/cache/apt/archives/dokku_0.3.18_amd64.deb (--unpack):
    subprocess new pre-installation script returned error exit status 1
    Errors were encountered while processing:
    /var/cache/apt/archives/dokku_0.3.18_amd64.deb
    E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by dalareo** [comment]
I have set DOKKU_TAG=master and everything seems OK

**Comment by martijndeh** [comment]
@hzhu That's a different issue and is because `~/.ssh/id_rsa.pub` doesn't exist. `0.3.19` can't be installed at all.

**Comment by josegonzalez** [comment]
Sorry I hadn't uploaded a new package until just now - long flight - though version 0.3.19 should be up now.

**Comment by FWeinb** [comment]
Still getting the same error on Digital Ocean: 
```
Preparing to unpack .../dokku_0.3.19_amd64.deb ...
reload: Unknown instance:
dpkg: error processing archive /var/cache/apt/archives/dokku_0.3.19_amd64.deb (--unpack):
 subprocess new pre-installation script returned error exit status 1
Errors were encountered while processing:
 /var/cache/apt/archives/dokku_0.3.19_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by josegonzalez** [comment]
@FWeinb that seems to be a separate issue related to nginx reloading. I'm actually going to fix this right now.

**Comment by josegonzalez** [comment]
@hzhu your issue is different, and related to the first 2 lines in the output.

**Comment by FWeinb** [comment]
@jagandecapri Thanks for fixing it this fast. Is it possible to install that somehow? I would also like to switch to the `apt-get` based installation.

**Comment by josegonzalez** [comment]
@FWeinb try the following:

```
sudo su -
cd /root/dokku
/etc/init.d/nginx stop
service nginx start
apt-get install dokku
service nginx stop
/etc/init.d/nginx start
```

**Comment by FWeinb** [comment]
That worked great, thanks.
