### ISSUE TITLE
Is it possible to set custom docker run command?

### ISSUE THREAD

**Issue by kilianc** [progrium/dokku#1249]
Is it possible to override the `CMD` directive in the `Dockerfile` with a per app conf? With base docker I do this just doing `docker run myimage echo hello` and it will ignore the `CMD`

This will be very useful when deploying the same image for multiple envs or just the same app but with different parameters

**Comment by michaelshobbs** [comment]
https://docs.docker.com/reference/builder/ (See Entrypoint) 
Also, google dockerfile cmd vs entrypoint.

**Comment by kilianc** [comment]
I am sorry @michaelshobbs but I don't understand why you closed this and directed me to bunch of docs I am well aware of.

The question is how do I change the deploy container `CMD` aka `docker run $CONTAINER_DEPLOY_PARAMS dokku/myapp $START_CMD`.

I tried to figure it out myself looking at source code here: https://github.com/progrium/dokku/blob/master/dokku#L94 but I can't find where `$START_CMD` is set.

**Comment by kilianc** [comment]
I also looked at http://progrium.viewdocs.io/dokku/docker-options but this only allows me to setup container options.

Hoping this will make my question even more clear, if you look here https://docs.docker.com/reference/run/ you can see:

`$ docker run [OPTIONS] IMAGE[:TAG|@DIGEST] [COMMAND] [ARG...]`

I am only able to set `[OPTIONS]` through `DOCKER_OPTIONS_DEPLOY` and not `[COMMAND] [ARG...]` regardless of the fact I did set an entry point or not. Without `[COMMAND] [ARG...]` docker run just executes the last `CMD` / `ENTRYPOINT` he finds in the image.

**Comment by michaelshobbs** [comment]
I closed the issue as it seemed you were asking about docker and not dokku. Also, `$START_CMD` is empty when deploying a dockerfile.

**Comment by kilianc** [comment]
@michaelshobbs ok, now that the question is clear may I have an answer?

**Comment by josegonzalez** [comment]
@michaelshobbs I think he wants to specify a `START_CMD`, allowing him to reuse the same docker image. Can you set the cmd/entrypoint via an option in docker?

**Comment by kilianc** [comment]
@josegonzalez yes just `docker run myimage mycommand`.

If you setup and `ENTRYPOINT` `mycommand` will be passed as arg to it, if a `CMD` is defined it will be ignored and `mycommand` executed

**Comment by kilianc** [comment]
Looking at the code I just need a way to set `$START_CMD`, but I may be wrong

**Comment by michaelshobbs** [comment]
Ah I see. My bad. There is no way currently to set `$START_CMD`

**Comment by kilianc** [comment]
What about:

```bash
[[ -z "$DOKKU_BUILDSTEP" ]] && START_CMD=$(dokku config:get $APP DOKKU_DOCKERFILE_START_CMD)
``` 
?

**Comment by michaelshobbs** [comment]
PRs are always welcomed.

**Comment by kilianc** [comment]
@michaelshobbs sure, will do my best because I am not really expert in bash scripting. I guess there is also a test suite to add. I will investigate and try to pull it off. :+1:
