### ISSUE TITLE
config:set doesn't allow spaces in values over ssh

### ISSUE THREAD

**Issue by kilianc** [progrium/dokku#1253]
```
dokku config:set myapp DOKKU_DOCKERFILE_START_CMD="http-server --proxy https://github.com"
Usage: dokku config:set APP KEY1=VALUE1 [KEY2=VALUE2 ...]
Must specify KEY and VALUE to set.
```

**Comment by kilianc** [comment]
I just figured that this happens only through SSH and works just fine on local machine

**Comment by michaelshobbs** [comment]
You'll want to escape the quotes as we do in our tests.

```
ssh dokku@dokku.me config:set app_name test_var=true test_var2=\"hello world\"
```

**Comment by kilianc** [comment]
@michaelshobbs makes sense, I read another thread here where about this problem and one of the things that came up is the fact that simply splitting by `=` would work if we drop support for multiple set per command.

I 100% agree with that, it's a lot of code to parse for basically no gain in terms of UX.

**Comment by michaelshobbs** [comment]
If you are suggesting we drop support for setting multiple variables at once, I'd definitely want more voices in that discussion that just ours.

**Comment by kilianc** [comment]
@michaelshobbs sure and I just agreed to dropping support to multiple set reading this: https://github.com/progrium/dokku/issues/482

I don't think anybody expects multiple sets as standard behavior, if the issue is the app restarting every time then we should have an option to avoid that, I think...

**Comment by michaelshobbs** [comment]
My understanding is that dokku is supposed to mirror Heroku functionality as closely as possible. 

https://devcenter.heroku.com/articles/config-vars

**Comment by kilianc** [comment]
If that's the case then we must keep it. To be honest the way I see this heading, the whole concept of buildstep and the consistency to heroku is just overcomplicating things... We have dockerfile support now, why would anyone use anything but that? Wouldn't it make sense to focus on building docker images for each type of app?

Rant aside, again, if the goal is to be heroku then it's ok to be consistent with it.

**Comment by michaelshobbs** [comment]
Those are valid questions. I'm relatively new to this party so I'll leave these to be answered by someone with more historical context.

**Comment by kilianc** [comment]
I wonder what mister @progrium thinks about dropping buildsteps support and in general diverging from heroku being the de facto the opensource push to deploy docker PaaS.

**Comment by progrium** [comment]
It's on its way to having less focus on buildstep/Heroku builds...

On Thu, Jun 25, 2015 at 9:44 PM, Kilian Ciuffolo <notifications@github.com>
wrote:

> I wonder what mister @progrium <https://github.com/progrium> thinks about
> dropping buildsteps support and in general diverging from heroku being the
> de facto the opensource push to deploy docker PaaS.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/progrium/dokku/issues/1253#issuecomment-115505391>.
>



-- 
Jeff Lindsay
http://progrium.com

**Comment by michaelshobbs** [comment]
@progrium can you be more specific? I am not quite clear on your point as less focus does not mean dropped support.

**Comment by progrium** [comment]
Ah, I didn't have full context of issue/thread here. I think at one point
emulating Heroku fairly closely was a good goal for Dokku, but I don't
think it needs to remain the goal. Dokku should focus on providing value to
users while remaining simple and hackable.



On Fri, Jun 26, 2015 at 6:39 AM, Michael Hobbs <notifications@github.com>
wrote:

> @progrium <https://github.com/progrium> can you be more specific? I am
> not quite clear on your point as less focus does not mean dropped support.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/progrium/dokku/issues/1253#issuecomment-115692513>.
>



-- 
Jeff Lindsay
http://progrium.com

**Comment by josegonzalez** [comment]
I'm -1 to dropping buildstep support, and if there are any changes to that, I'm actually going to stop helping maintain dokku.

Not everyone here wants to learn Dockerfile syntax, nor should we expect users to. Giving users an easy migration path from Heroku to Dokku also means we have both a larger pool of users/testers and that we have a more polished app due to everyone's feedback. I don't think we would be providing value by dropping features that currently work - and work quite well.

If you just want to be able to run dockerfiles via git push, Dokku is overkill.

Re: this issue, I think this is solved client-side by the `heroku` client - and that they speak over not-ssh with the heroku server - so I'm not sure we can solve this other than by potentially serializing all the data in a client and then deserializing it server-side.

**Comment by progrium** [comment]
We've always been loose on exact ux emulsion of Heroku. It's more about the
build and runtime, which will always be part of Dokku. You will always be
able to run Heroku apps on Dokku.

On Friday, June 26, 2015, Jose Diaz-Gonzalez <notifications@github.com>
wrote:

> I'm -1 to dropping buildstep support, and if there are any changes to
> that, I'm actually going to stop helping maintain dokku.
>
> Not everyone here wants to learn Dockerfile syntax, nor should we expect
> users to. Giving users an easy migration path from Heroku to Dokku also
> means we have both a larger pool of users/testers and that we have a more
> polished app due to everyone's feedback. I don't think we would be
> providing value by dropping features that currently work - and work quite
> well.
>
> If you just want to be able to run dockerfiles via git push, Dokku is
> overkill.
>
> Re: this issue, I think this is solved client-side by the heroku client -
> and that they speak over not-ssh with the heroku server - so I'm not sure
> we can solve this other than by potentially serializing all the data in a
> client and then deserializing it server-side.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/progrium/dokku/issues/1253#issuecomment-115708726>.
>


-- 
Jeff Lindsay
http://progrium.com

**Comment by josegonzalez** [comment]
If we remove setting multiple env vars, we'll immediately get a user asking for that feature back. I guarantee it.

**Comment by progrium** [comment]
I imagine! I guess I don't understand why this particular thing is a big deal to support. 

I know this key value with quotes and shell arg parsing is messy, but if we were to change it slightly so users need to do `config:set key1=foobar "key2=multiple words"` this will significantly reduce complexity in parsing. Each key-value is an arg which can then be split by `=`.

**Comment by michaelshobbs** [comment]
We do support that UX when `dokku` is invoked locally. This particular issue is specifically about support of ssh. Currently you must use `ssh dokku@host config:set app_name var1=true var2=\"hello world\"`

**Comment by kilianc** [comment]
@josegonzalez 

> Not everyone here wants to learn Dockerfile syntax, nor should we expect users to. Giving users an easy migration path from Heroku to Dokku also means we have both a larger pool of users/testers and that we have a more polished app due to everyone's feedback. I don't think we would be providing value by dropping features that currently work - and work quite well.

I didn't mean to drop support to heroku, I meant to remove buildsteps and just have dokku/app-type images and have a consistent docker based PaaS but this is just a thought from outsider.

> If you just want to be able to run dockerfiles via git push, Dokku is overkill.

Dokku does exactly what I need, sets my ENV, build and deploy the image, updates nginx. I am not aware of any other project providing this.

This said, this is can be closed since the issue seems resolved.
