### ISSUE TITLE
Dockerfile builds: config variables not available at build time

### ISSUE THREAD

**Issue by hnrch02** [progrium/dokku#1255]
When using a Dockerfile build all config variables set with `dokku config:set` are nether available at build time nor while the container is running. Is this intentional? If yes how would I work around that?

**Comment by michaelshobbs** [comment]
I don't think it was necessarily intentional. Dockerfile support is quite new however and definitely could use some more eyes on it. Feel like making a PR?

**Comment by hnrch02** [comment]
I would've already sent one if I had fixed it – I'm just getting started with Docker and dokku so I'm not yet as familiar with it as I would like to be. I played around with it a bit yesterday though and tried copying
the [build-env pre-build hook](https://github.com/progrium/dokku/blob/48eca101f119392809411e17c7c8838b4c6c071a/plugins/build-env/pre-build) to a plugin as the `pre-build-dockerfile` hook and it didn't work, I figured it's because [`docker build`](https://github.com/progrium/dokku/blob/48eca101f119392809411e17c7c8838b4c6c071a/plugins/00_dokku-standard/commands#L46) overwrites previous `docker commit`s to an image. If you could point me in the right direction I'd gladly submit a PR.

**Comment by michaelshobbs** [comment]
Oh actually I did this....this is supposed to work

https://github.com/progrium/dokku/blob/48eca101f119392809411e17c7c8838b4c6c071a/plugins/config/docker-args-deploy#L8-L13

**Comment by hnrch02** [comment]
Interesting. I tried using some of the config vars in a node script (via `process.env`) and it didn't work. After that I tried `RUN env` directly and it didn't print them either. Could it be possible that they are only available in the finished container but not while building the image?

**Comment by hnrch02** [comment]
I guess it makes sense that they're not available in the build because the aren't sourced anywhere and I'm using `FROM node:0.12`.

**Comment by michaelshobbs** [comment]
There's definitely no way they would be available during the build phase as there is no `docker-args-build` pluginhook in the config plugin. That can be added easily. However, I'm not clear why its not working for you.

**Comment by hnrch02** [comment]
I guess I should rephrase my original claim then, they aren't available at build time (that's where I need them), I actually haven't tested the running container. Sorry, should've checked that first.

**Comment by michaelshobbs** [comment]
Ah ok! Now I remember why. This was done to maintain functional parity with buildstep based apps. I'm definitely open to a discussion around including them in dockerfile builds. Anybody have thoughts on this?

**Comment by michaelshobbs** [comment]
Sidenote: I verified this do get included in the running container and when you use `dokku run app cmd`. (There's a test for this as well :smile:)

**Comment by kilianc** [comment]
@michaelshobbs docker made this not possible on purpose to have consistent images. The whole concept of passing an env variable to the build process is against the purpose of building the image itself, which needs to be consistent. Everything that needs customization needs to be run as `CMD` or have a buildimage docekrfile.

I stumbled with this myself months ago, where I was trying to pass NODE_ENV=dev/stag/prod to a statically built website at build time.

I ended up having 3 dockerfiles one per env. You can specify the dockerfile to use in dokku using the build phase container options if I am not wrong.

for ref: https://github.com/docker/docker/issues/6822

**Comment by hnrch02** [comment]
I see but how would I then go about implementing the "real" build the application needs? Like precompiling assets and uploading them to S3? I suppose I could write a plugin and use `docker run` and then `docker commit` after the image was built.

**Comment by kilianc** [comment]
That depends on what you need to do, you need to have a static website where the build is ENV dependent? I suggest you create multiple dockerfile with different `ENV` directive in it. Not really DRY but it's the best I got so far.

An extra docker run + commit is also viable...
Also you can have a builder image.

**Comment by hnrch02** [comment]
No, it's not really dependent on any ENV vars. It just need my AWS credentials (which are saved as config vars on the dokku app) when I run the S3 script. And also the `git rev-parse HEAD` for a different script. Anyway, I'll try the workaround I suggested above and see if that works for me now.

**Comment by hnrch02** [comment]
I wanted to follow-up on this: I solved my problem by using a plugin which commits a modified version of the image in a `post-build-dockerfile` - it's not optimal but it works. I guess what I'm saying is that it would be nice if dokku could make this easier. (modifying the image post build and commiting it)

**Comment by kilianc** [comment]
-1 on having dokku doing it. It's a Docker design issue that they are trying to fix. For the time being this is best in userland. You should publish a post build commit plugin to help others.

**Comment by mixxorz** [comment]
You could have the static assets be built during buildtime, but uploaded to S3 during execution time. You need to modify the CMD command in your Dockerfile. During execution time, environment variables are available. I feel like this is a cleaner option as docker would be able to build your image wherever you want.

**Comment by hnrch02** [comment]
@mixxorz Wouldn't that approach upload them every time the container is restarted? I agree that it would be the cleaner solution.

**Comment by mixxorz** [comment]
You're right, I didn't think of that. Maybe you could set an environment variable with `docker run -e` that your upload script looks at?

**Comment by michaelshobbs** [comment]
Closing this as the OP has a solution and there's been no movement on further discussion.
