### ISSUE TITLE
EXPOSE parser doesn't understand port protocol

### ISSUE THREAD

**Issue by kilianc** [progrium/dokku#1259]
something like `EXPOSE 8888/tcp` is not supported, if you are using some else's image that was not tailored for dokku this can easily happen.

**Comment by josegonzalez** [comment]
The "offending" line is [here](https://github.com/progrium/dokku/blob/master/plugins/00_dokku-standard/commands#L39) though I'm not quite sure how to modify it off the top of my head. @michaelshobbs thoughts?

**Comment by kilianc** [comment]
I think `| sed 's/\/.*//'` so

```bash
DOCKERFILE_PORT=$(grep EXPOSE Dockerfile | head -1 | awk '{ print $2 }' | | sed 's/\/.*//' || true)
```

lmk if I can PR on this

**Comment by josegonzalez** [comment]
Please do. Updated tests would be *lovely* :).

**Comment by michaelshobbs** [comment]
:+1:
