### ISSUE TITLE
docker 1.7 seems to break plugin compatibility

### ISSUE THREAD

**Issue by michaelshobbs** [progrium/dokku#1263]
some plugins rely on `docker ps` output that contains the tag name of the running image.
ex: https://github.com/Kloadut/dokku-pg-plugin/blob/35edfebd9bc4eafcdf9f3ecfc32cef3404853b9b/commands#L42

docker 1.7.0 seems to have dropped that from the default `docker ps` output

docker 1.7.0:
```
root@dokku:~/dokku# docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED              STATUS              PORTS               NAMES
7979e3cafe92        dokku/node-js-app   "/start web"        About a minute ago   Up About a minute                       boring_mccarthy
```

docker 1.6.2:
```
root@dokku:~/dokku# docker ps
CONTAINER ID        IMAGE                      COMMAND             CREATED             STATUS              PORTS               NAMES
fe73dbd209be        dokku/node-js-app:latest   "/start web"        13 seconds ago      Up 12 seconds                           gloomy_bardeen
```

**Comment by michaelshobbs** [comment]
@josegonzalez perhaps we pin to docker 1.6.2 for now?

**Comment by josegonzalez** [comment]
I think we should, give me a sec to figure that out.

**Comment by Crispy1975** [comment]
I will second pinning to 1.6.2. Currently a problem in Ubuntu 14.04 with apt is the lxc-docker package depends on lxc-docker-1.7.0, so when you install lxc-docker-1.6.2 dokku is removed as lxc-docker is removed... fun, fun.

**Comment by josegonzalez** [comment]
PR made, I can make a release in a bit.

**Comment by Crispy1975** [comment]
Awesome, ready to try when it's there.

**Comment by gcohen55** [comment]
I just wanted to include a link to https://github.com/docker/docker/issues/13191 for others who come across this issue and need a workaround in Ubuntu if they don't have Dokku installed the deb-way.

Quick summary, tho:
Downgrading to Docker 1.6.2 in Ubuntu 14.04 (maybe others). The command will remove the currently installed version and install the 1.6.2 version.
<pre>
apt-get install lxc-docker-1.6.2
</pre>


-g

**Comment by wingrunr21** [comment]
FYI, as @Crispy1975 pointed out, `lxc-docker` is locked on 1.7.0 on 14.04. Since `buildstep` depends on `lxc-docker`, there's no way to install `buildstep` and `lxc-docker-1.6.2` at the same time.

**Comment by josegonzalez** [comment]
@wingrunr21 the buildstep issue should be fixed. Just `apt-get update` before upgrading dokku and you're set.

**Comment by josegonzalez** [comment]
We've pinned our version to 1.6.2, and it seems like docker is not going to fix their output. Not sure what we should do here...

**Comment by Crispy1975** [comment]
As a note we used v0.3.20 and were able to get our new server up with minimal hassle. :) Shame about Docker 1.7 as we were hoping to use it due to their memory leak fixes.

**Comment by josegonzalez** [comment]
0.3.21 was released to fix incompatibilities with buildstep when installing via deb packages. If you install via source, feel free to experiment with newer versions of docker - and hopefully we can fix this issue for plugins somehow.
