### ISSUE TITLE
Unable to install Dokku

### ISSUE THREAD

**Issue by RR2DO2** [progrium/dokku#1268]
While trying to install Dokku on a fresh Ubuntu 14.04 machine (fully updated) I turned out to be unable to do so. Following the installation instructions executing the bootstrap shell script fails due to 'Unable to correct problems, you have held broken packages.'. Turns out this comes from the install line in bootstrap that runs  sudo apt-get install -y dokku=0.3.20. Running that separately it looks like an issue with 'buildstep':

"The following packages have unmet dependencies:  dokku : Depends: buildstep but it is not going to be installed"

There are no held back packages or anything else odd on this system, it's a fresh install.

Installing buildstep manually (sudo apt-get install buildstep) works, but this doesn't resolve the issue with installing dokku. I'm still trying to track down what might be the root-cause of the problem.

**Comment by RR2DO2** [comment]
Trying to install all dependencies manually, it appears that buildstep and lxc-docker-1.6.2 are mutually exclusive, but both are dependencies of the dokku package.

**Comment by josegonzalez** [comment]
Should be fixed by #1269. Forgot to peg buildstep. There is a new version of it out now, so `apt-get update` and `apt-get install dokku` should work now.

**Comment by RR2DO2** [comment]
Confirmed fixed, cheers!

**Comment by sungwoncho** [comment]
I am seeing this error.

Running the install script in the README gives me:

    E: Unable to correct problems, you have held broken packages.

`apt-get update & apt-get install dokku` gives me:

```
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dokku : Depends: lxc-docker-1.6.2 but it is not going to be installed
         Depends: herokuish but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

on Ubuntu 14.04.

**Comment by sungwoncho** [comment]
Fixed after running `apt-get install -f lxc-docker-1.6.2` and `apt-get update`.
