### ISSUE TITLE
Killed dokku deploy "$APP"

### ISSUE THREAD

**Issue by kilianc** [progrium/dokku#1270]
Can you guys help me out figuring out what's happening?

```
-----> Releasing appname...
-----> Deploying appname...
-----> Running pre-flight checks
       For more efficient zero downtime deployments, create a file CHECKS.
       See http://progrium.viewdocs.io/dokku/checks-examples.md for examples
       CHECKS file not found in container: Running simple container check...
-----> Waiting for 10 seconds ...
remote: App container failed to start!!
=====> workfolio container output:
       Starting up http-server, serving ./ on: http://0.0.0.0:8080
       Hit CTRL-C to stop the server
=====> end workfolio container output
remote: /usr/local/bin/dokku: line 49: 20781 Killed                  dokku deploy "$APP"
```

**Comment by kilianc** [comment]
And if I manually do `docker run --rm dokku/appname` it works

**Comment by josegonzalez** [comment]
Are you maybe running out of memory? Try setting up swap if you are running on a low-memory server.

**Comment by kilianc** [comment]
@josegonzalez it may be, but I have swap setup... also if I run the image manually it works... I tried using top to monitor CPU/memory and everything is below 30%. The app is a static server with no build process just a `COPY` and `CMD`

**Comment by kilianc** [comment]
I just created a new 4G swapfile just to be sure and still same problem

**Comment by kilianc** [comment]
Is there any way that I can see logs of what goes wrong? I tried `tail -f /var/log/{messages,kernel,dmesg,syslog}` but I don't see errors :/

**Comment by josegonzalez** [comment]
Can you gist your dockerfile?

**Comment by kilianc** [comment]
@josegonzalez multiple acutally, and after some test and a reboot I figured that after a fixed number of machine it stops being able to deploy apps, but I can run the container manually no problem. Seems resource related.

Here 2 example docker files:

```
FROM php:5.6-apache
RUN a2enmod rewrite
COPY ./ /var/www/html/
EXPOSE 80
```

```
FROM kilianciuffolo/static
WORKDIR /website
COPY ./ ./
EXPOSE 8080
```

I can run max 10 apps, the 11th wil fail to deploy, if I stop one the same app will work fine. Containers all use 0-10mb according to docker ps and and it makes sense since it's all test apps.

I have no problem add your key to my server for debugging in case is needed.

**Comment by josegonzalez** [comment]
Can you gist the output of a deploy with `dokku trace on` set? Also, how many containers are you running after the 10th deploy?

**Comment by kilianc** [comment]
10 is the number of lines of `docker ps` I am trying to save the trace but I can't figure it out, I am doing `git push dokku master 2>&1 > ../deploy.log` but file stays empty, suggestions? #noob

**Comment by josegonzalez** [comment]
`nohup COMMAND &` ? :P

**Comment by kilianc** [comment]
That did it https://gist.github.com/kilianc/c643a4c03fb78ad15b2b

**Comment by josegonzalez** [comment]
Looks like `docker inspect` failed to respond correctly for your containers. Are you running dokku 0.3.21?

**Comment by kilianc** [comment]
`v0.3.18-80-gc0f8764`

**Comment by josegonzalez** [comment]
Can you come onto irc? I'm `savant` there, might be faster to work it out via chat :)

**Comment by kilianc** [comment]
cc/ @michaelshobbs https://botbot.me/freenode/dokku/2015-07-03/?msg=43594263&page=2

**Comment by josegonzalez** [comment]
Looks like we need to remove that `-q` and pipe output to `/dev/null`, which will fix the issue and suppress output.

**Comment by kilianc** [comment]
shall I wait for @michaelshobbs blessing before PR on this?

**Comment by josegonzalez** [comment]
Make a pr :)

**Comment by chuckbutler** [comment]
Nice! This was plauging me for the last couple days - and I had not made the correlation that it was due to the number of containers running. I was pulling plugins in/out of my Dokku install to address this - I can confirm this patch resolves the issue for me w/ ~ 16 apps running in Dokku. I've published an additional 10 to verify scale-up works. 

:+1:

**Comment by kilianc** [comment]
I wonder how the number of apps relates to the fix O_o

**Comment by taeram** [comment]
+1.

I was having the same issue with `0.3.21`, and manually applying this change to `/var/lib/dokku/plugins/checks/check-deploy` fixed the issue for me.

**Comment by kilianc** [comment]
btw there a re a bunch of bullet proof ways to do this without involving grep:

```
docker top $CID
```

```
docker inspect -f {{.State.Running}} $CID
```

**Comment by josegonzalez** [comment]
@kilianc feel free to PR those instead :)

**Comment by michaelshobbs** [comment]
I'm not following what the source of the issue is. Something about >10 running containers and `docker ps` output?

**Comment by josegonzalez** [comment]
Yeah it seems weird to me as well. `grep` shouldn't fail in this way based on a flag.

**Comment by michaelshobbs** [comment]
I'm down with a better approach for sure. Do we have a PR coming or shall I put one together?

**Comment by kilianc** [comment]
> Yeah it seems weird to me as well. grep shouldn't fail in this way based on a flag.

I would feel better if we had this part figured out. `docker ps` doesn't seem to stop at 10 results so if it works for 0-10 it should work for the 11th container as well.

I amended the commit to use `docker top`
