### ISSUE TITLE
`dokku ls` shows invalid `Container Type` when using FQDN App Name

### ISSUE THREAD

**Issue by znz** [progrium/dokku#1271]
When `App Name` is `app.example.com`, `Container Type` is `example` instead of `web`.
Because `echo /home/dokku/app.example.com/CONTAINER.web.1 | awk -F. '{ print $2 }'` is `example`.

**Comment by znz** [comment]
I think that `sort` of https://github.com/progrium/dokku/blob/4d30fdfb0ef339d39f7037fcaede5735f2a3cb1d/dokku#L139-L141 have similar problems.

**Comment by michaelshobbs** [comment]
That sounds very likely. I'll have a look.
