### ISSUE TITLE
git dir deleted in build folder

### ISSUE THREAD

**Issue by hnrch02** [progrium/dokku#1284]
[Caused by this line](https://github.com/progrium/dokku/blob/ce9dabf384476ed05103a8e7f3f28ae4e44ba855/plugins/git/commands#L21). Is this necessary?

I'm trying to work around the [mtime build cache bug in Docker](https://github.com/docker/docker/pull/12031) until the fix ships with 1.8 (but that's still quite some time away, I reckon) by using the techniques described [in this article](http://www.clock.co.uk/blog/a-guide-on-how-to-cache-npm-install-with-docker). For that to work I need the git repo in the temporary build directory.

Also, (I don't know if I should file a separate issue for this) would it be acceptable to pass the temporary work directory as the second parameter to the `pre-build-dockerfile` hook [here](https://github.com/progrium/dokku/blob/ce9dabf384476ed05103a8e7f3f28ae4e44ba855/plugins/00_dokku-standard/commands#L43)? I'm currently modifying this file manually and my changes get overwritten every time I update dokku.

**Comment by josegonzalez** [comment]
It was added in 7f0591fa1e99b4b92e56edc01b0651e4f955986c. I think it's so we don't shove a `.git` directory into the docker image, no?

**Comment by josegonzalez** [comment]
That second thing should just be a PR.

**Comment by hnrch02** [comment]
> That second thing should just be a PR.

I'll submit one in a bit.

**Comment by hnrch02** [comment]
> It was added in 7f0591f. I think it's so we don't shove a .git directory into the docker image, no?

Makes sense. Maybe we could add an option to toggle this behavior and set it to delete by default?

**Comment by josegonzalez** [comment]
Moar options! I'm minus one on that, though if you want to submit a PR which did it on a per-app basis, that could work.

**Comment by josegonzalez** [comment]
@hnrch02 #1301 is a new plugin now.

**Comment by mixxorz** [comment]
Oh wow. I don't know how I missed this issue. Sorry ! >.<

Anyway, yes. The plugin I made works around the docker mtime issue. My Dockerfile based apps build super fast now! :grinning:

**Comment by hnrch02** [comment]
@josegonzalez Thanks! That seems to solve my troubles. I didn't realize I could just set the mtime to a fixed date instead of what `git show` spits out. Also, my second request is bogus since the cwd in the script is the temp work dir anyway. Sorry for the noise.
