### ISSUE TITLE
PATH

### ISSUE THREAD

**Issue by suppix** [progrium/dokku#1286]
App container failed to start!!
=====> app container output:
       /app/start_nginx: line 4: exec: nginx: cannot execute: Is a directory
=====> end app container output

After last changes it seems that PATH do not set valid.
https://github.com/florianheinemann/buildpack-nginx.git

**Comment by michaelshobbs** [comment]
We test with this static buildpack and it seems to work.

https://github.com/yabawock/buildpack-nginx

**Comment by michaelshobbs** [comment]
Closing for now. If that buildpack doesn't work, please feel free to reopen this issue.

**Comment by bloogrox** [comment]
Yes, it worked for me. Thank you!
