### ISSUE TITLE
Error pulling image (cedar14) from progrium/cedarish, Untar exit status 1 unexpected EOF

### ISSUE THREAD

**Issue by snadal** [progrium/dokku#1290]
I am installing dokku on a new VM with Ubuntu 14.04 server.

But after some time I get the following error message (Sorry, it's in Spanish):

```
Configurando buildstep (0.0.2) ...
Importing buildstep into docker (around 5 minutes)
time="2015-07-07T01:27:30+02:00" level=info msg="Error pulling image (cedar14) from progrium/cedarish, Untar exit status 1 unexpected EOF" 
dpkg: error al procesar el paquete buildstep (--configure):
 el subproceso instalado el script post-installation devolvió el código de salida de error 1
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

Any hint ?

**Comment by michaelshobbs** [comment]
Transient error? Network issue? Can you confirm that it persists?

**Comment by snadal** [comment]
It seems persistent. It happened for the last 8 hours, from different network locations. 

Will you need me to send some extra logs ?

**Comment by snadal** [comment]
It's weird, as doing the same steps on a new digital ocean droplet (14.04.2 LTS too) works fine.

I am trying to isolate the issue (may be related to the use of spanish locale?)

**Comment by michaelshobbs** [comment]
Weird. Any difference in networking setting between the two instances? IPv6 enabled perhaps?

**Comment by snadal** [comment]
Not at all. Just default 14.04.2 install. Only "Open SSH Server" selected on install wizard.

I tried downloading iso again and reinstalling from scratch with the same result. I think I'll use digital ocean workaround and will investigate later.

**Comment by michaelshobbs** [comment]
Feel free to re-open this when you investigate further.

**Comment by stephenbaidu** [comment]
Faced this problem whiles setting up on an EC2 but running `sudo DOKKU_TAG=v0.3.21 bash bootstrap.sh` again resolved the issue.

**Comment by snadal** [comment]
Just confirming that this was a transient issue. Two weeks later it works on every system I've tried.
