### ISSUE TITLE
Solved #116, I had to create a new issue.

### ISSUE THREAD

**Issue by juanpastas** [progrium/dokku#1293]
The problem I was having from #116 was solved:

1. I removed `/home/dokku/.ssh/authorized_keys` from the server
2. I run this in local computer `cat ~/.ssh/id_rsa.pub | ssh root@45.xxx.xxx.xxx "sudo sshcommand acl-add dokku added_from_ssh_command"`

Thanks.

Now I will work on how to add postgresql. @josegonzalez, do you have any pointer?

**Comment by josegonzalez** [comment]
You'll need to use a plugin to add postgresql. There are a few documented [here](http://progrium.viewdocs.io/dokku/plugins)
