### ISSUE TITLE
Can't access port-app

### ISSUE THREAD

**Issue by pearlymaccha** [progrium/dokku#1294]
Hello, I push a node.js project and it looks done successfully. But I don't know how to access the app via port-app, for example, I can access another app via port "http://172.16.41.46:32770/". Here's the result:

root@ubuntu1st:/home/apps/apptest/node-js-getting-started# git push dollynode master
Enter passphrase for key '/root/.ssh/id_rsa':
Counting objects: 406, done.
Compressing objects: 100% (320/320), done.
Writing objects: 100% (406/406), 217.66 KiB | 0 bytes/s, done.
Total 406 (delta 54), reused 406 (delta 54)
-----> Cleaning up...
-----> Building nodegtstrtd from buildstep...
-----> Adding BUILD_ENV to build environment...
-----> Node.js app detected

       Node engine:         0.12.2
       Npm engine:          unspecified
       Start mechanism:     Procfile
       node_modules source: package.json
       node_modules cached: false

       NPM_CONFIG_PRODUCTION=true
       NODE_MODULES_CACHE=true

-----> Installing binaries
       Downloading and installing node 0.12.2...

-----> Building dependencies
       Installing node modules
       ejs@2.3.2 node_modules/ejs

       express@4.9.8 node_modules/express
       +-- utils-merge@1.0.0
       +-- merge-descriptors@0.0.2
       +-- fresh@0.2.4
       +-- cookie@0.1.2
       +-- escape-html@1.0.1
       +-- range-parser@1.0.2
       +-- cookie-signature@1.0.5
       +-- finalhandler@0.2.0
       +-- vary@1.0.0
       +-- media-typer@0.3.0
       +-- methods@1.1.0
       +-- parseurl@1.3.0
       +-- serve-static@1.6.5
       +-- path-to-regexp@0.1.3
       +-- depd@0.4.5
       +-- qs@2.2.4
       +-- on-finished@2.1.1 (ee-first@1.1.0)
       +-- etag@1.4.0 (crc@3.0.0)
       +-- debug@2.0.0 (ms@0.6.2)
       +-- proxy-addr@1.0.8 (forwarded@0.1.0, ipaddr.js@1.0.1)
       +-- send@0.9.3 (destroy@1.0.3, ms@0.6.2, mime@1.2.11, on-finished@2.1.0)
       +-- accepts@1.1.4 (negotiator@0.4.9, mime-types@2.0.14)
       +-- type-is@1.5.7 (mime-types@2.0.14)

-----> Checking startup method
       Found Procfile

-----> Finalizing build
       Creating runtime environment
       Exporting binary paths
       Cleaning up build artifacts
       Caching node_modules for future builds

-----> Build successful!
       node-js-getting-started@0.1.4 /tmp/build
       +-- ejs@2.3.2
       +-- express@4.9.8

-----> Discovering process types
       Procfile declares types -> web
-----> Releasing nodegtstrtd...
-----> Deploying nodegtstrtd...
-----> DOKKU_SCALE not found in app image. Defaulting to a single web process
-----> New DOKKU_SCALE file generated
=====> web=1
-----> Running pre-flight checks
       For more efficient zero downtime deployments, create a file CHECKS.
       See http://progrium.viewdocs.io/dokku/checks-examples.md for examples
       CHECKS file not found in container: Running simple container check...
-----> Waiting for 10 seconds ...
-----> Default container check successful!
=====> nodegtstrtd container output:
       Node app is running on port 5000
=====> end nodegtstrtd container output
-----> Running post-deploy
=====> unsupported vhost config found. disabling vhost support
-----> Setting config vars
       NO_VHOST: 1
=====> Application deployed:
       http://172.16.41.11

To dokku@dokku.me:nodegtstrtd
 * [new branch]      master -> master

Can someone tell me what I should do to access my app? Thank you.

**Comment by michaelshobbs** [comment]
Can you gist a deployment with `DOKKU_TRACE` on?

**Comment by pearlymaccha** [comment]
@michaelshobbs hello Michael, here, I can only copy half of the process, I try to deploy another app:
https://gist.github.com/pearlymaccha/b45b090bd06908e89afb

**Comment by pearlymaccha** [comment]
I found "echo http://172.16.41.11:32773" with DOKKU_TRACE. But why I can't find my port app without DOKKU_TRACE on? @michaelshobbs

**Comment by michaelshobbs** [comment]
Verified. Working on a fix now.
