### ISSUE TITLE
Memory usage question

### ISSUE THREAD

**Issue by chrisjhoughton** [progrium/dokku#1297]
Hey guys, sorry if this is the wrong place to bring this up, but I thought I'd start here. I've been monitoring a 4GB RAM server using Datadog, which runs two Dokku apps. The `system.memory` used chart looks like this:

![screen shot 2015-07-09 at 17 45 16](https://cloud.githubusercontent.com/assets/2671525/8601183/789202ce-2662-11e5-8c8e-f2943b04d4db.png)

As you can see, the memory keeps climbing until it hits the server limit. Note that __nothing__ has crashed - everything is working just fine.

Is this a normal thing thing with Dokku/Docker? Or have I written some horrific code? 

Look forward to hearing thoughts.

**Comment by josegonzalez** [comment]
Do you know what process is using that much memory? Looks like its your own code - dokku is just a set of bash scripts, and docker is unlikely to trigger memory issues.

**Comment by chrisjhoughton** [comment]
Thanks for the reply, I've been doing a little more digging here. I just tried switching off __all__ of the dokku containers (`dokku ps:stop appname`) and saw a noticeable drop on memory usage: (The trough is the memory used when nothing is running)

![screen shot 2015-07-14 at 13 54 22](https://cloud.githubusercontent.com/assets/2671525/8673615/ef621670-2a2f-11e5-9f94-20d507a469b0.png)

However that's still over 4GB, when apparently nothing is running. 

I did a little more digging and ran `docker ps -q | xargs docker stats` to get the docker stats for all containers:

<img width="722" alt="screen shot 2015-07-14 at 14 00 39" src="https://cloud.githubusercontent.com/assets/2671525/8673738/c69ec94e-2a30-11e5-8bec-0725c8f024c7.png">

The memory these containers are using is decent, but combined, they're not more than ~1GB. 

This might just be a reporting thing related to how Docker manages memory?

**Comment by josegonzalez** [comment]
Is there nothing else running on your server? Might be worth checking `ps auxf`.

**Comment by hhff** [comment]
I'm not an expert at this stuff, by any means, but on my dokku servers I sporadically run:

`docker rm $(docker ps -a -q)`

to remove all stopped containers, and 

`docker rmi $(docker images | grep "^<none>" | awk "{print $3}")`

to remove all untagged images.

**Comment by josegonzalez** [comment]
Closing. I dont think this is at all related to docker/dokku, and as I have no idea what else is running on your server, it's hard for me to suggest anything.

**Comment by chrisjhoughton** [comment]
This was a reporting issue, sorry for bringing it here.
