### ISSUE TITLE
Documentation: Improvements about explanation about custom nginx-conf

### ISSUE THREAD

**Issue by fwolfst** [progrium/dokku#1303]
Hey there,

I struggle(d) a bit with nginx-configuration per app, and still have a confusing issue. I prematurely issued a PR, which I will improve upon and bump here.

Have fun
Felix

**Comment by josegonzalez** [comment]
Thanks for the docs change.

**Comment by fwolfst** [comment]
Hey,
I wasn't finished yet, its not correct as-is. Still have to spend some minutes understanding what happens. Could you re-open?
Thanks,
Felix

**Comment by josegonzalez** [comment]
You can open pull requests with your changes, no need to have this issue open to do that.

**Comment by fwolfst** [comment]
There is something in https://github.com/progrium/dokku/issues/1309 that I have not yet understood, will update the docs when I understood (or fixed) what is happening
