### ISSUE TITLE
Ruby  ! [remote rejected] master -> master (pre-receive hook declined)

### ISSUE THREAD

**Issue by pearlymaccha** [progrium/dokku#1304]
Hello, I was pushing a Ruby app to Dokku, but always failed. Here's the process:

https://gist.github.com/pearlymaccha/084b289c6a1cc6975b2b

Can someone help me please? I've been stuck for a week :(

**Comment by michaelshobbs** [comment]
You might try the latest ruby buildpack and disable ipv6, if enabled. Also try using https://gist.github.com/ to post shell output in the future.

Check out "Specifying a custom buildpack" here: http://progrium.viewdocs.io/dokku/application-deployment

**Comment by pearlymaccha** [comment]
How can I update the latest ruby buildpack? I've seen it on https://github.com/progrium/buildstep/issues/132, but I'm not sure how to update it.

**Comment by michaelshobbs** [comment]
Check out that section of the documentation. You add a `.env` file that specifies the appropriate environment variable.

**Comment by pearlymaccha** [comment]
I've added 'export BUILDPACK_URL=https://github.com/heroku/heroku-buildpack-ruby#v133' to .env and add an empty .static file and also updated the Ruby buildstep. Here's the process:
https://gist.github.com/pearlymaccha/47d22b04077e805d7d0e

How can i fix the problem below?

-----> Fetching custom buildpack
-----> Ruby app detected
-----> Compiling Ruby/Rails
       !
       !     An error occurred while installing Ruby ruby-2.1.6
       !     For supported Ruby versions see https://devcenter.heroku.com/articles/ruby-support#supported-runtimes
       !     Note: Only the most recent version of Ruby 2.1 is supported on Cedar-14
       !     Command: 'set -o pipefail; curl --fail --retry 3 --retry-delay 1 --connect-timeout 5 --max-time 30 https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/cedar-14/ruby-2.1.6.tgz -s -o - | tar zxf - ' failed unexpectedly:
       !
       !     gzip: stdin: invalid compressed data--format violated
       !     tar: Unexpected EOF in archive
       !     tar: Unexpected EOF in archive
       !     tar: Error is not recoverable: exiting now
       !

**Comment by pearlymaccha** [comment]
I got the solution to solve this problem. My app-name is 'blog-app'

Run the command:
#  curl --fail --retry 3 --retry-delay 1 --connect-timeout 5 https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/cedar-14/ruby-2.1.6.tgz -s -o - | tar zxvf -

*Note: run the command without '--max-time 30' and add 'v' at the last word, 'zxvf'

# dokku config:set blog-app CURL_TIMEOUT=600

# dokku config:set blog-app BUILDPACK_URL=https://github.com/heroku/heroku-buildpack-ruby.git#138
