### ISSUE TITLE
How to allow collaborate to push to server?

### ISSUE THREAD

**Issue by windweller** [progrium/dokku#1308]
Hi!
    I'm maintaining a DigitalOcean server for a university lab. Recently I graduated and need to hand the server to another student. I know how to add another ssh file to digitalOcean, but I'm wondering what's going to happen with Dokku server. Is there anyway for me to add a user so he can also have access to Dokku and do local git push to update the app?

I couldn't find tutorial elsewhere except a little bit from here https://github.com/dokku-alt/dokku-alt (which is not really the dokku I'm using)

**Comment by michaelshobbs** [comment]
Try this:

```
echo <string_of_users_public_key> | sshcommand acl-add dokku <user_name>
```

**Comment by windweller** [comment]
Hi! Thank you for responding to my question! What does this command do? public_key normally tends to be long, do I just copy and paste the whole thing in the middle?

**Comment by michaelshobbs** [comment]
[sshcommand](https://github.com/progrium/sshcommand) is a subcomponent of dokku. Feel free to read up on it. Yes just echo the public (not private) key into sshcommand.

Example:
```
echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7ScmhllvMKCnT0Ury5n6hgP9iNLV3KO38NP++15SyWbUqxM3qmJZiwwfJZuVLE5n5qCItRRpahfgbbRiaybszR47FMc9WiKyp8Pk8DuYrCOjj8RV73UKq5gwHYoedAPDIe8PK21W6KRvbQI+zbtt4mRFXGCyKTogZbttoAUDv4OE3jOG8haB0b55nXcdeqxOsjS6A0XFk3BUtRTJI/DwiBmxJk18uMVqZb98GxyxWX2JzRp6hU2cE3onQyvo+pHrf2mOcTVYr3z/htiKlRs2XMg3XkxuBYrGxgqksgeKeCJi7WWsWnYPajtOJOeZONT32rbhD0n3M3d6RArWlAXZR mhobbs@hostname" | sshcommand acl-add dokku mhobbs
```

**Comment by kilianc** [comment]
@windweller save the key to a file and `$ cat key.pub  | sshcommand acl-add dokku <user_name>`.

If this user has a github account with only one key then you can do: `$ culr https://github.com/kilianc.keys | sshcommand acl-add dokku kilian` for example

**Comment by windweller** [comment]
Thank you! I'll try that tomorrow :)
