### ISSUE TITLE
PHP extensions specified in composer.json not installing on build. 

### ISSUE THREAD

**Issue by tyler274** [progrium/dokku#1316]
Specifically the Mbstring extension. 

```
"require": {
  "ext-mbstring": "*"
}
```

**Comment by michaelshobbs** [comment]
Seems like an issue for the buildpack and not dokku, no?

**Comment by josegonzalez** [comment]
@tyler274 can you gist your deploy logs for us?

**Comment by tyler274** [comment]
Resolved as a buildpack issue / composer update not triggering on deploy.
