### ISSUE TITLE
Change Domain Name

### ISSUE THREAD

**Issue by windweller** [progrium/dokku#1317]
Hi! Quick question, how should I change the configuration of Dokku/Nginx if I'm changing the domain name of the website, and changing it from normal HTTP to HTTPS?

I deployed on DigitalOcean, and yes I know one way is to erase the server and restart everything, but I'm just trying to know if there is a way that this can be done faster.

**Comment by michaelshobbs** [comment]
So wait....are you trying to add SSL or are you changing the domain name of the site?

**Comment by windweller** [comment]
Change domain. The domain happens to be SSL, while the old one isn't

**Comment by michaelshobbs** [comment]
Use the domains plugin. Check out the docs for more info.

**Comment by michaelshobbs** [comment]
Also if you want nginx to handle SSL, that's in the docs as well. Give it a shot and feel free to comment back here with questions.
