### ISSUE TITLE
installing v0.3.21 - can't delete old buildstep image

### ISSUE THREAD

**Issue by javoire** [progrium/dokku#1320]
Because I have an old dokku setup on the machine, and old containers.
```
Removing old buildstep image
Error response from daemon: Conflict, cannot delete 9b9a84718daf because the running container 8b7f3bcf8473 is using it, stop it and use -f to force
FATA[0000] Error: failed to remove one or more images
```
would it be safe to force remove `-f` it in this situation? https://github.com/progrium/dokku/blob/7954f186df8f5b219c6cfa10b3ca62686e9d00a0/deb.mk#L78

**Comment by michaelshobbs** [comment]
Assuming you have no running apps dependent on this image, you can run `dokku cleanup` and then `docker rmi progrium/buildstep`. 

As I understand it, if you run `rmi -f` you may end up with "dangling" image layers that will be left consuming space on your disk.

**Comment by javoire** [comment]
I see, well in my case the installer reported a fatal error (that I don't know the consequences of). Not sure which is the preferred alternatuve though

**Comment by javoire** [comment]
might be low prio
