### ISSUE TITLE
automatic port mapping not working correctly?

### ISSUE THREAD

**Issue by javoire** [progrium/dokku#1322]
Following these instructions for Dockerfile deployments: http://progrium.viewdocs.io/dokku/application-deployment

I'm expecting dokku to assing a random port (eg 32576) and map it to the port specified in `EXPOSE` when running the container and in the nginx config. However that doesn't seem to be the case! Dokku version 0.3.21

Building the app:
```
-----> Setting config vars
       DOKKU_DOCKERFILE_PORT: 4444
```

docker ps (no external port mapped): 
```
CONTAINER ID        IMAGE                    COMMAND             CREATED             STATUS              PORTS               NAMES
35017d9c7fc1        dokku/myapp:latest   "node server.js"    34 minutes ago      Up 34 minutes       4444/tcp            prickly_darwin
```

`myapp/nginx.conf` wrong port mapped?
```
upstream sthlmclub {
  server 172.17.0.46:4444;
}
```

My Dockerfile
```
FROM node:0.10

WORKDIR /app

COPY ./ /app

RUN npm install --unsafe-perm .
RUN ./node_modules/bower/bin/bower install --allow-root --config.interactive=false
RUN ./node_modules/gulp/bin/gulp.js build

CMD ["node", "server.js"]

EXPOSE 4444
```

What am I doing wrong / missing here? Cheers!

**Comment by javoire** [comment]
I think I figured it out, closing for now

**Comment by josegonzalez** [comment]
@javoire what was your issue?

**Comment by choxi** [comment]
@javoire I'm having the same issue, what was your fix?

**Comment by josegonzalez** [comment]
@choxi You are unlikely to be having the same issue as we rewrote how ports are exposed in 0.5.x. Please read our docs on [exposed dockerfile ports](http://dokku.viewdocs.io/dokku/deployment/dockerfiles/#exposed-ports) and hop on slack/irc if you are still having issues.
