### ISSUE TITLE
Procfile deployment for Ruby script

### ISSUE THREAD

**Issue by kennetham** [progrium/dokku#1323]
@michaelshobbs a quick question here. I was wondering, I have a ruby script that is executed with `ruby server.rb`. My question is how do I and where to I configure this in Dokku's Procfile. I understand Procfile has a web and a worker role configuration. I am kind of confused which do I put this in.

There isn't a web interface, it just runs as backend service.

**Comment by michaelshobbs** [comment]
You can call it whatever you want actually. Calling web should be the easiest and deploy with out any additional steps. Give it a shot.

**Comment by kennetham** [comment]
So correct me if I am wrong, my Procfile should look something like this?

```config
web: ruby server.rb
```

and Ruby Buildpacks would automatically find that?

**Comment by michaelshobbs** [comment]
Ostensibly yes. Check out Heroku's docs on ruby deployment for more info though.

**Comment by kennetham** [comment]
Gotcha! Thanks. Another question I have in mind, so now that I have deployed my application, and if I update my application, does it automatically update or I would have to rebuild. Is there a zero downtime update process?

**Comment by michaelshobbs** [comment]
You would just push your updated repo to the dokku target to redeploy. We support a simple 'time up' type zero downtime check for non-web process containers. Basically we make sure the new container is up for x number of seconds before shutting down the old one. That time is configurable via an env variable. Check out the docs for more detail.

**Comment by kennetham** [comment]
Okay but I don't see that in the docs. I have looked through the docs unless I missed it?

**Comment by michaelshobbs** [comment]
Ah I see. The default check isn't mentioned. Sorry about that. 

The zero downtime stuff is located here: http://progrium.viewdocs.io/dokku/application-deployment

However (almost) everything I said previously is a lie since the default "wait" check is not configurable as of today. 

https://github.com/progrium/dokku/blob/master/plugins/checks/check-deploy#L94

**Comment by kennetham** [comment]
@michaelshobbs I see. Thanks for clarifying. I got some errors with my Ruby script while deploying, I am rectifying if it's Redis issue when Redis isn't setup on Dokku yet.

**Comment by kennetham** [comment]
@michaelshobbs if an application stops unexpectedly, does Dokku automatically revives it or some required settings are needed. Also, if I were to scale an application, how do I know if that application is scaled?

**Comment by michaelshobbs** [comment]
No you are responsible for the uptime of your app. I generally use the supervisor plugin for this. 

The `dokku ls` command shows running containers, their type and to which app they belong.

**Comment by kennetham** [comment]
@michaelshobbs roger that.
