### ISSUE TITLE
Recommended Minimum System?

### ISSUE THREAD

**Issue by ariporad** [progrium/dokku#1326]
Hi,

I was wondering if there was a recommended minimum system for dokku to run on (ie. Will it run on an EC2 micro instance)?

Thanks!

**Comment by michaelshobbs** [comment]
Dokku is just bash glue to manipulate docker and nginx at its core. There are no real system requirements for dokku. The real question is what are the minimum requirements for the app(s) you want to deploy with dokku.

**Comment by michaelshobbs** [comment]
Closing. Let us know if you have further questions.

**Comment by TheNotary** [comment]
For future Googlers, linking to the [system requirements](https://dokku.com/docs/getting-started/installation/#system-requirements) mentioning an ideal 1GB of ram for smooth deployments.
