### ISSUE TITLE
Auto restarting crashed containers

### ISSUE THREAD

**Issue by olalonde** [progrium/dokku#1327]
Is there any way to tell dokku to automatically attempt to restart crashed apps or apps that are not responding to the `CHECK`? I'm deploying a Node.js server without a Dockerfile.

**Comment by michaelshobbs** [comment]
I've been using supervisor to babysit my nose apps. There are a couple dokku plugins that enable this behavior. Check out the links in the docs for more info.

**Comment by olalonde** [comment]
Ok thanks. It would probably a good feature to have natively though, hope it is considered for a future release. Cheers.
