### ISSUE TITLE
RFC - Implement a dokku enter command

### ISSUE THREAD

**Issue by claudyus** [progrium/dokku#1332]
I don't know if it was previously discussed but what about and `dokku enter <name> [bash]` command that allow the admin to easly enter a running container using `bash`.

I often have the need to enter a deployed container just to debug some daemon port bind and running docker commands is pretty slow.

This command should be an alias of something like
```
sudo docker ps
sudo docker exec -it <id> bash
```

**Comment by michaelshobbs** [comment]
Sure :smile:

**Comment by michaelshobbs** [comment]
In the case of an app that has been scaled or has multiple proc types (i.e. multiple containers) how do know which container to enter by default? Suggestions on syntax for allowing the use to specify this?

**Comment by michaelshobbs** [comment]
@claudyus ping for feedback

**Comment by claudyus** [comment]
Hi @michaelshobbs,

I believe that in a scaled scenario we could report the user the multiple container id, than the user could use the id to enter the proc type.
In this case the command could be:
```
dokku enter <name|container-id>  [command]
```

In this case can we simple determinate if the enter arg is a project name or container-id?

**Comment by josegonzalez** [comment]
@claudyus that sounds good to me. Check by name first and then check container id seems like a good route.

**Comment by josegonzalez** [comment]
Or perhaps something like:

```shell
dokku enter APP # random instance
dokku enter --container-id CONTAINER_ID # specific container
```

**Comment by josegonzalez** [comment]
Closing as there is an open pr for this feature.
