### ISSUE TITLE
Usage Question

### ISSUE THREAD

**Issue by zimt28** [progrium/dokku#1336]
Hey there! I'm quite new to Docker and was looking for a way to easily deploy my apps - seems like dokku is a good fit :) I now want to deploy a really basic app, but can't get it running ..

Here's the `Dockerfile`:
```Dockerfile
FROM ubuntu:14.04

RUN apt-get update
RUN apt-get install -y nginx
RUN echo 'Hello from your container' \
  >/usr/share/nginx/html/index.html

CMD ["nginx",  "-g", "daemon off;"]

EXPOSE 80
```

I can build the image `docker build -t="zimt28/static_web" .` and run a container `docker run -d -p 80 zimt28/static_web`. Locally, everything works fine; I can now access the container using the port from `docker ps`.

I've now created a git repo, added the Dockerfile and the dokku remote and pushed the app. My app gets listed using `dokku apps` on the server and I can get a url using `dokku url appname`.  However, when I open that url, I can't connect to the server. I've then added the `-d` and `-p 80` options using `dokku docker-options:add appname run` and restarted the server using `dokku ps:restart appname`. However, I still can't access the page.

Can you tell me, what I'm doing wrong here?
Thank you :)

**Comment by josegonzalez** [comment]
What is the output of `docker ps`?

**Comment by zimt28** [comment]
```
root@minon1:~# docker ps
CONTAINER ID        IMAGE               COMMAND                CREATED             STATUS              PORTS                             NAMES
284a3d44cdd6        dokku/master        "nginx -g 'daemon of   12 minutes ago      Up 12 minutes       0.0.0.0:32775->80/tcp             boring_almeida
9a87301abcaa        dokku/master        "nginx -g 'daemon of   18 minutes ago      Up 18 minutes       80/tcp, 0.0.0.0:32774->5000/tcp   sharp_tesla
```

**Comment by zimt28** [comment]
Ok, so now when I open the app on port `32775`, everything works fins. Looks like `dokku url` is just giving me the port of the second container

**Comment by michaelshobbs** [comment]
what is the output of `dokku url` and `docker ps` from the same deployment?

**Comment by zimt28** [comment]
Outputs are `http://{serverIP}:32774` and 
```
CONTAINER ID        IMAGE               COMMAND                CREATED             STATUS              PORTS                             NAMES
284a3d44cdd6        dokku/master        "nginx -g 'daemon of   15 hours ago        Up 15 hours         0.0.0.0:32775->80/tcp             boring_almeida
9a87301abcaa        dokku/master        "nginx -g 'daemon of   15 hours ago        Up 15 hours         80/tcp, 0.0.0.0:32774->5000/tcp   sharp_tesla
```

**Comment by zimt28** [comment]
I just stopped and removed the second container, but still get the same result from `dokku url`

**Comment by zimt28** [comment]
I've now tried to deploy again and it looks like it's a port problem. In my `Dockerfile` I have `EXPOSE 80`, but when I push to dokku, I get something like:
```
PORTS 
80/tcp, 0.0.0.0:32782->5000/tcp
```
When I do 
```
dokku docker-options:add static deploy "-d"
dokku docker-options:add static deploy "-p 80"
```
and `dokku ps:restartall`, I get a new container with these ports:
```
PORTS
0.0.0.0:32784->80/tcp, 0.0.0.0:32783->5000/tcp
```
When I now access the server on port `32784` it works fine, but `dokku url` still gives me port `32783`.

What I can't see from the docs is, if I need to set `-d` using `dokku docker-options:add static deploy "-d"`. The docs say:
> By default, we will extract the first EXPOSE port and tell nginx to proxy your app to that port.
I skipped `Use virtualhost naming for apps` so I just want to access the app on the port. The docs just talk about `nginx`, do I have to set `-p 80` for the `run` or `deploy` stage (not sure which one) or will dokku take care of the port? At the moment, dokku always seems to use port 5000, which is wrong.

**Comment by michaelshobbs** [comment]
Dokku doesn't support running an app on port 80 without some modification. Specifically shutting down nginx. Though I'm sure other things are necessary. 

Feel free to play around with it and report back how to make it work if you'd like.

**Comment by josegonzalez** [comment]
@michaelshobbs we should probably document that.

**Comment by michaelshobbs** [comment]
@zimt28 another question I have is how did you wind up with two containers running? Did you use the `ps:scale` command?

**Comment by michaelshobbs** [comment]
@zimt28 you can accomplish what you want by following these steps

```
# stop nginx
/etc/init.d/nginx stop
# remove incorrect docker option
dokku docker-options:remove static deploy "-p 80"
dokku docker-options:add static deploy "-p 80:80"
dokku ps:restart static
```

step 3: profit!! :smile:

**Comment by michaelshobbs** [comment]
@josegonzalez in light of this information, what specifically do you think needs to be documented? the root take-away here is that if you want static port binding, you must use the nginx-vhosts plugin.

**Comment by zimt28** [comment]
@michaelshobbs I've never used the `dokku ps:scale` command. One container was stated by dokku, and I started `boring_almeida` manually. However, I've had situations before where dokku ran three containers of my app in parallel after restarting it or pushing again.

I'm not sure if I misunderstood you, but what I want to achieve is not running my app on the host on port 80, I'm fine with any port. The nginx server in my example runs on port 80, so I need dokku to "redirect" to that port. Just like locally, I `EXPOSE 80` and then run using `-p 80`. `docker ps` will then show me, which port docker has given the container: `0.0.0.0:32768->80/tcp`. Containers started using dokku instead try to redirect to port 3000: `0.0.0.0:32774->5000/tcp`.

**Comment by michaelshobbs** [comment]
@zimt28 an example can be found in the test suite [here](https://github.com/progrium/dokku/blob/master/tests/apps/dockerfile/Dockerfile)

However, it seems you did find a bug here! Thank you for that. As I've mentioned previously (in other issues at least) dockerfile support is very "green" and we can definitely use some more real life use cases. Thanks again!

Patch coming.

**Comment by michaelshobbs** [comment]
@zimt28 give master a shot with a fresh app (i.e. no extra docker-options) and let us know if it works

**Comment by zimt28** [comment]
Here we go, works great :) I'll let you know if I run into any other issues using docker with dokku.
Thanks for your work!
