### ISSUE TITLE
Push Dokku App via Git Bash?

### ISSUE THREAD

**Issue by pearlymaccha** [progrium/dokku#1339]
Hello, I'm wondering if I can push a Dokku app via Git Bash or other application? For example, a Windows developer wants to push a repository/app to Dokku via Git Bash. Is it possible or not? I've tried it and it failed. The result is:

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
$ git remote add user1 dokku@dokku.me:java-gs-ap
$ git push user1 master
FATAL ERROR: Network error: Connection refused
fatal: Could not read from remote repository.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Is there another step I missed or is it impossible? Should I set SSH?

**Comment by michaelshobbs** [comment]
Caveat: I don't really understand the question. 

However, the example given should work assuming ssh is running on the 'dokku.me' host and dokku is installed there, of course.

**Comment by josegonzalez** [comment]
Is `dokku.me` setup in your `/etc/hosts`?

**Comment by pearlymaccha** [comment]
I have a condition like this:
1. A developer is working on Windows 7
2. A virtual server (node), I'm using Ubuntu 14.04 for Dokku. dokku.me is set in /etc/hosts with private IP address
3. The environment is still on private network

Problem:
Developer wants to push his app/repository to Dokku, still working on private network. So developer tries Git Bash to send commands to Dokku, with
$ git remote add user1 dokku@dokku.me:java-gs-ap
$ git push user1 master
But developer wasn't able to push the app to Dokku. For details, developer is working on working repository (Windows 7) and he wants to push the app to local repository (a node that contains Dokku).

Question:
1. Is it possible to send command like "git push" via Git Bash to another IP address on the same network (private netwok)?
2. Is there another application that support git commands to help developer push an app to Dokku node?
3. Should I use a public IP Address and make DNS on Dokku, so I can push an app to Dokku node via Git Bash?
3. Can someone help me or do you need any explanation? Thank you very much :)

**Comment by michaelshobbs** [comment]
So I've never used Git Bash before but if you can `ssh dokku@dokku.me` and see the dokku help message, you should be able to `git push` to it. 

Answers:
1. I don't really understand what you're asking. However, it sounds like you want to push to a different server. You can run `git remote add <alias> dokku@<server>:<app>` and number of times with a different alias/server/app combo....
2. Probably?
3. This is not necessary

**Comment by pearlymaccha** [comment]
I think I have to build a Git server before pushing a repo to my Dokku server. Closing this issue :)
