### ISSUE TITLE
How Can I Buy @josegonzalez and @michaelshobbs A Beer?

### ISSUE THREAD

**Issue by hhff** [progrium/dokku#1340]
You guys are doing amazing work.  I just wanted to say thankyou!  Can you guys setup a Gratipay / Paypal etc so I can send you both (and @progrium) a beer?

Really really appreciate the hard work.

**Comment by michaelshobbs** [comment]
Best GH issue I've seen yet :stuck_out_tongue_winking_eye:

**Comment by progrium** [comment]
+1

On Friday, July 24, 2015, Michael Hobbs <notifications@github.com> wrote:

> Best GH issue I've seen yet [image: :stuck_out_tongue_winking_eye:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/progrium/dokku/issues/1340#issuecomment-124514366>.
>


-- 
Jeff Lindsay
http://progrium.com

**Comment by JMSwag** [comment]
+1

**Comment by michaelshobbs** [comment]
Being a long time "bash guy," I really enjoy contributing to this project and since I use it in many different environments in my day job, I feel very fortunate to be able to do so. It's really cool to hear that folks are getting value out of our collective work.

**Comment by turicas** [comment]
+1

**Comment by joshco** [comment]
I like dokku too.  But why is this issue still open and not fixed?  The solution seems fairly straightforward.
Who is responsible for the delay here?

**Comment by progrium** [comment]
Probably me.

**Comment by josegonzalez** [comment]
I'm at a bar, so send your money to O'Hanlons at 14th and 1st.

**Comment by michaelshobbs** [comment]
Ha! Awesome

**Comment by hhff** [comment]
:heart:

**Comment by jakearchibald** [comment]
Yep, huge thanks for this project

**Comment by josegonzalez** [comment]
Gratipay accounts (in alphabetical order)!

- [josegonzalez](https://gratipay.com/~josegonzalez/)
- [michaelshobbs](https://gratipay.com/~michaelshobbs/)
- [progrium](https://gratipay.com/~progrium/)

They don't yet have teams on gratipay, so for now the "fix" is to add individual buttons to the readme, and wait for teams to re-appear.

**Comment by jnettome** [comment]
+1

**Comment by josegonzalez** [comment]
Closing. If you want to give back, I added the gratipay accounts above. Feel free to make a pr adding buttons to the readme if this really bugs you :)

**Comment by hhff** [comment]
i can't seem to figure out how to give directly - I think we might need a dokku team?  https://gratipay.com/introtopython/

**Comment by josegonzalez** [comment]
Interesting. I've applied for a team [here](https://github.com/gratipay/team-review/issues/63) then.

**Comment by josegonzalez** [comment]
Note: we've since created an account at [OpenCollective](https://opencollective.com/dokku)., so if you are *actually* interested in giving a monetary contribution to Dokku, I highly recommend doing so [there](https://opencollective.com/dokku).
