### ISSUE TITLE
Unable to setup SSL

### ISSUE THREAD

**Issue by Arm1stice** [progrium/dokku#1342]
I was trying to setup SSL for my Dokku server today, however no matter what I tried, I could not get Dokku to recognize my application as an SSL one and generate the correct nginx.conf (Dokku kept generating a regular HTTP only one)

My System
- Ubuntu 14.04 x64
- Latest Dokku installed using readme script

Things I have tried
- Generating key and certificate, tarring and using nginx:importssl (There is no output, and upon redeploy the Dokku again generates a standard HTTP config)

- Putting server.crt and server.key into /home/dokku/<app>/tls and redeploying (same thing happens, an HTTP config is created)

- Generating a wildcard certificate, putting server.crt and server.key into /home/dokku/tls, uncommenting the lines referring to in the documentation, reloading nginx config, and redeploying (to no avail, another HTTP config is created)

The domain in the certificate matches the app domain, so that isn't the problem either.

Is there anything I am missing? I have looked everywhere online but everything tutorial I find suggests one of the three things listed above, all of which didn't work for me.

**Comment by Arm1stice** [comment]
Pinging @josegonzalez

**Comment by josegonzalez** [comment]
I get notifications for issues, no need to ping me. I'll take a look when I get a chance ;)

**Comment by michaelshobbs** [comment]
So same thing as from #1343...

Please post a [gist](https://gist.github.com/)  of the following items.
- full deploy log with `dokku trace on`
- your app's nginx config `/home/dokku/$APP/nginx.conf`
- the output of `docker ps -a`
- the output of `docker inspect <running_app_container>` (the running `/start web`, if is exists)
- the output of `find /home/dokku/tls /home/dokku/*/tls -ls`

**Comment by Arm1stice** [comment]
It seems the problem was that I was putting a wildcard domain cert into `/home/dokku/$APP/tls/` and dokku wasn't registering as being usable. I created another certificate, this time with just the single base domain (not a wildcard) and dokku correctly identified it and setup SSL for my app. Sorry for the mixup guys :disappointed:

**Comment by michaelshobbs** [comment]
Glad you got it working.
