### ISSUE TITLE
502 Connection Refused After Configuring SSL for a Ruby on Rails Site on Digital Ocean

### ISSUE THREAD

**Issue by jasonleibowitz** [progrium/dokku#1343]
I am trying to enable SSL on a Rails website hosted on Digital Ocean through Dokku and when I follow the steps in the [docs](http://progrium.viewdocs.io/dokku/nginx/) I get a 502 connection refused error. 

I purchased an organization level SSL certificate from Comodo and followed [online instructions](https://gist.github.com/bradmontgomery/6487319) to combine them into an ssl bundle file:

```
cat www_example_com.crt COMODORSADomainValidationSecureServerCA.crt  COMODORSAAddTrustCA.crt AddTrustExternalCARoot.crt > ssl-bundle.crt
```

I then renamed that file to server.crt and uploaded it along with the server.key file I had previously created to ```/home/dokku/tls```. I then opened the ```/etc/nginx/conf.d/dokku.conf``` file and uncommented out the following lines:

```
ssl_certificate /home/dokku/tls/server.crt;
ssl_certificate_key /home/dokku/tls/server.key;
```

Lastly, in my rails application I uncommented out the line ```config.force_ssl = true``` in production.rb. 

After doing all of this, in the console of dokku I released then re-deployed my application using ```dokku release myapp``` and ```dokku deploy myapp```. Upon visiting the URL, however, I receive a 502 connection refused error. I have confirmed that the common name for the certificate I received from Comodo is the same as the domain and that the VHOST matches both of those.

To see if I should have done a *per app* rather than *all subdomains* SSL configuration I followed the [instructions for that](http://progrium.viewdocs.io/dokku/nginx/). I removed the work done above by deleted the folder ```/home/dokku/tls``` and recommenting out the lines in ```/etc/nginx/conf.d/dokku.conf```. I then tar'ed the server.key and server.crt files together using ```tar cvf cert-key.tar server.crt server.key```. Finally, I installed this file for my app by using ```ssh dokku@ip-of-your-dokku-server nginx:import-ssl < cert-key.tar```. This still didn't work and I again got a 502 connection refused error. 

I set up this dokku instance via Digital Ocean's one-click application setup. 

Am I missing a step? Am I doing something wrong? Thank you for your help.

**Comment by Arm1stice** [comment]
I am having the same issue as well in #1342, still looking for a fix

**Comment by Arm1stice** [comment]
Could this problem have been introduced in 0.3.22?

**Comment by michaelshobbs** [comment]
Not sure where to start here. The answer to your last comment is yes of course. This is open-source software bugs happen. However, the test suite covers SSL fairly well. 

We're going to need some more info to get anywhere. So, please leverage (gists)[https://gist.github.com/] and post the following items.

- full deploy log with `dokku trace on`
- your app's nginx config `/home/dokku/$APP/nginx.conf`
- the output of `docker ps -a`
- the output of `docker inspect <running_app_container>` (the running `/start web`, if is exists)
- the output of `find /home/dokku/tls /home/dokku/*/tls`

Since you tried a few things, I'd like to get a better understanding of where the config is sitting right now.

**Comment by jasonleibowitz** [comment]
@michaelshobbs Thanks for getting back to me. Here is everything you requested:

* [full deploy log](https://gist.github.com/jasonleibowitz/cf2c456b088b1cdc5129)
  * I ssh'ed into the server and typed ```dokku trace on``` then did a deploy. Not sure if I did this one right...
* [app's nginx config](https://gist.github.com/jasonleibowitz/e0fd3b7a87c7c8b2c5f7)
* [output of docker ps -a](https://gist.github.com/jasonleibowitz/450baee13b140a1d0081)
* [output of docker inspect aeb74c754711](https://gist.github.com/jasonleibowitz/25b5d5b18c21f64827a3)
* [output of find /home/dokku/tls /home/dokku/*/tls -ls](https://gist.github.com/jasonleibowitz/d4639e884f4d5f837ab9)

**Comment by michaelshobbs** [comment]
Yeah `dokku trace on` is the correct command. However, the output is not from a deploy where that is enabled. I also noticed your output is not consistent with the current state of dokku. What version are you running? (`dokku version`)

**Comment by jasonleibowitz** [comment]
I'm on v0.2.3. That could be a problem. I have dokku from a Digital Ocean [one-click setup](https://www.digitalocean.com/community/tutorials/how-to-use-the-dokku-one-click-digitalocean-image-to-run-a-ruby-on-rails-app). I did some googling, but I'm not sure how to upgrade my Dokku version after having set it up that way. I read the [dokku docs](http://progrium.viewdocs.io/dokku/upgrading/) and went ahead and updated my version of dokku using the instructions for downloading from source. 

So I've updated my version of docker and now I'm on ```v0.3.22-35-g8df24ff```. I then followed the dokku docs for adding SSL for one app - I ran ```ssh dokku@ip-of-your-dokku-server nginx:import-ssl < cert-key.tar``` and added the ```server.key```, ```server.crt```, and ```cert-key.tar``` files to ```/home/dokku/wolflax/tls```

Here is updated info you may need:

* [deploy log](https://gist.github.com/jasonleibowitz/ff23136d4ea4160a3d44)
* [Updated nginx.conf](https://gist.github.com/jasonleibowitz/345196040f479d05f1bf)
* [Updated docker ps -a](https://gist.github.com/jasonleibowitz/3a5c896266e6252ed1d3)
* [Updated docker inspect c12e32b0ff66](https://gist.github.com/jasonleibowitz/d06d6042210c8ecc150a)
* [Updated find tls folders](https://gist.github.com/jasonleibowitz/b77b1052a75bb7fafebd)

The current issue I'm having ever since updating the dokku version is that when I visit my URL I'm redirected to HTTPS and I get an ERR_CONNECTION_REFUSED error. I think it's a 502 error - here are the last few lines on the [nginx access.log](https://gist.github.com/jasonleibowitz/1792cba00ded341c4ea3). Also, after running docker logs and the container id I get [this](https://gist.github.com/jasonleibowitz/343ab49c3599c32d4c22).

Thanks again for the help.

**Comment by michaelshobbs** [comment]
That makes sense. That's why dokku trace didn't work. 

In your original post you mentioned uncommenting the lines in `/etc/nginx/conf.d/dokku.conf`. Make sure those are commented out. Stop nginx. Kill nginx just in case. Start it up again. Just want to make sure nginx is in a good state. 

The root of the problem is still that we don't have SSL config generated for the app. So we really need dokku trace enabled to figure out what's happening here.

You can manually enable it by running this:
```
echo "export DOKKU_TRACE=1" > /home/dokku/.dokkurc/
```

Additionally let's see what your CNs are in that crt.
```
openssl x509 -in /path/to/server.crt -noout -subject 
```

**Comment by jasonleibowitz** [comment]
I don't think manually enabling dokku trace worked because this was the output:

```
root@wolflax:~# echo "export DOKKU_TRACE=1" > /home/dokku/.dokkurc/
-bash: /home/dokku/.dokkurc/: Is a directory
```

However, I ran ```dokku trace on``` now that I've updated my version of dokku and that worked. Here is the [full deploy log](https://gist.github.com/jasonleibowitz/ac0b2fa520ba7bcf681d) with dokku trace now on. 

And here is the output from the openssl command: 

```
root@wolflax:~# openssl x509 -in /home/dokku/wolflax/tls/server.crt -noout -subject
subject= /C=US/postalCode=80112/ST=CO/L=Englewood/street=10200 E Dry Creek Road/O=GS24 Camps LLC/OU=InstantSSL/CN=wolflax.com
```

The common name is ```wolflax.com``` which is my domain name. Also, just to give you more info, this is what's in my VHOST file inside ```/home/dokku/wolflax```

```
wolflax.wolflax.com
wolflax.com
```

**Comment by michaelshobbs** [comment]
Crap! Typo on my part. Sorry
```
echo "export DOKKU_TRACE=1" > /home/dokku/.dokkurc/DOKKU_TRACE
```

**Comment by jasonleibowitz** [comment]
Cool. I entered your updated dokku trace command and there was no output message. I did another deploy after having entered that command. Here is the [second full deploy log](https://gist.github.com/jasonleibowitz/f67677ca51e0080c88bd).

**Comment by michaelshobbs** [comment]
Looks like you have an issue with the location of the cert?

```
remote: nginx: [emerg] SSL_CTX_use_PrivateKey_file("/home/dokku/wolflax/tls/server.key") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
remote: nginx: configuration file /etc/nginx/nginx.conf test failed
```

**Comment by michaelshobbs** [comment]
Nope it seems its an issue with crt bundle? http://nginx.org/en/docs/http/configuring_https_servers.html

> If the server certificate and the bundle have been concatenated in the wrong order, nginx will fail to start and will display the error message:
> ```
SSL_CTX_use_PrivateKey_file(" ... /www.example.com.key") failed
   (SSL: error:0B080074:x509 certificate routines:
    X509_check_private_key:key values mismatch)
```

**Comment by jasonleibowitz** [comment]
You're right, the issue is with the existing certs. It seems either that I'm using the wrong private key -- the certificates don't match, or that I concatenated them in the wrong order. Just to see if I could get SSL up and running with the guidance you've already given, I've created new self-signed certificates that I've validated do match. I deleted the old certs from the ```/home/dokku/wolflax/tls``` folder and put the new self-signed certificates in there. 

I also tar'ed the two certs together and ran ```ssh dokku@woflax.com:wolflax nginx:import-ssl < cert-key.tar```, but got a timeout error on port 22. 

Regardless, I've confirmed that the site is now working on HTTPS with these self-signed certs. To fix this now I'll have to figure out why my old certs weren't matching. Thank you so much for your help! 

Out of curiosity what command did you run to get those last two error message? 

Thanks again for all your help.

**Comment by michaelshobbs** [comment]
That output is from lines 2935-2936 in your gist: https://gist.github.com/jasonleibowitz/f67677ca51e0080c88bd

**Comment by jasonleibowitz** [comment]
Hah, thanks again. You can mark this close now. The fix was that my certs weren't working and I was on an old version of Dokku.

**Comment by michaelshobbs** [comment]
Cool. Let us know if you run into any other issues.

**Comment by stanislasdrg** [comment]
Hello, I am encountering the same problem with dokku 0.6.5, and can't figure out why SSL is not working at the moment. I generated a self signed certificate and had a look at the different issues people had. Unlike Jason, my certs seem ok. 

Here are the different outputted logs :

- [Deploy](https://gist.github.com/stanislasdrg/0119c1c5b84bea1e769ce24391f4007b)
- [Nginx config](https://gist.github.com/stanislasdrg/387cff477e5f9af768c6fb5b21415edd)
- [docker ps -a](https://gist.github.com/stanislasdrg/ae525a0057e8ac19e87b51635f66fa23)
- [docker inspect <container>](https://gist.github.com/stanislasdrg/ae8ea3906636f4aab6535ee1b7205b3b) 
- [find /home/dokku/tls /home/dokku/*/tls -ls](https://gist.github.com/stanislasdrg/35e672ad8d24e40e9cb468ff7a69e574)
- [openssl x509 -in /path/to/server.crt -noout -subject ](https://gist.github.com/stanislasdrg/c2d2f356bab815df7fc49e53ac33bb46)

`openssl x509 -in tls/server.crt -noout -text | grep --after-context=1 '509v3 Subject Alternative Name:'
` 
Returns nothing.

Any hints on what might be wrong ?

Thank you for your help.
