### ISSUE TITLE
Define worker command when using Dockerfile

### ISSUE THREAD

**Issue by bennibu** [progrium/dokku#1350]
As I understand from the [documentation](http://progrium.viewdocs.io/dokku/process-management/) the commands for the server process and the worker process shoud be defined in the `Procfile`.

But how do I define the worker command when I am using a `Dockerfile` instead of the buildpacks? The config `DOKKU_DOCKERFILE_START_CMD` is applied to all process types. web as worker.

**Comment by michaelshobbs** [comment]
If you want multiple commands running in a Dockerfile deployment, I think you'll need to handle that within the Dockerfile. e.g. a process manager or some other self managed method

**Comment by josegonzalez** [comment]
Would be nice to be able to reuse a dockerfile-based deploy for multiple apps. Perhaps we can inject a `PROCESS_TYPE_NUMBER` to each build, and make it be something like `web.1` or `docker.1`?

**Comment by michaelshobbs** [comment]
I agree in principle with your first statement. However, I do not understand what you're getting at with the `PROCESS_TYPE_NUMBER` thing. How do we know what the user wants to do here?

**Comment by josegonzalez** [comment]
Their process manager can then decide what to do based on which number they are. So if they want 10 instances of their container, their process manager can say "docker.1 - docker.5 are web and the rest are worker" or something.

Not sure how else it would work...

**Comment by michaelshobbs** [comment]
Ah that makes sense

**Comment by josegonzalez** [comment]
Closing as there is an open PR to add a `DYNO_TYPE_NUMBER` which can be used to implement this feature.
