### ISSUE TITLE
Multiple app container

### ISSUE THREAD

**Issue by cphubs** [progrium/dokku#1351]
Hi
some times when i run some command like ps:rebuild and then run Docker ps multiple docker container like below exist in list: this is true?

169df1a46cf0        dokku/sample4:latest       "/start web"           8 seconds ago        Up 7 seconds                                                                         thirsty_wright
ad461b4d145a        dokku/sample4:latest       "/start web"           21 seconds ago       Up 20 seconds                                                                        clever_morse
bb3032a497c4        dokku/sample4:latest       "/start web"           About a minute ago   Up About a minute                                                                    condescending_almeida
28698feaeb78        ohardy/mariadb:latest      "manage start"         About a minute ago   Up About a minute   127.0.0.1:3306->3306/tcp                                         mariadb_single_container

**Comment by michaelshobbs** [comment]
The 'old' containers will hang out for ~60s by default. If you see them ~5+ minutes after a deployment then there is probably an issue.
