### ISSUE TITLE
Multi level subdomains

### ISSUE THREAD

**Issue by zimt28** [progrium/dokku#1353]
I have my website running on a domain `mydomain.com`. In my DNS setup `mydomain.com` and `www.mydomain.com` point to the the [webflow.com](http://webflow.com) servers.

Now I want to let dokku handle subdomains, so I've set `*.mydomain.com` to point to my dokku server.
This seems to work; I've added a git remote `[...]:dev.app.mydomain.com`. When I access `dev.app.mydomain.com`, I  can access my app.

However, I can also use `anything.app.mydomain.com` or just `app.mydomain.com` to access my app, so dokku seems to only look at the first level subdomain (*app*). It would be cool if dokku would support mutli level subdomains, so that `any.level.domain.com` and `www.any.level.domain.com` would point to an app.

**Comment by michaelshobbs** [comment]
That makes sense given you configuration. To prevent this behavior in my environments I've used a sort of "blackhole" method in my nginx config. This block allows ELB health checks and my NewRelic monitor to hit any name but returns 410 if it encounters a request for an unknown one.

```
server {
  if (\$http_user_agent !~* (ELB-HealthChecker/.*|newrelic-nginx-agent/.*)) {
    return 410;
  }
  log_not_found off;
}
```

**Comment by josegonzalez** [comment]
I think this is application-specific enough that we shouldn't need to support it. It's easy enough to provide a custom `nginx.conf.template` with whatever method you think is necessary though :)

@michaelshobbs re-open if you disagree.

**Comment by zimt28** [comment]
Dokku has the same problem when you run the dokku server itself on a subdomain. This might actually be not so application-specific.

**Comment by KerryRitter** [comment]
Is there still an issue deploying to third-level domains? i.e. <app>.server01.mycompany.com?

**Comment by josegonzalez** [comment]
If you're having a problem, please do not comment on a three year old, closed issue. File a new one if you see any issues. Thanks.
