### ISSUE TITLE
Cannot deploy without web process

### ISSUE THREAD

**Issue by eljojo** [progrium/dokku#1355]
Hi awesome people!
I recently set up a new machine with the latest dokku and noticed I was having problems deploying.
my scale settings are configured for ``worker=4 web=0``.

Here's the output:

```
-----> Running post-deploy
-----> Configuring SSL for example.com...
-----> Configuring SSL for www.example.com...
-----> Creating https nginx.conf
-----> Running nginx-pre-reload
       Reloading nginx
remote: nginx: [emerg] host not found in upstream "maggie" in /home/dokku/maggie/nginx.conf:30
remote: nginx: configuration file /etc/nginx/nginx.conf test failed
To dokku@web2.ext.example.com:maggie
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'dokku@web2.ext.example.com:maggie'
```

Any hints?
It might be worth noting that my workers are actually running fine.

**Comment by josegonzalez** [comment]
Interesting, that should work fine... What is in your Procfile?

**Comment by josegonzalez** [comment]
Also, @michaelshobbs you did the work on process scaling, any thoughts on what might be happening?

**Comment by eljojo** [comment]
```
$ cat Procfile
web: bundle exec puma -C config/puma.rb
worker: bundle exec sidekiq -C ./config/sidekiq.yml
mail_forwarder: bundle exec bin/mail_forwarder
```

**Comment by michaelshobbs** [comment]
Not having looked at the code, I'd say this is just an adjustment needed in the nginx plugin. I can take a look.

**Comment by michaelshobbs** [comment]
BUG!!!! Patch and test on its way!

**Comment by eljojo** [comment]
you people rock!
