### ISSUE TITLE
Node.js app - build failed

### ISSUE THREAD

**Issue by pearlymaccha** [progrium/dokku#1362]
Hello. Lately I got a problem when pushing app to Dokku:

       root@ubuntu1st:/home/apps/apptest/node-js-getting-started# git push nodes master
       Enter passphrase for key '/root/.ssh/id_rsa':
       Counting objects: 426, done.
       Compressing objects: 100% (340/340), done.
       Writing objects: 100% (426/426), 219.20 KiB | 0 bytes/s, done.
       Total 426 (delta 62), reused 404 (delta 54)
       -----> Cleaning up...
       -----> Building nodess from buildstep...
       -----> Adding BUILD_ENV to build environment...
       -----> Node.js app detected

       -----> Creating runtime environment

       NPM_CONFIG_LOGLEVEL=error
       NPM_CONFIG_PRODUCTION=true
       NODE_MODULES_CACHE=true

       -----> Installing binaries
       engines.node (package.json):  0.12.2
       engines.npm (package.json):   unspecified (use default)

       Downloading and installing node 0.12.2...
       remote:
       remote: gzip: stdin: unexpected end of file
       remote: tar: Child returned status 1
       remote: tar: Error is not recoverable: exiting now

       -----> Build failed

       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys

       If you're stuck, please submit a ticket so we can help:
       https://help.heroku.com/

       Love,
       Heroku

       To dokku@dokku.me:nodess
        ! [remote rejected] master -> master (pre-receive hook declined)
       error: failed to push some refs to 'dokku@dokku.me:nodess'

Can someone tell me the solution for this? Thank you :)
*for information:
        node --version: v0.10.25
        npm --version: v1.3.10
and it's my package.json: https://gist.github.com/pearlymaccha/5b2945d176d2748298e3

**Comment by pearlymaccha** [comment]
I've fixed this by pushing with private IP address. Seems like there's something wrong with the ISP I subscribe. Closed :)

**Comment by busla** [comment]
@pearlymaccha could you elaborate on how you fixed this? I´m getting the same error.

**Comment by josegonzalez** [comment]
@busla can you open a new issue and provide the debugging information we ask for [here](https://github.com/progrium/dokku/blob/master/CONTRIBUTING.md#reporting-other-issues)? Thank you.

**Comment by busla** [comment]
Yeah mate, sorry about that :-)
