### ISSUE TITLE
Allow user to turn on nginx cache with a command.

### ISSUE THREAD

**Issue by isundaylee** [progrium/dokku#1363]
So I was just configuring nginx to serve cache for my Rails backend app. It occurred to me that maybe it'd be a really useful feature to allow user to turn on nginx cache with a simple command. 

The implementation can be as simple as creating a nginx.conf.d/cache.conf file for the user. That way, it won't affect the current implementation at all. 

This would be pretty useful as a simple alternative to Varnish, especially since that getting Varnish to work with dokku is a non-trivial process.

**Comment by michaelshobbs** [comment]
My initial reaction...

dokku is quite complex already in its feature set of docker container management and slight nginx management. We seem to have been fairly deliberate in the past about minimizing the automation of nginx management and left it to the end user to ship appropriate configuration for a given application or system as a whole. 

Do we really want to expand this feature set to expose further nginx configuration?

(For the record, my intention is not to shut this topic down in anyway as I definitely think this conversation is worth having as a community)

ping recent contributors @progrium @josegonzalez @alessio @Flink @fwolfst @lmars @SonicHedgehog @3onyc and anyone I may have missed.

**Comment by progrium** [comment]
I agree Dokku core should not be in the business of managing extra Nginx configuration. Unless it hands it off to something else that does it ....

**Comment by isundaylee** [comment]
I definitely get your concern. 

The initial reason I brought this up is that I think it is similar to the SSL support that we are providing out of the box. But you can also argue that SSL/TLS is a much more frequently used case than this.

**Comment by josegonzalez** [comment]
:-1: 

This most certainly seems like it is better handled on a per-app basis, and not something dokku should build into it's core. Yes, it would be nice if it was built into the core, but I think adding your own cache configuration is easy enough, and you can do it in the global nginx conf if you'd like.

SSL is something that many users will use, and is a feature that heroku provides, thus I'm relatively comfortable with including it in the core (however janky some of the processing for it might be).

**Comment by isundaylee** [comment]
Alright guess I'll go ahead and close it then?

**Comment by Flink** [comment]
I agree too with the decision but it might be interesting to make a plugin for your feature @isundaylee no? (as I made one to have a maintenance mode you can turn on and off with a simple command)

**Comment by alessio** [comment]
Nice idea, though in my view it shouldn't be up to the core to manage nginx's configuration.

**Comment by 3onyc** [comment]
I agree too, this should be a plugin, not core functionality

**Comment by isundaylee** [comment]
@Flink Sure, that's a good idea. The thing is that this also requires modifying `/etc/nginx/nginx.conf` for `http` block level configuration, so I am still trying to figure out how best to approach it.
