### ISSUE TITLE
dokku expects the container to have /bin/bash ?

### ISSUE THREAD

**Issue by dnephin** [progrium/dokku#1364]
Apologies if there is an existing issues for this, I looked, but didn't find one.

Dokku version 0.3.22
Docker version 1.6.2

I run containers based on `alpine:3.2` which doesn't have `/bin/bash` (it has `/bin/sh`).

When I `git push dokku` I see this, but it doesn't result in a fatal error (the service is still deployed and run):

```
...
Successfully built 221de4a9b663
-----> Releasing alpine-mirror...
-----> Deploying alpine-mirror...
remote: time="2015-08-03T17:53:48Z" level=fatal msg="Error response from daemon: Cannot start container f41ba3da1134ac0d1bf5835e2fa66f95fad9920e33ff5548e3861c8a41b1a4e8: [8] System error: exec: \"/bin/bash\": stat /bin/bash: no such file or directory" 
remote: exec: "/bin/bash": stat /bin/bash: no such file or directory
remote: time="2015-08-03T17:53:48Z" level=fatal msg="Error response from daemon: Cannot start container 0a4fab06d4805a014cd13c3ccc7d8987da99b49d3c341d4a31e81901ef83e58e: [8] System error: exec: \"/bin/bash\": stat /bin/bash: no such file or directory" 
-----> Running pre-flight checks
...
```

I tried `ln -s /bin/sh /bin/bash` but I hit some other warning `remote: bash: applet not found`, and I'd rather not add that line to every single `Dockerfile`.

Any way I can configure dokku to only expect `/bin/sh` to get rid of these errors? 

I took a couple minutes to try and locate the `exec` call, but nothing came up. If someone more familiar with dokku could point me at the code which runs this, that would be awesome.

Thanks!

**Comment by josegonzalez** [comment]
Can you paste in a deploy with `dokku trace on`?

**Comment by dnephin** [comment]
I didn't know about trace, cool. 

I found the line that's running it here: https://github.com/progrium/dokku/blob/v0.3.22/plugins/common/functions#L137

**Comment by michaelshobbs** [comment]
Ah yea. This seems reasonable. Patch coming.

**Comment by dnephin** [comment]
Thanks for the quick fix!

**Comment by chrisnicola** [comment]
This appears to be broken still. Scripts detected in `app.json` are run using /bin/bash.

```
emote: docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory".
remote: execution of 'rake db:migrate' failed!
       container_linux.go:247: starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory"
```

**Comment by Ferrari** [comment]
Same +1
This still happen when using alpine image.

**Comment by josegonzalez** [comment]
@Ferrari thanks for the +1, but we know the issue exists and we have an open issue (linked above) for it. If you'd like to contribute a fix, that would be greatly appreciated.
