### ISSUE TITLE
Don’t automatically configure certificate’s CN and SANs as domains

### ISSUE THREAD

**Issue by SonicHedgehog** [progrium/dokku#1368]
Currently, [the certificate’s Common Name and its Subject Alternative Names are automatically added to `VHOST`](https://github.com/progrium/dokku/blob/v0.3.22/plugins/nginx-vhosts/commands#L79-L89). However, your certificate may contain domains which you do not want to use for your particular dokku app.

I would therefore propose to either require configuring additional domains manually ([as documented by Heroku](https://devcenter.heroku.com/articles/ssl-endpoint#dns-and-domain-configuration)) or to only write the CN and SANs to `VHOST` if the file doesn’t already exist.

**Comment by josegonzalez** [comment]
Can you give us a use-case where this is a problem?

**Comment by SonicHedgehog** [comment]
For example, [StartSSL won’t issue a certificate without the primary root domain](https://forum.startcom.org/viewtopic.php?f=15&t=2400). So, if you try to obtain a certificate only for `cdn.example.com`, your certificate must also include `example.com`. However, you can’t even remove `example.com` using `dokku domains:remove` because it will just be added again on the next deployment.

The same goes for any multi-domain certificate.

**Comment by michaelshobbs** [comment]
I like the part where dokku does less "magic" and abides by the Heroku documentation. This would make that part of dokku far less complex

**Comment by josegonzalez** [comment]
@michaelshobbs if you want to do the work for this, cool. I know you put in a ton of work around ssl certificate handling, and to be honest I don't know quite what this would entail changing...

**Comment by olalonde** [comment]
I had the same problem with a sslmate multi domain certificate. The certificate is for mydomain.com, service1.mydomain.com and service2.mydomain.com, which are 3 distinct dokku apps. When I add the SSL certificate to any of the apps though, it adds `mydomain.com` to that app and I end up with 3 dokku apps trying to serve traffic for `mydomain.com`.

**Comment by michaelshobbs** [comment]
I'm completely behind reducing the complexity here. I'll take a swing at reimplementing to the Heroku UI and functionality. (including docs and links to the "Heroku way" :smile:)

**Comment by josegonzalez** [comment]
Closing as there is a fix provided. Please track progress in #1414.
