### ISSUE TITLE
Clone a container or a app in dokku

### ISSUE THREAD

**Issue by jhonn921007** [progrium/dokku#1371]
I'm using Dokku for a creator store (shopify style), I work pretty well, I wonder if there is any way to clone a store with Dokku clone a container for reuse whenever you have a new store? 

Thanks in advance, I love this project. I would love to contribute to the community.

**Comment by mixxorz** [comment]
Are you asking if you can have another instance of the same app? If so, you can just push up your app under a different name. Now you have two separate instances of the same app.

**Comment by michaelshobbs** [comment]
@jhonn921007 does @mixxorz's suggestion work for your use-case?

**Comment by jhonn921007** [comment]
I could fix it!
With this plugin:
https://github.com/agco/dokku-registry

Create a container base which climbed to copy and docker.com
And every time I need to create an app, just do:
  dokku apps: create shop
  dokku registry: myusername pull myapp / myapp: 1.2.3

Thank you all, Dokku is great.

**Comment by michaelshobbs** [comment]
:+1:
