### ISSUE TITLE
Dokku app dies and refuses to restart

### ISSUE THREAD

**Issue by tyler274** [progrium/dokku#1373]
root@server1:/run# dokku rebuild blog
-----> Cleaning up...
-----> Building blog from ...
Building image source type  not supported!

root@server1:/run# dokku ps blog
FATA[0000] Error response from daemon: no such id: 85b29f6665f2974d9c158ad89d7ff25f09b73bad9bdb89e74bdb798462480f8f

root@server1:/run# dokku ls
-----> App Name           Container Type            Container Id              Status
blog                      web                       85b29f6665f2              stopped
blog                      web                       2ecd4b65c04f              stopped
blog                      web                       0823cd24adcf              stopped

root@server1:/run# dokku ps:start blog
Error: No such image or container: 85b29f6665f2974d9c158ad89d7ff25f09b73bad9bdb89e74bdb798462480f8f
Error: No such image or container: 2ecd4b65c04f0e9875488cc21969f76d0f8c501749eddba09d8b8687d01404f0
Error: No such image or container: 0823cd24adcfe67a9ebb93a111e0dc5053076c3e68328f655f1fc64d2e538878

**Comment by josegonzalez** [comment]
Looks like your image didn't have a base image? Did you upgrade dokku recently?

**Comment by michaelshobbs** [comment]
@tyler274 you're using the rebuild plugin with a later version of dokku than is supported I think. what version of dokku are you on? 

in dokku v0.3.14 or later, run
```
dokku ps:rebuild blog
```

**Comment by josegonzalez** [comment]
@tyler274 Did you have any luck upgrading and using the official `dokku ps rebuild APP` command?

**Comment by josegonzalez** [comment]
Closing as there hasn't been any movement in a month.
