### ISSUE TITLE
limit app resource

### ISSUE THREAD

**Issue by cphubs** [progrium/dokku#1375]
Can i limit app resource like cpu, memory, disk and ... ?

**Comment by josegonzalez** [comment]
You can do so via the official [`docker-options`](http://progrium.viewdocs.io/dokku/docker-options/) plugin. There is nothing finer-grained than that, so basically anything you can do with docker, you can do through that interface on a per-app basis.

**Comment by cphubs** [comment]
Good tip
thanks
