### ISSUE TITLE
Setting UID/GIDs

### ISSUE THREAD

**Issue by rcarmo** [progrium/dokku#1376]
I'm having a little trouble sharing volumes across containers due to randomized UID/GIDs. 

Would it be possible to have a per-app config setting to pin down the UID/GID for the running process?

**Comment by josegonzalez** [comment]
Seems like the best way to do this would be via [data-only containers](http://stackoverflow.com/a/27021154)?

**Comment by rcarmo** [comment]
Hmm. In the description you linked to, the need for consistent UID/GIDs is explicitly mentioned - right now, UIDs/GIDs don't seem to be consistent among containers when using a `Procfile`, and reading further docker/docker#7198 is still open.

I was using dokku-alt previously, and this was fixed in dokku-alt/dokku-alt#141 by tweaking `buildstep`. 

I'm going to see if I can do something about this by tweaking statianzo/dokku-shoreman, which I need anyway because I need to run `web` and `worker` processes inside the same container for IPC (at least until I sort some things out)

**Comment by josegonzalez** [comment]
@rcarmo did you figure out a workaround for this?

**Comment by rcarmo** [comment]
Not yet. I didn't want to risk breaking my "production" box and started working on an ansible playbook to redeploy my entire setup, and then there were two releases in a row, so I'm kind of waiting until the dust settles... But the UID seems to be set by `buildstep` - it's just that it's costly (in terms of time) to track this down and test, but it will happen -- if not me, then someone else, since this is such a common problem...

**Comment by josegonzalez** [comment]
Not for nothing, but first time we hear of the uid/gid requirement, so I doubt it's a common problem. I'll keep the issue open regardless until someone has time to track down what the necessary change might be.

**Comment by Cactusbone** [comment]
I have the same problem. I'm sharing a folder on the host between 2 dokku apps which both need to write to it.

right now i adde a+w to the folder

**Comment by josegonzalez** [comment]
@michaelshobbs might it be possible to set the user's uid/guid to the same as the dokku user when we boot instances?

**Comment by michaelshobbs** [comment]
With herokuish, you can export `$USER` to define which user to run everything as in a herokuish based container.

**Comment by Cactusbone** [comment]
yeah i noticed that recently, but it's from herokuish 0.2. it seems the packaged one in ubuntu is 0.0.1
I'm trying with a custom build :)

setting USER in dokku config:set is enough right ?

**Comment by josegonzalez** [comment]
@Cactusbone what do you mean, packaged in ubuntu? We package our own version, which should be `0.3.1`...

**Comment by Cactusbone** [comment]
i only checked `apt-cache madison herokuish`
i guess the package version displayed might be wrong.
In that case, setting USER in dokku config did not work :/

**Comment by michaelshobbs** [comment]
@Cactusbone The `$USER` variable is used in the build process. You'd need to set it and do a `ps:rebuild`. Currently `config:set` just calls `release_and_deploy` which does not rebuild the app.

**Comment by josegonzalez** [comment]
Oh heh, the version in the `deb.mk` doesn't correspond with the actual herokuish version...

**Comment by Cactusbone** [comment]
@michaelshobbs yep i saw that but it didn't seem to work.
I'm using https://github.com/sehrope/dokku-logging-supervisord so I'm checking where it might have gone wrong

**Comment by Cactusbone** [comment]
I've used `dokku config:set --global USER=1000` then ps:rebuild and the final process was launched by 23709 (with user u23709 created in docker)

**Comment by michaelshobbs** [comment]
IIRC, the user must exit first. Maybe try `USER=nobody`?

**Comment by Cactusbone** [comment]
with USER=nobody, it still ended up with user 23711 :(

**Comment by Cactusbone** [comment]
I tried without supervisord, and it's still the same result.
when i inspect the docker container, USER isn't in ENV, so i'm not sure dokku config data is available during app startup

**Comment by michaelshobbs** [comment]
@Cactusbone are you deploying a dockerfile or a regular buildpack app?

**Comment by Cactusbone** [comment]
regular nodejs app

**Comment by michaelshobbs** [comment]
Ok but are you deploying using the Dockerfile or buildpack method?

**Comment by Cactusbone** [comment]
Buildpack method. (with a procfile)

**Comment by michaelshobbs** [comment]
Oh I was just re-reading some previous comments here and it looks like you're using buildstep? The `$USER` env variable is only available (as I understand it) when using herokuish. That means you'll need to upgrade to dokku 0.3.26. Can you do that in a test env perhaps? I know you mentioned not wanting to disturb your production env.

**Comment by Cactusbone** [comment]
Nope, that was rcarmo,  i'm using herokuish with dokku 0.3.26 (trunk version built yesterday)

**Comment by michaelshobbs** [comment]
Oh great! (I apparently can't read)

I'm working on another PR at the moment but once I'm finished I'll poke around in herokuish and see what I can sort out.

**Comment by rcarmo** [comment]
That would be awesome, Michael, thanks.

**Comment by Cactusbone** [comment]
great ! :) in the meantime `dokku docker-options:add <app> deploy -e USER=nobody` does the trick for me :)

**Comment by michaelshobbs** [comment]
@rcarmo does that work for you?

**Comment by rcarmo** [comment]
Theoretically, yeah, would be great!

**Comment by michaelshobbs** [comment]
Can you give it a shot and let us know?

**Comment by rcarmo** [comment]
Only next weekend - I'm kind of in between projects and helping out with an event, so CLI time is limited. 

But it does seem like the right way to do things - I can set the UID to www-data on my projects (since that seems to be consistent across Debian/Ubuntu) and see if they work.

**Comment by michaelshobbs** [comment]
@rcarmo ok. i'll close this then. feel free to re-open if necessary

**Comment by josegonzalez** [comment]
@rcarmo we should have this documented ;)

**Comment by michaelshobbs** [comment]
:+1:
