### ISSUE TITLE
Old containers are not cleaned

### ISSUE THREAD

**Issue by eljojo** [progrium/dokku#1378]
Hi everyone,
I have a machine I set up one or two weeks ago with 0.3.22.

I noticed that the old containers are not being cleaned (the machine ran out of space).

As a patch solution, I am running ``docker rm `docker ps --no-trunc -aq` `` which deletes all un-used containers, not just dokku's. For me that's acceptable.

```
root@web2:~# docker ps
CONTAINER ID        IMAGE                  COMMAND                CREATED             STATUS              PORTS                                                    NAMES
c08a62c247a7        dokku/maggie:latest    "/start worker"        11 minutes ago      Up 11 minutes                                                                elated_wozniak
7f22285ab304        eljojo/statsd:latest   "node stats.js confi   9 days ago          Up 9 days           172.17.42.1:8126->8126/tcp, 172.17.42.1:8125->8125/udp   jovial_morse
root@web2:~# docker ps -a
CONTAINER ID        IMAGE                       COMMAND                CREATED             STATUS                         PORTS                                                    NAMES
c08a62c247a7        dokku/maggie:latest         "/start worker"        11 minutes ago      Up 11 minutes                                                                           elated_wozniak
06f3d393048f        dokku/maggie:latest         "/start worker"        11 minutes ago      Exited (2) 18 seconds ago                                                               hopeful_meitner
e456f67f1c3c        dokku/maggie:latest         "/start worker"        12 minutes ago      Exited (2) 18 seconds ago                                                               stupefied_lalande
8f3f4cb0288a        dokku/maggie:latest         "/start worker"        12 minutes ago      Exited (2) 18 seconds ago                                                               stupefied_brattain
624aab7aaccb        dokku/maggie:latest         "/start worker"        12 minutes ago      Exited (2) 18 seconds ago                                                               berserk_thompson
3a1aa8bc2d10        dokku/maggie:latest         "/start worker"        12 minutes ago      Exited (2) 18 seconds ago                                                               serene_goldstine
3b73a0154833        dokku/maggie:latest         "/start worker"        12 minutes ago      Exited (2) 18 seconds ago                                                               trusting_feynman
4d7770555558        dokku/maggie:latest         "/start worker"        12 minutes ago      Exited (2) 19 seconds ago                                                               modest_mcclintock
d9717a00c3d6        dokku/maggie:latest         "/start worker"        13 minutes ago      Exited (2) 19 seconds ago                                                               serene_ptolemy
bc767dfbb109        dokku/maggie:latest         "/bin/bash -c 'mkdir   13 minutes ago      Exited (0) 13 minutes ago                                                               ecstatic_hopper
c726aa8c491b        dokku/maggie:latest         "/bin/bash -c 'mkdir   13 minutes ago      Exited (0) 13 minutes ago                                                               loving_kirch
1a5230878d46        dokku/maggie:latest         "/start worker"        28 hours ago        Exited (0) About an hour ago                                                            nostalgic_hawking
0e139323ae00        dokku/maggie:latest         "/start worker"        28 hours ago        Exited (0) About an hour ago                                                            fervent_ardinghelli
be6f60a9d3ba        dokku/maggie:latest         "/start worker"        28 hours ago        Exited (0) About an hour ago                                                            happy_lovelace
2141558ca8e5        dokku/maggie:latest         "/start worker"        28 hours ago        Exited (0) About an hour ago                                                            gloomy_sammet
6af5154ec4f9        dokku/maggie:latest         "/start worker"        28 hours ago        Exited (0) About an hour ago                                                            boring_banach
0f08d84fb093        dokku/maggie:latest         "/start worker"        28 hours ago        Exited (0) About an hour ago                                                            condescending_engelbart
439c43563458        dokku/maggie:latest         "/start worker"        28 hours ago        Exited (0) About an hour ago                                                            drunk_mayer
d7e4c4971070        dokku/maggie:latest         "/start worker"        28 hours ago        Exited (0) About an hour ago                                                            jolly_brown
e2c6cf3bc54d        dokku/maggie:latest         "/start worker"        28 hours ago        Exited (0) About an hour ago                                                            clever_sammet
aeecfb152466        dokku/maggie:latest         "/start worker"        28 hours ago        Exited (0) About an hour ago                                                            clever_goldstine
[ the list keeps going ]
7f22285ab304        eljojo/statsd:latest        "node stats.js confi   9 days ago          Up 9 days                      172.17.42.1:8125->8125/udp, 172.17.42.1:8126->8126/tcp   jovial_morse
```

**Comment by michaelshobbs** [comment]
The very first step of a dokku deploy is the cleanup phase that runs similar commands.

https://github.com/progrium/dokku/blob/v0.3.22/dokku#L189L196
https://github.com/progrium/dokku/blob/v0.3.22/dokku#L56

Are you deploying new versions of your app or running other commands?

**Comment by eljojo** [comment]
Yeah, I've been deploying new versions at least once a day, and most certainly also running commands with ``dokku run``.
I have a vanilla dokku installation.

I've seen this behaviour since at least 0.3.17

**Comment by michaelshobbs** [comment]
What happens when you run `dokku cleanup`? Do you see fewer containers left over?

You can also use the syntax `dokku --rm run ...` to automatically remove the container when it's finished.

**Comment by eljojo** [comment]
I'll check out what ``dokku cleanup`` does after I have more containers. I just cleaned them all.

``dokku run`` doesn't automatically remove the containers once they're finished? why is that? any reason to keep them?

**Comment by michaelshobbs** [comment]
Yeah there was a discussion about this in another issue. It makes sense for debugging and sine there's no way to get the info back once the container is removed, the decision was made to leave the default to not remove them.

**Comment by eljojo** [comment]
hm that's somewhat counter intuitive, isn't it? Would it make sense to re-start the conversation around it?
The way I perceive ``dokku run`` is as a one-time-thing. 
If the only reason to keep the container is debugging, wouldn't it be better to have a ``--keep-container`` flag (or ``--debug``)?

This is definitely causing at least some of my uncleaned containers, but as you can see in the pasted output, some of them were stated with ``"/start worker"``. Any reason why those would not be cleaned?

**Comment by michaelshobbs** [comment]
A conversation is always welcomed. I was merely giving you context. 

The container clean up is done using simple docker commands as you can see in the links provided in my earlier comment. So the docket daemon is deciding what it can and cannot reap. I suggest running these commands manually and inspecting the output to see if it leads you to a more informative message.

**Comment by michaelshobbs** [comment]
@eljojo did you find any more detail from running the commands manually?

**Comment by eljojo** [comment]
I couldn't find a lot of time to do tests.
ran ``dokku cleanup`` after creating some containers and they were cleaned.

It's probably best to close this issue. I'll re-open it if I find out something.

**Comment by CherryDT** [comment]
I have a similar problem even now, but as a workaround I use this command to clean all containers which are old and either have the `random_words` form or the `something.1234567890` form.

```docker ps -q --format={{.Names}} | grep -P '^\w+$|\.\d{10,}$' | xargs docker rm -f```

**Comment by josegonzalez** [comment]
@CherryDT thats a good call, the `something.NUMBER` format isn't a thing we clean up very well. Can you open up an issue so we can also clean those up in dokku?

We should also maybe label all intermediate containers so that we can clean up by label as well, @michaelshobbs .

**Comment by CherryDT** [comment]
@josegonzalez There you go #2482

**Comment by michaelshobbs** [comment]
@josegonzalez I thought we already did this actually....apparently I am wrong?
