### ISSUE TITLE
Global Docker options?

### ISSUE THREAD

**Issue by ernoaapa** [progrium/dokku#1384]
Hi,
is there a way to set global Docker options? I would like to set for example "--restart=always" to every app. Looking at source code looks like that it reads only DOCKER_OPTIONS_* from app directory, but any workaround? Modify Docker run command or something?

**Comment by michaelshobbs** [comment]
Currently there is not a global docker options scope. A PR would be welcomed though.

**Comment by josegonzalez** [comment]
Also, `--restart=always` would almost certainly break how the checks plugin works.

**Comment by ernoaapa** [comment]
@josegonzalez you mean that there will come problems because restart would cause the container ids change but the `CONTAINER` file contains old id?
Is it crazy idea if `get_app_container_ids` would fallback to image id when resolving container ids?

I just try to find a way how can I make it more update friendly (by allowing Docker restart) and more fail safe by supporting container and server restarts.

**Comment by michaelshobbs** [comment]
@ernoaapa i think its worth creating a plugin that does this to experiment some and perhaps gauge interest. there have been a few convos around this since that option was made available but it seems to not jive (at least in concept) with dokku being a container manager.

**Comment by josegonzalez** [comment]
I'm going to close this as I think it will lead to lots of complications in the code that maintains this and it can be handled via plugins I think.

**Comment by ernoaapa** [comment]
Ok. I'm not sure where to start with the plugin and. 

For now I just block Docker updates in our configuration management tool and consider moving to use Deis for more fail safe setup.
