### ISSUE TITLE
Environment variables from buildpack not available during runtime

### ISSUE THREAD

**Issue by SonicHedgehog** [progrium/dokku#1385]
For example, [Heroku’s Node.js buildpack sets `NODE_ENV` to `production`](https://github.com/heroku/heroku-buildpack-nodejs/blob/v79/lib/environment.sh#L5):

```
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NPM_CONFIG_PRODUCTION=true
       NODE_ENV=production
       NODE_MODULES_CACHE=true
```

However, during runtime this environment variable is no longer set. Is this an intentional feature?

**Comment by michaelshobbs** [comment]
In my mind, it is intentional. Not everybody wants production in their dokku envs. In my dokku node systems, I explicitly set `NODE_ENV=production`.

**Comment by SonicHedgehog** [comment]
> Not everybody wants production in their dokku envs.

Definitely. `NODE_ENV=production` may be a sane default, though, because, for example, Express does not include an error’s stack trace in the production environment.

In general, mistakenly running `NODE_ENV=production` in development is less harmful than mistakenly running `NODE_ENV=development` in production.

**Comment by josegonzalez** [comment]
Well, that env var is set from the buildpack, not via dokku. I don't think setting an arbitrary env var like this is a good idea, because not everyone uses dokku in a production env. I certainly don't, and would hate this sort of env var being injected.

If you think it's a bug, I would file it upstream with the buildpack maintainers so that heroku *and* dokku users can benefit.

**Comment by SonicHedgehog** [comment]
While not everyone uses dokku in a production environment, dokku/Heroku are arguably predestined for production deployments. Furthermore, `NODE_ENV=production` is a more secure default.

Consider the following scenario: I just deployed a Node.js application to production. Because the buildpack clearly states that it’s creating a runtime environment with `NODE_ENV` set to `production` I thought there’s no need to do so. I only came across this issue after someone hit an error in my application and was presented the full stack trace by Express.

> If you think it's a bug, I would file it upstream with the buildpack maintainers so that heroku and dokku users can benefit.

As far as I can tell, [Heroku considers this a feature](https://devcenter.heroku.com/articles/nodejs-support#runtime-behavior) and only asks you to change the environment variable if you want to run in a non-production environment.

**Comment by michaelshobbs** [comment]
Being a Heroku default is a valid point. Do we think it's safe enough to pass in as a default for any app type or do we need to attempt to figure out the app type we're deploying?

@SonicHedgehog care to make a PR for this?

**Comment by josegonzalez** [comment]
@michaelshobbs This sounds like a bug in the buildpack - or at most herokuish - not a bug here.

**Comment by michaelshobbs** [comment]
Oh I see. perhaps make the buildpack set up the app env via the release step to export this variable?

**Comment by SonicHedgehog** [comment]
[According to Heroku’s documentation](https://devcenter.heroku.com/articles/buildpack-api#default-config-values), a default environment should be set up using a `.profile.d` script and [they explicitly list `NODE_ENV=production` as an example](https://devcenter.heroku.com/articles/buildpack-api#default-config-values).

Either dokku isn’t picking up on the `.profile.d` directory (although [it seems to be supported](https://github.com/progrium/dokku/issues/92#issuecomment-21005003)) or the buildpack isn’t setting the `NODE_ENV` variable in a `.profile.d` script. If time permits, I’ll take a look at this tomorrow.

**Comment by michaelshobbs** [comment]
Here's what I see from my deployment of the sample nodejs app using the master branch from https://github.com/heroku/heroku-buildpack-nodejs

```
root@3d1d27a65941:~# cd /app/.profile.d/
root@3d1d27a65941:/app/.profile.d# ll
total 16
drwxr-xr-x  2 u32672 u32672 4096 Aug 14 17:47 ./
drwxr-xr-x 22 u32672 u32672 4096 Aug 14 17:47 ../
-rw-r--r--  1 u32672 u32672   53 Aug 14 17:47 00-global-env.sh
-rw-r--r--  1 u32672 u32672    0 Aug 14 17:47 01-app-env.sh
-rwxr-xr-x  1 u32672 u32672 1128 Aug 13 23:43 nodejs.sh*
root@3d1d27a65941:/app/.profile.d# grep NODE_ENV *
root@3d1d27a65941:/app/.profile.d# cat nodejs.sh
calculate_concurrency() {
  MEMORY_AVAILABLE=${MEMORY_AVAILABLE-$(detect_memory 512)}
  WEB_MEMORY=${WEB_MEMORY-512}
  WEB_CONCURRENCY=${WEB_CONCURRENCY-$((MEMORY_AVAILABLE/WEB_MEMORY))}
  if (( WEB_CONCURRENCY < 1 )); then
    WEB_CONCURRENCY=1
  elif (( WEB_CONCURRENCY > 32 )); then
    WEB_CONCURRENCY=32
  fi
  WEB_CONCURRENCY=$WEB_CONCURRENCY
}

log_concurrency() {
  echo "Detected $MEMORY_AVAILABLE MB available memory, $WEB_MEMORY MB limit per process (WEB_MEMORY)"
  echo "Recommending WEB_CONCURRENCY=$WEB_CONCURRENCY"
}

detect_memory() {
  local default=$1
  local limit=$(ulimit -u)

  case $limit in
    256) echo "512";;     # Standard-1X
    512) echo "1024";;    # Standard-2X
    16384) echo "2560";;  # Performance-M
    32768) echo "6144";;  # Performance-L
    *) echo "$default";;
  esac
}

export PATH="$HOME/.heroku/node/bin:$HOME/bin:$HOME/node_modules/.bin:$PATH"
export NODE_HOME="$HOME/.heroku/node"

calculate_concurrency

export MEMORY_AVAILABLE=$MEMORY_AVAILABLE
export WEB_MEMORY=$WEB_MEMORY
export WEB_CONCURRENCY=$WEB_CONCURRENCY

if [ "$LOG_CONCURRENCY" = "true" ]; then
  log_concurrency
fi
```

Seems like @josegonzalez may be right that it's a bug in the buildpack?

**Comment by SonicHedgehog** [comment]
[I have opened a pull request against the buildpack](https://github.com/heroku/heroku-buildpack-nodejs/pull/258). I have already tested it with dokku and it fixes this issue. Sorry for all the trouble but I’m glad we got it tracked down.

**Comment by michaelshobbs** [comment]
Excellent! Glad we got it sorted as well.

**Comment by brmullikin** [comment]
I'm asking the question here since I don't know if it warrants a new question/issue...

in my Dokku apps, the ENV file has: `export key=value ` rather than `key=value`.

When I do `dokku config myapp` I get the expected result of 
    key: value
    key2: value2

But in app, my env keys are `env["export key"]` and `env["export key2"]` (rather than simply `env["key"]`

Is this expected behavior?

Removing `export` from before keys in the ENV file results in `dokku config myapp` not returning anything.

Perhaps I configured something incorrectly? So far as I can tell all else seems to be working as expected. (I'm migrating apps from Heroku)
