### ISSUE TITLE
Error install_in_parallel on deploy

### ISSUE THREAD

**Issue by 0994f** [progrium/dokku#1386]
Hi Guys,

Have this error on deploy my app : 

![capture d ecran 2015-08-15 20 50 43](https://cloud.githubusercontent.com/assets/2165129/9290351/5568b4ec-438f-11e5-93ff-da63fbf7de05.png)

At this time have found any solution.

Thanks

**Comment by 0994f** [comment]
Fixed with an other buildpack (export BUILDPACK_URL=https://github.com/heroku/heroku-buildpack-ruby.git)

**Comment by josegonzalez** [comment]
What buildpack were you using?
