### ISSUE TITLE
Unattended installation via debconf causes apt errors

### ISSUE THREAD

**Issue by jimeh** [progrium/dokku#1387]
I'm working on a chef cookbook to install dokku on my machines, and as such I'm using the `debconf` approach to perform a unattended installation, as per the [docs](http://progrium.viewdocs.io/dokku/getting-started/install/debian/).

Here's the specific fork/branch I'm working on: https://github.com/jimeh/chef-dokku-simple/blob/a575752d648edde5a56382c3c86b019d8c9c8637/recipes/default.rb#L26-L60

The problem is when debconf is used before the first installation, then subsequent installations via a newer version of `bootstrap.sh`, or just plain `apt-get install dokku` fails with the following error:

```
E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?
E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?
dpkg: error processing package dokku (--configure):
 subprocess installed post-installation script returned error exit status 100
Errors were encountered while processing:
 dokku
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

No process has the `/var/lib/dpkg/lock` file open, and deleting it doesn't make a difference.

Here's the exact steps I perform:

```bash
$ echo "dokku dokku/web_config boolean false" | sudo debconf-set-selections && \
  echo "dokku dokku/vhost_enable boolean true" | sudo debconf-set-selections && \
  echo "dokku dokku/hostname string dokku.me" | sudo debconf-set-selections && \
  echo "dokku dokku/key_file string /root/.ssh/id_rsa.pub" | sudo debconf-set-selections

$ wget https://raw.github.com/progrium/dokku/v0.3.22/bootstrap.sh
$ sudo DOKKU_TAG=v0.3.22 bash bootstrap.sh
# Dokku successfully installs

$ rm bootstrap.sh
$ wget https://raw.github.com/progrium/dokku/v0.3.23/bootstrap.sh
$ sudo DOKKU_TAG=v0.3.23 bash bootstrap.sh
# Installation fails with above mentioned error.

$ sudo apt-get install dokku
# Installation again fails like above.
```

I've also tried to clear out the debconf settings, but that didn't work either, the value is just set again during the failing installation:

```bash
$ echo UNREGISTER dokku/web_config | sudo debconf-communicate dokku
$ echo UNREGISTER dokku/vhost_enable | sudo debconf-communicate dokku
$ echo UNREGISTER dokku/hostname | sudo debconf-communicate dokku
$ echo UNREGISTER dokku/key_file | sudo debconf-communicate dokku

$ echo GET dokku/web_config | sudo debconf-communicate dokku
10 dokku/web_config doesn't exist
$ echo GET dokku/vhost_enable | sudo debconf-communicate dokku
10 dokku/vhost_enable doesn't exist
$ echo GET dokku/hostname | sudo debconf-communicate dokku
10 dokku/hostname doesn't exist
$ echo GET dokku/key_file | sudo debconf-communicate dokku
10 dokku/key_file doesn't exist

$ wget https://raw.github.com/progrium/dokku/v0.3.23/bootstrap.sh
$ sudo DOKKU_TAG=v0.3.23 bash bootstrap.sh
# Errors out just like before.

$ echo GET dokku/web_config | sudo debconf-communicate dokku
0 true
$ echo GET dokku/vhost_enable | sudo debconf-communicate dokku
0 false
$ echo GET dokku/hostname | sudo debconf-communicate dokku
0 dokku.me
$ echo GET dokku/key_file | sudo debconf-communicate dokku
0 /root/.ssh/id_rsa.pub
```

So far I haven't figured out a way to fix this, and just resorted to rolling back the VM to before dokku was installed and try again.

**Comment by rcarmo** [comment]
I was about to upgrade my ansible playbooks to use the new version too, so I'm curious: can you get 3.2.22 to install and then upgrade to current in _any_ way?

**Comment by jimeh** [comment]
@rcarmo At this point I can't update Dokku at all if the initial install used debconf. I made some attempts at fixing it once broken, but ultimately rolled back the VM and altered the installation to see if it could be avoided.

I have one last theory I haven't tried yet, which is I set the `key_file` via debconf to a temporary cache file that won't exist later. I won't be able to test it for another 10ish hours, but maybe that file needs to stay in place to prevent the package update process from failing.

**Comment by michaelshobbs** [comment]
Out of curiosity, as part of your chef recipe, are you installing any 3rd party plugins?

**Comment by jimeh** [comment]
@michaelshobbs I am actually. I'm pretty sure I had a couple of runs without plugins though, but I'll make sure to skip it when I dig into this again in the next day or two.

**Comment by michaelshobbs** [comment]
Ah! I think then #1205 may be related

**Comment by jimeh** [comment]
Hmm, does indeed look related. I'll post an update when I've tested (definitely) without plugins.

**Comment by jimeh** [comment]
Ok, it is indeed the same issue as #1205. I had plugins that called `apt-get install` from the `install` hook. For the time being I'll simply make the chef cookbook remove all plugin it's managing before upgrading dokku, and then reinstall them again.
