### ISSUE TITLE
Set Github project URL to http://progrium.viewdocs.io/dokku/

### ISSUE THREAD

**Issue by olalonde** [progrium/dokku#1391]
I always have to search around for the docs page.

**Comment by joshco** [comment]
Also please make the table of contents work.  The new splash page is pretty but it makes navigating the docs harder.
Maybe put a button to click through to what used to be the docs landing page

**Comment by josegonzalez** [comment]
@joshco what table of contents?

@progrium we need you to set that url (also would be nice if this project was transferred to the dokku org, but thats a separate conversation).

**Comment by progrium** [comment]
done

On Tue, Aug 18, 2015 at 11:05 AM, Jose Diaz-Gonzalez <
notifications@github.com> wrote:

> @joshco <https://github.com/joshco> what table of contents?
>
> @progrium <https://github.com/progrium> we need you to set that url (also
> would be nice if this project was transferred to the dokku org, but thats a
> separate conversation).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/progrium/dokku/issues/1391#issuecomment-132261490>.
>



-- 
Jeff Lindsay
http://progrium.com

**Comment by olalonde** [comment]
Thanks @progrium
