### ISSUE TITLE
Disabling HTTPS redirection

### ISSUE THREAD

**Issue by olalonde** [progrium/dokku#1392]
Is it possible to disable HTTP to HTTPS redirects? I just installed certs on my dokku app and would like to get rid of this feature.

**Comment by josegonzalez** [comment]
Use a different nginx configuration than the default one.

Why would you want duplicate content on http vs https? I can't imagine a situation where you'd want http when https is available...

**Comment by olalonde** [comment]
Can I just edit the nginx.conf file in `/home/dokku/appname`? Won't that be overwritten next time I deploy?

> Why would you want duplicate content on http vs https? I can't imagine a situation where you'd want http when https is available...

The reason is that I'm using Cloudflare for https termination on my top level domain (somedomain.com) and somedomain.com therefore needs to be http. However, the same app also runs a websocket server which Cloudflare doesn't support I need to access it from https://appname.d.somedomain.com.

**Comment by josegonzalez** [comment]
@olalonde you can follow the instructions [here](http://progrium.viewdocs.io/dokku/nginx/) to customize your app's nginx configuration.

**Comment by olalonde** [comment]
Thanks. The docs mentions: 

> If you'd like to provide a custom template for your application, you should copy the existing template - ssl or non-ssl - into your application repository's root directory as the file nginx.conf.template

But it doesn't mention where the existing template is located.

**Comment by olalonde** [comment]
Oh, I guess it refers to that file? https://github.com/progrium/dokku/blob/master/plugins/nginx-vhosts/templates/nginx.ssl.conf.template

**Comment by michaelshobbs** [comment]
Yeah that's the ssl version of course

**Comment by freddi301** [comment]
Hi,
this [page](http://progrium.viewdocs.io/dokku/nginx/) explains nothing.
Please provide a better documentation and a simple example oh how just disable http -> https redirection retianing all other confs
