### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by theccc** [progrium/dokku#1396]
sudo DOKKU_TAG=v0.3.23 bash bootstrap.sh
Preparing to install v0.3.23 from https://github.com/progrium/dokku.git...
Hit http://mirrors.service.networklayer.com precise Release.gpg
Hit http://mirrors.service.networklayer.com precise-updates Release.gpg
Hit http://mirrors.service.networklayer.com precise-security Release.gpg
Hit http://mirrors.service.networklayer.com precise Release
Hit http://mirrors.service.networklayer.com precise-updates Release
Hit http://mirrors.service.networklayer.com precise-security Release
Hit http://mirrors.service.networklayer.com precise/main Sources
Hit http://mirrors.service.networklayer.com precise/restricted Sources
Hit http://mirrors.service.networklayer.com precise/universe Sources
Hit http://mirrors.service.networklayer.com precise/multiverse Sources
Hit http://mirrors.service.networklayer.com precise/main amd64 Packages
Hit http://mirrors.service.networklayer.com precise/restricted amd64 Packages
Hit http://mirrors.service.networklayer.com precise/universe amd64 Packages
Hit http://mirrors.service.networklayer.com precise/multiverse amd64 Packages
Hit http://mirrors.service.networklayer.com precise/main i386 Packages
Hit http://mirrors.service.networklayer.com precise/restricted i386 Packages
Hit http://mirrors.service.networklayer.com precise/universe i386 Packages
Hit http://mirrors.service.networklayer.com precise/multiverse i386 Packages
Hit http://mirrors.service.networklayer.com precise/main TranslationIndex
Hit http://mirrors.service.networklayer.com precise/multiverse TranslationIndex
Hit http://mirrors.service.networklayer.com precise/restricted TranslationIndex
Hit http://mirrors.service.networklayer.com precise/universe TranslationIndex
Hit http://mirrors.service.networklayer.com precise-updates/main Sources
Hit http://mirrors.service.networklayer.com precise-updates/restricted Sources
Hit http://mirrors.service.networklayer.com precise-updates/universe Sources
Hit http://mirrors.service.networklayer.com precise-updates/multiverse Sources
Hit http://mirrors.service.networklayer.com precise-updates/main amd64 Packages
Hit http://mirrors.service.networklayer.com precise-updates/restricted amd64 Packages
Hit http://mirrors.service.networklayer.com precise-updates/universe amd64 Packages
Hit http://mirrors.service.networklayer.com precise-updates/multiverse amd64 Packages
Hit http://mirrors.service.networklayer.com precise-updates/main i386 Packages
Hit http://mirrors.service.networklayer.com precise-updates/restricted i386 Packages
Hit http://mirrors.service.networklayer.com precise-updates/universe i386 Packages
Hit http://mirrors.service.networklayer.com precise-updates/multiverse i386 Packages
Hit http://mirrors.service.networklayer.com precise-updates/main TranslationIndex
Hit http://mirrors.service.networklayer.com precise-updates/multiverse TranslationIndex
Hit http://mirrors.service.networklayer.com precise-updates/restricted TranslationIndex
Hit http://mirrors.service.networklayer.com precise-updates/universe TranslationIndex
Hit http://mirrors.service.networklayer.com precise-security/main Sources
Hit http://mirrors.service.networklayer.com precise-security/restricted Sources
Hit http://mirrors.service.networklayer.com precise-security/universe Sources
Hit http://mirrors.service.networklayer.com precise-security/multiverse Sources
Hit http://mirrors.service.networklayer.com precise-security/main amd64 Packages
Hit http://mirrors.service.networklayer.com precise-security/restricted amd64 Packages
Hit http://mirrors.service.networklayer.com precise-security/universe amd64 Packages
Hit http://mirrors.service.networklayer.com precise-security/multiverse amd64 Packages
Hit http://mirrors.service.networklayer.com precise-security/main i386 Packages
Hit http://mirrors.service.networklayer.com precise-security/restricted i386 Packages
Hit http://mirrors.service.networklayer.com precise-security/universe i386 Packages
Hit http://mirrors.service.networklayer.com precise-security/multiverse i386 Packages
Hit http://mirrors.service.networklayer.com precise-security/main TranslationIndex
Hit http://mirrors.service.networklayer.com precise-security/multiverse TranslationIndex
Hit http://mirrors.service.networklayer.com precise-security/restricted TranslationIndex
Hit http://mirrors.service.networklayer.com precise-security/universe TranslationIndex
Hit http://mirrors.service.networklayer.com precise/main Translation-en
Hit http://mirrors.service.networklayer.com precise/multiverse Translation-en
Hit http://mirrors.service.networklayer.com precise/restricted Translation-en
Hit http://mirrors.service.networklayer.com precise/universe Translation-en
Hit http://mirrors.service.networklayer.com precise-updates/main Translation-en
Hit http://mirrors.service.networklayer.com precise-updates/multiverse Translation-en
Hit http://mirrors.service.networklayer.com precise-updates/restricted Translation-en
Hit http://mirrors.service.networklayer.com precise-updates/universe Translation-en
Hit http://mirrors.service.networklayer.com precise-security/main Translation-en
Hit http://mirrors.service.networklayer.com precise-security/multiverse Translation-en
Hit http://mirrors.service.networklayer.com precise-security/restricted Translation-en
Hit http://mirrors.service.networklayer.com precise-security/universe Translation-en
Ign http://get.docker.io docker Release.gpg
Ign http://get.docker.io docker Release
Hit https://packagecloud.io trusty Release.gpg
Hit https://packagecloud.io trusty Release
Hit https://packagecloud.io trusty/main amd64 Packages
Hit https://packagecloud.io trusty/main i386 Packages
Ign https://packagecloud.io trusty/main TranslationIndex
Get:1 https://packagecloud.io trusty/main Translation-en_US [162 B]
Ign http://get.docker.io docker/main TranslationIndex
Ign https://packagecloud.io trusty/main Translation-en_US
Ign https://packagecloud.io trusty/main Translation-en
Err http://get.docker.io docker/main amd64 Packages
  Undetermined Error [IP: 52.1.30.230 80]
Err http://get.docker.io docker/main i386 Packages
  Undetermined Error [IP: 52.1.30.230 80]
Ign http://get.docker.io docker/main Translation-en_US
Ign http://get.docker.io docker/main Translation-en
W: Failed to fetch http://get.docker.io/ubuntu/dists/docker/main/binary-amd64/Packages  Undetermined Error [IP: 52.1.30.230 80]

W: Failed to fetch http://get.docker.io/ubuntu/dists/docker/main/binary-i386/Packages  Undetermined Error [IP: 52.1.30.230 80]

E: Some index files failed to download. They have been ignored, or old ones used instead.

Any Solution?

**Comment by josegonzalez** [comment]
@theccc Dokku is only installable on 64-bit Trusty. You should upgrade to a VM that has those specs.

Unrelated, I changed from http to https docker repositories.
