### ISSUE TITLE
VHOST is used for apps even when 'Use virtualhost naming for apps' is left unchecked on the post install web config page

### ISSUE THREAD

**Issue by egoddard** [progrium/dokku#1403]
dokku version 0.3.25, buildstep 0.0.2 installed on ubuntu via apt. hostname is set with a subdomain like subdomain.example.edu.

After installing dokku and completing the install through the web interface, I left the 'use virtualhost naming for apps' checkbox unchecked so that new apps will be assigned a port. After the app is pushed, it displays:
```
=====> Application deployed:
       http://app.subdomain.example.edu
```
which is unreachable. As was mentioned in Issue #879, manually setting the NO_VHOSTS config option fixed the app's url. I think the NO_VHOSTS option should be set on deploy if the use virtualhost naming for apps is set to false.

**Comment by michaelshobbs** [comment]
Yeah I thought this was the case already. What ended up in `/home/dokku/HOSTNAME` and `/home/dokku/VHOST` after you ran the installer?

**Comment by egoddard** [comment]
They both contain subdomain.example.edu.

**Comment by josegonzalez** [comment]
Weird, sounds like an odd bug. Are you able to reproduce this at all?

**Comment by michaelshobbs** [comment]
@egoddard Interested to know if this is still an issue in `0.4.x`

**Comment by egoddard** [comment]
I'm not sure, I'm using VHOSTS file since we have our subdomain configured now.

**Comment by michaelshobbs** [comment]
ok. closing for now as I know `urls` was changed in `0.4.x`.
