### ISSUE TITLE
logs -t over ssh

### ISSUE THREAD

**Issue by digitalsadhu** [progrium/dokku#1404]
Hey guys, I am the maintainer of the npm module dokku-toolbelt https://github.com/digitalsadhu/dokku-toolbelt 

I'm having issues with running `logs -t` over ssh
the output from tailing is not really working for me. Has anyone else seen this or know why this might be?

Or if theres anything that can be done about it?

The command i'm running looks like: `ssh -T dokku@dokku.me -- logs <app> -t` 

And the result is that the logs are first tailed, then when logs come in, the cursor writes and rewrites some of the log data. So it is doing something, its just not quite right. I'm having no issues if I first ssh onto the server and then run `dokku logs <app> -t` its just over ssh that seems to be the issue.

thanks.

EDIT: Changed 'then when errors come in' to 'then when logs come in'

**Comment by josegonzalez** [comment]
What do you mean by "then when errors come in"?

**Comment by digitalsadhu** [comment]
oh sorry, i just meant log entries. In my case I was hitting a bad url which was crashing the process and restarting the server and generating log entries for me

**Comment by digitalsadhu** [comment]
Hmm, looking further. I think I might be seeing a slightly glitchy (but mostly working) stdout only without stderr. Does dokku logs produce a blending of logs from stdout and stderr? Could running the command through ssh be only showing the following of stdout maybe?

**Comment by josegonzalez** [comment]
It's just calling `docker logs` for [every container](https://github.com/progrium/dokku/blob/master/plugins/00_dokku-standard/commands#L135).

**Comment by josegonzalez** [comment]
@digitalsadhu Were you able to figure out what was going on? Perhaps your ssh connection is being reset?

**Comment by josegonzalez** [comment]
@digitalsadhu bump :)

**Comment by digitalsadhu** [comment]
Hey man, sorry for the delay. Got swamped and lost track of things.
So I refactored things a bit and the current version is now working. I suspect the issue was that I was expecting to see more in the log stream than there actually was. I have just tested again to make sure now and I'm definitely seeing node process errors being logged correctly with -t
I'll close out the issue. Thanks!
