### ISSUE TITLE
Domains automatically added after enabling SSL

### ISSUE THREAD

**Issue by olalonde** [progrium/dokku#1405]
Is there any way to disable this feature? I have two dokku apps which share the same multi domain SSL certificate though they are both distinct apps. Right now, if I add the SSL certificate to any app, it always automatically adds the main domain of the certificate which is not what I want.

**Comment by josegonzalez** [comment]
At the moment, I believe the only fix is to create a custom nginx configuration for your application.

Note, I *think* this is a duplicate of #1368. The solution to that should also solve this I think.

**Comment by olalonde** [comment]
Yep, seems like a duplicate. I created a custom nginx config for the moment.
