### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by cphubs** [progrium/dokku#1406]
I try to install dokku v0.3.25 with bootstrap.sh on vultr.com and this error occured:

Get:17 https://packagecloud.io trusty/main Translation-en_US
Ign https://packagecloud.io trusty/main Translation-en_US
Ign https://packagecloud.io trusty/main Translation-en
Fetched 3,304 kB in 5s (628 kB/s)
Reading package lists... Done
curl: (28) Operation timed out after 0 milliseconds with 0 out of 0 bytes received
gpg: no valid OpenPGP data found.

**Comment by josegonzalez** [comment]
Sounds like your call to get the gpg data failed. You more or less want to run the following:

http://progrium.viewdocs.io/dokku/getting-started/install/debian/

**Comment by cphubs** [comment]
same error occured again

**Comment by josegonzalez** [comment]
At what step?

**Comment by cphubs** [comment]
curl -sL https://get.docker.io/gpg 2> /dev/null | sudo apt-key add - 2>&1 >/dev/null
gpg: no valid OpenPGP data found.

**Comment by josegonzalez** [comment]
Remove thepiping to dev/null. Sounds like you are having network issues on your vps.

**Comment by cphubs** [comment]
I install dokku on fresh ubuntu 14.04 x64 - Vultr.com
two days ago everything work prefect and i install dokku - i think Vultr.com change ubuntu image. for example remove nginx from this image. i install it

**Comment by michaelshobbs** [comment]
@cphubs I think the point here is to see what error you're getting from the curl command. Give it a shot and let us know.

**Comment by cphubs** [comment]
I change Location from London to Sydney on Vultr.com and then can install dokku.

**Comment by josegonzalez** [comment]
Sounds like an issue with vultr networking, so closing this for now.
