### ISSUE TITLE
Documentation missing/inaccurate for DOKKU_SCALE and CHECKS files

### ISSUE THREAD

**Issue by m-z-b** [progrium/dokku#1409]
1. The documentation references a **DOKKU_SCALE** file, but does not says where to put it: code comments elsewhere suggest it should in fact be called **SCALE** and placed in the app directory relative to the git root. 

2. The documentation also references a **CHECKS** file, but does not say where to put it. Stackoverflow answers suggest it should be placed in the app directory relative to the git root.

**Comment by josegonzalez** [comment]
1. Fixed via #1410. Note, the file is most certainly called `DOKKU_SCALE`. I checked myself :)
2. The documentation states to place the `CHECKS` file in the root of the directory [here](http://progrium.viewdocs.io/dokku/application-deployment/).

**Comment by m-z-b** [comment]
Awesomely quick fix... thanks.  

Might also be worth mentioning that the DOKKU_SCALE file doesn't support comments.

**Comment by michaelshobbs** [comment]
This can be fixed. I'll get a patch going.
