### ISSUE TITLE
ps:scale command is invalid

### ISSUE THREAD

**Issue by chrisjhoughton** [progrium/dokku#1424]
Hi team, just trying to use the command `dokku ps:scale` to scale one of our apps, but I'm getting the following message:

```
`ps:scale tracker-pipeline worker=2` is not a dokku command.
```

When typing `dokku help`, I noticed that the `ps:scale` command isn't there:

```
ps <app>              List processes running in app container(s)
ps:rebuildall         Rebuild all apps
ps:rebuild <app>      Rebuild an app
ps:restartall         Restart all deployed app containers
ps:restart <app>      Restart app container(s)
ps:start <app>        Start app container(s)
ps:stop <app>         Stop app container(s)
```

Feels like I'm missing something stupid?

**Comment by josegonzalez** [comment]
What version of dokku are you running?

**Comment by chrisjhoughton** [comment]
0.3.18

**Comment by josegonzalez** [comment]
You may need to upgrade, scaling was introduced in 0.3.19 and the current version is 0.3.26.

**Comment by chrisjhoughton** [comment]
Gotcha, thanks
