### ISSUE TITLE
Fetch Custom Buildpack Failing

### ISSUE THREAD

**Issue by hhff** [progrium/dokku#1433]
Hi All!

Just started a new fresh Dokku VM.  Attempting to deploy a static site via [Nginx Static Buildpack](https://github.com/florianheinemann/buildpack-nginx).

[Seems to be hitting a hard stop here](https://gist.github.com/hhff/fe990d2be528c3a07ce4#file-gistfile1-txt-L858).  I have no idea how to read this trace, but maybe someone can see what's wrong?

This was working super nice on an old Dokku VM I had.  Unsure what has changed?

**Comment by josegonzalez** [comment]
How are you setting the custom buildpack?

**Comment by hhff** [comment]
thanks @josegonzalez ! 

setting it with `.env` at the project root, as per the README above

**Comment by josegonzalez** [comment]
Can you set it via the `BUILDPACK_URL` env var instead? Something like:

```
dokku config:set BUILDPACK_URL=https://github.com/florianheinemann/buildpack-nginx.git
```

**Comment by hhff** [comment]
Same issue:

```
-----> Cleaning up...
-----> Building test-static-buildpack from herokuish...
-----> Adding BUILD_ENV to build environment...
-----> Fetching custom buildpack
To dokku@sanctuarycomputer.link:test-static-buildpack
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'dokku@sanctuarycomputer.link:test-static-buildpack
```

**Comment by josegonzalez** [comment]
How long does it take for that to bail out? If it takes a while, might be that it's timing out on the curl call?

**Comment by hhff** [comment]
pretty much as soon as it hits `-----> Fetching custom buildpack` it dies.  less than a second, id say

**Comment by proitm** [comment]
Plus one to this issue.
Here are logs:
```
Counting objects: 65, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (61/61), done.
Writing objects: 100% (65/65), 684.90 KiB | 0 bytes/s, done.
Total 65 (delta 16), reused 0 (delta 0)
-----> Cleaning up...
-----> Building personal from herokuish...
-----> Adding BUILD_ENV to build environment...
-----> Fetching custom buildpack
To dokku@proitm.pro:personal
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'dokku@proitm.pro:personal'
```

Here is .env:
```
export BUILDPACK_URL=https://github.com/yabawock/buildpack-nginx
```

**Comment by proitm** [comment]
I have fixed my problem by changing the buildpack to https://github.com/florianheinemann/buildpack-nginx. This might be helpful for people who search a fast solution. But the question, why my previous buildpack has been failing, is still open.

**Comment by michaelshobbs** [comment]
FWIW, we use `https://github.com/yabawock/buildpack-nginx` in our static app test

**Comment by josegonzalez** [comment]
Seems like the issue cropped up again on irc. Not sure why custom buildpacks for nginx would fail...

**Comment by michaelshobbs** [comment]
@hhff the nginx static buildpacks all seem to require a `.static` file in the root of the repo. it will fail in this way if that's not the case.

**Comment by hhff** [comment]
yup - I'm using `.static`, and tried bother yabawock & florian's versions.

**Comment by michaelshobbs** [comment]
@hhff can you try this on the latest dokku (0.3.26) and adding TRACE=true to the build phase.
```
dokku docker-options:add $APP build "-e TRACE=true"
```
deploy again and let's see what the output is.

**Comment by josegonzalez** [comment]
@hhff bump

**Comment by hhff** [comment]
been traveling the last few days!  haven't forgotten about this - will hopefully have a chance on the weekend

**Comment by hhff** [comment]
OK!  Trace is here
https://gist.github.com/hhff/4fb1085d533250fba101

Action starts around here: https://gist.github.com/hhff/4fb1085d533250fba101#file-gistfile1-txt-L96

Hope this helps guys!

**Comment by michaelshobbs** [comment]
`detect` fails on line 915. Have a look at the buildpack and see what detect tries to do.

**Comment by josegonzalez** [comment]
@hhff any luck?

**Comment by josegonzalez** [comment]
*bump*

**Comment by josegonzalez** [comment]
Closing, I think it's just the custom buildpack's detect method doesn't work for your repo, so fixing the detect method will fix your deploys :)

**Comment by hhff** [comment]
ahh sorry guys - I moved off Dokku for this particular project :heart: will let you know how it goes in the future.  Would love if Dokku had an official static site Buildpack!

**Comment by josegonzalez** [comment]
This is the one we use in tests: https://github.com/yabawock/buildpack-nginx

Probably would help if we added this to herokuish. @michaelshobbs thoughts?

**Comment by hhff** [comment]
:+1: that would be gnarly, i would use dokku for erryting in that case

**Comment by michaelshobbs** [comment]
Yeah why not? :shrug:

**Comment by hhff** [comment]
Added an issue over there https://github.com/gliderlabs/herokuish/issues/79

**Comment by greyrain** [comment]
I had same problem with custom heroku buildpack. After `dokku ps:restart` the trouble was fixed. Amazing magic.
