### ISSUE TITLE
Dokku cannot find 'webpack' (pre-receive hook declined)

### ISSUE THREAD

**Issue by Serfenia** [progrium/dokku#1434]
I have an issue with pushing an application that uses webpack to dokku. Webpack itself is located in the devDependencies of the package.json.

Once pushed it starts installing node_modules. But once it starts to execute the 'postinstall' script it says the following:
```
sh: 1: webpack: not found

npm ERR! Linux 3.16.0-30-generic
npm ERR! argv "/tmp/build/.heroku/node/bin/node" "/tmp/build/.heroku/node/bin/npm" "install" "--quiet" "--userconfig" "/tmp/build/.npmrc"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! profortool-app@0.2.0 postinstall: `webpack`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the profortool-app@0.2.0 postinstall script 'webpack'.
npm ERR! This is most likely a problem with the profortool-app package,
npm ERR! not with npm itself.
```
Things I tried:

Use a bash script to install webpack globally first and then execute webpack.
Put webpack in the 'dependencies' instead of 'devDependencies'
Try to execute webpack locally within the dokku app.
None of these things worked out. Does anyone have an idea how to fix this?

My package.json:
```
{
  "name": "some-app",
  "description": "some app",
  "author": "<Author>",
  "version": "0.2.0",
  "engines": {
    "node": "0.12.7"
  },
  "scripts": {
    "build": "webpack",
    "serve": "http-server -p 8080 build/",
    "serve:dev": "webpack-dev-server --hot --inline --progress --colors --port 8080 --content-base ./build",
    "serve:backend": "nodemon --harmony server/app.js",
    "test": "mocha --compilers js:6to5/register --require should",
    "postinstall": "webpack"
  },
  "dependencies": {
    "bluebird": "^2.9.34",
    "bootstrap": "^3.3.5",
    "chalk": "^1.1.0",
    "connect": "^3.4.0",
    "debug": "^2.2.0",
    "faker": "^3.0.0",
    "http-server": "^0.8.0",
    "invariant": "^2.1.0",
    "jquery": "^2.1.4",
    "lodash": "^3.10.0",
    "material-ui": "^0.11.0",
    "react": "^0.13.3",
    "react-router": "^0.13.3",
    "socket.io": "^1.3.6",
    "socket.io-client": "^1.3.6",
    "superagent": "^1.3.0"
  },
  "devDependencies": {
    "autoprefixer": "^5.2.0",
    "autoprefixer-core": "^5.2.1",
    "babel-core": "^5.8.22",
    "babel-loader": "^5.3.2",
    "css-loader": "^0.16.0",
    "expose-loader": "^0.7.0",
    "extract-text-webpack-plugin": "^0.8.2",
    "file-loader": "^0.8.4",
    "html-loader": "^0.3.0",
    "html-webpack-plugin": "^1.6.1",
    "json-loader": "^0.5.2",
    "less": "^2.5.1",
    "less-loader": "^2.2.0",
    "mocha": "^2.2.5",
    "postcss-loader": "^0.5.1",
    "react-hot-loader": "^1.1.0",
    "should": "^7.0.3",
    "style-loader": "^0.12.3",
    "url-loader": "^0.5.6",
    "webpack": "^1.11.0",
    "webpack-dev-server": "^1.10.1"
  }
}
```

Regards, Patrick van Vuuren

**Comment by josegonzalez** [comment]
Does this code work on heroku?

**Comment by Serfenia** [comment]
@josegonzalez Haven't tested that yet. Does heroku give more information about what's going on relative to Dokku?

**Comment by josegonzalez** [comment]
No. My suggestion is such that if it works on heroku, then its something that may be a bug here or in herokuish (what we use for buildpacks). If it doesn't work on heroku, then maybe its the way you are specifying the binary.

**Comment by Serfenia** [comment]
I have googled about the same issue in heroku, and found [this article](http://forum.railsonmaui.com/t/notes-on-deploying-to-heroku-with-gsl-and-node/89/5). I also found [dokku-multi-build](https://github.com/pauldub/dokku-multi-buildpack) to use. I don't use GSL but this may fix it?

@josegonzalez Dont you have experience with webpack not being found? I currently execute webpack in postinstall as a global script, do I have to refer to `./node_modules/.bin/webpack` so it uses the locally installed dependency?

**Comment by josegonzalez** [comment]
> I hate node with a passion, and try not to use it.

It seems like maybe `$PATH` isn't set to what it should be whenever you are calling webpack? @michaelshobbs any idea if thats a bug in herokuish?

**Comment by Serfenia** [comment]
@josegonzalez I have solved the issue by placing devDependencies in normal dependencies (probably has something to do with being in production mode on dokku) and I changed the postinstall script to `node_modules/.bin/webpack`.

**Comment by michaelshobbs** [comment]
As I understand it, that is the correct solution here.

**Comment by axelboc** [comment]
The problem comes from NPM running in production mode, and therefore not installing any of the `devDependencies`. On Heroku, this can be fixed by adding the following to the config:

```
heroku config:set NPM_CONFIG_PRODUCTION=false
```

**Comment by alfonmga** [comment]
If I'm not wrong, Heroku does a full npm install; includes both the dependencies and devDependencies. It, however, does appear to prune the devDependencies as a last step to save disk space.

Dokku does this also? @josegonzalez 

P.S. I'm sorry for bump this :/

**Comment by josegonzalez** [comment]
Dokku defaults to using Heroku's buildpacks, so we do more or less whatever they do.
