### ISSUE TITLE
Create a CONTRIBUTING.md

### ISSUE THREAD

**Issue by josegonzalez** [progrium/dokku#1435]
@michaelshobbs I think it's time we codify how we merge stuff, decide what goes into a release, how people should contribute etc. Do you have thoughts on what is useful data to provide for bugs? What about the structure of how and why people should ask for features vs things that should go into plugins?

We'll also want to extend this to the official plugins, though some of the rules may be different.

/cc @Flink since you're starting to get back into contributing and might have some thoughts as an outsider.

**Comment by michaelshobbs** [comment]
Bugs (admittedly taken from docker):

Description of problem:

`dokku version`:
`dokku plugins`:
`docker version`:
`docker info`:
`uname -a`:
deploy with DOKKU_TRACE=1:


Environment details (AWS, VirtualBox, physical, etc.):

How reproducible:

Steps to Reproduce:
1.
2.
3.

Actual Results:

Expected Results:

Additional info:

```

**Comment by michaelshobbs** [comment]
I also like docker's contribution tips and guidelines: https://github.com/docker/docker/blob/master/CONTRIBUTING.md#quick-contribution-tips-and-guidelines

**Comment by Flink** [comment]
Everything in their CONTRIBUTING file seems quite interesting. Convention, coding style, writing tests, using git correctly to have good PR and history (rebase), etc. We should definitely have something like this IMO :)

**Comment by josegonzalez** [comment]
Closing as there is a PR open.
