### ISSUE TITLE
Problem with rails public folder

### ISSUE THREAD

**Issue by khirul** [progrium/dokku#1436]
I deploy my app using dokku digitalocean droplet. Everything work fine except access to public folder. Im using bootsy editor that allow me to upload picture to public folder.. but server refuse to write the image.. there is any solution to make public folder accessible?

**Comment by josegonzalez** [comment]
This sounds like an app-level permissions issue. Without more info on what error is occurring, we can't really debug the problem.

**Comment by khirul** [comment]
i put all my pdf file in public folder and allow user to upload image/avatar to public folder.. everything work in my local server.. when i deploy to digital ocean, all link to file in public folder give me error. Image upload function also didn't work. Image didnt save.. same problem in heroku

**Comment by josegonzalez** [comment]
What "error" are you getting? Not saving can mean a bunch of things.

Note: I think this is application-related, and you should probably use something like paperclip to upload those files to s3.

**Comment by josegonzalez** [comment]
Closing as there hasn't been a response in 2+ weeks. Feel free to comment if you have any updates.
