### ISSUE TITLE
Custom nginx.conf.template is not used

### ISSUE THREAD

**Issue by sbrosinski** [progrium/dokku#1441]
The documentation states that I can put a nginx.conf.template in my app root. 
Dokku doesn't seem to use it. When I check /home/dokku/myapp on the server it always ends up with the default nginx.conf, but not mine.

I tried to validate my nginx conf with `nginx -t -c nginx.conf.template`, which can't succeed because of the undefined template variables.

My nginx.conf.template looks like this:

````
server {
  listen      [::]:80;
  listen      80;
  server_name $NOSSL_SERVER_NAME;
  access_log  /var/log/nginx/${APP}-access.log;
  error_log   /var/log/nginx/${APP}-error.log;



  location {
    add_header X-Served-By Stephan;

    gzip on;
    gzip_min_length  1100;
    gzip_buffers  4 32k;
    gzip_types    text/css text/javascript text/xml text/plain text/x-component application/javascript application/x-javascript application/json application/xml  application/rss+xml font/truetype application/x-font-ttf font/opentype application/vnd.ms-fontobject image/svg+xml;
    gzip_vary on;
    gzip_comp_level  6;

    proxy_pass  http://$APP;
    proxy_http_version 1.1;
    proxy_set_header Upgrade \$http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host \$http_host;
    proxy_set_header X-Forwarded-Proto \$scheme;
    proxy_set_header X-Forwarded-For \$remote_addr;
    proxy_set_header X-Forwarded-Port \$server_port;
    proxy_set_header X-Request-Start \$msec;
  }
  include $DOKKU_ROOT/$APP/nginx.conf.d/*.conf;
}
```

**Comment by sbrosinski** [comment]
Right, it is. Here is the trace:
https://gist.github.com/sbrosinski/f343fc805ef7a9789eda

**Comment by josegonzalez** [comment]
What version of dokku are you using? This feature was introduced in `0.3.22`. Can you run `dokku version` and let me know?

**Comment by sbrosinski** [comment]
A shoot, I'm on v0.3.19. I'll set up another instance with v0.3.26 and test again. Thank you.
