### ISSUE TITLE
Error during WebSocket handshake: Unexpected response code: 502

### ISSUE THREAD

**Issue by olalonde** [progrium/dokku#1443]
Getting this error when trying to connect to a secure websocket with `wss://chatws.mydomain.com` but it works fine with `ws://chatws.mydomain.com`. Https is correctly configured for the app. I assume this is an issue with Nginx configuration? `dokku logs someapp` indicates that nginx never actually forwards the request to my app when using the `wss` scheme.

```bash
root@d:~# nginx -v
nginx version: nginx/1.8.0
root@d:~# dokku version
v0.3.18
root@d:/home/dokku/chatws# cat nginx.conf
server {
  listen      [::]:80;
  listen      80;
  server_name chatws.mydomain.com ;
  location    / {
    proxy_pass  http://chatws;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection upgrade;
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header X-Request-Start $msec;
  }
  include /home/dokku/chatws/nginx.conf.d/*.conf;
}
upstream chatws { server 172.17.1.42:5000; }
```

**Comment by josegonzalez** [comment]
That nginx conf doesn't appear to have ssl support, so secure web sockets wouldn't work.

**Comment by josegonzalez** [comment]
[Here](https://github.com/nicokaiser/nginx-websocket-proxy/blob/master/simple-wss.conf) is an example configuration that works.

**Comment by josegonzalez** [comment]
@olalonde any luck getting ^ to work?

**Comment by olalonde** [comment]
Yes thanks I had indeed forgotten to setup ssl for some reason.
