### ISSUE TITLE
build process crashed on step curl .... http://nodejs.org/dist/v0.10.30/node-v0.10.30-linux-x64.tar.gz

### ISSUE THREAD

**Issue by edit** [progrium/dokku#1454]
I have in the build process the error:

        !     Command: 'set -o pipefail; curl --fail --retry 3 --retry-delay 1 --connect-timeout 30 --max-time 900 http://nodejs.org/dist/v0.10.30/node-v0.10.30-linux-x64.tar.gz -s -o - | tar zxf - node-v0.10.30-linux-x64/bin/node' failed unexpectedly:
       !
       !     gzip: stdin: not in gzip format
       !     tar: Child returned status 1
       !     tar: Error is not recoverable: exiting now

It looks, that nodejs.org has move the url http://nodejs.org/dist/v0.10.30/node-v0.10.30-linux-x64.tar.gz it  to https.

**Comment by rgarner** [comment]
Yep, w/dokku 0.3.16 on DigitalOcean suddenly I can't deploy anything either :)

**Comment by rgarner** [comment]
At this stage an [upgrade](https://github.com/progrium/dokku/blob/master/docs/upgrading.md) (to v0.3.26-121-gc4766b7, from source) has fixed the issue. Resulted in some downtime, but all good now.

**Comment by michaelshobbs** [comment]
I wonder if alternatively using a newer version of the nodejs buildpack would have solved this.

**Comment by rgarner** [comment]
@michaelshobbs This was the rails buildpack. It seemed to have a hard-coded dependency on a node download.

**Comment by michaelshobbs** [comment]
Ah man. That buildpack had been very problematic. Closing as it seems we have a resolution.
