### ISSUE TITLE
Proposal to make those plugins official ones

### ISSUE THREAD

**Issue by Flink** [progrium/dokku#1483]
Since we want to “emulate” Heroku as best as possible, I think those plugins I made could become official ones:

* [dokku-maintenance](https://github.com/Flink/dokku-maintenance) mimics maintenance mode on heroku. You can also set a custom maintenance page.
* [dokku-named-containers](https://github.com/Flink/dokku-named-containers) will name your containers like this: app.web.1, app.worker.2, etc. So when using Papertrail for example, those names will appear in the aggregated logs as seen on Heroku.
* [dokku-colored-logs](https://github.com/Flink/dokku-colored-logs) will display logs with color, container names and with a format which mimics the one on Heroku (not exactly the same though).

Also [dokku-http-auth](https://github.com/Flink/dokku-http-auth) could be useful even if Heroku does not provide commands to enable HTTP auth on your app.

@josegonzalez @michaelshobbs  Thoughts? :)

**Comment by josegonzalez** [comment]
- `dokku-maintenance`: This one seems like a good candidate for an official plugin. I'm :+1: if you want to initiate a transfer.
- `dokku-named-containers`: Any reason why this can't just be the default? It sounds useful in the general case. My only concern is `Dockerfile` deploy support.
- `dokku-colored-logs`: Nice. Would this break on any specific type of shell? We should move the `logs` command to it's own plugin in the core, and then add this as an argument - `--color` perhaps? - at worst, and at best it's own command.
- `dokku-http-auth`: A feature that people have asked for in the past, and I think your implementation is pretty good. :+1: initiate the transfer.

@michaelshobbs thoughts on his proposals?

**Comment by josegonzalez** [comment]
@Flink one other thought I had as I was making PRs to community plugins: Can you go through them and look for other plugins that make good candidates for official status (core or otherwise)?

**Comment by Flink** [comment]
* `dokku-maintenance`: on its way!
* `dokku-named-containers`: No, no reason in particular I think :) I didn’t have any problem with `Dockerfile` containers.
* `dokku-colored-logs`: I didn’t test on every shell but I don’t think there’s a problem. Color codes are ANSI ones like everywhere else :) This could also become the default `logs` command, we’ll have nice logs like with the `heroku` command.
* `dokku-http-auth`: Ok!

@josegonzalez no problem, I’ll do that ;)

**Comment by Flink** [comment]
@josegonzalez hmmm can’t transfer the repos to the `dokku` org since I don’t have any admin permissions it says :/ I added you as a collaborator on one of the repo but I don’t think you could transfer. Do you know how to proceed?

**Comment by josegonzalez** [comment]
Fixed. Try and transfer it now.

**Comment by Flink** [comment]
Thanks and done!

**Comment by michaelshobbs** [comment]
@josegonzalez :+1: on your comments.

**Comment by josegonzalez** [comment]
@Flink feel free to make PRs for the other issues.

**Comment by Flink** [comment]
Will do ;)
