### ISSUE TITLE
dokku plugin:install-dependencies --core fails with "hook: command not found" error

### ISSUE THREAD

**Issue by vijayviji** [progrium/dokku#1487]
I'm using windows 10 machine. I synced the git repo@v0.4.0 and when did "vagrant up", it ran many things (including creating VM and installing dokku).

When it reaches  the step "dokku plugin:install-dependencies --core", it fails

==> dokku: /var/lib/dokku/core-plugins/enabled/20_events/dependencies: line 1: hook: command not found
==> dokku: make:
==> dokku: *** [plugin-dependencies] Error 127

And so, the entire installation was getting cancelled. Inside "/var/lib/dokku/core-plugins/enabled/20_events/dependencies" file, it has only "hook" word in it.

*Root Cause:*
This is because, the symlink files don't work in Windows. Basically, "/var/lib/dokku/core-plugins/enabled/20_events/dependencies" is a symlink to "/var/lib/dokku/core-plugins/enabled/20_events/hook". But in windows, git creates a file for symlink and makes the content of the file to be the filename of the symlink.

As vagrant exports the directory to the VM and tries to install from it, all the problems were happening.

**Comment by vijayviji** [comment]
Check out http://stackoverflow.com/questions/5917249/git-symlinks-in-windows

**Comment by josegonzalez** [comment]
This one is a weird issue, since dokku is meant to work on linux and we've never tested a vagrant vm from linux. The *easiest* fix is to just copy the hook into each file. 

Note that this *also* affects other official plugins that use the same symlinking pattern. Not sure what we're going to decide to do here...

**Comment by vijayviji** [comment]
I'm not sure how to solve this for contributors.

But for users, there are two solutions to this. When creating the VM through vagrant, instead of sharing the folder from host to guest, we can sync the git repo again from guest OS and start a fresh install. Other is to create a basic Ubuntu VM and run the "installation" script which does the same thing through inline script.

As no contributor is using vagrant (for virtual box) and that too from windows, I think we can follow this.

**Comment by josegonzalez** [comment]
I use vagrant to contribute to dokku exclusively (other than testing deb packages on a live site and other experiments).

Starting fresh seems like a bad idea since then people will be confused as to why their changes aren't synced into the vm.

**Comment by vijayviji** [comment]
Then we need to create two vm environment in Vagrantfile, one for contributing (dev) and another for production (or users).

https://docs.vagrantup.com/v2/multi-machine/index.html

**Comment by josegonzalez** [comment]
Sure, do you want to come up with a pr for this?

**Comment by michaelshobbs** [comment]
We now have a windows "profile" for vagrant. Do we think that's good enough to close this issue?
