### ISSUE TITLE
bootstrap.sh prompts users, doesn't work unattended

### ISSUE THREAD

**Issue by callahad** [progrium/dokku#1495]
When bootstrap.sh [installs the dokku package](https://github.com/progrium/dokku/blob/v0.4.0/bootstrap.sh#L57-L61), it doesn't pass `-y` to `apt-get install`, so the user has to interactively confirm the installation:

```bash
if [[ -n $DOKKU_CHECKOUT ]]; then
  apt-get install dokku=$DOKKU_CHECKOUT
else
  apt-get install dokku
fi
```

Is this intended?

**Comment by callahad** [comment]
Looks like this is a regression from https://github.com/progrium/dokku/commit/1e479c63bd15c62c916f8803fb055e95b25480d1#diff-3af436e6760a0c5f1e3d16a3384853a8 two weeks ago.

**Comment by michaelshobbs** [comment]
merged. thanks for the PR!
