### ISSUE TITLE
wishlist: plugin to automatically obtain SSL certs from LetsEncrypt

### ISSUE THREAD

**Issue by callahad** [progrium/dokku#1497]
In just under two months, LetsEncrypt.org will begin offering free domain validation certs via its [ACME protocol](https://letsencrypt.org/howitworks/technology/). Since this should work unattended, it'd be really great if someone could put together a plugin that automatically obtains certs for deployed apps.

They won't be issuing wildcard certs, so each app will have to acquire its own cert, even in the vhost scheme.

**Comment by josegonzalez** [comment]
Yep, would be nice as a plugin. I don't think the functionality should be in the core, but if it gets created, we could probably adopt it as an official plugin in the same vein as the ones listed [here](https://github.com/dokku).

Closing as there isn't anything actionable at the moment.

**Comment by sgulseth** [comment]
This is my first dokku-plugin, but I made a small plugin to fetch letsencrypt certificates. https://github.com/sgulseth/dokku-letsencrypt
As of now it requires you to manually stop nginx/apache/(whatever running on port 80 and 443), but I think it should be possible for this plugin to stop and start the nginx process. Its only be tested on ubuntu. Feel free to create issues and/or send PRs!

**Comment by sseemayer** [comment]
I've gone a bit further with a plugin that gets around the starting/stopping of nginx by temporarily adding a reverse proxy to the letsencrypt standalone webserver: 

https://github.com/sseemayer/dokku-letsencrypt

**Comment by m-vdb** [comment]
I gotta say @sseemayer everything worked perfectly! thanks for sharing :)

**Comment by sgulseth** [comment]
Nice. Sorry for the late reply, I've been busy the last weeks. I'll update my repo as deprecated with a link to your plugin when I get home from the holidays.

**Comment by sseemayer** [comment]
Thanks @sgulseth for making the first step into getting this to work in the first place! I'd be happy for your input on the plugin.
