### ISSUE TITLE
wrong instructions on v0.4.0 release page

### ISSUE THREAD

**Issue by vincentfretin** [progrium/dokku#1499]
https://github.com/progrium/dokku/releases/tag/v0.4.0 says to install

    wget https://raw.github.com/progrium/dokku/v0.3.26/bootstrap.sh
    sudo DOKKU_TAG=v0.3.26 bash bootstrap.sh

maybe something is wrong here?

**Comment by josegonzalez** [comment]
Fixed, sorry!
