### ISSUE TITLE
dokku plugin:install <git url> is not documented

### ISSUE THREAD

**Issue by jazzzz** [progrium/dokku#1503]
The doc indicates this:

```shell
cd /var/lib/dokku/plugins/available
git clone <git url>
dokku plugin:install
```
whereas 
```shell
dokku plugin:install <git url>
```
should work, but I get this error:

`/var/lib/dokku/plugins/enabled/00_dokku-standard/install: line 16: /etc/init/dokku-redeploy.conf: Permission denied`

It works adding `sudo`, but I'm not sure it should be needed.

**Comment by josegonzalez** [comment]
Well it seems as though `/var/lib/dokku` is owned by root, not the dokku user.

@michaelshobbs what do you think we should do here? `chown` all the things?

**Comment by michaelshobbs** [comment]
@jazzzz the documentation is either in the man page or help.

```
root@dokku:~# dokku help
Usage: dokku [--quiet|--trace|--rm-container|--rm|--force] COMMAND <app> [command-specific-options]

Options:
...
    plugin:disable <name>                                              Disable an installed plugin (third-party only)
    plugin:enable <name>                                               Enable a previously disabled plugin
    plugin:install [--core|git-url]                                    Optionally download git-url & run install trigger for active plugins (or only core ones)
    plugin:install-dependencies [--core]                               Run install-dependencies trigger for active plugins (or only core ones)
    plugin                                                             Print active plugins
    plugin:uninstall <name>                                            Uninstall a plugin (third-party only)
    plugin:update [git-url]                                            Optionally download git-url & run update trigger for active plugins
...
```

@josegonzalez the issue reported here is from this code and will require root. This code and subsequent requirement of root execution has existed for quite some time.  53395bfa08e4edca3442832d91a2ca8c903069c8

https://github.com/progrium/dokku/blob/f8c9d9b8239cf5b20020366ecec2e2c799185718/plugins/00_dokku-standard/install#L16-L26

I don't think there is anything to do but run `plugin:install` as root.

**Comment by jazzzz** [comment]
@michaelshobbs there is a doc there also: https://github.com/progrium/dokku/blob/master/docs/plugins.md#installing-a-plugin

**Comment by michaelshobbs** [comment]
That method works as well.

**Comment by josegonzalez** [comment]
Shouldn't dokku-redeploy not require root? Didn't we add that command to sudoers?

**Comment by michaelshobbs** [comment]
No we did not. `dokku-redeploy` is a service that "starts" on boot to make sure all apps are up when a machine reboots. The creation of the `/etc/init/dokku-redeploy.conf` is absolutely a function for the root user.

```
$ ls -lad /etc/init
drwxr-xr-x 2 root root 4096 Sep 16 21:11 /etc/init
```

**Comment by josegonzalez** [comment]
Okay so I guess the question is whether or not we should be triggering that particular hook on `plugin:install` when you install a specific plugin?

**Comment by michaelshobbs** [comment]
Haha! This hails back to the whole plugin reorganization wrt `core-plugins`. We can't guarantee other plugins won't require `root`. IMO, the easiest implementation is to require `root` for all `plugin:install` executions.

**Comment by josegonzalez** [comment]
Okay, so the the documentation should state that instead of dancing around it ;)

**Comment by michaelshobbs** [comment]
Please propose your changes in #1504 then....
