### ISSUE TITLE
Pushing a new python app with no runtime.txt results in: Requested runtime (python-2.7.10) is not available for this stack (cedar-14).

### ISSUE THREAD

**Issue by darkpixel** [progrium/dokku#1506]
```
19:06:13 [aaron@ender:~/code/myapp] [myapp] master* 1 ± git push production master
Counting objects: 608, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (591/591), done.
Writing objects: 100% (608/608), 83.56 KiB | 0 bytes/s, done.
Total 608 (delta 365), reused 0 (delta 0)
remote: 2015/09/25 22:21:21 open /var/lib/dokku/plugins/available/dokku-deployment-keys/plugin.toml: no such file or directory
-----> Cleaning up...
-----> Building myapp from herokuish...
remote: 2015/09/25 22:21:22 open /var/lib/dokku/plugins/available/dokku-deployment-keys/plugin.toml: no such file or directory
remote: 2015/09/25 22:21:22 open /var/lib/dokku/plugins/available/dokku-deployment-keys/plugin.toml: no such file or directory
-----> Python app detected
-----> Installing runtime (python-2.7.10)
       !     Requested runtime (python-2.7.10) is not available for this stack (cedar-14).
       !     Aborting.  More info: https://devcenter.heroku.com/articles/python-support
To dokku@e1.myapp.net:myapp
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'dokku@e1.myapp.net:myapp'
19:23:46 [aaron@ender:~/code/myapp] [myapp] develop 1 ±
```

The linked heroku article says it supports python-2.7.10.
I tried adding a runtime.txt with python-2.7.10 and I get the same error.

```
root@e1:~#  uname -a
Linux e1.myapp.net 3.13.0-57-generic #95-Ubuntu SMP Fri Jun 19 09:28:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
root@e1:~# docker version
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64
root@e1:~# docker -D info
Containers: 2
Images: 8
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 12
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-57-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 1
Total Memory: 994 MiB
Name: e1.myapp.net
ID: DPBB:XYEL:WTKW:MEUC:DG7O:47OS:TOOL:7Q6G:4YWW:I5UJ:VMKO:LWKV
WARNING: No swap limit support
root@e1:~# dokku version
v0.4.0
root@e1:~# 
```

**Comment by darkpixel** [comment]
Bah!  Outbound firewall.  Disregard.

**Comment by josegonzalez** [comment]
Yayayaya I was in the middle of trying to reproduce this and tearing out my (luxurious) hair.

**Comment by darkpixel** [comment]
I ended up forking the buildpack, turning tracing on, adding a bunch of echo statements, and then facepalmed when I realized the host was managed by puppet and the firewall was blocking the docker interface.  I double-facepalmed when I looked at my commit message for the firewall code on my other server and had run into this about a year ago.

I must be going senile.

**Comment by ivotoman** [comment]
I have the same problem. I went through the page:
https://devcenter.heroku.com/articles/python-support
and I still receive the error:

remote: -----> Python app detected
remote: -----> Installing runtime (python-2.7.10 )
remote:  !     Requested runtime (python-2.7.10 ) is not available for this stack (cedar-14).
remote:  !     Aborting.  More info: https://devcenter.heroku.com/articles/python-support
remote: 
remote:  !     Push rejected, failed to compile Python app
...
To git@heroku.com:wordcounts-ivo-stage.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'git@heroku.com:wordcounts-ivo-stage.git'

I am on a personal laptop running mac os x 10.11. I have not toyed with any default firewall policies. any advice, please?

**Comment by darkpixel** [comment]
Did you ever have a runtime.txt in the project?  If so, go to /home/dokku/youappname and blow away the cache directory.  Try pushing again.

**Comment by ivotoman** [comment]
@darkpixel : thanks a lot. you were right about the .runtime file. I removed the .runtime file, also removed incompatible libraries, committed and everything worked.

**Comment by webknjaz** [comment]
Wow! I've experienced the same error message, but it turned out to be some network issue. When I re-ran the deploy it succeeded.

**Comment by josegonzalez** [comment]
Please don't comment on a two year old issue.
