### ISSUE TITLE
No clue how to get to the web-installer

### ISSUE THREAD

**Issue by bobvanderlinden** [progrium/dokku#1507]
The front-page of Dokku (http://progrium.viewdocs.io/dokku/) still mentions the web-installer. I had no clue how to get to the web-installer, since I only get nginx default webpage when accessing my servers ip. It would be nice if the notes that are in https://github.com/harshjv/dokku/blob/master/docs/installation.md are also mentioned in the front-page, or the notes here http://progrium.viewdocs.io/dokku/getting-started/install/debian/#user-content-unattended-installation. One or both (or a link to those docs) would help out a lot.

**Comment by leonardodino** [comment]
I agree it should be somewhere in the docs, not sure where. I encountered the same situation in one of my installations. Fortunately the makefile is easy to read.

it should be enough cd'ing to the root of the repository and running a command, when installed from source
for future records: 
```shell
$ cd /root/dokku/
$ sudo make dokku-installer
```

not sure about when installed via APT, maybe cloning the project _on the server_ and running the command should be ok.

**Comment by josegonzalez** [comment]
I *think* 0.4.1 fixed this regression. I'm afk but if someone wants to confirm, I'll dedicate my next beer to them.

**Comment by callahad** [comment]
AFAICT, the current homepage is good here. It explicitly states "Go to your server's IP and follow the web installer", and the installation doc has similar: "By default, this will start the web-based installer on your server's IP"

:shipit:

**Comment by bobvanderlinden** [comment]
Reinstalled dokku with 0.4.1, it does indeed work now like the frontpage says: webserver is running. So, confirmed to be working now!

**Comment by josegonzalez** [comment]
@bobvanderlinden I had two beers and some hookah in your honor.

**Comment by bobvanderlinden** [comment]
Haha, well deserved :)
