### ISSUE TITLE
Let's Encrypt Implementation

### ISSUE THREAD

**Issue by yngndrw** [progrium/dokku#1509]
So for those of you who don't know about the [Let's Encrypt](https://letsencrypt.org/) project, essentially they are a new (Upcoming) certificate authority who will provide free certificates for everyone. They are intending to go live over the next couple of months and they even [have a nice little tool](https://letsencrypt.org/howitworks/) which can automatically get and install the certificates.

I wanted to start a discussion on the best way to implement this within Dokku. (Either as a plugin or built into the core implementation.) The integration would need to handle the following sorts of events:
* Startup
* Application creation
* Application destruction
* Hostname change
* Re-Deployment (?)

The way I see it working is to, for each application in question, run an instance of the client in "automatic mode". This should then be stopped, reconfigured and restarted as required upon any of the above events occurring. this means that we'd take advantage of the automatic certificate retrieval and renewal, as well as the automatic deployment to Nginx. (Although I haven't yet worked out exactly how that part works and how it would work with the config that Dokku uses.) It could also be used in the "download only" mode where the Nginx config would be managed by Dokku.

Any thoughts ?

**Comment by josegonzalez** [comment]
This was brought up in #1497. If someone wants to work on it, it could be a nice official plugin, but I don't think it strictly belongs in the dokku core.
