### ISSUE TITLE
dokku run not release prompt in ssh model

### ISSUE THREAD

**Issue by shingara** [progrium/dokku#1510]
If I run the commande `dokku run tco rails c` on my server, I get the prompt. If I do the same from the ssh with the ssh-command. I never get the prompt.

**Comment by josegonzalez** [comment]
What prompt are you referring to?

**Comment by shingara** [comment]
The prompt to use the console. The command is end and we can't use the -it from docker by example

**Comment by josegonzalez** [comment]
What o you mean by prompt? Can you show what you expect and what is actually output?

**Comment by shingara** [comment]
ok My bad. To try explain much more my bug I found the issue. I not use the `-t` option in my ssh. With `-t` option it's works.

Sorry for the bad issue openning and your time.
