### ISSUE TITLE
Unable to upgrade dokku - herokuish conflict

### ISSUE THREAD

**Issue by darklow** [progrium/dokku#1513]
Currently i have dokku `0.3.22` (Ubuntu 14.04). Installed some time ago using `apt-get install dokku`
Now i tried running:
```
apt-get update && apt-get install dokku
```

And got error:
```
The following packages have unmet dependencies:
 dokku : Depends: herokuish but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
````
I am stuck at this and can't upgrade.

I tried installing herokuish manually (not sure if this is good idea) but it also failed:
```
The following packages have unmet dependencies:
 herokuish : PreDepends: docker-engine but it is not installable
E: Unable to correct problems, you have held broken packages.
```

Maybe because i have `lxc-docker-1.6.2` not `docker-engine`?!

I have lot of existing apps and really don't want to perform fresh install.
Could someone please advise me how to perform upgrade?

Thanks

**Comment by darklow** [comment]
Found the workaround - for those who have same problem, this is how i resolved it.
Found answer here: https://github.com/progrium/dokku/pull/1467

```
apt-get install herokuish=0.0.1
apt-get install dokku
```

**Comment by josegonzalez** [comment]
You can certainly upgrade dokku without upgrading herokuish. The latest version of dokku can work with either [`lxc-docker | docker-engine`](https://github.com/progrium/dokku/blob/master/debian/control#L6). 

Upgrading via the `bootstrap.sh` script - which is just a wrapper for the deb way - works fine for me...

**Comment by tbug** [comment]
`0.4.5` Dokku depends on herokuish.
Looks like it has been this way since `0.3.26`

On my Ubuntu 14.04.3 LTS:
```
tbug@lzy:~$ apt-cache show dokku
Package: dokku
Priority: optional
Section: web
Maintainer: Jose Diaz-Gonzalez <dokku@josediazgonzalez.com>
Architecture: amd64
Version: 0.4.5
Depends: locales, git, make, curl, gcc, man-db, herokuish, sshcommand, docker-engine-cs | docker-engine | lxc-docker (>= 1.6.2) | docker.io (>= 1.6.2), software-properties-common, python-software-properties
Pre-Depends: nginx (>= 1.4.6), dnsutils, apparmor, cgroupfs-mount | cgroup-lite, plugn, sudo, ruby, ruby-dev, rubygem-rack , rubygem-rack-protection, rubygem-sinatra, rubygem-tilt
Filename: pool/trusty/main/d/dokku/dokku_0.4.5_amd64.deb
Size: 33442
MD5sum: 9b3ba0e69d7f8e96115f3fe5cd4e3b69
SHA1: 93b5848ef9dcc857c24be0666b41cd4286909b6e
SHA256: e4faf11dc7a45802b5896657e9ce3eb21feba41973f771587a925b54cc5b321e
SHA512: 8165e0b126cecee7d1a3d970f06a9423c9902739809849f3d8af1e6a9b3bc9006ac5a3510ee7b53ff81b6a48613c450967f5234b013a663d68ab67d8f4d9706f
Description: Docker powered mini-Heroku in around 100 lines of Bash
Description-md5: 34a5b55b244fdb4b5d231179b2e73c46

......
```

Anywho, not a problem. `herokuish` depends on `docker-engine` and my system was older than that, so I updated my apt sources ( see http://docs.docker.com/engine/installation/ubuntulinux/ ) and installed docker engine. Dokku upgrade itself and installed herokuish.

After that a simple `dokku ps:restore` and everything redeployed just fine. :)
