### ISSUE TITLE
Update readme on upgrading

### ISSUE THREAD

**Issue by busla** [progrium/dokku#1526]
Would be great to add info about upgrading from v0.4.0 to v0.4.1.

Can I just re-install with:
```
wget https://raw.githubusercontent.com/progrium/dokku/v0.4.1/bootstrap.sh
sudo DOKKU_TAG=v0.4.1 bash bootstrap.sh
```
?

Also, this message could be made a bit clearer:

```
Warning: the "docker" command appears to already exist on this system.

If you already have Docker installed, this script can cause trouble, which is
why we're displaying this warning and provide the opportunity to cancel the
installation.

If you installed the current Docker package using this script and are using it
again to update Docker, you can safely ignore this message.

You may press Ctrl+C now to abort this script. 
```

The two paragraphs can be understood as contradicting. Based on this message I´m not sure if I can safely upgrade by re-installing.

Cheers :-)

**Comment by josegonzalez** [comment]
Yep, upgrades work exactly like that.

The message is from the docker installation script, so that is outside of our control. You can safely ignore it though.
