### ISSUE TITLE
Persistent container name

### ISSUE THREAD

**Issue by busla** [progrium/dokku#1527]
I have two containers that I link with dokku:
`dokku docker-options:add app1 build,run,deploy "--link app2_container_name:some-alias"`

App1 is now linked to App2 using App2´s container name (kickass_banach).

App1 is a REST service that communicates with App2 (also a REST service).

What happens is that that the App2´s ip number is not set as an environment variable on App1.

That´s fine since I can reference the `some-alias` hostname from App1´s `/etc/hosts` where the request takes place in my code:

`var requestUrl = "http://some-alias/"`.

Now, what happens is that when push an update to App2 it´s assigned an arbitrary container name (suspicious_feynman) which breaks the links between the apps, since they are linked by the previous name (kickass_banach).

Every time I push changes to App2 I need to remove the existing links and add new ones using the new container name.

Is there a way to have a persistent container name?

Or should the ip on App2 be set as an env variable on App1 and something is not working correctly?

Thanks!

**Comment by beardicus** [comment]
You might check out this plugin: https://github.com/Flink/dokku-named-containers

Seems to work, though I find something gets messed up when you reboot the host. I read somewhere that maybe this functionality would be rolled into dokku proper. Can anybody comment on that? It would be pretty smart and useful to consistently name containers upon creation.

**Comment by josegonzalez** [comment]
As of 0.4.2, this functionality is now in the core. Please open a new issue if there are any bugs with it's usage.
