### ISSUE TITLE
Web Installer Missing

### ISSUE THREAD

**Issue by hhff** [progrium/dokku#1539]
Hi Guys!

Just spun up a fresh `Ubuntu 14.04x64` box on Digital Ocean, ssh'd in and ran:

```
wget https://raw.githubusercontent.com/progrium/dokku/v0.4.1/bootstrap.sh
sudo DOKKU_TAG=v0.4.1 bash bootstrap.sh
```

The web installer isn't showing @ the IP - just the ```Welcome to nginx on Debian!``` page.

Am I missing something?

**Comment by stephenbaidu** [comment]
Have you checked if dokku sas installed successfully? I faced a similar issue and running `sudo DOKKU_TAG=v0.4.1 bash bootstrap.sh` again resolved it.

**Comment by hhff** [comment]
uh-huh!  Running `sudo DOKKU_TAG=v0.4.1 bash bootstrap.sh` a second time fixed it for me.  Thankyou @stephenbaidu

**Comment by Hahlh** [comment]
This happened to me to on both Ubuntu 14.04 and Debian 9 (dedicated Oneprovider).
Running the command a second time also fixed this for me.

**Comment by josegonzalez** [comment]
Please don't comment on 4 year old issues.
