### ISSUE TITLE
How to do app permission with dokku?

### ISSUE THREAD

**Issue by dmr** [progrium/dokku#1540]
This is not really an issue, a question:
One year ago there was https://github.com/mlebkowski/dokku-acl to manage permissions.

What are you using today? Does the plugin still word with the current dokku versions?
Great work with 0.4.0 and all the plugins, thank you!

**Comment by josegonzalez** [comment]
We don't yet have any permission system. I'm honestly of the opinion that it should be handled with a database-backed ssh-command and some light glue in dokku. Not sure what @progrium thinks here though.

**Comment by josegonzalez** [comment]
@dmr I just made a pull request to that repository that *should* work for 0.4.x, but no promises. I suggest you test/:+1: that pr so it gets merged :)

Closing as we have no plans at the moment to handle this feature, and it's currently best left to a plugin.

**Comment by dmr** [comment]
Thank you very much! It's already merged :)
