### ISSUE TITLE
Setting locale failed

### ISSUE THREAD

**Issue by benmarten** [progrium/dokku#1542]
I am having trouble with my dokku installation. Dokku can't seem to find the locale. It's set correctly when logging in via bash though, any ideas whats missing?

	perl: warning: Setting locale failed.
	perl: warning: Please check that your locale settings:
		LANGUAGE = (unset),
		LC_ALL = (unset),
		LC_CTYPE = "UTF-8",
		LANG = "en_US.UTF-8"
	    are supported and installed on your system.
	perl: warning: Falling back to the standard locale ("C").

**Comment by josegonzalez** [comment]
How did you install dokku and how/from where are you connecting it to?

**Comment by benmarten** [comment]
I spun up a brand new Ubuntu 14.04 machine on AWS and ran the install script:
    wget https://raw.githubusercontent.com/progrium/dokku/v0.4.1/bootstrap.sh
    sudo DOKKU_TAG=v0.4.1 bash bootstrap.sh
then simply pushed my repo (node.js) to the server...

**Comment by benmarten** [comment]
I just reran this on a new server and saw the following lines during installation:

        ubuntu@ip-172-31-xx-xx:~$ sudo DOKKU_TAG=v0.4.1 bash bootstrap.sh
	perl: warning: Setting locale failed.
	perl: warning: Please check that your locale settings:
		LANGUAGE = (unset),
		LC_ALL = (unset),
		LC_CTYPE = "UTF-8",
		LANG = "en_US.UTF-8"
	    are supported and installed on your system.
	perl: warning: Falling back to the standard locale ("C").
	locale: Cannot set LC_CTYPE to default locale: No such file or directory
	locale: Cannot set LC_ALL to default locale: No such file or directory

**Comment by michaelshobbs** [comment]
Maybe just add this to `bootstrap.sh` to ensure it's set?

```
export LANG=en_US.UTF-8
export LANGUAGE=$LANG
```

**Comment by benmarten** [comment]
Thanks Michael, I tried that, doesn't help, though...

Now i think the problem is that the locale is not set inside the docker virtual environment... Because when I login via ssh to my aws instance:

    Ben@Bens-MacBook-Pro ~/d/vagrant> vagrant ssh box1
    ubuntu@box1:~$ echo $LANG
    en_US.UTF-8

When I push the nodejs-example-app edited with this line:
    app.get('/', function(request, response) {
      response.send('$LANG: "' + process.env.LANG + '"')
    })

It outputs nothing...! Any ideas how to set it?

**Comment by michaelshobbs** [comment]
Interesting. Can you try deploying this to heroku and see if it returns a value there?

**Comment by benmarten** [comment]
Both are the same:
https://murmuring-everglades-1807.herokuapp.com
http://test.box1.colibriapps.com

I still see the LOCALE issue in the deploy log though :/ - Any other ideas?!

Full Log: https://gist.github.com/benmarten/fd2bba8c7a516db68459

**Comment by michaelshobbs** [comment]
Ok. Just wanted to verify we weren't doing something different than Heroku.

You can set these variables in your app using the `config:set` command.

```
root@dokku:~/dokku# dokku config:help
    config (<app>|--global), Display all global or app-specific config vars
    config:get (<app>|--global) KEY, Display a global or app-specific config value
    config:set (<app>|--global) KEY1=VALUE1 [KEY2=VALUE2 ...], Set one or more config vars
    config:unset (<app>|--global) KEY1 [KEY2 ...], Unset one or more config vars
```

**Comment by benmarten** [comment]
Tried that, but also no luck...

I also tried adding a Dockerfile with that content:
# Pull base image.
FROM ubuntu:14.04

# Set the locale
    
    RUN locale-gen en_US.UTF-8
    ENV LANG en_US.UTF-8
    ENV LANGUAGE en_US:en
    ENV LC_ALL en_US.UTF-8

but the push is always rejected:

	remote: Error response from daemon: Cannot kill container 7ee13107a5c7cdd0147c1b98a7a0a48c536721add19a7e0a8e04c070c9994ad6: Container 7ee13107a5c7cdd0147c1b98a7a0a48c536721add19a7e0a8e04c070c9994ad6 is not running
	remote: Error: failed to kill containers: [7ee13107a5c7cdd0147c1b98a7a0a48c536721add19a7e0a8e04c070c9994ad6]
	To dokku@box1.colibriapps.com:test
	 ! [remote rejected] master -> master (pre-receive hook declined)
	error: failed to push some refs to 'dokku@box1.colibriapps.com:test'

This might be also related to setting the timezone?!

**Comment by michaelshobbs** [comment]
Now I'm not clear on what we're solving here. The original question seemed to indicate an issue with the `bootstrap.sh` installation method.

To further troubleshoot, please include the information outlined [here](https://github.com/progrium/dokku/blob/master/CONTRIBUTING.md)

**Comment by benmarten** [comment]
Ok, so this turned out to be a linux issue. Found that out by running: `ubuntu@box1:~$ locale`

These answers fixed it for me:
http://askubuntu.com/a/229512
http://askubuntu.com/a/162394

Thanks for your help ;)

**Comment by michaelshobbs** [comment]
What exactly did you end up doing?

**Comment by benmarten** [comment]
I ssh'ed into my instance and ran: `locale` which showed the same errors as mentioned in my first post.

To solve it, i put these lines into `/etc/default/locale`

    LC_ALL=en_US.UTF-8
    LANG=en_US.UTF-8

Then I ran: 

    sudo locale-gen en_US en_US.UTF-8
    sudo dpkg-reconfigure locales

**Comment by josegonzalez** [comment]
Note: You should *always* set server time to UTC, otherwise you're going to fall into a world of hurt when trying to query against data inserted from different timezones :)

**Comment by michaelshobbs** [comment]
Yeah I was apparently confused as your question was in regards to setting locale environment variables on your host and not in your app container.
