### ISSUE TITLE
dokku logs for specific process

### ISSUE THREAD

**Issue by stephenbaidu** [progrium/dokku#1543]
Would be nice to have `dokku logs <app> <process>` as well. At the moment, I just want to tail logs on the `web` processes without worrying about the logs from my `worker` processes.

**Comment by u2mejc** [comment]
@stephenbaidu I was working on a branch that might meet your needs, I'll clean it up and shoot over a PR.

**Comment by josegonzalez** [comment]
Closing in favor of #1534, which has more discussion on this topic.
