### ISSUE TITLE
Need to install custom binaries

### ISSUE THREAD

**Issue by vijayviji** [progrium/dokku#1549]
Right now, there seems to be no way to install custom binaries in dokku app containers. Nor there's a way to execute binaries in those containers. My Nodejs app uses docker client and so I need docker client to be installed in the container.

Ways I tried:
* Create a Dockerfile and create all the buildsteps: This way just wasted my one day time. There's no proper documentation on this. After trying out many ways, I tried to do follow a simple dockerfile installation -> http://blog.stevenedouard.com/git-deploy-nodejs-apps-dockerfiles-using-dokku/. This resulted in "pre-receive hook declined" error. When I searched for this error, I bumped into a discussion about someone reporting this as an issue. But the solution suggested was to use .env file. But when I tried to use this .env file, dokku ignores Dockerfile I've created.

* Download the docker binary and place it with git repo of my source code. This makes it the binary to be non-executable. I've to log into container using 'docker exec -it <container_id> /bin/bash' and change the permission everytime

* I can't use the custom buildpack 'https://github.com/ddollar/heroku-buildpack-apt' to do apt-get install also, since installing docker requires key addition and other steps.

**Comment by michaelshobbs** [comment]
You might want to check out the dokku-apt plugin

**Comment by vijayviji** [comment]
@michaelshobbs  Thanks Michael. I looked at it. How to import the repo keys? I'm trying to use this -> https://get.docker.com/ubuntu/

**Comment by michaelshobbs** [comment]
Ah yes that's a good question for the plugin maintainer and a good feature if they don't already support it. Ultimately you have two choices to accomplish custom package installation.
1. Create or use a `pre-build-buildpack` plugin to execute the `apt-*` commands (like dokku-apt)
2. Create a custom herokuish docker image. (I do this in my environments)

example custom herokuish dockerfile
```
FROM gliderlabs/herokuish:latest
ENV LC_ALL C
ENV DEBIAN_FRONTEND noninteractive

ADD ./stack/ /stack
RUN /stack/add_ons.sh && rm -rf /stack
```
add_ons.sh just runs apt-get on a package list

Hope this helps.
