### ISSUE TITLE
nginx:enable fails after initial nginx:disable

### ISSUE THREAD

**Issue by meskyanichi** [progrium/dokku#1565]
I might've come across a bug. After disabling nginx for `example-app`, I am unable to enable it again. Dokku thinks that it's both enabled, as well as disabled (it is actually disabled at this point).

```
dokku@Dokku:/root$ dokku nginx:enable example-app
-----> nginx is already enabled for app (example-app)
dokku@Dokku:/root$ dokku nginx:disable example-app
-----> nginx is already disable for app (example-app)
dokku@Dokku:/root$ dokku nginx:enable example-app
-----> nginx is already enabled for app (example-app)
```

To reproduce:

```
dokku apps:create example-app
```

Then deploy an app and verify it works in the browser. Once verified, disable nginx:

```
dokku nginx:disable example-app
```

Once disabled, for some reason it doesn't immediately take effect, so `sudo reboot`. Once rebooted, the endpoint no longer resolves. Now try to enable nginx again:

```
dokku@Dokku:/root$ dokku nginx:enable example-app
-----> nginx is already enabled for app (example-app)
```

**Comment by michaelshobbs** [comment]
can you provide the output of `dokku config example-app`?

**Comment by michaelshobbs** [comment]
Nevermind. I see the bug.
