### ISSUE TITLE
App tls has not been deployed

### ISSUE THREAD

**Issue by mmerickel** [progrium/dokku#1571]
Saw this at the end of `ps:restartall`:

```
App tls has not been deployed
```

Obviously this folder holds the wildcard ssl certs as per the docs and is not an app.

Dokku v0.4.2.

**Comment by josegonzalez** [comment]
@michaelshobbs another example where we are mixing config with application code :(

**Comment by michaelshobbs** [comment]
Yeah the dokku_deploy cookbook that's out and about on the internet causes a similar "issue"

**Comment by jmatsushita** [comment]
+1 for separating config from app code. Just bumped into the same message.
