### ISSUE TITLE
nginx:access-logs permission denied

### ISSUE THREAD

**Issue by mmerickel** [progrium/dokku#1572]
clean install on a new virtual machine and things are running fine but the first time I ran `ssh -t dokku@dokku nginx:access-logs myapp -t` I got permission denied.

Further investigation shows the `/var/log/nginx` folder with `drwxr-x--- www-data adm` permissions, preventing the `dokku` user from accessing the folder.

I'm not sure what the "best" solution is here. If I just allow `+x` on the folder then inotify doesn't work with tail (it needs to be able to read the directory). So the folder probably needs to be changed to the dokku group or something else.

This is using ubuntu 14.04 LTS, dokku v0.4.2.

**Comment by michaelshobbs** [comment]
I was pretty sure we did that on install. I'll have to look when I'm back at a computer.

**Comment by mmerickel** [comment]
I can't find a reference to anything that looks like it'd touch /var/log/nginx anywhere in the debian preinst/postinst scripts.

**Comment by michaelshobbs** [comment]
I think it's in an `install` trigger. Maybe under the nginx-vhosts plugin.

**Comment by mmerickel** [comment]
Ok well I still can't find it if it's there and my filesystem says otherwise!

**Comment by michaelshobbs** [comment]
Here it is 
https://github.com/progrium/dokku/blob/master/plugins/20_events/install#L12-L13

**Comment by mmerickel** [comment]
@michaelshobbs that only applies to `/var/log/dokku`, not `/var/log/nginx`.

**Comment by michaelshobbs** [comment]
Ah! Fair point. Interesting though that your installation doesn't run tail as root....

```
root@dokku:/var/log/nginx# dokku apps
=====> My Apps
node-js-app
root@dokku:/var/log/nginx# ls -lad /var/log/nginx/ /var/log/nginx/node-js-app*
drwxr-x--- 2 www-data adm  4096 Oct 18 06:50 /var/log/nginx/
-rw-r----- 1 www-data adm   426 Oct 19 17:14 /var/log/nginx/node-js-app-access.log
-rw-r--r-- 1 root     root 1449 Sep 18 05:50 /var/log/nginx/node-js-app-access.log.1
-rw-r--r-- 1 root     root  566 Oct 19 17:14 /var/log/nginx/node-js-app-error.log
root@dokku:/var/log/nginx# dokku nginx:access-logs node-js-app -t
10.0.0.1 - - [19/Oct/2015:17:14:00 +0000] "GET / HTTP/1.1" 502 568 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.71 Safari/537.36"
10.0.0.1 - - [19/Oct/2015:17:14:03 +0000] "GET /favicon.ico HTTP/1.1" 502 568 "http://node-js-app.dokku.me/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.71 Safari/537.36"
```
```
vagrant@dokku:~$ ps -ef| grep tail
root      5501  5500  0 17:14 pts/0    00:00:00 tail -F /var/log/nginx/node-js-app-access.log
```

**Comment by mmerickel** [comment]
Your example in your above comment is running as root when running nginx:access-logs so of course it works. I'm not sure I see your point there.

> ```bash
if [[ $(id -un) != "dokku" && $1 != plugin:*install* && $1 != "plugin:update" && $1 != nginx:*-logs ]]; then
  sudo -u dokku -E -H $0 "$@"
  exit
fi
```

I don't understand that check. That's checking if the user is **not** dokku then to run things as root if the command is **NOT** any of those? I'd expect something closer to (assuming I knew bash well enough):

```
if [[ $(id -un) != "root" && ($1 == plugin:*install* || $1 == "plugin:update" || $1 != nginx:*-logs) ]]; then
  sudo -u dokku -E -H $0 "$@"
  exit
fi
```

**Comment by mmerickel** [comment]
Wait, nevermind... the check is trying to explicitly run things **as** dokku. Fine. This means that the `/var/log/nginx` must be accessible by the dokku user which as I've stated previously is not true.

**Comment by michaelshobbs** [comment]
Right and to my point that I'm not sure why your `/var/log/nginx` perms differ. That's all. Did you already have nginx installed before installing dokku perhaps?

**Comment by mmerickel** [comment]
It was a new VM where the first thing I did was run the bootstrap script.

**Comment by michaelshobbs** [comment]
I must have misread you previous response. Your directory permissions are correct and match mine. The point I was actually attempting to make is that `dokku nginx:access-logs myapp -t` should be executed as **root** not **dokku**. 

However, I was not testing over ssh and I think that is the issue. Can you attempt to run `dokku nginx:access-logs myapp -t ` locally on the instance to verify?

**Comment by michaelshobbs** [comment]
Ok so this is definitely an issue over SSH only. I'll look into how best to patch this.

**Comment by josegonzalez** [comment]
@mmerickel mind commenting here with the issue you are seeing and your personal recommendations?

**Comment by mmerickel** [comment]
AFAICT the fix in #1585 is not actually a fix because nginx's logrotate script switches new log files back to `www-data:adm` so unless that script is switched to `www-data:dokku` or dokku is added to the adm group this is still a problem.

Came back to work on Monday after logrotate and my access-log tail was busted again with permission denied.

```
/var/log/nginx/*.log {
        weekly
        missingok
        rotate 52
        compress
        delaycompress
        notifempty
        create 0640 www-data adm
        sharedscripts
        prerotate
                if [ -d /etc/logrotate.d/httpd-prerotate ]; then \
                        run-parts /etc/logrotate.d/httpd-prerotate; \
                fi \
        endscript
        postrotate
                service nginx rotate >/dev/null 2>&1
        endscript
}
```

I'd recommend updating the work done to `s/invoke-rc.d/service` to also `s/www-data adm/www-data dokku` if you are going to continue down this route. The simpler fix is to revert #1585 and just add dokku to the adm group but I remember @josegonzalez pushing back on that in irc due to security concerns despite adm being used for only logs.

**Comment by michaelshobbs** [comment]
Are you sure you're still seeing this issue? In my installation, the log files are world-readable. can you post the output from `ls -l /var/log/nginx` after a logrotate has completed?

**Comment by mmerickel** [comment]
```
$ ls -l /var/log | grep nginx
drwxr-x--x 2 www-data  dokku   4096 Nov  6 06:45 nginx
$ ls -l /var/log/nginx
-rw-r----- 1 www-data adm         0 Nov  6 06:45 myapp-access.log
```

I'm not sure what the confusion is but the logrotate conf file I pasted above clearly shows the 0640 permissions after rotate.

**Comment by michaelshobbs** [comment]
Ah yea. I missed that. Sorry. This should be simple enough to patch.
