### ISSUE TITLE
"open plugin.toml no such file or directory"

### ISSUE THREAD

**Issue by arnthorsnaer** [progrium/dokku#1580]
Hi there 

I am having a small problem. I installed a plugin () but once I discovered it did not support dokku 0.4, I removed it. Since then I've been having problems one of my apps, since it currently pipes out quite a few "no such file or directory" on app start.

```
remote: 2015/10/19 19:41:10 open /var/lib/dokku/plugins/available/redis/plugin.toml: no such file or directory
remote: 2015/10/19 19:41:10 open /var/lib/dokku/plugins/available/redis-plugin/plugin.toml: no such file or directory
```

Have you got any ideas about this?
How can I remove every shred of a plugin besides removing the folder of the plugin.

**Comment by michaelshobbs** [comment]
Not sure if you tried this but we have this built into the `plugin` command. Though, I'm not sure how `plugn` reacts when attempting to uninstall a plugin when there are missing toml files. Anywho, give it a shot.

```
root@dokku:~/dokku# dokku plugin:help
    plugin, Print active plugins
    plugin:install [--core|git-url], Optionally download git-url & run install trigger for active plugins (or only core ones)
    plugin:install-dependencies [--core], Run install-dependencies trigger for active plugins (or only core ones)
    plugin:update [git-url], Optionally download git-url & run update trigger for active plugins
    plugin:enable <name>, Enable a previously disabled plugin
    plugin:disable <name>, Disable an installed plugin (third-party only)
    plugin:uninstall <name>, Uninstall a plugin (third-party only)
```

However, the uninstall command is just deleting the files on disk. See [here](https://github.com/progrium/plugn/blob/b5372ff92aefb74c7da7857f8ddaf1d35694cf03/bashenv/plugn.bash#L13-L14)

You can also manually run the `rm` commands.
```
	rm -rf "$PLUGIN_PATH/enabled/$plugin"
	rm -rf "$PLUGIN_PATH/available/$plugin"
```

**Comment by arnthorsnaer** [comment]
Thanks! There was a remaining link in the enabled directory. Removing it did the trick.
