### ISSUE TITLE
Host volumes / environment variables not available during container build stage

### ISSUE THREAD

**Issue by wjdp** [progrium/dokku#1588]
I have the following set up

```
Build options:
    --link dokku.postgres.xsacdb-database:dokku-postgres-xsacdb-database
    -v /storage/xsacdb/conf:/app/conf
    -v /storage/xsacdb/media:/app/media
Deploy options:
    --link dokku.postgres.xsacdb-database:dokku-postgres-xsacdb-database
    -v /storage/xsacdb/conf:/app/conf
    -v /storage/xsacdb/media:/app/media
Run options:
    --link dokku.postgres.xsacdb-database:dokku-postgres-xsacdb-database
    -v /storage/xsacdb/conf:/app/conf
    -v /storage/xsacdb/media:/app/media
```

However when pushing and triggering a build these directories are not accessible.

```
ls: cannot access /app/conf: No such file or directory
ls: cannot access /app/media: No such file or directory
```

They are available once the container is built

```
dokku run xsacdb bash
$ ls /app/conf
files here!
```

My Dockerfile: https://gist.github.com/wjdp/c19959534f6876214d33

In addition the DATABASE_URL environment variable set my the postgres plugin is also not available at build time.

**Comment by michaelshobbs** [comment]
Yeah Dockerfile deployments could use some help here. It's definitely not our primary use case. That being said, the code would indicate we don't trigger `docker-args-build` for Dockerfile deployments and that would yield your experience.

@josegonzalez any reason you can think of that we shouldn't trigger `docker-args-build` for dockerfile deployments?

**Comment by josegonzalez** [comment]
None I can think of, especially if we trigger it everywhere else.
