### ISSUE TITLE
Plugin: serving static assets (images, javascript, etc) from nginx

### ISSUE THREAD

**Issue by matthewmueller** [progrium/dokku#1592]
This has definitely been discussed a ton before, but seems to get left at, you need to go into your server and customize the template yourself or create a custom buildpack. Personally, I think a plugin would be the way to go. How feasible would be it to create a plugin that writes to the nginx template? That doesn't overwrite or get overwritten by new changes? Seems like we just need a way to add locations and then just pass config to it:

Here's an old nginx file:

```
location ~ \.(jpg|jpeg|gif|css|png|js|ico|html|eot|svg|ttf|woff)$ {
  root /home/matio/mat.io/build;
  gzip_static on;
  expires max;
  add_header Cache-Control public;
  access_log off;
}
```

root would need to be partially resolved (first part), but everything else could have a sensible default and be overwritten. Something like:

```
dokku nginx:assets app <match> [options, ... ]
```

**Comment by michaelshobbs** [comment]
A couple thoughts on this
- there is already a static buildpack that does this. (no need to write your own)
- as you noted, the other (and prescribed) way to do this is using a custom nginx template

I personally don't think there is value in further expanding our already overly complex interface into nginx configuration. I'm willing to be swayed here but I have yet to hear a cogent argument.

**Comment by josegonzalez** [comment]
The `build` dir is deleted after a deploy, no? So you'd need to mount it onto the host and somehow copy the files out.

**Comment by matthewmueller** [comment]
Yah, I think if you go with the static buildpack route you'd have to add these assets to a volume. You'd also need a way to update them. At that point I think it's about as easy to setup a CDN.

I'm sorta just looking for the simplest way to take advantage of nginx's speed and not bog down our node server. 

With the custom NGINX template, would it get overwritten if anyone adds or changes a domain or does anything operation on the template?

**Comment by michaelshobbs** [comment]
you could definitely write your own plugin to manage some nginx config

**Comment by josegonzalez** [comment]
Closing as the proper solution is to build this in a plugin.

**Comment by matthewmueller** [comment]
Thanks guys, appreciate the feedback!

**Comment by chiedo** [comment]
Hey all!

I just want to make sure I'm not missing something.

I followed this:
http://dokku.viewdocs.io/dokku~v0.4.3/nginx/

I get that there is no easy way to access the files in the Docker container.

So is using something like S3 really the only option?

There's no way to just serve static files from a path in my repo via nginx as opposed to node?

Thanks,

**Comment by josegonzalez** [comment]
That is correct. You'd also have similar issues on any other cloud provider, or any other deployment of docker.

You'd probably want a post-build hook that copies out the assets onto the system and has nginx proxy them from there. While it seems like a nice enhancement, thats way outside of where we want to take Dokku, so I would suggest you build a plugin for this.

I highly recommend using a CDN in front of your applications if you care about speed of response when accessing static assets.

**Comment by chiedo** [comment]
Thanks @josegonzalez 

I usually do use a S3 for my static assets but for this specific app, there are only about 5 of them. Haha.

Was trying to avoid the extra setup for each client running an instance of my app.

Thanks for the quick response.
