### ISSUE TITLE
Set NODE_ENV to production by default

### ISSUE THREAD

**Issue by rsteckler** [progrium/dokku#1595]
So this caused a really hard to track down bug on my site, but here's the short story:
Some node modules (like express and connect-assets) change behavior when they're running in production vs. development environments.  They check this by testing the NODE_ENV variable.  Heroku sets this to 'production' by default (https://devcenter.heroku.com/articles/nodejs-support#runtime-behavior)
I believe Dokku should, as well, for compatibility reasons and just to be a good citizen.

**Comment by josegonzalez** [comment]
We use the nodejs buildpack which [already does this](https://github.com/heroku/heroku-buildpack-nodejs/search?utf8=%E2%9C%93&q=NODE_ENV). The article you link to is specifically for the nodejs-buildpack, and that seems to work fine for us.

Where are you not seeing this?

**Comment by rsteckler** [comment]
That's strange.  I have a fresh Ubuntu instance that I installed Dokku on.  Everything works great, in general.
I shell into that dokku machine.
sudo docker ps
Grab the instance ID of a running container that dokku deployed.
sudo docker exec -it <container_id> bash
Now I'm on the docker instance.
printenv
And I don't see a definition for NODE_ENV

I discovered this when I saw that connect-assets wasn't minifying my code as it was being served via express-static.  

Things I tried before manually setting NODE_ENV:
Rebuild
Redeploy
Delete cache and rebuild
Restart container
The dokku machine has never been rebooted, I don't think.

**Comment by michaelshobbs** [comment]
Your docker exec attempt failed because the app startup process sources everything in `/app/.profile.d`. At least I think this is the correct path. Can you check that path for `NODE_ENV` in a running app container? I'm mobile right now but I'll check my node containers when I get back to a computer.

**Comment by josegonzalez** [comment]
If you want to enter a container, use the the [`dokku enter`](http://progrium.viewdocs.io/dokku/deployment/one-off-processes/#entering-existing-containers) command.

Looks like that was broken for a while and was [fixed](https://github.com/heroku/heroku-buildpack-nodejs/commit/6b4809db429868aabbbd5b34f09053bcec20e63f) as of v80 of the nodejs buildpack. @michaelshobbs can you make a new herokuish release? I can build a new package once thats done.

**Comment by michaelshobbs** [comment]
new release building now

**Comment by michaelshobbs** [comment]
I have multiple node envs. I can confirm that the one using the herokuish built-in nodejs buildpack is broken and the one that uses master is not.

**Comment by michaelshobbs** [comment]
Oh and herokuish 0.3.4 is released and up on docker hub

**Comment by rsteckler** [comment]
Sorry - I got lost trying to follow what happened.  
Is the herokuish build back something that dokku will automatically update next time I build, or do I need to re-install/update dokku?

I'd like to get rid of my explicit dokku config:set variable...

**Comment by josegonzalez** [comment]
Run `apt-get install herokuish` and rebuild your app and everything should work.
