### ISSUE TITLE
Cannot run first build using docker and postgres

### ISSUE THREAD

**Issue by WilliamMayor** [progrium/dokku#1609]
I'm new to dokku so sorry if I've missed anything obvious.

I created a new app and linked a postgres container to it. I then tried to push my docker-based app into dokku for the first time. There was an error about the `--link` flag being 'provided but not defined'.

I poked around a bit and I think it's because the docker-options plugin uses the same args for build and run. If you've linked a postgres container to the app before you've built it, then you'll get a `--link` provided in the build stage.

I think I've skirted the problem by unlinking postgres, pushing into dokku, then relinking. Not sure if this is the right thing to do though.

**Comment by josegonzalez** [comment]
Can you provide the information we request in our [Contributing Guide](https://github.com/progrium/dokku/blob/master/CONTRIBUTING.md#reporting-other-issues)?

**Comment by WilliamMayor** [comment]
OK...

**Description of problem:**

If I try to push a repo for an app that uses Docker to a Dokku app with a linked postgres container the deploy fails with the error message `remote: flag provided but not defined: --link`.

I suspect this is because the `docker-options` plugin seems to pass the same args to `docker build` as it does to `docker run`.

**Output of the following commands:**

    $ uname -a
    Linux QueenOfHearts 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
    $ docker version
    Client:
     Version:      1.8.3
     API version:  1.20
     Go version:   go1.4.2
     Git commit:   f4bf5c7
     Built:        Mon Oct 12 05:37:18 UTC 2015
     OS/Arch:      linux/amd64
    
    Server:
     Version:      1.8.3
     API version:  1.20
     Go version:   go1.4.2
     Git commit:   f4bf5c7
     Built:        Mon Oct 12 05:37:18 UTC 2015
     OS/Arch:      linux/amd64
    $ docker -D info
    Containers: 9
    Images: 46
    Storage Driver: aufs
     Root Dir: /var/lib/docker/aufs
     Backing Filesystem: extfs
     Dirs: 64
     Dirperm1 Supported: true
    Execution Driver: native-0.2
    Logging Driver: json-file
    Kernel Version: 3.19.0-25-generic
    Operating System: Ubuntu 14.04.3 LTS
    CPUs: 2
    Total Memory: 3.857 GiB
    Name: QueenOfHearts
    ID: HCJS:OCJC:NDC4:BJ67:GHB7:PBBY:MFUM:VHUV:U6CH:S2PC:3NTX:YR4P
    WARNING: No swap limit support
    $ dokku version
    0.4.3
    $ dokku plugin
      00_dokku-standard    0.4.0 enabled    dokku core standard plugin
      20_events            0.4.0 enabled    dokku core events logging plugin
      apps                 0.4.0 enabled    dokku core apps plugin
      backup               0.4.0 enabled    dokku core backup plugin
      build-env            0.4.0 enabled    dokku core build-env plugin
      certs                0.4.0 enabled    dokku core certificate management plugin
      checks               0.4.0 enabled    dokku core checks plugin
      common               0.4.0 enabled    dokku core common plugin
      config               0.4.0 enabled    dokku core config plugin
      docker-options       0.4.0 enabled    dokku core docker-options plugin
      domains              0.4.0 enabled    dokku core domains plugin
      enter                0.4.0 enabled    dokku core enter plugin
      git                  0.4.0 enabled    dokku core git plugin
      logs                 0.4.0 enabled    dokku core logs plugin
      named-containers     0.4.0 enabled    dokku core named containers plugin
      nginx-vhosts         0.4.0 enabled    dokku core nginx-vhosts plugin
      plugin               0.4.0 enabled    dokku core plugin plugin
      postgres             1.0.0 enabled    dokku postgres service plugin
      ps                   0.4.0 enabled    dokku core ps plugin
      shell                0.4.0 enabled    dokku core shell plugin
      tags                 0.4.0 enabled    dokku core tags plugin
      tar                  0.4.0 enabled    dokku core tar plugin

**Environment details (AWS, VirtualBox, physical, etc.):** An old iMac
**How was dokku installed?:** Using the bootstrap script

**How reproducible:** Very, I think. The two apps I've created so far have this behaviour.

**Steps to Reproduce:**

Create a new Dokku app, according to the application deployment instructions:

    (server) $ dokku apps:create my-app
    (server) $ sudo dokku plugin:install https://github.com/dokku/dokku-postgres.git
    (server) $ dokku postgres:create my-app-database
    (server) $ dokku postgres:link my-app-database my-app

Create a new repo for the app

    (other) $ mkdir my-app
    (other) $ cd my-app
    (other) $ git init
    (other) $ echo "FROM nginx" > Dockerfile
    (other) $ git add .
    (other) $ git commit -m 'Add Dockerfile'
    (other) $ git remote add dokku dokku@dokku.me:my-app

Try to deploy new app

    (other) $ git push dokku master
    Counting objects: 3, done.
    Writing objects: 100% (3/3), 233 bytes | 0 bytes/s, done.
    Total 3 (delta 0), reused 0 (delta 0)
    -----> Cleaning up...
    -----> Building fail from dockerfile...
    remote: flag provided but not defined: --link
    remote: See 'docker build --help'.
    To dokku@dokku.me:my-app
     ! [remote rejected] master -> master (pre-receive hook declined)
    error: failed to push some refs to 'dokku@dokku.me:my-app'

**Actual Results:** Fails to deploy
**Expected Results:** Successful deploy

**Additional info:**

In order to avoid the problem you can unlink the postgres container and then link it back in afterwards. The problem I had with this is that my app fails to launch if the DB isn't available and so the deploy still fails.

    (server) $ dokku postgres:unlink my-app-database my-app
    ...
    (other) $ git push dokku master
    ...
    (server) $ dokku postgres:link my-app-database my-app

I've since exposed the postgres container and added the `DATABASE_URL` config in manually. I had to add a docker option of `--net=host` to the `run` phase of my app in order to get it to connect.

    (server) $ dokku postgres:unlink my-app-database my-app
    (server) $ dokku postgres:expose my-app-database
    (server) $ dokku config:set my-app DATABASE_URL=postgres://postgres:...@localhost:PORT/my_app_database
    (server) $ dokku docker-options:add my-app run --net=host

I'm not certain this is going to work completely as required but it seems to be OK so far.

**Comment by josegonzalez** [comment]
Can you gist deploy logs after using `dokku trace on`?

**Comment by WilliamMayor** [comment]
Sure, the actual app I created to reproduce this is called `fail` not `my-app`:

https://gist.github.com/WilliamMayor/c6942c85f271ca83e59f

**Comment by josegonzalez** [comment]
@Flink seems like we have a bug with the official plugins. We shouldn't link containers in the `build` phase it seems, just `run` and `deploy`. The [`docker build`](https://docs.docker.com/reference/commandline/build/) command doesn't have `--link`, leading to this issue. I'll come up with a pr after I verify my debian installation changes...

@WilliamMayor thanks for reporting this issue! We'll get it fixed up right away :)

**Comment by WilliamMayor** [comment]
@josegonzalez np, thanks for getting back to me so quickly :)

**Comment by Flink** [comment]
@josegonzalez we need to remove the `--link` option when building a docker image then but absolutely not when building with buildpack. When deploying a Rails application for example, having PG and/or Redis at the build phase can be useful for certain apps (Discourse for instance needs Redis when building assets).

**Comment by josegonzalez** [comment]
Interesting. Not sure if there is a straightforward fix here other than including even more phases:

- `buildpack-build`, `dockerfile-build`
- `buildpack-run`, `dockerfile-deploy`
- `buildpack-deploy`, `dockerfile-deploy`

I'm not a big fan of that. Not sure if there is a good fix otherwise...

**Comment by josegonzalez** [comment]
One thing we  *can* do is try and filter out the harmful options in dokku core? If the option begins with `--link`, ignore it for dockerfile deploys. Do you think that's feasible, @Flink ?

**Comment by Flink** [comment]
@josegonzalez yes I was thinking about something like that :) Some sort of blacklist/whitelist for options when using Dockerfiles.

**Comment by michaelshobbs** [comment]
Isn't this more directly an issue with add `--link` to the build phase from the postgres plugin. I don't think adding filtering (and thus complexity here) is the right move. Seems to me fixing the plugins and documenting that using `--link` in the build phase is not recommended and in fact not supported in `Dockerfile` deployments.

This obviously assumes that `--link` is never necessary in the `build` phase. I cannot think of a reason at the moment that you'd expect that. The postgres container (in this case) doesn't need to be linked at build time, correct?

**Comment by Flink** [comment]
@michaelshobbs well there is the official discourse repo https://github.com/discourse/discourse but this is quite cumbersome to setup. This is when the `rake assets:precompile` task is called that discourse makes calls to Redis. If Redis isn’t there, you can’t build the app.
For buildpacks builds, services should be available in the build phase, you can’t know for sure what an app will do or will need.

If you look at the official Cozy Cloud Dockerfile (https://github.com/cozy-labs/cozy-docker/blob/master/Dockerfile), you’ll see calls to CouchDB. So if you want an external CouchDB, you’ll have to modify their Dockerfile completely. (this is indeed what I did to use CozyCloud with dokku ;)). In the end, I think we can’t apply the same things between Dockerfile and Buildpacks since they’re quite differents and have their specifics each.

**Comment by michaelshobbs** [comment]
Ah. Just to be clear, `rake assets:precompile` is called by the buildpack and thus in dokku's `build` phase, correct?

**Comment by Flink** [comment]
@michaelshobbs exactly!

**Comment by michaelshobbs** [comment]
Understood

**Comment by oliverkane** [comment]
Hey all, I'm having difficulty trying to get Docker-Gitlab working with Dokku, and it appears that this is the same issue as I'm also getting ``` remote: flag provided but not defined: --link ``` on git push.  Would the steps needed to reproduce at this point be welcomed, or is the issue well understood?  Basically, I'm looking to contribute, though I'm not sure what'd be useful.

**Comment by josegonzalez** [comment]
The issue is understood. We basically want to remove `--link` on the build phase [here](https://github.com/dokku/dokku-postgres/blob/2d6684d6e3323e9fda8ff39d01f6344a6ab7929c/functions#L92) if it is a Dockerfile deploy.

I'd sort of rather not have a hack in dokku core for this, though it might be necessary.

We can probably get away with something like the following:

- If the app is running, check if it was a dockerfile deploy and don't use `--link` on that phase
- If it isn't running, allow a user to specify whether it is a dockerfile deploy or not before linking.

Thoughts @Flink ?

**Comment by oliverkane** [comment]
I've build ``` Docker-Gitlab ``` locally using the Dockerfile method. Since it looks like Dokku uses Heroku style buildpacks, would it be safe to assume that using that system to define my project would bypass this issue?  I'm unfamiliar with Heroku's buildpacks, but provided they can accomplish what a Dockerfile does, I can look into that and fork https://github.com/sameersbn/docker-gitlab.  

Thoughts?

**Comment by michaelshobbs** [comment]
I'm not certain how the plugin would handle as it seems you would want to link in the build phase for buildpack apps but not dockerfile apps and I don't think the plugin knows the type of app, right?

**Comment by josegonzalez** [comment]
@oliverkane we support [Dockerfile](http://progrium.viewdocs.io/dokku/deployment/dockerfiles/) deploys as well.

@michaelshobbs hooray for your pr :)

**Comment by oliverkane** [comment]
@michaelshobbs hooray for your pr x2.

**Comment by michaelshobbs** [comment]
I think there is something wrong with the static test. I'd like to fix that before merging #1712

**Comment by Flink** [comment]
Sorry for being late :grin: I think we could do this in the plugins (if we can indeed detect that the linked app is a docker one and not a herokuish one) but since Michael has already implemented a working solution, no need for that now :smile: And :+1: for your PR @michaelshobbs !

**Comment by oliverkane** [comment]
Many a thanks guys!  While I'm still having troubles with some package specific things to docker-gitlab, I'm able to continue troubleshooting now that the ``` --link ``` isn't a blocking Issue.  

Looks like stuck on getting that darn Postgres db to initialize. Once/If I get it up, I'll throw up a video tutorial about the journey. 

Thanks again! I do love this platform.

**Comment by Flink** [comment]
@oliverkane thanks for your support! :smile:

**Comment by oliverkane** [comment]
Cool. I got everything running aside from making this image persist. Also got RocketChat and a few other containers going now that the link is up.  Good stuff gents.
