### ISSUE TITLE
"dokku events -t" stops updating after a while

### ISSUE THREAD

**Issue by mmerickel** [progrium/dokku#1615]
I'm not sure what the deal is here but I'm watching the event logs over ssh and they stop working after a while. When I restart things work again. I've only paid attention to this over the course of days so I can't really define a "while". I can say it's not SSH because I'm also tailing nginx logs and such and they do not stop updating. It's just events.

Ubuntu 14.04.3 LTS, dokku v0.4.2.

**Comment by michaelshobbs** [comment]
Can you check on the server side and see if the log is still being written to?

**Comment by mmerickel** [comment]
Sure, I'll investigate more when I reproduce it again.
