### ISSUE TITLE
modify log format for nginx

### ISSUE THREAD

**Issue by mmerickel** [progrium/dokku#1616]
It'd be nice if globally or on a per-app basis I could configure a log format for nginx without having to override every nginx template. This could be as simple as defining a format in `/etc/nginx/conf.d/dokku.conf` and having every app use it. Then I could just change it in that file. But we could go so far as to define an $NGINX_LOG_FORMAT template parameter overridable per-app too. This issue is mostly to start the conversation. Personally I want to affect all apps in my deployment.

**Comment by u2mejc** [comment]
I think this feature may be covered in documentation of conf.d files and custom nginx.conf.template's: http://progrium.viewdocs.io/dokku/nginx/

Related: https://github.com/progrium/dokku/issues/1629

**Comment by josegonzalez** [comment]
Closing in favor of #1629.
