### ISSUE TITLE
Azure Documentation

### ISSUE THREAD

**Issue by sedouard** [progrium/dokku#1618]
It would be cool to have some installation notes and a deployment template for Azure to deploy dokku.

I actually have a [PR in progress](https://github.com/Azure/azure-quickstart-templates/pull/751) on the Azure templates repository. Once thats merged I'll add the PR with a couple quick notes for getting started on azure.

**Comment by u2mejc** [comment]
Related PR was merged : https://github.com/progrium/dokku/pull/1623 
Can see changes live here: http://progrium.viewdocs.io/dokku/installation/

**Comment by sedouard** [comment]
yup!
