### ISSUE TITLE
Add dokku trace to help output?

### ISSUE THREAD

**Issue by u2mejc** [progrium/dokku#1619]
Before I shoot over the PR, is there a reason this is a hidden feature? I entering dokku debug yes, then dokku verbose yes, until I remembered it's dokku trace yes.

**Comment by josegonzalez** [comment]
No reason, just forgot to turn it on.

I typically do `dokku trace on|off` btw.

**Comment by u2mejc** [comment]
good point, I can't remember it! Just making sure it wasn't intentional, I'm committing the one line PR now.
