### ISSUE TITLE
Dokku installation in vagrant stuck at importing herokuish into docker

### ISSUE THREAD

**Issue by dianseptiana** [progrium/dokku#1620]
I have ubuntu 14.04 fresh install Vagrant VM, and tried to install dokku v0.4.3 using bootstrap.sh. I set up the VM with 1GB memory. The problem is that the installation always stuck at "Importing herokuish into docker". Although it says that it will take about 5 minutes, but i have waited for about 30 minutes and still, the installation doesn't continue. Is it normal?

```
Setting up python3-pycurl (7.19.3-0ubuntu3) ...
Setting up python3-software-properties (0.92.37.5) ...
Setting up software-properties-common (0.92.37.5) ...
Setting up python-pycurl (7.19.3-0ubuntu3) ...
Setting up python-software-properties (0.92.37.5) ...
Setting up herokuish (0.3.4) ...
Importing herokuish into docker (around 5 minutes)
```

**Comment by josegonzalez** [comment]
That isn't normal. Can you try using the VM that comes with the dokku repository and see if that works?

**Comment by michaelshobbs** [comment]
Could be a transient issue with the docker hub or a networking issue on the client. Definitely not normal. Try destroying the vagrant machine (`vagrant destroy`) and bringing it up again (`vagrant up`).

**Comment by michaelshobbs** [comment]
Ah @josegonzalez is on it. I thought this was from our `Vagrantfile`. My bad.

**Comment by josegonzalez** [comment]
The bootstrap method should also work but I think thats a transient issue. Just want to make sure our vm works for you as well.

Are you perhaps behind a firewall or a "bad" internet connection? It's a fairly large file that needs to be downloaded/compiled.

**Comment by dianseptiana** [comment]
Thank you for your answers.

Actually I tried to run this command manually ```sudo docker build -t gliderlabs/herokuish /var/lib/herokuish```, since this code is in deb.mk. Now i can see logs that display download progress of docker.io/heroku/cedar repository. I don't know the total size of heroku cedar stack repository that need to be downloaded, but it seems the download process is quite slow. I tried to download file from another site just to test the connection, and the speed is fast enough. By the way, where i can find VM you mentioned @josegonzalez?

**Comment by josegonzalez** [comment]
@dianseptiana the vm is included with the dokku repository. Simply clone this repo and `vagrant up` in it.

**Comment by josegonzalez** [comment]
The file is about 500mb, so maybe you are being throttled on connecting to docker.io. Try downloading another large image from there. Are you on a local connection or on a VPS somewhere?

**Comment by dianseptiana** [comment]
I'm on local connection. I tried to create instance in amazon EC2, and install using bootstrap.sh. The installation completed successfully without any issues. I guess there is connection problem on my network when pull from docker.io.

I also tried the VM that come with dokku repository. When install use this method, it show logs of download process like this:
```
==> dokku: Start pulling herokuish from gliderlabs/herokuish:latest
==> dokku: docker images | grep gliderlabs/herokuish || docker pull gliderlabs/herokuish:latest
==> dokku: latest: Pulling from gliderlabs/herokuish
==> dokku: b254a22f653a: Pulling fs layer
==> dokku: a0230b138447: Pulling fs layer
==> dokku: 75231f98abec: Pulling fs layer
==> dokku: 59c44b748d4a: Pulling fs layer
==> dokku: cdc795cfce8a: Pulling fs layer
==> dokku: 612682c89906: Pulling fs layer
==> dokku: a0230b138447: Verifying Checksum
==> dokku: a0230b138447: Download complete
==> dokku: 75231f98abec: Verifying Checksum
==> dokku: 75231f98abec: Download complete
==> dokku: cdc795cfce8a: Verifying Checksum
==> dokku: cdc795cfce8a: Download complete
==> dokku: 612682c89906: Verifying Checksum
==> dokku: 612682c89906: Download complete
==> dokku: b254a22f653a: Verifying Checksum
==> dokku: b254a22f653a: Download complete
==> dokku: b254a22f653a: Pull complete
==> dokku: a0230b138447: Pull complete
==> dokku: 75231f98abec: Pull complete
```
so i can be sure that the process actually continues. Meanwhile when install using bootstrap.sh it just display ```Importing herokuish into docker (around 5 minutes)```.

**Comment by dianseptiana** [comment]
Although i tried using VM that come with dokku and it's display download process log, it still slow in my local machine. Then i found this https://github.com/docker/docker/issues/13309, i think it's related because when download smaller layers, the connection is fast. But when download the large layer with 448.2 MB size, the connection become very slow.

**Comment by josegonzalez** [comment]
Welp, this is an upstream issue, so not much we can do about it.
