### ISSUE TITLE
Missing server block in nginx conf when NO_VHOST=1

### ISSUE THREAD

**Issue by steverandy** [progrium/dokku#1625]
This is the only content in nginx conf generated by dokku:
```
upstream app_name {
  server 127.0.0.1:32773;
}
```

As per doc, what I understand is when NO_VHOST=1, dokku will still use nginx to proxy requests to dokker container.

**Comment by michaelshobbs** [comment]
Can you please provide the details outlined in our contributing doc?

**Comment by steverandy** [comment]
On this page http://progrium.viewdocs.io/dokku/nginx/

> On subsequent deploys, the nginx virtualhost will be discarded. This is useful when deploying internal-facing services that should not be publicly routeable. As of 0.4.0, nginx will still be configured to proxy your app on some random high port. This allows internal services to maintain the same port between deployments. You may change this port by setting DOKKU_NGINX_PORT and/or DOKKU_NGINX_SSL_PORT (for services configured to use SSL.)

**Comment by michaelshobbs** [comment]
Yes that is he expected behavior. We need more information. Can you please include the information requested in our contribution doc?

**Comment by steverandy** [comment]
- `uname -a`: Linux nodejs 3.13.0-57-generic #95-Ubuntu SMP Fri Jun 19 09:28:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

- `docker version`:
```
Client:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 05:37:18 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 05:37:18 UTC 2015
 OS/Arch:      linux/amd64
```
- `docker -D info`:
```
Containers: 6
Images: 11
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 23
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-57-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 2
Total Memory: 1.955 GiB
Name: nodejs
ID: JGKG:C4PX:RQRD:BMJV:QTH2:FPM5:IE3D:SHIW:2RU2:WGWE:72AX:2J2U
WARNING: No swap limit support
```

- `dokku version`: 0.4.3

- `dokku plugin`:
00_dokku-standard    0.4.0 enabled    dokku core standard plugin
  20_events            0.4.0 enabled    dokku core events logging plugin
  apps                 0.4.0 enabled    dokku core apps plugin
  backup               0.4.0 enabled    dokku core backup plugin
  build-env            0.4.0 enabled    dokku core build-env plugin
  certs                0.4.0 enabled    dokku core certificate management plugin
  checks               0.4.0 enabled    dokku core checks plugin
  common               0.4.0 enabled    dokku core common plugin
  config               0.4.0 enabled    dokku core config plugin
  docker-options       0.4.0 enabled    dokku core docker-options plugin
  domains              0.4.0 enabled    dokku core domains plugin
  enter                0.4.0 enabled    dokku core enter plugin
  git                  0.4.0 enabled    dokku core git plugin
  logs                 0.4.0 enabled    dokku core logs plugin
  named-containers     0.4.0 enabled    dokku core named containers plugin
  nginx-vhosts         0.4.0 enabled    dokku core nginx-vhosts plugin
  plugin               0.4.0 enabled    dokku core plugin plugin
  ps                   0.4.0 enabled    dokku core ps plugin
  shell                0.4.0 enabled    dokku core shell plugin
  tags                 0.4.0 enabled    dokku core tags plugin
  tar                  0.4.0 enabled    dokku core tar plugin

- `cat /home/dokku/<app>/nginx.conf` (if applicable):
upstream nodejs { 
  server 127.0.0.1:32768;
}

- Output of git push dokku:
```
-----> Discovering process types
       Default types for  -> web
-----> Releasing nodejs (dokku/nodejs:latest)...
-----> Deploying nodejs (dokku/nodejs:latest)...
-----> DOKKU_SCALE file not found in app image. Generating one based on Procfile...
-----> New DOKKU_SCALE file generated
=====> web=1
-----> Running pre-flight checks
       For more efficient zero downtime deployments, create a file CHECKS.
       See http://progrium.viewdocs.io/dokku/checks-examples.md for examples
       CHECKS file not found in container: Running simple container check...
-----> Waiting for 10 seconds ...
-----> Default container check successful!
=====> nodejs container output:
       > spuul-website@0.0.0 start /app
       > babel-node server.js
=====> end nodejs container output
-----> Running post-deploy
=====> unsupported vhost config found. disabling vhost support
-----> Setting config vars
       NO_VHOST: 1
-----> Setting config vars
       NO_VHOST: 1
-----> no nginx port set. setting to random open high port
-----> Setting config vars
       DOKKU_NGINX_PORT: 10909
-----> Creating http nginx.conf
-----> Running nginx-pre-reload
       Reloading nginx
=====> Application deployed:
       http://128.199.83.161:32768 (container)
       http://128.199.83.161:10909 (nginx)
```

Steps to Reproduce:
1. Create dokku droplet on digitalocean with `nodejs` as hostname
2. Deploy

Actual Results:
Application deployed successfully but nginx (http://128.199.83.161:10909) does not proxy correctly to container.

Expected Results:
nginx (http://128.199.83.161:10909) should proxy to container

**Comment by michaelshobbs** [comment]
@Flink @josegonzalez Wasn't there a recent change to this code after I did the initial work? Sorry I'm mobile right now

**Comment by josegonzalez** [comment]
Not as far as I am aware, no. There weren't any other meaningful nginx changes.

**Comment by michaelshobbs** [comment]
Was referring to 75b06bb02e47c26e80088ed9147f9c59bb5db5cb & dfafb7d0c72915896c2aecd4bf549523a61fd3ce

**Comment by michaelshobbs** [comment]
I verified reverting the former commit (75b06bb02e47c26e80088ed9147f9c59bb5db5cb) resolves this particular regression. @Flink this looks like your change. Can you have a look and potentially add a test case too?

**Comment by Flink** [comment]
@michaelshobbs I’ll try to do that yes. So we need to handle specifically `NO_VHOST=1`.

**Comment by michaelshobbs** [comment]
yeah `NO_VHOST` no longer means no nginx

**Comment by Flink** [comment]
@michaelshobbs fix was easy after all :) https://github.com/progrium/dokku/pull/1643
