### ISSUE TITLE
Using a v0.3.x Plugin on v0.4.3

### ISSUE THREAD

**Issue by hhff** [progrium/dokku#1631]
Hi guys!

I need to use this plugin: https://github.com/nonken/dokku-graphicsmagick-plugin

I just deploy'd an app to a new box with 0.4.3 - and this plugin doesn't play nicely.  There's no toml file - and event when I add it, it still doesn't inject GM into the container on a `ps:rebuild`

What can I do to get this working?

hx

**Comment by hhff** [comment]
Ideally just the bare minimum to get it going -

**Comment by josegonzalez** [comment]
Why not just use the [`dokku-apt`](https://github.com/F4-Group/dokku-apt) plugin?

**Comment by hhff** [comment]
Works great!!  Ahhhhhhh I love dokku & u guys so much
