### ISSUE TITLE
App being served at root domain instead of subdomain

### ISSUE THREAD

**Issue by 007design** [progrium/dokku#1646]
So far I've had pretty good success getting Dokku up and running using vagrant and deploying an app but I have a strange problem.  My app is being served properly but it's being served at http://dokku.me rather than at the subdomain.domain address I would expect (for example, http://myapp.mydomain.com).  Anyone have an idea what might be causing this?  Did I misconfigure something?
Thanks in advance!

**Comment by josegonzalez** [comment]
Nginx serves the first app by default as specified [here](http://progrium.viewdocs.io/dokku/nginx/#default-site). Are you *also* unable to get the subdomain working? I would suggest ensuring that you have a dns or `/etc/hosts` entry if it's being deployed to your local vagrant instance.

Please also provide all the information we ask for in our [CONTRIBUTING](https://github.com/progrium/dokku/blob/master/CONTRIBUTING.md#reporting-other-issues) documentation.

**Comment by josegonzalez** [comment]
@007design did you figure out your issue? If so, mind posting here what the problem was to benefit others?

**Comment by 007design** [comment]
wish i could say that i had figured it out but i think dns in a virtual machine is beyond me. :(

**Comment by josegonzalez** [comment]
You just need to set an entry in your `/etc/hosts` for your app:

```
# modify as appropriate
10.0.0.2 subdomain.dokku.me
```

And then you should be able to access it, assuming you are using `10.0.0.2` as the vm's IP and `dokku.me` as your domain.

**Comment by 007design** [comment]
what i understood from the docs was that i would add dokku.me to the hosts file and requests for subdomains would be routed to the app running on that container.  however, i don't see this behavior.  my app is served at dokku.me but not at myapp.dokku.me
sorry, my understanding of this is very poor.

**Comment by josegonzalez** [comment]
No. Like I said, if you are using the local setup, then you'll need to add entries for each domain to your hosts file.

**Comment by 007design** [comment]
but then how would i access different apps if not via myapp1.mydomain and myapp2.mydomain, etc.?

**Comment by josegonzalez** [comment]
You need to add entries for each of those subdomains. If you were using a VPS, then you would set a wildcard dns record for your domain name.

**Comment by adrianmoya** [comment]
You can setup a wildcard subdomain if your OS is ubuntu. Check this answer for how to do it:
http://stackoverflow.com/questions/22313142/wildcard-subdomains-with-dnsmasq

Then all subdomains will resolve to the ip of your dokku host.

**Comment by michaelshobbs** [comment]
Seems like there isn't anything else to do here. Please feel free to comment if that is not the case.
