### ISSUE TITLE
dokku certs:add only supports tarball

### ISSUE THREAD

**Issue by hhff** [progrium/dokku#1658]
`root@server:~# dokku certs:add production server.crt server.key`

outputs:

`Tar archive containing server.crt and server.key expected on stdin`

It should take those files separately, right?

**Comment by josegonzalez** [comment]
Interesting. Are the `server.crt` and `server.key` in the directory where you ran that command?

**Comment by hhff** [comment]
Yessir - but in my case they're actually named `example_com.crt` `example_com.key`

**Comment by u2mejc** [comment]
ok to close?

**Comment by hhff** [comment]
thanks dudes!
