### ISSUE TITLE
Deploy fail on Node version update when using native modules (node-gyp)

### ISSUE THREAD

**Issue by aral** [progrium/dokku#1663]
I can recreate this consistently:

On an app that has native dependencies (that use node-gyp)…

1. Update Node version for your app.
2. Deploy via dokku.

Deployment fails with node-gyp error (lost the actual error message and implemented the workaround, below). It looks like it’s still trying to install the versions in the previous version of package.json.

Workaround:

1. Make note of any config options and docker-options
2. Destroy the app (`dokku app:destroy app-name`)
3. Deploy again via dokku
4. Re-apply the options you made note of in 1.

(Needless to say a bit of a faff and results in downtime.)

Any ideas.

(Sorry, I lost the actual error message output this time around. Can update this ticket when I encounter it again — shouldn’t be long as I’ll be updating everything to Node 5.0.0 soon.)

**Comment by michaelshobbs** [comment]
Sounds like a result of dokku caching `node_modules`. I ran into something similar with `node-gyp` when upgrading to node 4. 

The workaround is to `rm $DOKKU_ROOT/$APP/cache` and deploy.

**Comment by aral** [comment]
Hey @michaelshobbs, I like your workaround *way* better — thank you. Will try that when I’m upgrading to 5.0.0 :)

**Comment by michaelshobbs** [comment]
It would be great if the buildpack had some smarts around this....

**Comment by aral** [comment]
I can take a look at it when I’m upgrading to 5.0.0. Haven’t really peeked under the hood of Dokku yet :) (And, of course, if anyone else wants to tackle it in the meanwhile…) ;)

**Comment by josegonzalez** [comment]
It's a heroku buildpack, so the change would have to go upstream.

There is an issue open for exposing a dokku command for clearing cache (amongst others) in #1570, so I'm going to close this for now.
