### ISSUE TITLE
Adopting a Code of Conduct

### ISSUE THREAD

**Issue by josegonzalez** [progrium/dokku#1669]
I just recently read this [lovely blog post](http://www.coglib.com/~icordasc/blog/2015/11/corporations-and-oss-do-not-mix.html)<sup>[1]</sup> and realized we don't have a code of conduct. 

I think the `CONTRIBUTING.md` file was great for documenting how we want people to interact on a technical level with the project. Given the influx of heroku users looking to setup dokku on their own - and in some cases a bit of assholery in irc regarding dokku's working state (or sometimes lack therof) - I'd like us to adopt a code of conduct to help nip that in the bud.

Hopefully by adopting a code of conduct, we can point users to the document when they are "misbehaving" and help guide our community to being better :) . I know I haven't been the best role model at times online either - woooo alcohol! - so I'd also say that we as maintainers should *also* be held to this high standard.

I've been reading through the [Contributor Covenant](http://contributor-covenant.org/) and think their latest version - [1.3.0](http://contributor-covenant.org/version/1/3/0/code_of_conduct.md) - would fit us just fine.

Does anyone have any objections/additions to the proposed code of conduct?

---

<sup>[1] Seriously, go read it</sup>

**Comment by zachfeldman** [comment]
Down with this

**Comment by callahad** [comment]
:+1: Contributor Covenant v1.3.0 looks good to me

**Comment by callahad** [comment]
Also, I've been a crotchety old curmudgeon re: Debian / minimizing impact on the host system / etc. Everyone on the Dokku side that I've interacted with has been super reasonable, respectful, and friendly. So, y'all are already doing pretty awesomely as custodians of a F/OSS project, and hopefully enshrining that awesomeness in a Code of Conduct will encourage more people to get involved.
