### ISSUE TITLE
00_dokku-standard/commands: line 171: /home/dokku/<app>/PORT.*: No such file or directory

### ISSUE THREAD

**Issue by kenips** [progrium/dokku#1678]
I'm getting this after upgrading from 0.3.x to 0.4.4 and after deploy:

```
/var/lib/dokku/plugins/enabled/00_dokku-standard/commands: line 171: /home/dokku/<app>/PORT.*: No such file or directory
```

I see that I have `NO_VOST=1` set so the command is doing the right thing. Question is how do I get this PORT file that it is looking for? This app has no external port that needs to be exposed.

**Comment by michaelshobbs** [comment]
Ah yes I do believe this is a bug.
