### ISSUE TITLE
Rights inside a container

### ISSUE THREAD

**Issue by krokhale** [progrium/dokku#1679]
I am trying to run some commands inside the container. Tried both:

    dokku enter
    dokku run 

Also, tried the above with sudo. I am able to enter but I am always getting this whenever i try to run anything(sudo does not exist inside):

    E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)
    E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?

What am i missing? Or is this not possible?

**Comment by michaelshobbs** [comment]
You are not root when starting a new container or entering an existing one with `dokku run` or `dokku enter`. 

You would need to user `docker` commands to be root. 

However if you are attempting to install a package, you should be aware that app images are discarded between deployment so your package installation would not persist. If you want to install a package for use by your app, you could use the [dokku-apt](https://github.com/F4-Group/dokku-apt) plugin.

**Comment by michaelshobbs** [comment]
Please let us know if you have any further questions here.

**Comment by krokhale** [comment]
Thanks Michael, so if that's the case, what would a good example of a use case for using dokku run or enter be?

**Comment by josegonzalez** [comment]
@krokhale both are documented in our docs on [one-off processes](http://progrium.viewdocs.io/dokku/deployment/one-off-processes/).

**Comment by boxed** [comment]
Current link: http://dokku.viewdocs.io/dokku/processes/one-off-tasks/

**Comment by josegonzalez** [comment]
Note that the docs for enter and run were split up. Checkout the "process management" section in the sidebar.

**Comment by krokhale** [comment]
Five years and still around @josegonzalez , dokku is pretty awesome :)

**Comment by nileio** [comment]
the answer to this question by using dokku-apt plugin is pretty misleading and unfortunatley resulted me cleaning up a lot in my server. i think the question is about installing additional packages INSIDE the container, but that dokku-apt actually injects packages to the host-
