### ISSUE TITLE
port issue 502 bad gateway

### ISSUE THREAD

**Issue by melihmucuk** [progrium/dokku#1680]
I develop sample go app with gin-gonic, If I set port `:8080` in codebase, I'm getting 502 bad gateway error. But If I set port `:5000`, It works. I tried set the port after deploy with this command but nothing changed.

`dokku config:set myApp DOKKU_DOCKERFILE_PORT=8080`

**Comment by michaelshobbs** [comment]
The app inside the container must listen on port `5000`.  You can set `$DOKKU_NGINX_PORT` to control the external listening port.

**Comment by melihmucuk** [comment]
how can I set `$DOKKU_NGINX_PORT` ?

**Comment by michaelshobbs** [comment]
Using the `dokku config` command. `dokku help` will guide you for syntax.

**Comment by melihmucuk** [comment]
thanks !

**Comment by michaelshobbs** [comment]
To clarify, are you deploying using a buildpack or a dockerfile?

**Comment by michaelshobbs** [comment]
Also I see why setting `$DOKKU_DOCKERFILE_PORT` would seem to make sense here. I'd have to dig further to see why that didn't work.

**Comment by melihmucuk** [comment]
I didn't use buildpack or dockerfile, I just develop and deploy my app to docker, I'm trying to learn dokku commands, therefore tried `$DOKKU_DOCKERFILE_PORT` command. But I realize my app deployed with buildpack (Herokuish).

**Comment by michaelshobbs** [comment]
To clarify here, dokku only uses `$DOKKU_DOCKERFILE_PORT` when deploying an app using a `dockerfile`. This is because a user can create a `dockerfile` with an arbitrary `EXPOSE` clause.

In the case of the default buildpack/heroku-style deployment dokku supports the heroku described implementation of setting a `$PORT` environment variable for your app to use to determine which port to bind to inside the container. See [here](https://devcenter.heroku.com/articles/runtime-principles#web-servers)

In order to manage on which port to access your app externally, as previously described, you will want to make use of the `$DOKKU_NGINX_PORT`. 

Let us know if this has answered your question.

**Comment by michaelshobbs** [comment]
Sounds like you got this working with setting `$DOKKU_NGINX_PORT`. Please feel free to comment if there is still an open question here.

**Comment by melihmucuk** [comment]
`$DOKKU_NGINX_PORT` is not working for me. Only works when my app serve from `:5000` and `$DOKKU_NGINX_PORT=80`.

If I set my app to serve from `:8080` and `$DOKKU_NGINX_PORT=8080`, It's not working.

create app logs:

<pre><code>Melih-MacBook-Air:myApp melih$ git push dokku master
Counting objects: 119, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (106/106), done.
Writing objects: 100% (119/119), 113.58 KiB | 0 bytes/s, done.
Total 119 (delta 9), reused 0 (delta 0)
-----> Cleaning up...
-----> Building myApp from herokuish...
-----> Adding BUILD_ENV to build environment...
-----> Go app detected
-----> Checking Godeps/Godeps.json file.
-----> Installing go1.5.1... done
-----> Running: godep go install -tags heroku ./...
-----> Discovering process types
       Procfile declares types -> web
-----> Releasing myApp (dokku/myApp:latest)...
-----> Deploying myApp (dokku/myApp:latest)...
-----> DOKKU_SCALE file not found in app image. Generating one based on Procfile...
-----> New DOKKU_SCALE file generated
=====> web=1
-----> Running pre-flight checks
       For more efficient zero downtime deployments, create a file CHECKS.
       See http://progrium.viewdocs.io/dokku/checks-examples.md for examples
       CHECKS file not found in container: Running simple container check...
-----> Waiting for 10 seconds ...
-----> Default container check successful!
=====> myApp container output:
=====> end myApp container output
-----> Running post-deploy
-----> Creating new /home/dokku/myApp/VHOST...
-----> Setting config vars
       DOKKU_NGINX_PORT: 80
-----> Configuring myApp.mydomain.com...
-----> Creating http nginx.conf
-----> Running nginx-pre-reload
       Reloading nginx
-----> Setting config vars
       DOKKU_APP_RESTORE: 1
=====> Application deployed:
       http://myapp.mydomain.com

To dokku@mydomain.com:myApp
 * [new branch]      master -> master</code></pre>

app:

<pre><code>package main

import (
	"github.com/gin-gonic/gin"
)

func main() {
	gin.SetMode(gin.ReleaseMode)
	r := gin.Default()
	r.GET("/ping", func(c *gin.Context) {
		c.JSON(200, gin.H{"status": true})
	})
	r.Run(":8080")
}</code></pre>

dokku config:

<pre><code>root@dokku:~# dokku config myApp
=====> myApp config vars
DOKKU_APP_RESTORE: 1
DOKKU_NGINX_PORT:  8080</code></pre>

**Comment by michaelshobbs** [comment]
You are hard coding your app to listen on 8080 inside the container. That port is not in any way related to what port you actually access your app. My recommendation is to set that to 5000 and be done or have it bind to `$PORT` as Heroku prescribes. Then set `$DOKKU_NGINX_PORT` to control on what port you can access your app via a browser or some other client.

**Comment by melihmucuk** [comment]
Ok, I changed last line of my app to `r.Run(":" + os.Getenv("PORT"))` and it works. Thanks!

**Comment by michaelshobbs** [comment]
Cool
