### ISSUE TITLE
rails console error "switch to inspect mode"

### ISSUE THREAD

**Issue by TheNotary** [progrium/dokku#1686]
When attempting to get into the rails console, I hit this error:

```
$ dokku run oc rails c
Loading production environment (Rails 4.1.2)
Switch to inspect mode.

$ 
```

My DOKKU_SCALE file only has a web process specified.  My current work around is to ssh into the server, `sudo su` and then do `dockker run <app name> bash` and then I have a console to the app.

**Comment by josegonzalez** [comment]
Do you have a tty setup for your ssh command?

**Comment by TheNotary** [comment]
Oops, my mistake, modifying my alias as per http://progrium.viewdocs.io/dokku/remote-commands/ solved it, thanks for the help, Josegonzalez!

**Comment by nimacpp** [comment]
in git bash what should i do ?

**Comment by josegonzalez** [comment]
This is a 7 year old ticket. Please don't comment on old tickets, and instead open a new one. Thanks.
