### ISSUE TITLE
vagrant nfs

### ISSUE THREAD

**Issue by crisward** [progrium/dokku#1689]
We've been using vagrant / virtualbox to develop our websites before pushing them to a live server also running dokku.

We access our development websites through an nfs share allowing us to update the code without restarting the container. We've been using dokku v0.2.3.

I've recently started updating our projects to the latest versions of everything and now get this error.
```
chown: changing ownership of '/app/public_html': Operation not permitted
```
It would appear dokku now uses a new user per container and chowns the folder at start, which is fine, but doesn't appear to work with NFS.

Has anyone got any ideas how I can either:
* Override this functionality in the dev environment, ie revert to root in each container
* Get NFS to play nice with this setup.

For reference this is the line in my vagrant file which sets up the share
```
  # nfs added
  config.nfs.map_uid = Process.uid
  config.nfs.map_gid = Process.gid
  
  #websites
  config.vm.synced_folder "/websites/", "/websites",
  type: "nfs",
  mount_options:['actimeo=2']
```

**Comment by josegonzalez** [comment]
Interesting. I don't use dokku under nfs. Would `rsync` maybe be a better option in your case?

**Comment by crisward** [comment]
Thanks for the very promt response, that's worked, the share folder is 4gb, so it took an eternity to start up the first time, should hopefully be quicker on restart. New settings are

```
  #websites
  config.vm.synced_folder "/websites/", "/websites",
  type: "rsync",
  rsync__exclude: ".git/",
  rsync__chown:false,
  rsync__auto:true
```

**Comment by josegonzalez** [comment]
Closing as this isn't a feature we support and there is an answer available now :)

**Comment by crisward** [comment]
Just as a note to anyone else having this issue. Rsync is really slow. NFS has file permission issues, but these can be got around with this plugin <https://github.com/gael-ian/vagrant-bindfs>

I'm sharing a root folder on my mac called `/websites/` inside the vagrant box with the following addition to my vagrant file.
```
  #websites
  config.vm.synced_folder "/websites", "/websites-nfs",
  type: "nfs",
  mount_options:['actimeo=2']
  config.bindfs.bind_folder "/websites-nfs", "/websites",
  perms: "u=rwx:g=rwx:o=rwx",
  options:"nonempty",
  chown_ignore: true,
  chgrp_ignore: true
```

The fixes the above issue without any loss in performance. Hopefully this will help others who are both developing and deploying with dokku.

**Comment by josegonzalez** [comment]
That's weird. Rsync has actually been faster for me than nfs. I wonder if the docker aufs setup is screwing around with the local vm performance.

Glad you got to the bottom of this though :)
