### ISSUE TITLE
Setting config --global DOKKU_RM_CONTAINER=1 is ignored in dokku run

### ISSUE THREAD

**Issue by petewest** [progrium/dokku#1704]
The documentation here: http://progrium.viewdocs.io/dokku/deployment/one-off-processes/ says to set `dokku config:set --global DOKKU_RM_CONTAINER=1` to automatically remove containers when using `dokku run`.

It looks like those config vars are not loaded during the `run` command. 

It might need another `eval "$(config_export global)"` around https://github.com/progrium/dokku/blob/master/plugins/00_dokku-standard/commands#L136

**Comment by michaelshobbs** [comment]
Thanks for the bug report. Fix pending.
