### ISSUE TITLE
post install problem

### ISSUE THREAD

**Issue by UlTriX** [progrium/dokku#1710]
Hi,

I did a sudo apt-get install dokku and a configuration screen appeared and I mistakenly
choose /root/.ssh/id_rsa.pub and now apt-get gives me this error everytime.

Is it possible to call again the configuration screen?

/var/lib/dpkg/info/dokku.postinst: 73: /var/lib/dpkg/info/dokku.postinst: cannot open /root/.ssh/id_rsa.pub: No such file
dpkg: error processing package dokku (--configure):
 subprocess installed post-installation script returned error exit status 2
Errors were encountered while processing:
 dokku
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by josegonzalez** [comment]
What version of dokku are you attempting to install?

**Comment by UlTriX** [comment]
I was upgrading to 0.4.4. (and i can see it correctly upgraded)

Previous version i installed via repository and did 

# upgrade to debian package-based installation
sudo make install

**Comment by josegonzalez** [comment]
Do you have that file there? You may need to clear out your apt preferences.

**Comment by UlTriX** [comment]
I don't. As I said i mistakenly did an ok on the default.

How can I clear out my apt preferences?

**Comment by josegonzalez** [comment]
`echo PURGE | debconf-communicate dokku`

**Comment by UlTriX** [comment]
thank you very much
