### ISSUE TITLE
Sensitive data has world readable permissions when using plugins

### ISSUE THREAD

**Issue by leshik** [progrium/dokku#1711]
Hi!

When using plugins (mysql in my case), dokku stores sensitive information in cleartext and with world readable permissions in /var/lib/services (mysql user & root passwords etc.):

drwxr-xr-x 5   999 docker 4096 Nov 16 13:48 data
-rw-r--r-- 1 dokku dokku    65 Oct 31 16:04 ID
-rw-r--r-- 1 dokku dokku     4 Nov 16 14:18 LINKS
-rw-r--r-- 1 dokku dokku    17 Oct 31 16:04 PASSWORD
-rw-r--r-- 1 dokku dokku    17 Oct 31 16:04 ROOTPASSWORD

**Comment by josegonzalez** [comment]
I would open this issue in one of the plugins - mysql in your case - rather than here.
