### ISSUE TITLE
Remote repo not updating

### ISSUE THREAD

**Issue by zachfeldman** [progrium/dokku#1716]
I'm working on the apps:rename command (see my pull request) and for some reason, my instance's code isn't updating anymore. I push to it, the push is successful, then the code in the container doesn't get changed.

Any ideas where to start looking here?

**Comment by michaelshobbs** [comment]
Providing most of the info in the contributing doc would be a good place to start. Most importantly, a gist of your push with dokku trace on.

**Comment by zachfeldman** [comment]
FIXED IT.

It's because my `apps:rename` function doesn't change the URLS and VHOST file.

**Comment by zachfeldman** [comment]
To clarify: once I renamed the app to the correct name in those files, I ran `dokku ps:rebuild <appname>` and suddenly the repo was updated.
