### ISSUE TITLE
Node not downloading + installing.

### ISSUE THREAD

**Issue by nathanmarks** [progrium/dokku#1722]
Just trying to get a basic app up and running. Been having a ton of issues including dokku thinking there is a container when there isn't and having to try all sorts of combinations of reboots/rebuilds just to get my app running. Now I'm seeing this when trying to build:

**EDIT**: is this an issue with herokuish?

```
-----> Installing binaries
       engines.node (package.json):  4.2.2
       engines.npm (package.json):   unspecified (use default)
       
       Downloading and installing node 4.2.2...
       Unable to download node 4.2.2; does it exist?
```

**Comment by michaelshobbs** [comment]
Sounds like it could be an issue with semver or node. Does this app deploy on Heroku?

**Comment by nathanmarks** [comment]
@michaelshobbs Never deployed it on heroku, but I had the container running on this exact VM just earlier today. How can I begin to debug this?

Also it isn't checking semver (unless I'm mistaken) as the version is explicitly listed as "4.2.2".

**Comment by michaelshobbs** [comment]
Try it on Heroku to see if the issue persists between envs.

**Comment by nathanmarks** [comment]
No problem on heroku:

```
remote: -----> Installing binaries
remote:        engines.node (package.json):  4.2.2
remote:        engines.npm (package.json):   unspecified (use default)
remote:        
remote:        Downloading and installing node 4.2.2...
remote:        Using default npm version: 2.14.7
remote: 
remote: -----> Restoring cache
remote:        Skipping cache restore (new runtime signature)
```

**Comment by josegonzalez** [comment]
Can you include the debugging output we ask for in our `CONTRIBUTING.md`? I'm curious to see what is stalling here...

**Comment by michaelshobbs** [comment]
Could be an old version of the buildpack. We just released new versions of dokku and herokuish yesterday. You might try an upgrade OR setting `$BUILDPACK_URL` so herokuish downloads the new one for you on deploy.

**Comment by nathanmarks** [comment]
Absolutely!

- `uname -a`:

```
Linux dokku.poweredbysearch.com 3.13.0-68-generic #111-Ubuntu SMP Fri Nov 6 18:17:06 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

- `docker version`:

```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64
```

- `docker -D info`:

```
Containers: 9
Images: 79
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 97
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-68-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 2
Total Memory: 1.955 GiB
Name: dokku.poweredbysearch.com
ID: Y6UD:HPJW:7KTL:BSRU:U72H:CR43:NRH3:7XWS:SQMY:FHE2:IRI2:3ZZT
WARNING: No swap limit support
```

- `dokku version`:

`0.4.5`

- `dokku plugin`:

```
  00_dokku-standard    0.4.0 enabled    dokku core standard plugin
  20_events            0.4.0 enabled    dokku core events logging plugin
  apps                 0.4.0 enabled    dokku core apps plugin
  backup               0.4.0 enabled    dokku core backup plugin
  build-env            0.4.0 enabled    dokku core build-env plugin
  certs                0.4.0 enabled    dokku core certificate management plugin
  checks               0.4.0 enabled    dokku core checks plugin
  common               0.4.0 enabled    dokku core common plugin
  config               0.4.0 enabled    dokku core config plugin
  docker-options       0.4.0 enabled    dokku core docker-options plugin
  domains              0.4.0 enabled    dokku core domains plugin
  enter                0.4.0 enabled    dokku core enter plugin
  git                  0.4.0 enabled    dokku core git plugin
  logs                 0.4.0 enabled    dokku core logs plugin
  mariadb              1.0.0 enabled    dokku mariadb service plugin
  named-containers     0.4.0.1 enabled    dokku core named containers plugin
  nginx-vhosts         0.4.0 enabled    dokku core nginx-vhosts plugin
  plugin               0.4.0 enabled    dokku core plugin plugin
  postgres             1.0.0 enabled    dokku postgres service plugin
  ps                   0.4.0 enabled    dokku core ps plugin
  redis                1.0.0 enabled    dokku redis service plugin
  shell                0.4.0 enabled    dokku core shell plugin
  tags                 0.4.0 enabled    dokku core tags plugin
  tar                  0.4.0 enabled    dokku core tar plugin
```

- Output of failing dokku commands with `dokku trace on` 

The output is huge (from git push dokku master), do you need it?

**Comment by michaelshobbs** [comment]
You could gist the output. Regarding the buildpack version, `herokuish` is using `v86` and `v87` is the latest. Try setting `dokku config:set <app> BUILDPACK_URL=https://github.com/heroku/heroku-buildpack-nodejs#v87` and redeploying.

**Comment by michaelshobbs** [comment]
This is where your deploy is failing. Could be a timeout?

**Comment by nathanmarks** [comment]
@michaelshobbs Looks like it

```
-----> Fetching custom buildpack
```

Fails after that.

**Comment by michaelshobbs** [comment]
oh some sort of networking issue inside the container. a gist of that deploy with dokku trace on will show a little more but it's probably a networking issue.

**Comment by nathanmarks** [comment]
@michaelshobbs Here's a gist of the deployment output:

https://gist.github.com/nathanmarks/6fc295181be7bc119322

**Comment by nathanmarks** [comment]
@michaelshobbs I rebooted the server, no luck. Restarted the docker service... worked.

Apologies for the time -- first time using docker.

**Comment by michaelshobbs** [comment]
No worries. Glad you got it sorted out.
