### ISSUE TITLE
Generating self signing ssl cert gives chmod error

### ISSUE THREAD

**Issue by Corstiaan84** [progrium/dokku#1724]
Hi there.

When I try to run "dokku certs:generate APP DOMAIN" I get the openSSL questions and all seems fine. Yet it finished with this statement:

-----> Installing certificate and key...
chmod: cannot access ‘/home/dokku/everseller/tls/server.csr’: No such file or directory

When I run "dokku ps:restartall" to restart my app I see these lines:

-----> No matching configured domains for everseller found in SSL certificate. Your app will show as insecure in a browser if accessed via SSL -> this is ok

-----> Please add appropriate domains via the dokku domains command -> my app has the appropriate domain installed.

-----> Creating https nginx.conf -> So I guess some SSL stuff is getting configured?

The app restarts successfully and serves my app fine without ssl. But when requesting the app over https the connections get refused.

What would be a solution? :-)

I did not have this issue under 0.4.4.

Thanks!

**Comment by josegonzalez** [comment]
Seems #1708 caused this. Might be worth backing out that change somehow.

@petewest since you wanted the original change, what do you think the permissions should be?

**Comment by petewest** [comment]
The chmod error is because the .csr is generated in $TMP_WORK_DIR and not copied/moved to $APP_SSL_PATH so it really doesn't exist to chmod.  Has it copied the .key & .crt to the tls folder?

If not, you could 770 $APP_SSL_PATH, and 660 the files so they can be overwritten or change the `cp` , `mv` and `chmod` to use sudo.

**Comment by josegonzalez** [comment]
It should be copied over here: https://github.com/progrium/dokku/pull/1708/files#diff-226056642bb78caf7bee818b3ea48ce3R96.

**Comment by Corstiaan84** [comment]
Thanks for the quick response :-). I am new to unix/bash. @petewest, could you please describe your solution in beginner terms so I can apply it?

**Comment by petewest** [comment]
@josegonzalez that line moves the .crt & .key, but https://github.com/progrium/dokku/pull/1708/files#diff-226056642bb78caf7bee818b3ea48ce3R98 also tries to change a .csr which I think is only in $TMP_WORK_DIR

@Corstiaan84 it should be possible to get yours up by running the following: 

    sudo touch /home/dokku/everseller/tls/server.csr
    sudo chown dokku:dokku /home/dokku/testapp/tls/server.csr
    dokku certs:generate APP DOMAIN

This should create the file that's missing and causing an error, then re-generate the certs and set everything back up again (I think...)

**Comment by josegonzalez** [comment]
Oh gotcha, that makes sense. Mind making a PR to fix that?

**Comment by Corstiaan84** [comment]
@petewest thanks :-).
Removed the cert to start with clean slate. Ran "sudo touch /home/dokku/everseller/tls/server.csr" and got this message:

"touch: cannot touch ‘/home/dokku/everseller/tls/server.csr’: No such file or directory"

Ideas? :-)

**Comment by petewest** [comment]
@Corstiaan84 certs:remove deletes that tls folder, you can recreate it (and the temporary fix):

    sudo mkdir /home/dokku/everseller/tls/
    sudo touch /home/dokku/everseller/tls/server.csr
    sudo chown -R dokku:dokku /home/dokku/everseller/tls

Then run your certs:generate as before.

@josegonzalez I'll create a test environment to see if I can recreate the original issue so I can make sure this is all that's required to fix it.

**Comment by Corstiaan84** [comment]
@petewest Ok, that worked thanks :-). No errors.

However, the https urls still gets refused. After the succesfull restart of the app, I see these two lines at the end:
=====> Application deployed:
http://app-domain.com
http://app-domain.com

Shouldn't one of these two read httpS://app-domain.com?

**Comment by michaelshobbs** [comment]
Fixed with #1732
