### ISSUE TITLE
Adding plugins in Vagrantfile

### ISSUE THREAD

**Issue by gaborcsardi** [progrium/dokku#1731]
I was wondering if it is possible to install some dokku plugins from the `Vagrantfile`? Can I just add another `vm.vm.provision` after the `make dokku-installer` line? At this stage dokku is not fully configured yet, is that a problem?

Or is there any other way to add plugins automatically?

**Comment by u2mejc** [comment]
@gaborcsardi The Vagrantfile is meant for local development environments mainly, it's safe to add more command line arguments since you can always tear it down and start fresh again. If this is a production server, please make sure you use the deb package as noted in the docs.

**Comment by josegonzalez** [comment]
Something I do locally for development is mount a bunch of plugins into place so that `vagrant up` picks them up and installs them properly. Quite useful for testing the plugin lifecycle.

**Comment by michaelshobbs** [comment]
@josegonzalez what do you mean by 'mount' specifically?

**Comment by josegonzalez** [comment]
Something like:

```rb
vm.vm.synced_folder File.dirname(__FILE__) + "/../plugins/dokku-postgres", "cd /var/lib/dokku/plugins/available/postgres"
```

**Comment by gaborcsardi** [comment]
@u2mejc Yes, it is for local development, I want to make it as easy as possible for users to run a multi-container app on their own laptop. 

So as I understand, it is not a problem that dokku is not configured when I install the plugin? But now that I think about it, I can just configure dokku from Vagrant, and then install the plugins. :)
