### ISSUE TITLE
Add nginx.conf.template to repository dokku

### ISSUE THREAD

**Issue by fabdelgado** [progrium/dokku#1736]
There nginx.conf.template way to add to the repository?
When making the deploy this configuration file take?
Thanks

**Comment by michaelshobbs** [comment]
Not 100% certain what the question is but lemme take a stab at it.

It sounds like you want to send your `nginx.conf.template` to dokku with your app repo. If that is true, you can check it into the root of your app repo and it will be used in the next deployment that you push to dokku.

**Comment by michaelshobbs** [comment]
ref: #1739

**Comment by josegonzalez** [comment]
@fabdelgado Yes, if you deploy your app with a new `nginx.conf.template` in the repo, it will be applied during that deploy. If you remove it, we will still use the last manually specified config.

**Comment by fabdelgado** [comment]
Thankyou

**Comment by fabdelgado** [comment]
Add in nginx.conf.template 
   if ($scheme = http) {
        return 301 https://$server_name$request_uri;
}

When I do deploy, message:

reloading nginx
remote: nginx: [emerg] invalid condition "=" in /home/dokku/tilo/nginx.conf:33
remote: nginx: configuration file /etc/nginx/nginx.conf test failed

**Comment by michaelshobbs** [comment]
The template gets parsed via eval I believe. You will need to escape your `$`

example:
```
    if (\$http_x_forwarded_proto != 'https') {
      rewrite ^ https://\$host\$request_uri? permanent;
    }
```

**Comment by michaelshobbs** [comment]
Also you can inspect the parsed version in `/home/dokku/tilo/nginx.conf` to see what happened after the template was parsed.

**Comment by fabdelgado** [comment]
Thankyou
