### ISSUE TITLE
Can Deb package Recommend instead of Depend on herokuish

### ISSUE THREAD

**Issue by beverku** [progrium/dokku#1738]
We have a dokku installation environment that is completely behind a firewall, and the only internet access is to proxy apt (and other) package repositories.  We currently have a working proxy to be able to GET and install the dokku deb package.  However, installing in this manner fails while installing the herokuish package, because it runs a curl to github.  

We are using Dokku with Dockerfile based building application building, so the herokuish package is unneeded in our situation.

Changing the herokuish package to Recommends instead of Depends would allow me to skip the installation of that package by specifying ```--no-install-recommends```, but herokuish would still be installed by other users by default.

**Comment by josegonzalez** [comment]
@beverku PRs welcome.

Are you able to pull images from docker hub? How are you going to be deploying things?

**Comment by beverku** [comment]
I will create a PR, assuming you are OK with the proposed change.

Yes, we have a proxy to docker hub as well.
