### ISSUE TITLE
Interface web

### ISSUE THREAD

**Issue by fabdelgado** [progrium/dokku#1741]
It could build on rails or other language a web interface to manage simplest Dokku.

**Comment by josegonzalez** [comment]
Sorry, this is outside of the scope of dokku. If anything, we will build a daemon that users can build apis on top of, and then web interfaces for those APIs.

If you want to work on #1559 - which may lead to an official web project, though not in the core - that would be pretty pro :)

**Comment by fabdelgado** [comment]
@josegonzalez  thankyou, There is a project for this?
