### ISSUE TITLE
Config en nginx cause net::ERR_TOO_MANY_REDIRECTS.

### ISSUE THREAD

**Issue by fabdelgado** [progrium/dokku#1743]
Config en nginx cause net::ERR_TOO_MANY_REDIRECTS.

Any ideas?
```
server {
  listen      [::]:$NGINX_PORT;
  listen      $NGINX_PORT;
  server_name $NOSSL_SERVER_NAME;
  access_log  /var/log/nginx/${APP}-access.log;
  error_log   /var/log/nginx/${APP}-error.log;

  listen      443 ssl;
  ssl_certificate     /home/dokku/tilo/tls/ssl-bundle.crt;
  ssl_certificate_key /home/dokku/tilo/tls/server.key;


  location    / {

    proxy_pass  http://$APP;
    proxy_http_version 1.1;
    proxy_set_header Upgrade \$http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host \$http_host;
    proxy_set_header X-Forwarded-Proto \$scheme;
    proxy_set_header X-Forwarded-For \$remote_addr;
    proxy_set_header X-Forwarded-Port \$server_port;
    proxy_set_header X-Request-Start \$msec;
  }
  include $DOKKU_ROOT/$APP/nginx.conf.d/*.conf;
}
```

**Comment by michaelshobbs** [comment]
What are the contents of the nginx.conf in the deployed app directory?

**Comment by fabdelgado** [comment]
@michaelshobbs  nginx.conf


erver {
  listen      [::]:80;
  listen      80;
  server_name tilo.dobled.uy ;
  access_log  /var/log/nginx/tilo-access.log;
  error_log   /var/log/nginx/tilo-error.log;

  listen      443 ssl;
  ssl_certificate     /home/dokku/tilo/tls/ssl-bundle.crt;
  ssl_certificate_key /home/dokku/tilo/tls/server.key;


  location    / {

    proxy_pass  http://tilo;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection upgrade;
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header X-Request-Start $msec;
  }
  include /home/dokku/tilo/nginx.conf.d/*.conf;
}
upstream tilo {
  server 172.17.0.3:5000;
}

**Comment by michaelshobbs** [comment]
I don't see anything in this that is redirecting. You'll need to inspect the rest of your nginx config (system-wide) to see if that is the cause. Otherwise the app is doing the redirecting I'd think.

**Comment by fabdelgado** [comment]
ok, thankyou @michaelshobbs

**Comment by michaelshobbs** [comment]
Let's us know what you find out
