### ISSUE TITLE
New graphite/statsd plugin with grafana frontend

### ISSUE THREAD

**Issue by jlachowski** [progrium/dokku#1744]
I've just created a new graphite/statsd plugin with grafana frontend (based on Jose Diaz-Gonzalez postgres plugin). How can I add a link to it in the dokku plugin documentation? 

My previous graphite/statsd plugin is there (in the doc's) but it is no longer maintained. 
The new plugin is available under: https://github.com/jlachowski/dokku-graphite-grafana.

Any comments welcomed.

**Comment by michaelshobbs** [comment]
Open a PR with the change to the plugins doc

**Comment by jlachowski** [comment]
PR created (https://github.com/progrium/dokku/pull/1750)
