### ISSUE TITLE
IP address support for SSL?

### ISSUE THREAD

**Issue by obrienmd** [progrium/dokku#177]
Per IRC convo today:
20:12 < rhy-jot> hm.. if someone wanted to contribute a PR to the nginx plugin it could be made to use the value(s) of ~git/\<app\>/IP for vhosts

Would it make sense to allow this for specifying IP in a vhost? My use case is clients that don't support SNI for SSL (ugh), but I suppose there may be others...

If there are no objections, I'll put a PR together.

**Comment by josegonzalez** [comment]
Closing as there hasn't been feedback from OP. If anyone wants to work on this, feel free to make a PR :)
