### ISSUE TITLE
Auto Restarting crashed apps

### ISSUE THREAD

**Issue by jwarzech** [progrium/dokku#216]
Is there a proposed solution for monitoring dokku apps and auto restarting if the crash?  Would just setting up something like http://godrb.com/ work?

**Comment by alanjds** [comment]
I remember Heroku to cease an desist of your app if it crashes and restart too often. I kind of liked this behavior in fact...

**Comment by tmikoss** [comment]
What about dockers own [`--restart=always`](https://docs.docker.com/reference/run/#restart-policies-restart) run option? Would that interfere in any way with how dokku handles the containers?

**Comment by josegonzalez** [comment]
@michaelshobbs We've definitely discussed this before, but I don't remember why we haven't added `--restart=always`. I assume thats because it conflicts with the zero-downtime checks, but I can't be sure. It seems as though we verify that the same container is still up, so maybe we can safely add it. It doesn't appear that we terminate the container on failure though, which we might consider a bug... Thoughts?

> Always restart the container regardless of the exit status. When you specify always, the Docker daemon will try to restart the container indefinitely.

**Comment by michaelshobbs** [comment]
Yeah the default zero downtime check relies on containers exiting on error.

**Comment by josegonzalez** [comment]
We can probably get around that by checking the number of restarts?

```shell
restarts=$(docker inspect -f "{{ .RestartCount }}" $DOKKU_APP_CONTAINER_ID)
[[ $restarts -ne 0 ]] && dokku_log_fail "App container failed to start!!"
```

Thoughts?

**Comment by josegonzalez** [comment]
Note: that would leave the container restarting 5ever, so we probably want to at least call `docker stop` as well.

**Comment by josegonzalez** [comment]
This could work:

```shell
container_restarts=$(docker inspect -f "{{ .RestartCount }}" $DOKKU_APP_CONTAINER_ID)
if [[ $container_restarts -ne 0 ]]; then
  docker stop "$DOKKU_APP_CONTAINER_ID" || true
  dokku_log_fail "App container failed to start!!"
fi
```

**Comment by tmikoss** [comment]
Maybe `--restart=on-failure:XX` would work, where `XX` is a reasonabe limit for retries? Though I was not able to find whether the limit gets reset after a container enters 'stable' state.

My use case as an app that dies maybe once in a couple of days due to extraordinary coincidences.

**Comment by josegonzalez** [comment]
Dokku doesn't have an agent, so unfortunately we can't do [smart crash restart policies](https://devcenter.heroku.com/articles/dynos#dyno-crash-restart-policy) like heroku does.

Perhaps the `--restart=on-failure:N` is a good alternative. I'll see what I can come up with.

**Comment by christiangenco** [comment]
Is the current best practice to use [dokku-logging-supervisord](https://github.com/sehrope/dokku-logging-supervisord) (which looks like it's had [a bug for the last year that makes restarting and deploying a lot slower](23)), or is crashed job restarting now built into dokku via. #1473?

i.e.: can I sleep soundly with the default dokku and this in my Procfile:

```
web:    bundle exec puma -C config/puma.rb
worker: bundle exec sidekiq -C ./config/sidekiq.yml
```

**Comment by christiangenco** [comment]
Well, I guess not. This morning I had two `worker`s with the above configuration crash without restarting.

The `supervisord` plugins look like they aren't being maintained anymore (["Not compatible with dokku 0.4+"](https://github.com/statianzo/dokku-supervisord)), so what's the best practice for this?

Would there be any downsides to doing something like:

    worker: while true; do bundle exec sidekiq -C ./config/sidekiq.yml; sleep 60; done

?

**Comment by epixa** [comment]
@christiangenco Have you encountered any crashes since your comment?

**Comment by josegonzalez** [comment]
@epixa please follow along in #1734. Thanks.
