### ISSUE TITLE
Use the docker index for buildstep

### ISSUE THREAD

**Issue by ghost** [progrium/dokku#327]
Builds under [progrium/buildstep](https://index.docker.io/u/progrium/buildstep/) now happen automatically.

Using the docker index would:
* Allow us to avoid having to rig up an update mechanism for the buildstep component (buildstep images are currently kept in docker until manually deleted & replaced)
* Take out the manual/slower process of updating the image to S3

Thoughts/comments?

**Comment by josegonzalez** [comment]
Closing this. At some point buildstep will be on docker, but thats an upstream issue and we'll switch to that when it's available.
