### ISSUE TITLE
Dokku Logs Rotation

### ISSUE THREAD

**Issue by fotisp** [progrium/dokku#417]
Hello,

I have dokku running on Digital Ocean, and one of my apps is log intensive. What is happening is that the logs are growing up to the HD limit.

One possible solution would be to use logrotate but the log filename is some sort of hash which I assume is created upon the initial deploy, so logrotate would need to be manually configured for every app deployed, which sort of kills the "Your own personal heroku" moto.

Is there any way to tell dokku to rotate or limit the size of log for an app?

**Comment by michaelshobbs** [comment]
@josegonzalez not sure what sort of enhancement you were thinking here as the logs are stored in docker internals. I don't think there is even a way to wipe the docker logs of a running container currently?

**Comment by josegonzalez** [comment]
Are the logs inside the container or outside? If inside, I do not propose we do anything - that would be upstream, maybe in buildstep? - but if outside, we can setup log rotation quite handily with the debian package.

**Comment by michaelshobbs** [comment]
In the standard (non-plugin augmented) dokku installation all logging is done inside the container as non-committed fs changes (i.e. logging to /some/path/with/no/volume/attached) or to stdout. In either case it's internal to the docker container.

**Comment by josegonzalez** [comment]
What do you think of using something based on @slaskis's plugin? Doesn't look too intrusive...

**Comment by michaelshobbs** [comment]
I feel rather strongly that log handling is out of scope for dokku core for a couple reasons.

1. There are plugins that already handle logging in their own way (i.e. sehrope/dokku-logging-supervisord)
2. Generally you want to handle logging in a more "holistic" way and not on an individual basis (i.e. a central syslog server or other log aggregator/archiver)

I'm definitely open to the debate if there are stronger feeling on the other side.

**Comment by michaelshobbs** [comment]
I also don't follow how we attach to a named container in that branch. Looks like the `deploy` phase doesn't name it either.

https://github.com/slaskis/dokku/blob/wip/logger-0.2/plugins/syslog/install#L37
https://github.com/slaskis/dokku/blob/wip/logger-0.2/dokku#L57

**Comment by josegonzalez** [comment]
Looks like the naming stuff is so that they can support multiple process types in different containers.

The more I think about it, the more I agree that we should leave this up to process management plugins. Feel free to close if you still think that way @michaelshobbs.

**Comment by theronic** [comment]
Facing this problem with Dokku v0.14.6 and Docker 18.09.3.
How to enable Docker log rotation when running on Dokku? I understand if Dokku defers this to Docker, but I'm using Dokku so that I don't have to worry about this kind of thing. Any help would be appreciated :).

**Comment by josegonzalez** [comment]
Please don't resurrect a 4+ year old issue.

There is nothing built into Dokku for managing logs. There is the #2268 issue, but if you'd like that to be worked on with any sort of urgency, feel free to contact me via email or on chat to figure out a consulting arrangement.
