### ISSUE TITLE
config:set broken in pre-release hooks

### ISSUE THREAD

**Issue by stephen-fanfair** [progrium/dokku#425]
Some plugins seem to trigger a config:set from a pre-release hook, which is broken and can cause an infinite loop. See this example: https://github.com/stephen-fanfair/dokku-mongo-plugin/blob/master/commands#L104.

It might be a good idea to not trigger config_restart_app while in the pre-release step.

**Comment by josegonzalez** [comment]
Closing and rolling this into #854. Please comment there if you're +1 on something like this :)
