### ISSUE TITLE
RACK_ENV and RAILS_ENV values are always 'production'

### ISSUE THREAD

**Issue by Zhomart** [progrium/dokku#503]
Hi, I set up dokku on vagrant and deployed there fresh rails app. I tried to run the app in 'staging' environment, but it's always run in 'production' environment.

```
vagrant@vagrant-ubuntu-precise-64:/var/lib/dokku/plugins$ sudo dokku config cat
=== cat config vars ===
RACK_ENV:         staging
RAILS_ENV:        staging
WAT:              YAY
```

I've checked ENV constant inside the app and it has a pair `ENV['WAT']='YAY'`. Is there any way to run rails app in 'staging' environment?

ENV of the app: https://gist.github.com/Zhomart/9700653

**Comment by josegonzalez** [comment]
We now have a `build-env` plugin which should handle this issue. If you are still bumping up against not being able to change it, please comment on this issue and I'll take a second look.
