### ISSUE TITLE
allocate_port: port is already mapped to ip

### ISSUE THREAD

**Issue by jcarlos7121** [progrium/dokku#529]
Hey guys, i cannot push :/ do you know why it rejects my push?

-----> Releasing app ...
-----> Deploying app ...
remote: 2014/04/07 00:00:57 Error: start: Cannot start container a4ea512b6939910320ebb39ef1034b79b11250155fb7f69cfbd82722af379372: allocate_port: port is already mapped to ip
To dokku@proglabs.co:app
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'dokku@proglabs.co:app'

**Comment by josegonzalez** [comment]
Closing as there hasn't been any movement on the issue. Feel free to comment if you're still seeing this :)
