### ISSUE TITLE
Can't specify specific revision of buildpack to use

### ISSUE THREAD

**Issue by motin** [progrium/dokku#537]
I'd like to be able to pin down the revision of the buildpack to use when building. However, I get the following:
```
remote: fatal: https://github.com/ddollar/heroku-buildpack-multi.git#529ee969a177d3ede775023cd7eb89eefb3a591a/info/refs not valid: is this a git repository?
```
with `.env` filled with `export BUILDPACK_URL=https://github.com/ddollar/heroku-buildpack-multi.git#529ee969a177d3ede775023cd7eb89eefb3a591a`

However, specifying a revision works within the .buildpacks file, so it may be related to the `.env` file.

**Comment by josegonzalez** [comment]
We didn't have user-env-compile at the time, so I'm guessing that was the issue. Please comment if this is still an issue on the latest stable/master release.
