### ISSUE TITLE
pre-receive hook declined, failed to build app with sbt

### ISSUE THREAD

**Issue by blork** [progrium/dokku#542]
I've just set up a 512mb droplet on DO with the Dokku image they provide. I'm hoping to push a Play! Framework app. I had to add a swap file to prevent some memory errors, but they seem to be solved. Now I'm getting the following (with `export DOKKU_TRACE=1` in `/home/dokku/dokkurc`): 

```
[warn] The global sbt directory is now versioned and is located at /build/app/.sbt_home/.sbt/0.13.
[warn]   You are seeing this warning because there is global configuration in /build/app/.sbt_home/.sbt but not in /build/app/.sbt_home/.sbt/0.13.
[warn]   The global sbt directory may be changed via the sbt.global.base system property.
[info] Loading project definition from /build/app/project
[warn] Multiple resolvers having different access mechanism configured with same name 'typesafe-ivy-releases'. To avoid conflict, Remove duplicate project resolvers (`resolvers`) or rename publishing resolver (`publishTo`).
 !     Failed to build app with sbt
+ for script in '$(ls -d /var/lib/dokku/plugins/*/commands)'
+ /var/lib/dokku/plugins/nginx-vhosts/commands git-receive-pack ''\''dokku'\'''
+ case "$1" in
To dokku@<ipaddress>:dokku
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'dokku@<ipaddress>:dokku'
```

I've seen similar issues (#103 #161) but the solutions there haven't helped. Locally the app compiles and runs, and all the dependancies are installed remotely (omitted for brevity). Is this likely to be a dokku issue or one with my project, and does anyone have advice for me?

**Comment by josegonzalez** [comment]
Closing as there hasn't been any movement on the issue. Feel free to comment if you're still seeing this :)
