### ISSUE TITLE
Rolling back app to previous deploy

### ISSUE THREAD

**Issue by fagiani** [progrium/dokku#553]
Does dokku have a way to quickly revert the latest deploy? Heroku uses a releases:rollback command that can revert to a given version. I know it can be tough to keep track of unlimited versions but it would be nice at least to revert to the last version as sometimes we just mess it up with a broken push...

Any thoughts or ideas?

**Comment by josegonzalez** [comment]
If someone wants to make a PR for this, would be great. Closing as we currently do not have plans to implement it - though I would be more than willing to merge something that does :)

**Comment by almereyda** [comment]
This is already possible via force pushing, i.e.

    git push -f dokku de7fc85:master

Also image tagging appears usable.

**Comment by guatedude2** [comment]
I know this is a bit late in the game but I created this tool to help manage deployments 

https://www.npmjs.com/package/dokku-deploy

Hope this helps someone

**Comment by josegonzalez** [comment]
Docker image tags can already be managed by our [image tags](http://dokku.viewdocs.io/dokku/deployment/methods/images/) plugin. If you wish add your package to our list of community plugins and packages, please do that instead of bumping a year old issue.
