### ISSUE TITLE
Installer needs to be run twice on 14.04

### ISSUE THREAD

**Issue by Rodeoclash** [progrium/dokku#590]
I had some trouble with the install script instructions. Steps were:

1. Provision new EC2 machine with Ubuntu 14.04 64 bit.
2. sudo apt-get update
3. sudo apt-get upgrade
4. Copy and pasted install code: ```wget -qO- https://raw.github.com/progrium/dokku/v0.2.3/bootstrap.sh | sudo DOKKU_TAG=v0.2.3 bash```
5. It couldn't find the git repo. It looked like the DOKKU_TAG ENV wasn't being set. If I manually ran ```export DOKKU_TAG=v0.2.3``` then the install progressed correctly.

**Comment by iannickb** [comment]
+1, same problem on Ubuntu Server 14.04 LTS on Amazon. (ami-9eaa1cf6)
I can make it work by downloading the bootstrap.sh file and running it as:
```
sudo bash bootstrap.sh
```

**Comment by josegonzalez** [comment]
Yeah I've seen people replicate it. We're currently looking at alternative options for packaging - debian/dockerfiles - which we'll have ready for testing really soon.

For now, you can get a debian package for dokku 0.3.13 [here](https://packagecloud.io/dokku/dokku/install), and we'll start transitioning docs to mention the alternative installation method soon!

**Comment by josegonzalez** [comment]
Dokku 0.3.13 is now released on Digital Ocean, and we'll try and keep this as up to date as possible going forward!
