### ISSUE TITLE
Setting up self-signed TLS

### ISSUE THREAD

**Issue by jbrooksuk** [progrium/dokku#608]
I'm trying to setup a self-signed certificate for our internal application. I've created the required TLS files in `/home/dokku/ssl-test/tls`, so I have:

- `server.crt`
- `server.csr`
- `server.key`

I then rebuild my application, but it doesn't not pick up the TLS support. Am I missing something? Do self-signed certificates not work?

**Comment by josegonzalez** [comment]
That refers to the directory on the dokku machine.

You can import ssl `server.crt` and `server.key` files using the `nginx:import-ssl` command on a tar file, as noted in the documentation.
