### ISSUE TITLE
Rails on Dokku running as root

### ISSUE THREAD

**Issue by rringham** [progrium/dokku#614]
It looks like Dokku is running rails as root, and I'm wondering if this is a security risk? Is there a way to configure Dokku to not run rails as root? Or am I misinterpreting the below / and or is this not actually a security risk?

```
me:~$ ps aux | grep rails
root      9614  0.9 17.0 647304 173660 ?       Sl   10:03   0:07 ruby bin/rails server -p 5000 -e production
me        9787  0.0  0.0  11744   904 pts/0    S+   10:16   0:00 grep --color=auto rails
```

**Comment by josegonzalez** [comment]
This was fixed upstream I believe.
