### ISSUE TITLE
[Push rejected] Quantal repository no long available

### ISSUE THREAD

**Issue by marqu3z** [progrium/dokku#627]
This morning dokku started rejecting pushes.
The problem is caused by ubuntu quantal repository that are not supported anymore and were been removed from the default domain `archive.ubuntu.com` to `old-release.ubuntu.com`

You can find it here: http://packages.ubuntu.com/

If someone is experiencing the problem can use and compile this version of progrium/buildstep

https://github.com/marqu3z/buildstep

Just clone and compile

````
git clone https://github.com/marqu3z/buildstep
cd buildstep
make build
```

In the Dockerfile it will replace the deprecated repository in the `/etc/apt/source.list`

```
sed -i s/archive/old-releases/g /etc/apt/sources.list
````

it should solve #626

**Comment by josegonzalez** [comment]
Fixed in upstream.
