### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by alexei-yakovlev** [progrium/dokku#629]
MacBook-Pro-Alexei-2:idistribution alexei$ git push origin master
Counting objects: 88, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (81/81), done.
Writing objects: 100% (88/88), 20.37 KiB | 0 bytes/s, done.
Total 88 (delta 2), reused 0 (delta 0)
-----> Cleaning up ...
-----> Building website ...
remote: Cloning into '/tmp/tmp.sP65vA2A1K'...
remote: warning: You appear to have cloned an empty repository.
remote: done.
remote: HEAD is now at 96f4855... initial
       Ruby app detected
-----> Compiling Ruby/Rails
 !
 !     Command: 'set -o pipefail; curl --fail --retry 3 --retry-delay 1 --connect-timeout 3 --max-time 30 https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/ruby-2.0.0.tgz -s -o - | tar zxf -' failed unexpectedly:
 !
 !     gzip: stdin: invalid compressed data--format violated
 !     tar: Unexpected EOF in archive
 !     tar: Unexpected EOF in archive
 !     tar: Error is not recoverable: exiting now
 !
To dokku@idistribution.by:website
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'dokku@idistribution.by:website'

**Comment by josegonzalez** [comment]
We test pushes for ruby apps now, and our tests don't seem to fail. Please open a new issue if you think you're having this problem.

**Comment by wader** [comment]
Happened for me now. Does not seems to be a DNS problem. Tried manually from container, vagrant guest and host.

```
vagrant@dokku:~$ sudo docker run --rm progrium/buildstep curl https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/cedar-14/ruby-2.1.0.tgz
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>BBDC8D1B2B696A4D</RequestId><HostId>obNqOboHO+53BTR4nv31QTlo+s5fXcOjuXWOsIXDWgAHitsd0ixY4BjUZAwxnpW+bAwv2zWb+sk=</HostId></Error>
vagrant@dokku:~$ curl https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/cedar-14/ruby-2.1.0.tgz
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>80D1ABFAF2424DF7</RequestId><HostId>MW3mQ5reDzYblA99UrKme6UuCIIuYu8/gv6mKjvNsGOUAPBvJghaG3y/S3Tk8XFQluqTSUMHH5Q=</HostId></Error>vagrant@dokku:~$
vagrant@dokku:~$ logout
Connection to 127.0.0.1 closed.
mattias@cocospro:dokku (master)$ curl https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/cedar-14/ruby-2.1.0.tgz
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>C9A071382CE0016D</RequestId><HostId>/2URB60Z9By7QidU46CN+ke+AJd+FbVKGu1YoeXD/EJj1H+GbZ/VHfVazxAyMLBY2p8gBLa45Mc=</HostId></Error>
```

(removed some output for clarity)

**Comment by josegonzalez** [comment]
Message is pretty clear, that ruby version doesn't exist - and it's not the same error as what @alexei-yakovlev encountered. You may want to set your ruby version to 2.1.5, since that is the latest stable ruby (or pin it to 2.1.x somehow).

**Comment by wader** [comment]
@josegonzalez Thanks! work now with latest stable. Got confused by the 403 access denied response.

**Comment by Artaud** [comment]
I solved this problem as documented in https://github.com/dokku-alt/dokku-alt/issues/169
by giving curl a little more time. For me the connect_timeout was critical.

#/home/dokku/ENV (used to be /home/dokku/BUILD_ENV)
export CURL_TIMEOUT=600
export CURL_CONNECT_TIMEOUT=600

**Comment by praveenaj** [comment]
I was using Dokku provided by DigitalOcean but I ran into the same issue discussed here. To me upgrading herokuish worked.

```cd /tmp
git clone https://github.com/gliderlabs/herokuish.git
cd herokuish
git pull origin master
IMAGE_NAME=gliderlabs/herokuish BUILD_TAG=latest VERSION=master make -e build-in-docker```
