### ISSUE TITLE
App available on all subdomains (plus root)

### ISSUE THREAD

**Issue by yazinsai** [progrium/dokku#650]
I have a Rails app deployed to `example.com` (with namespaced subdomains defined for `api.example.com` and `dashboard.example.com`). 

They all work fine .. but visiting `foo.example.com` displays the `example.com` site.

I tried the solution offered in #423 (shown below), and then reseting nginx - but that didn't resolve the problem:

>
Try creating a /etc/nginx/sites-available/default with the following contents:
```nginx
server {
    listen [::]:80 default_server;
    listen 80 default_server;
    root /usr/share/nginx/html;
    index index.html;
    server_name _;
}
```

I have the following DNS entries:
```
A   example.com   1.2.3.4
A *.example.com   1.2.3.4
```

**Comment by michaelshobbs** [comment]
@josegonzalez should we include a default site with dokku that just routes to the welcome page?

**Comment by josegonzalez** [comment]
Maybe, but that would require a bit of design work. Not sure of the nginx routing implications.

**Comment by michaelshobbs** [comment]
Yeah I don't think we should dictate this. Too many potential preferences to consider.

**Comment by josegonzalez** [comment]
So just document this in the nginx documentation with steps on how to not route everything to the default app?

Isn't there a way to make nginx not route to a default and just null-terminate?
