### ISSUE TITLE
Git push fails when attempting to follow tutorial: How To Use the Dokku One-Click DigitalOcean Image to Run a Go App

### ISSUE THREAD

**Issue by rwbogy** [progrium/dokku#663]
URL of tutorial
https://www.digitalocean.com/community/tutorials/how-to-use-the-dokku-one-click-digitalocean-image-to-run-a-go-app

Output with DOKKU_TRACE enabled:
https://gist.github.com/rwbogy/6456b447099fbebf581a

**Comment by josegonzalez** [comment]
Buildstep has been updated and we have a new dokku image available on DO. Closing since our docs are now up to date with what people deploy.
