### ISSUE TITLE
Redirect subdomains to root domain and have custom ports

### ISSUE THREAD

**Issue by osaatcioglu** [progrium/dokku#674]
I have installed Dokku on DigitalOcean instance and it works really nice. Moreover; I would like have the following scenario regarding the subdomains of my domain and ports.

1. I want all subdomains to be Redirected to root domain and my production instance to be in the root domain listening port 80.
2. I also want a custom port for my staging instance. Of course, for the staging case also, all subdomains will be redirected to root domain by keeping the port. 

For example 
http://randomsubdomain.example.com will be redirected to http://www.example.com and be responded by my prod-app instance.
http://yarandomsubdomain.example.com:2323 will be redirected to http://www.example.com:2323 and be responded by my stag-app instance.

I looked DigitalOcean DNS, nginx and dokku plugins but I couldn't figure out how to do that. I appreciate any kind of help to give me a direction. Thanks.

**Comment by michaelshobbs** [comment]
I think this can now be accomplished with an nginx template and the domains plugin, no? Use the nginx template to do the redirection and the domains plugin to tie the root domain to a given app. Let me know if that works for your case.

**Comment by michaelshobbs** [comment]
The first part can potentially can be accomplished if we do #924. The ports bit might be tricky.

**Comment by michaelshobbs** [comment]
We now have custom ports via `$DOKKU_NGINX_PORT` and `$DOKKU_NGINX_SSL_PORT`

**Comment by michaelshobbs** [comment]
We also have an [official redirect plugin](https://github.com/dokku/dokku-redirect). Closing. Let us know if these do not satisfy your use case.
