### ISSUE TITLE
Golang App deploy issue

### ISSUE THREAD

**Issue by manugarri** [progrium/dokku#694]
I followed [digital ocean's tutorial](https://www.digitalocean.com/community/tutorials/how-to-use-the-dokku-one-click-digitalocean-image-to-run-a-go-app) to install a Go app in dokku.

I changed the main.go to the main.go in [this](http://www.mircozeiss.com/host-your-golang-app-on-digital-ocean/) link (to avoid installing psql)

However the installation stops at:

    manugarri@manugarri:~/go/src/go_test$ gp dokku master
    Counting objects: 19, done.
    Delta compression using up to 8 threads.
    Compressing objects: 100% (16/16), done.
    Writing objects: 100% (19/19), 2.44 KiB | 0 bytes/s, done.
    Total 19 (delta 6), reused 0 (delta 0)
    -----> Cleaning up ...
    remote: Cloning into '/tmp/tmp.sAry83M9CY'...
    -----> Building test ...
    remote: warning: You appear to have cloned an empty repository.
    remote: done.
    remote: HEAD is now at 88f9be0... Clean up code
      Go app detected
    -----> Using go1.3

       Tired of waiting for bzr and hg?
       Try github.com/kr/godep for faster deploys.

       Installing Virtualenv...To dokku@IP:test
     ! [remote rejected] master -> master (pre-receive hook declined)
    error: failed to push some refs to 'dokku@IP:test'

Any reason why its not working? I used a fresh digital ocean droplet with Dokku v0.2.3

**Comment by josegonzalez** [comment]
The buildstep image in use was updated, and we also updated the dokku image on digital ocean. Please comment if you're still seeing this issue. Closing for now.
