### ISSUE TITLE
Dokku not creating repo on server?

### ISSUE THREAD

**Issue by walkemskies** [progrium/dokku#714]
Hi,

I am using Windows 7 with OpenSSH. I recently set up a ubuntu-dokku droplet on Digital Ocean and configured my SSH key. I can currently log in to either the dokku or root username on my droplet without a password using Putty, WinSCP, and ssh at the command line (OpenSSH).

However, I am having issues trying to push my repo onto dokku. I have my repo set up on my local machine (and it is sync'd up with my Github remote), and then ran the following:

git remote add host dokku@<mydomain>:LeagueSides.<mydomain>
git push host master
When I did that, I got the following error:

c:\Code\Projects\LeagueSides> git push host master 
fatal: 'LeagueSides.<mydomain>' does not appear to be a git repository 
fatal: Could not read from remote repository.
Please make sure you have the correct access rights and the repository exists.

I get the same error if I call:

ssh-agent bash -c 'ssh-add c:\users/<myuser>/.ssh/id_rsa; git push host master

I then tried the solution from http://stackoverflow.com/questions/25971580/how-to-set-the-root-application-directory/25971857#25971857 but created the repos within the dokku folder instead of root. Now I get this:

bash-3.1$ ssh-add id_rsa; git push dokku master
Identity added: id_rsa (id_rsa)
Counting objects: 16, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (14/14), done.
Writing objects: 100% (16/16), 3.83 KiB | 0 bytes/s, done.
Total 16 (delta 1), reused 0 (delta 0)
To dokku@jlchang.me:LeagueSides
 * [new branch]      master -> master

Which indicates my git bash has access to the dokku folder and is able to push there, but Dokku doesn't seem to recognize the repo and is not building/deploying the app. I've read elsewhere that you are not supposed to create the repo yourself on the server, that git remote add takes care of that, but that did not work for me. Is there something I'm missing in the app?

Any help is greatly appreciated!

**Comment by josegonzalez** [comment]
Sorry I never got to this, but I don't see how this would be the case. Seems as though maybe dokku wasn't installed properly. Did you ever figure out what the problem was?

**Comment by michaelshobbs** [comment]
@walkemskies it would seem the initial problem was with `git remote add host dokku@:LeagueSides`?There is no host after the `@`. 

In any case, you may want to try the latest release and if you're still running into issues, post a deploy with tracing on. (i.e. `dokku trace on && git push dokku master`)

**Comment by michaelshobbs** [comment]
Closing as we've not heard back. Please reopen if there's any more info or you're still running into the issue.

**Comment by tedf20** [comment]
Hello,

I seem to be running in the same error under the same conditions, that is why I decided to write here.

>I am using Windows 7 with OpenSSH. I recently set up a ubuntu-dokku droplet on Digital Ocean and configured my SSH key. I can currently log in to either the dokku or root username on my droplet without a password using Putty, WinSCP, and ssh at the command line (OpenSSH).

The above is true for me also. I have my repo set up on my local machine, and the remote connection is set up, which is proved by
    git remote -v
    demodok dokku@46.101.53.77:demodok (fetch)
    demodok dokku@46.101.53.77:demodok (push)
    origin  https://github.com/imchairmanm/demo_application.git (fetch)
    origin  https://github.com/imchairmanm/demo_application.git (push)

When I run
    git push demodok master
I get
    Warning: Permanently added '46.101.53.77' (ECDSA) to the list of known hosts.
    fatal: 'demodok' does not appear to be a git repository
    fatal: Could not read from remote repository.

    Please make sure you have the correct access rights
    and the repository exists.

I also tried creating and initiating an app folder on the server - in that case git recognises it and pushes the files, but dokku doesn't recognise the push and therefore doesn't build the app, therefore I made a step back.

By the way, I turned tracing on, but got no additional information to troubleshoot the issue.

Now I have literally run out of solutions found over the internet, therefore the help would be greatly appreciated :)

**Comment by josegonzalez** [comment]
Did you setup your ssh key using the web ui?

**Comment by tedf20** [comment]
No, I created the droplet without ssh and then added it manually.
