### ISSUE TITLE
Restart policy

### ISSUE THREAD

**Issue by gmaclennan** [progrium/dokku#725]
Would it make sense for dokku to implement a restart policy on docker containers, as implemented in docker 1.2 https://github.com/docker/docker/pull/7414?

My understanding is that this would automatically restart containers on error.

**Comment by mnibecker** [comment]
It's probably best doing this using a plugin like [dokku-docker-options](https://github.com/dyson/dokku-docker-options/blob/master/docker-args) and adding the argument `--restart=always`.

The problem I've been running into with this is that if you use the `dokku run [app] [cmd]` plugin, that process enters an infinite restarting loop. I don't know perhaps add some logic in the run plugin to remove any restart commands?

**Comment by josegonzalez** [comment]
The `docker-args` pluginhook now also gets the command being run for docker, so you could check if it's a `run` command and *not* add the `--restart=always` argument.

**Comment by mnibecker** [comment]
There doesn't seem to me any good reason why you need to use `docker run` command in the run plugin. Could we just replace the line with:

`docker exec -ti #CONTAINER /exec "$@"`

That way you don't even have to include any `docker-args`. Perhaps I'm missing something...

**Comment by josegonzalez** [comment]
`docker run` runs the command in an isolated container, similar to how `heroku run` runs the command in it's own container. The goal here is to mimic the heroku api.

**Comment by josegonzalez** [comment]
We do have plans to implement docker-options natively, but for now you can use the existing pluginhook to handle whether a given `docker run` gets the `--restart=always` argument.
