### ISSUE TITLE
Why is the docker port exposed to all interfaces by default?

### ISSUE THREAD

**Issue by aaronz8** [progrium/dokku#726]
"When no host interface is provided, the port is bound to all available interfaces of the host machine (aka INADDR_ANY, or 0.0.0.0).When no host port is provided, one is dynamically allocated."

https://github.com/progrium/dokku/blob/master/dokku:66-67:

    id=$(docker run -d -p (host interface is not specified)5000 -e PORT=5000 $DOCKER_ARGS $IMAGE /bin/bash -c "/start web")
    port=$(docker port $id 5000 | sed 's/[0-9.]*://')

Any reason why the docker port is exposed by default? Nginx already proxies this connection/port, so I can't think of a use case for this. 

Why not change it to this:

    id=$(docker run -d -p 127.0.0.1::5000 -e PORT=5000 $DOCKER_ARGS $IMAGE /bin/bash -c "/start web")

**Comment by josegonzalez** [comment]
@michaelshobbs was this taken care of by 948d7902f22c60dd9ba952306f8a6d75a7efe729?

**Comment by michaelshobbs** [comment]
I'd say so.
