### ISSUE TITLE
Pushes failing

### ISSUE THREAD

**Issue by pandringa** [progrium/dokku#727]
I've been trying to get dokku setup for the last few days and have run into a ton of trouble (mostly related to the MongoDB plugin), but at the moment I'm having issues even deploying... Right now when I deploy the pre-receive hook is declined (see https://gist.github.com/pandringa/13e7f5d6d239e6db5d14 for the logs), but I can't tell what's going wrong and what's causing it. How should I fix this?

Thanks in advance for your help!
Peter

**Comment by josegonzalez** [comment]
@pandringa sorry for not getting to this, but were you able to figure this out by adding your ssh key to the box? Let us know or hop onto irc and we'll try and help out :)

**Comment by michaelshobbs** [comment]
Closing as we've not heard back on this and a new image has been uploaded to DO that seems to solve a lot of our DO issues. Please reopen if this is not the case.
