### ISSUE TITLE
Fix Ubuntu locale issue

### ISSUE THREAD

**Issue by MarcDiethelm** [progrium/dokku#731]
Fresh Ubuntu instances have a problem where the locales are set up incorrectly resulting in errors and warnings when installing 'stuff', e.g like f***ing up the MongoDB plugin install.

Here's a fix that actually works:
```
sh -c "echo 'LANG=en_US.UTF-8\nLC_ALL=en_US.UTF-8' > /etc/default/locale"
```
CC: https://github.com/jeffutter/dokku-mongodb-plugin/issues/31

**Comment by josegonzalez** [comment]
I think we can safely add this in the `bootstrap.sh` file. @michaelshobbs thoughts?

**Comment by michaelshobbs** [comment]
Yeah that's probably ok for 95% of installations. Might this cause issues with upgrades?

**Comment by josegonzalez** [comment]
I don't think so? Most people setup dokku and leave it as is, right?

**Comment by michaelshobbs** [comment]
Just thinking if you change the locale on a db, won't you get weird encoding errors? Also, is this supposed to go into `/etc/default/locale' in the app image or on the host itself?

**Comment by josegonzalez** [comment]
It's not for a database, its for the system. Database encoding will stay the same. This is for the host, not the app image afaik.

**Comment by michaelshobbs** [comment]
Sorry I suppose I meant db clients. Things like postgres attempt to default to the system locale (via these env vars) when you spin up a cluster and then the client also uses the env unless you set it explicitly. Hence the OP's issue. So if we change these on an already running system, redeploy the app, wouldn't we potentially cause an issue? Maybe my understanding is incorrect?

**Comment by yabawock** [comment]
I don't think dokku should mess with the system configuration any more than absolutely needed. The locale problem normally results from the client (via SSH) requesting locale that the server has not available resulting in a message along these lines:

```bash
warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = "de_DE.UTF-8",
	LANG = "de_DE.utf8"
    are supported and installed on your system.
```

If you do a absolutely minimal Ubuntu install even en_US.utf8 won't be available, just the fallback 'C' locale, thus the above mentioned fix wouldn't even work. The real fix is to either make sure you always connect with SSH using the 'C' locale (which is always available) or provide the supported locales on your server (for example `apt-get install language-en language-pack-de`). 

I would be pretty annoyed if the installer modifies my system configuration without a real need, even if the configuration management would revert the change sooner than later, especially if it's for a bad workaround that fails for large parts of the world that use non-english localizations.

**Comment by josegonzalez** [comment]
@yabawock You are right. If anything, this is a developer concern. While I'd love to set the default to `utf-8` - just like I like setting the timezone to `UTC` on all my servers - the more I think about it, the more I think we'll just get this wrong for our users. As well, this seems like a bug with the plugin (or maybe even mongodb!) that we should be too concerned with in Dokku Core (I haven't seen any other reports about similar issues).

Closing. Feel free to state that you feel strongly against this opinion.
