### ISSUE TITLE
Enable configuring which process type (web, worker, etc.) to run instead of defaulting to "web"

### ISSUE THREAD

**Issue by motin** [progrium/dokku#732]
Currently, [dokku is hard-coded to start the "web" process on deploy](https://github.com/progrium/dokku/blob/c092dd1719b77843cc1c565688de9482f3046ede/dokku#L66). 

Instead, this should be configurable so that any process type (web, worker, etc.) defined in the Procfile can be run. A config-directive `PROCESS_TYPE` that defaults to `web` if not set to determine this, maybe?

This would make it possible to start worker processes as different docker containers / deployments so that we don't have to resort to using [dokku-shoreman](https://github.com/statianzo/dokku-shoreman) or [dokku-supervisord](https://github.com/statianzo/dokku-supervisord), who both require manual efforts to avoid port collisions. 

This brings dokku closer to how Heroku and other PaaS handle process types - each process is started in it's own container/dyno.

**Comment by josegonzalez** [comment]
As of #1118, we now have container-level scaling, which allows you to run whichever process in the Procfile you see fit :)
