### ISSUE TITLE
dokku plugin-install keeps installing postgres, ignores new plugins

### ISSUE THREAD

**Issue by dwenaus** [progrium/dokku#741]
Whenever I run $dokku plugins-install it seems to run the same thing again and again - the pg installer from https://github.com/Kloadut/dokku-pg-plugin. There is no error, but now subsequent plugins such as link or elasticsearch are ignored.

$ dokku plugins-install
Cloning into '/tmp/dokku-pg-dockerfiles'...
... lots of output ...
Successfully built 2e592c81702e

I'm running dokku v0.2.3-60-gc05488b

**Comment by josegonzalez** [comment]
Closing as there hasn't been an update from OP. Please comment if you have some more info for us :)
