### ISSUE TITLE
not rebuilding updated version in package.json

### ISSUE THREAD

**Issue by aaronz8** [progrium/dokku#752]
Apologies in advance if this is an npm issue instead of a dokku one.
Previous push was using `node` 0.10.32 and `email-templates` 0.1.8. I tried to push updated code, using `node` 0.11.14 and `email-templates` 1.1.2. These version numbers were specified in `package.json`.

However, when I tried to push the updated code, npm didn't even try to rebuild `email-templates`. Dokku said `-----> Node version changed since last build; rebuilding dependencies` but it didn't.

It only started working once I removed `email-templates` from package.json to force an unbuild, and readded it for the next push to get it to build with the right version.

Is this a legit bug / are there any workarounds for this / is there any way to force rebuild everything?

**Comment by josegonzalez** [comment]
Closing as we haven't heard from OP in over a month and it's a heroku buildpack issue, not a dokku issue.

**Comment by aaronz8** [comment]
Thanks for the ping, I totally forgot to submit the issue to the buildpack since my temporary "fix" was enough for my purposes. We'll see what happens there.

**Comment by josegonzalez** [comment]
No worries!
