### ISSUE TITLE
dokku run: clean up exited containers and images?

### ISSUE THREAD

**Issue by lenada** [progrium/dokku#793]
Each `dokku run` spins up a new docker container.
Over time a a lot of containers and aufs layers are piling up (especially with `dokku run` cronjobs)
Eventually certain file/docker limits will be exceeded...

It seems to be a good practice to clean up after docker
https://github.com/docker/docker/issues/928

It would be great if `dokku run` could take care of the containers that have exited, or clean up in the app space selectively. somewhere after
https://github.com/progrium/dokku/blob/master/plugins/00_dokku-standard/commands#L34

adding a `docker rm $(docker ps -qa)` maybe is a bit too radical?

@progrium what is your take on this? should this even be a responsibility of dokku?

**Comment by josegonzalez** [comment]
Closing this as `dokku cleanup` - run during deploys - cleans up unused images already, and you can run that manually.

**Comment by andyjeffries** [comment]
Out of interest @josegonzalez why does it run early in the deploy, rather than at the end? I often seem to get old containers left running. Sure they get cleaned up on the next deploy, but until then they're left using twice the memory they should be.

**Comment by josegonzalez** [comment]
The "old containers" are still running for a minute or two to handle zero-downtime. We update the proxy and let those containers stick around to continue handling existing requests. This is documented [here](http://dokku.viewdocs.io/dokku/deployment/zero-downtime-deploys/), and has nothing to do with `dokku cleanup`.
