### ISSUE TITLE
Vagrant install instructions make no sense

### ISSUE THREAD

**Issue by anentropic** [progrium/dokku#795]
http://progrium.viewdocs.io/dokku/installation
- Download and install VirtualBox
- Download and install Vagrant
- Clone Dokku `git clone https://github.com/progrium/dokku.git`
- Setup SSH hosts in your /etc/hosts `10.0.0.2 dokku.me`
- Setup SSH Config in ~/.ssh/config `Host dokku.me  Port 2222`
- Create VM `vagrant up`
- Copy your SSH key via cat ~/.ssh/id_rsa.pub | pbcopy and paste it into the dokku-installer at http://dokku.me

So... I clone the dokku source to my laptop but do nothing with it. I fiddle around with my hosts file and then fire up a vagrant vm.  But I haven't installed dokku anywhere.  Then I point my browser at my vm's hostname hoping for a dokku web ui to be there?  How is that supposed to work?

I have tried to puzzle this out myself by:
- setting up a Vagrant (Ubuntu 14.04) vm using `shell` provisioning, that runs the install command from the README: `$ wget -qO- https://raw.github.com/progrium/dokku/v0.3.7/bootstrap.sh | sudo DOKKU_TAG=v0.3.7 bash`
- so now I have a Vagrant vm with Dokku installed on it
- edit the `/etc/hosts` file on my laptop to point to the `private_network` ip of the vm
- if I visit http://dokku.me I can now see a default "Welcome to nginx on Debian!" page

Feel like I'm halfway there...

The docs also seem to be missing any description of how to initially set up an app on the dokku box, we arrive directly at deployment: 
http://progrium.viewdocs.io/dokku/application-deployment
```
$ cd node-js-sample
$ git remote add progrium dokku@progriumapp.com:node-js-app
$ git push progrium master
```
I'm guessing these commands are run on my host laptop... and `progriumapp.com` should be the hostname of my dokku box? and `node-js-app` is the name of a repo that should exist on the dokku box?

**Comment by Telemakhos** [comment]
Followed current instructions to the letter and when I try to ssh into the machine I get:

    The provider for this Vagrant-managed machine is reporting that it
    is not yet ready for SSH. Depending on your provider this can carry
    different meanings. Make sure your machine is created and running and
    try again. Additionally, check the output of `vagrant status` to verify
    that the machine is in the state that you expect. If you continue to
    get this error message, please view the documentation for the provider
    you're using.

After reading @JensDebergh , the solution is skipping the addition of....

    Host dokku.me
        Port 2222

...in `/etc/hosts`.

**Comment by JohnyMoSwag** [comment]
@Telemakhos once you have 10.0.0.2 set in your hosts file you can browse to "dokku.me" and paste your public key on the setup page. No need to add your key in the way you would for a non vagrant setup.

**Comment by Telemakhos** [comment]
@JohnyMoSwag yeah, the vagrantfile picked up my public key and auto-filled the install page correctly. But still I couldn't ssh into the vagrant box, so I decided to try this other way (didn't work either). Then I nmap'ed the box like JensDebergh:

    $ nmap -v -A dokku.me

    Starting Nmap 6.47 ( http://nmap.org ) at 2015-01-18 11:58 
    NSE: Loaded 118 scripts for scanning.
    NSE: Script Pre-scanning.
    Initiating Ping Scan at 11:58
    Scanning dokku.me (10.0.0.2) [2 ports]
    Completed Ping Scan at 11:58, 0.00s elapsed (1 total hosts)
    Initiating Connect Scan at 11:58
    Scanning dokku.me (10.0.0.2) [1000 ports]
    Discovered open port 22/tcp on 10.0.0.2
    Discovered open port 111/tcp on 10.0.0.2

It seems like vagrant now is running the ssh daemon in the default port (22), so looks like the step of including the ```2222 port``` in ```/etc/hosts``` is not necessary...

**Comment by JohnyMoSwag** [comment]
@Telemakhos I apologize. I assumed you were referring to your host file, not your ssh config. I also skipped adding the port to my config and it worked like a charm :)

**Comment by josegonzalez** [comment]
To ssh onto the box, you can do `vagrant ssh`.

**Comment by Telemakhos** [comment]
@JohnyMoSwag No need to apologise man... =)

@josegonzalez  `vagrant ssh` was working, but I couldn't deploy the test app with `git push`. It was giving me a timeout, and skipping the `/etc/hosts` part fixed it. As I said I've followed the install instructions step by step. This week I'll repeat the process since I've to help a co-worker installing dokku. I'll double-check and report back.

**Comment by josegonzalez** [comment]
@Telemakhos like mentioned in the docs, you want to verify the port by doing `vagrant ssh-config`.

**Comment by Telemakhos** [comment]
Not working either... 
![screen shot 2015-01-18 at 21 46 33](https://cloud.githubusercontent.com/assets/2261077/5794003/5f84895c-9f5b-11e4-82ef-fd4c86e368e0.png)

**Comment by josegonzalez** [comment]
sorry, `vagrant ssh-config dokku`. I'll update the docs tomorrow for this and run through them all.
