### ISSUE TITLE
Scala apps not building

### ISSUE THREAD

**Issue by elliottsj** [progrium/dokku#848]
Scala apps, including Play Framework apps, are not building and instead giving this error:
```
$ git push dokku
Counting objects: 51, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (29/29), done.
Writing objects: 100% (51/51), 5.51 KiB | 0 bytes/s, done.
Total 51 (delta 12), reused 0 (delta 0)
-----> Cleaning up ...
-----> Building scala-getting-started ...
-----> Adding BUILD_ENV to build environment...
-----> Scala app detected
remote: 
remote: gzip: stdin: unexpected end of file
remote: tar: Child returned status 1
remote: tar: Error is not recoverable: exiting now
To dokku@example.com:scala-getting-started
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'dokku@example.com:scala-getting-started'
```
Above, I'm using Heroku's [scala-getting-started](https://github.com/heroku/scala-getting-started) repo as described in their [getting started guide](https://devcenter.heroku.com/articles/getting-started-with-scala#prepare-the-app).

I'm using Dokku v0.3.11 on a fresh Digital Ocean droplet with Ubuntu 14.04 x64.

**Comment by josegonzalez** [comment]
I'm beginning to think there is some weirdness with digital ocean's networking. We seem to consistently have issues with not being able to retrieve s3 items within docker on DO.

Is this an ipv6 docker instance?

**Comment by elliottsj** [comment]
Yes, I believe I was using an IPv6 droplet. I've just tried on a couple fresh droplets with the latest version of Dokku and scala looks to build properly on both an [IPv4](https://gist.github.com/elliottsj/0d4f4e4143ae4c2289a0) and and [IPv6](https://gist.github.com/elliottsj/f7dab1b658b0ff6b7227) droplet.

**Comment by josegonzalez** [comment]
Then I'm going to continue to say that sometimes networking is broken on DO instances.
