### ISSUE TITLE
Redis plugin Dokku buildstep

### ISSUE THREAD

**Issue by Daniel-ltw** [progrium/dokku#853]
time="2014-12-26T05:04:25Z" level="fatal" msg="Error response from daemon: Could not find entity for redis_supermarket"

Have anyone encountered this error before?

**Comment by josegonzalez** [comment]
Does that container exist in docker?

**Comment by josegonzalez** [comment]
Whats the output of `sudo docker ps`?

**Comment by Daniel-ltw** [comment]
I'm closing this issue. Looking at the problem, it might be a possibility that the VPS is having certain issues. 

Moved onto DigitalOcean and this problem seem to disappear. 

Will look back into it once I have the time.
