### ISSUE TITLE
High Memory usage running Node

### ISSUE THREAD

**Issue by lafama** [progrium/dokku#855]
Is it normal for nodejs apps (mean.io) to be using alot of memory. 
I have managed to run 3 very simple application on a VPS and here is the memory usage according to newrelic
```
node (root) |  0.5 % (CPU usage) |  1200 MB (Memory Usage) | 8 Running Processes 
```
if i stop one application (Has 1 web and 1 worker process ) i suspect to be using alot of memory  i get the following (This are two running apps)
```
node (root) |  0.1 % (CPU usage) |  240 MB (Memory Usage) | 4 Running Processes 
```
Secondly should the running Processes be 2 instead of 4, considering that am not running workers only 1 web per application

**Comment by michaelshobbs** [comment]
@lafama this seems to be incomplete ps output. Where are the process command strings? Hard to tell what's what. In any case, depending on how a process is executed and subsequently internally managed you may have multiple processes for a given service. What does you `Procfile` look like and do you have any dokku plugins installed like supervisord or foreman?

**Comment by josegonzalez** [comment]
Closing as we haven't had feedback from OP in a month. If this is still an issue, please comment and we'll try to debug more.

**Comment by lafama** [comment]
Sorry about that.
I figured out what was causing this, its newrelic monitoring plugin and its not related to dokku.
```
require('newrelic');
```
i removed that and the memory issues disappeared
