### ISSUE TITLE
Use HAProxy instead of Nginx for VHOSTs

### ISSUE THREAD

**Issue by motin** [progrium/dokku#856]
The suggestion is to use HAProxy instead of Nginx as the reverse proxy for publicly facing domains.

## Rationale
As I understand it, Dokku's plugin nginx-vhost uses Nginx to handle two things:
1. Mapping (sub)domain names to docker container ports
2. Configuration of SSL Termination

Some buildpacks build containers that include their own Nginx (for instance [1](https://github.com/CHH/heroku-buildpack-php), [2](https://github.com/Scalingo/appsdeck-buildpack-php), [3](https://github.com/cloudfoundry-incubator/staticfile-buildpack), [4](https://github.com/joelcogen/heroku-buildpack-rails-unicorn-nginx)), and having two Nginx proxies like this causes confusion, difficulties in troubleshooting and the necessity to duplicate some nginx configuration directives on the dokku host (for instance via https://github.com/neam/dokku-nginx-vhosts-custom-configuration#background)

This is not an issue with Heroku since it already performs this reverse proxying at the network layer (possibly already using HAProxy).

## Example HAProxy configuration
1. Mapping (sub)domain names to docker container ports example configuration: http://serverfault.com/questions/105824/how-to-divert-traffic-based-on-hostname-using-haproxy/126799#126799
2. Configuration of SSL Termination: https://serversforhackers.com/haproxy-ssl-termation-pass-through/ (Personally, I prefer to configure SSL at the network layer via Cloudflare DNS)

**Comment by motin** [comment]
But we do have Docker :) We can use either https://github.com/tutumcloud/tutum-docker-clusterproxy which supports virtual host mapping configured using environment variables or https://github.com/tnolet/haproxy-rest that can be configured by a RESTful API.

**Comment by josegonzalez** [comment]
@motin I'd prefer a docker-based solution (since that's where we want to go anyhow), so the first one seems decent (though not great, given it's config). The second seems useful, though seems like a lot of extra stuff we may not need/want to setup.

Would you be willing to prototype a haproxy-vhosts plugin?

**Comment by josegonzalez** [comment]
I'm going to close this. While I think it could be useful to have a proxy layer, it would be more difficult to allow people to customize their haproxy installs, so we'd be dropping some features in favor of a potentially more difficult to interface with service.

I'm still +1 on having a proxy layer of some sort, but think that it should not be in dokku core.

**Comment by motin** [comment]
Please consider re-opening, I think there is a misunderstanding. 

Why would people want to customize the haproxy installs? Nobody customizes their **routing** layer at heroku... It simply works and is out of the way. In contrast the Nginx used by Dokku is out of the way requiring a high level of expertise to be able to debug and workaround why file uploads, websockets and request/response headers are not working as expected.

Thus, using haproxy would make it much easier for people to customize their nginx configuration since there will only be one layer of nginx installations to customize. 

If closing this, we should instead propose that people leave nginx out of their docker images and instead use buildpacks that only exposes for instance php-fpm. That would be more dockeresque (since only one public process per image has a public port), but that would make Dokku incompatible with most of the current Heroku buildpacks.

**Comment by josegonzalez** [comment]
The only repo you listed that uses nginx with cause is the static one. CHH isn't maintained anymore afaik, and the official PHP buildpack should cover the use cases by Scalingo.

That said, here are a few warts we'd need to cover to use haproxy:

- Custom domains
- Adding SSL support (1.5 isn't in the Trusty 14.04 apt repos)

While I personally would like to use haproxy - perhaps in it's own docker container somehow - I don't see myself working on this. I also haven't personally seen any pain points with our current nginx setup - it's quite simple and easy to extend/hack upon. Are there places where the current setup falls on it's face for you?

As I asked before, are you willing to prototype a haproxy-vhosts plugin? If so, then we can move forward with potentially replacing nginx or offering haproxy as an alternative.

**Comment by josegonzalez** [comment]
Re-opening. Let me know if you get around to a haproxy plugin, could be quite cool :)

**Comment by motin** [comment]
The official Heroku PHP buildpack offers Nginx as well: https://github.com/heroku/heroku-buildpack-php - hopefully with cause.

> While I personally would like to use haproxy - perhaps in it's own docker container somehow - I don't see myself working on this.

No pressure :)

> I also haven't personally seen any pain points with our current nginx setup - it's quite simple and easy to extend/hack upon. 

Easy if you know Nginx well. And most of the times, customizing the Dokku nginx layer requires root access to the Dokku host - which rhymes badly with the PaaS concept.

> Are there places where the current setup falls on it's face for you?

Websockets, Configuring large file upload limits, Set up prerender.io nginx config, Request/Response header debugging (try setting up a memcache/redir/varnish cache with proxying based on headers and cache hit/miss), and more. Basically only simple HTTP proxying works without issues.

> As I asked before, are you willing to prototype a haproxy-vhosts plugin? If so, then we can move forward with potentially replacing nginx or offering haproxy as an alternative.

Maybe, but first I will familiarize myself with Tutum and how applications can be deployed to production there. I am pursuing a workflow where Dokku is used to build the docker images, after which they are deployed to Tutum.

**Comment by motin** [comment]
I have thought about this and to my understanding, Dokku is probably not the right platform for more complex use-cases where custom Nginx configuration is important. It took ages for Dokku to accept [the PR that allows plugins to safely include configuration files without overwriting the whole nginx configuration over and over again](https://github.com/progrium/dokku/pull/579), and as you say, most don’t even run into issues that requires custom Nginx configuration.

Furthermore, the use of HAProxy via a container is probably not relevant before [the refactoring of Dokku to be 100% containerized](https://github.com/progrium/dokku/wiki/Refactoring#100-containerized) is done. The power of Dokku is the simplicity of git-to-push simple web apps, not having complete control over your stack.

Instead, I'll be using Docker Stack (https://github.com/neam/docker-stack/), a pure Docker-based solution where it is trivial to adapt your php/nginx configuration on a per-app basis, versioned together with your application source code. Adding HAProxy to a Docker Stack is trivial as well, and deployment can be done on [Tutum](https://www.tutum.co/) for high availability and unlimited scalability :)

Thanks for introducing me to Docker workflows, Dokku, and a special thanks to you @josegonzalez and the other new maintainers for putting Dokku on track again after the hiatus :)

**Comment by helsont** [comment]
beautiful post @motin

**Comment by josegonzalez** [comment]
A few things:

- I use Haproxy and Nginx interchangeably, and find setting up nginx much easier, though Haproxy more powerful. I'm able to do quite a few things, at scale, on both platforms.
- Our target audience is the single-server user, who is likely to not have real issues with using Nginx. If they do, then nginx is certainly capable of performing those tasks, they just have to do a bit more work.
- As of 0.6.0, you can implement your own [proxy implementation](http://dokku.viewdocs.io/dokku/advanced-usage/proxy-management/) to replace nginx-vhosts. I still think that having nginx is a better default than haproxy, but this allows users to do whatever they wish.
- Dokku is certainly never going to solve all problems, and our users are free to go off on their own and maintain their own infrastructure. I'm happy to see that you've solved your problem in a way you are comfortable with.
- Finally, commenting on issues that are a year+ old isn't really useful to anyone involved, and I'd much prefer users open up new issues if the problem is relevant.
