### ISSUE TITLE
VHOST Disable Nginx Server version information

### ISSUE THREAD

**Issue by lafama** [progrium/dokku#857]
Currently this is what we get on the response header
```
Status Code: 200
date: Thu, 01 Jan 2015 14:20:52 GMT
content-encoding: gzip
server: nginx/1.6.2
.....
```
Can we just have server: nginx without the version information as the default, without need to create nginx.conf.template on all applications. Am sure this is possible by setting
```
https://github.com/progrium/dokku/blob/master/plugins/nginx-vhosts/templates/nginx.conf
https://github.com/progrium/dokku/blob/master/plugins/nginx-vhosts/templates/nginx.ssl.conf
```
to have this value
```
server_tokens off;
```

**Comment by josegonzalez** [comment]
Sounds good to me :)

**Comment by josegonzalez** [comment]
Closing as there is a PR open.
