### ISSUE TITLE
tests.mk being invoked during installation

### ISSUE THREAD

**Issue by josegonzalez** [progrium/dokku#862]
Seems line 42 is being invoked when calling `make install`. This is the line:

```
ifeq ($(shell grep dokku.me /home/dokku/VHOST),)
```

And here is how I know:

```
==> default: stdin: is not a tty
==> default: grep:
==> default: /home/dokku/VHOST
==> default: : No such file or directory
==> default: wget -qO /usr/local/bin/sshcommand https://raw.github.com/progrium/sshcommand/master/sshcommand
```

That happens right at the start of the install :(

@michaelshobbs assigning to you since you originally setup the test integration.

**Comment by michaelshobbs** [comment]
The way I implemented it was to just include tests.mk in the top-level Makefile so we can run everything from the root of the repo. As far as I understand it, conditional logic runs at invocation of make as it reads the Makefile. 

So we have some options here. First, we can just hide the stderr from grep as we really don't care about. Alternatively, we can not include tests.mk in the top-level Makefile, move it to the tests dir and change the `test` target to cd in to tests and run the test targets from there. 

The second option may lead to further issues in the test suite; all of which can be resolved of course. I vote for the first option as its the easiest and least prone to causing issues.

Thoughts?

**Comment by josegonzalez** [comment]
I hate make. Lets do option one, since it's a smaller change :)
