### ISSUE TITLE
Migrate testing to CircleCI

### ISSUE THREAD

**Issue by michaelshobbs** [progrium/dokku#865]
Opening an issue to track progress and conversation.

**Comment by michaelshobbs** [comment]
@josegonzalez @progrium  currently circle's docker implementation supports btrfs and I know we seem to push aufs. What is the reason behind this? I don't want to add another moving part by supporting btrfs necessarily but I'd like to understand our current requirement of aufs.

**Comment by progrium** [comment]
It's only a requirement because when Dokku started you had to make it was
installed and docker didn't support anything else. If actually like to see
it work with btrfs

On Saturday, January 3, 2015, Michael Hobbs <notifications@github.com>
wrote:

> @josegonzalez <https://github.com/josegonzalez> @progrium
> <https://github.com/progrium> currently circle's docker implementation
> supports btrfs and I know we seem to push aufs. What is the reason behind
> this? I don't want to add another moving part by supporting btrfs
> necessarily but I'd like to understand our current requirement of aufs.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/progrium/dokku/issues/865#issuecomment-68607685>.
>


-- 
Jeff Lindsay
http://progrium.com

**Comment by michaelshobbs** [comment]
Ok makes sense. I'll keep working with circle. I think they have the btrs dirs locked down a bit too tightly.

**Comment by progrium** [comment]
They're responsive to fixing their apparmor settings as such. If you find
anything really in the way drop them a note.

On Sat, Jan 3, 2015 at 2:34 PM, Michael Hobbs <notifications@github.com>
wrote:

> Ok makes sense. I'll keep working with circle. I think they have the btrs
> dirs locked down a bit too tightly.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/progrium/dokku/issues/865#issuecomment-68612331>.
>



-- 
Jeff Lindsay
http://progrium.com

**Comment by michaelshobbs** [comment]
Yup. I have a note into them about it. I'm use them for all my other projects. They've been great!

**Comment by michaelshobbs** [comment]
This is coming along great. I think I have the last issue ironed out. I'll have a PR together tonight or first thing in the AM. 

@progrium Can you follow the project in CircleCI?  https://circleci.com/?join=dont-test-alone

**Comment by michaelshobbs** [comment]
@progrium We'll also need a status API token to badge the readme.

**Comment by josegonzalez** [comment]
Closing as there is a PR open.
