### ISSUE TITLE
Cannot install on Ubuntu 14.04 Kernel 3.14.27

### ISSUE THREAD

**Issue by Antonhansel** [progrium/dokku#866]
Dokku is not compatible with the kernel 3.14.27-xxxx-grs-ipv6-64 on ubuntu 14.04 and Ubuntu 12.04.
```
Error: 
wget -qO /usr/local/bin/sshcommand https://raw.github.com/progrium/sshcommand/master/sshcommand
chmod +x /usr/local/bin/sshcommand
sshcommand create dokku /usr/local/bin/dokku
Adding user `dokku' ...
Adding new group `dokku' (1000) ...
Adding new user `dokku' (1000) with group `dokku' ...
Creating home directory `/home/dokku' ...
Copying files from `/etc/skel' ...
wget -qO /tmp/pluginhook_0.1.0_amd64.deb https://s3.amazonaws.com/progrium-pluginhook/pluginhook_0.1.0_amd64.deb
dpkg -i /tmp/pluginhook_0.1.0_amd64.deb
Selecting previously unselected package pluginhook.
(Reading database ... 25028 files and directories currently installed.)
Unpacking pluginhook (from .../tmp/pluginhook_0.1.0_amd64.deb) ...
Setting up pluginhook (0.1.0) ...
lsmod | grep aufs || modprobe aufs || apt-get install -y linux-image-extra-`uname -r`
Opening /proc/modules: No such file or directory
FATAL: Could not load /lib/modules/3.14.27-xxxx-grs-ipv6-64/modules.dep: No such file or directory
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package linux-image-extra-3.14.27-xxxx-grs-ipv6-64
E: Couldn't find any package by regex 'linux-image-extra-3.14.27-xxxx-grs-ipv6-64'
make: *** [aufs] Error 100
```
This error seems to be a duplicate of #624 and #238 , with a possible workaround found here: https://gist.github.com/colmarius/9164345

But uname -a still prints: Linux mydomain.com 3.14.27-xxxx-grs-ipv6-64 #1 SMP Wed Dec 17 14:02:42 CET 2014 x86_64 x86_64 x86_64 GNU/Linux

Should I try to downgrade Kernel (Its *NOT* a VPS)? I tried to replace /bin/uname with a script that echoes the right version of kernel, but it's not working.

**Comment by josegonzalez** [comment]
What VPS are you trying to run this on?

**Comment by Antonhansel** [comment]
Thank you for your response and sorry, I meant to say it is NOT a VPS, I'm on a dedicated server from OVH.

**Comment by josegonzalez** [comment]
Is there a way for you to get aufs support *without* using an external repository? My concern here is that by adding an external - potentially untrusted - repository, we open up users to security/stability issues.

**Comment by Antonhansel** [comment]
After further investigating, the problem actually comes from OVH forking its own weird kernel (without warning their clients when you order a server).
I'm probably going to switch to digital ocean, thank you for your help :)

**Comment by josegonzalez** [comment]
Very well, closing. We should probably warn users that we do not support non-standard kernels :P
