### ISSUE TITLE
Wrong ip in generated nginx.conf after adding a domain

### ISSUE THREAD

**Issue by vincentfretin** [progrium/dokku#870]
Hi,
I use a fresh install of dokku master post v0.3.12, 2015-01-05 19:58 566cc1508143bb4c63a3d7a860c40704644f5f0b

cd myapp
git remote add deploy dokku@wholphin:myapp
git push deploy master

myapp.example.com is accessible, the generated nginx.conf contains
upstream myapp { server 172.17.0.52:5000; }
all good.

Now if I add a domain
ssh dokku@wholphin domains:add myapp wwww.myapp.example.com
The application is inaccessible because I have this in the generated nginx.conf:
upstream myapp { server 127.0.0.1:5000; }

**Comment by michaelshobbs** [comment]
What are the contents of the following in both cases?

```
$DOKKU_ROOT/HOSTNAME
$DOKKU_ROOT/VHOST
$DOKKU_ROOT/myapp/VHOST
```

**Comment by michaelshobbs** [comment]
Ah nevermind. I see the issue. I'll get this sorted and tested momentarily.

**Comment by michaelshobbs** [comment]
Whoops. Didn't mean to link that issue.
