### ISSUE TITLE
Error when adding domain to not yet deployed app

### ISSUE THREAD

**Issue by vincentfretin** [progrium/dokku#871]
Hi,
I use a fresh install of dokku master post v0.3.12, 2015-01-05 19:58 566cc15
ssh dokku@wholphin apps:create myapp
ssh dokku@wholphin domains:add myapp www.myapp.example.com
/var/lib/dokku/plugins/nginx-vhosts/commands: line 19: /home/dokku/novaideo_presentation/PORT: No such file or directory

The VHOST contains both myapp.example.com and www.myapp.example.com. Good.
The error here is because we're trying to generate the nginx.conf file and reload nginx.
I guess we should check that the app if deployed before trying to generate the nginx.conf here.

**Comment by michaelshobbs** [comment]
refs #870

**Comment by michaelshobbs** [comment]
@josegonzalez Was the domains plugin intended to be used prior to deploying an app?

**Comment by josegonzalez** [comment]
I don't see why not. Same arguments can be said about the config plugin.

**Comment by michaelshobbs** [comment]
The config app already works prior to an app being deployed. Should be fairly simple to make this happen. I can have a look at it.
