### ISSUE TITLE
`dokku plugins-install` is resulting in "Permission denied" error

### ISSUE THREAD

**Issue by thomasyip** [progrium/dokku#875]
I have successfully deploying and running a few dokku apps on amazon EC2 and vagrant (both on ubuntu 14 LTS).

But, on both system, I am not able to deploy any plugin using `dokku plugins-install` command.

```bash
$ dokku plugins-install https://github.com/beedesk/dokku-docker-options.git
/var/lib/dokku/plugins/00_dokku-standard/install: line 16: /etc/init/dokku-redeploy.conf: Permission denied
```

The relevant lines look like this:

```bash
# temporary hack for https://github.com/progrium/dokku/issues/82
# redeploys all apps after a reboot
case "$DOKKU_DISTRO" in
  ubuntu)
    sudo cat<<EOF > /etc/init/dokku-redeploy.conf
    ...
EOF
```

At first, I thought it was issue #82. But, I tried to change the owner of the conf file, but it only get me another permission error in one of the next step. 

I couldn't find other related issue, so I decide to file this.

Is it a known bug?

Is there some workaround I can use to get around the problem?

**Comment by josegonzalez** [comment]
The `plugins-install` command does not install plugins, it merely runs the `install` pluginhook. You need to follow the directions of that plugin to install it.

**Comment by thomasyip** [comment]
@josegonzalez, thanks for the quick reply.

**Comment by mattions** [comment]
hey guys,

just want to report I found this error again today.

```
    mattions@carrier:~$ dokku plugins-install
    /var/lib/dokku/plugins/00_dokku-standard/install: line 16: /etc/init/dokku-redeploy.conf: Permission denied
```


The solutions was to run dokku with sudo:

```
    sudo dokku plugins-install
```

and I've managed to install the mariadb plugin.
