### ISSUE TITLE
Wrong app URL when no VHOST file exists

### ISSUE THREAD

**Issue by 1player** [progrium/dokku#879]
**Problem:**

If you delete the VHOST file because you want to use port-based deployment (i.e. you're installing dokku in a VM), I expect the application to be deployed at http://`hostname`:`port` as per documentation.
But the current release deploys the app on http://`app-name`.`hostname`, ignoring the fact that no VHOST is set.

**Steps to reproduce:**

1) Install dokku
2) Remove /home/dokku/VHOST
3) Deploy sample node-js-app
4) In the git push output you'll see

    =====> Application deployed:
    http://node-js-app.<hostname>

**Expected outcome:**

    =====> Application deployed:
    http://<hostname>:<port>

**Possible fix:**

`dokku url node-js-app` returns the wrong hostname although the logic is correct.
The issue is in `dokku nginx:build-config node-js-app` as the logic to deploy on a port is executed only when the NO_VHOST variable is set (https://github.com/progrium/dokku/blob/master/plugins/nginx-vhosts/commands#L32)

Setting it manually works as expected:

    root@combotest:~# env NO_VHOST=1 dokku nginx:build-config node-js-app
    -----> NO_VHOST set, deleting node-js-app/VHOST
    -----> NO_VHOST set, deleting nginx.conf
    -----> NO_VHOST set, reloading nginx after nginx.conf deletion

I suspect this NO_VHOST variable should be set after deploy before calling nginx:build-config, but it isn't.

If you can point out which is the best place to set this variable, I can do a pull request myself.

**Comment by michaelshobbs** [comment]
I'm not sure that is the correct procedure for port based deployment. My understanding (perhaps incorrectly) is that we want to support the ability to deploy some apps with vhost support and some without on the same host. Therefore the correct method to deploy an app using the port based access config would be to set NO_VHOST with the `config:set` command. Again, I may be wrong here but I know that was the assumption I've approached the last few PRs with for the `domains` and `nginx-vhosts` plugins. 

@josegonzalez What is the correct procedure for port based deployment and are we expected to support a mix of VHOST and non VHOST apps on the same dokku host?

**Comment by 1player** [comment]
I found a note about NO_VHOST in the documentation, the problem is that in the Installation Guide, I quote:

> Make sure /home/dokku/VHOST is set to this domain. By default it's set to whatever hostname the host has. This file is only created if the hostname can be resolved by dig (dig +short $(hostname -f)).  Otherwise you have to create the file manually and set it to your preferred domain. If this file still is not present when you push your app, dokku will publish the app with a port number
> https://github.com/progrium/dokku/blob/master/docs/installation.md#configuring

Either we fix the configuration, or, what I would prefer, is that NO_VHOST is set upon deploy, whether or not that particular setting is enabled in the app configuration file.

**Comment by michaelshobbs** [comment]
To clarify, you'd prefer dokku automatically set NO_VHOST in the case that `/home/dokku/VHOST` doesn't exist. Is that correct?

**Comment by josegonzalez** [comment]
If the file isn't specified on first deploy, what would the url be? How do we reconcile it with custom domains?

Unless there is a straightforward answer to that, I think the docs need to change to say "If the file does not exist on first deploy, the domain will be set to host:port" or something similar.

**Comment by 1player** [comment]
@michaelshobbs Yes.

@josegonzalez Your suggested documentation change is incorrect, as the bug report states that even when VHOST does not exist, the URL returned after git push does not show any port.

Either dokku is fixed to follow what's stated in the installation guide, or we should just change it to say:
"If VHOST doesn't exist, you need to manually set the NO_VHOST configuration option for port-based deployment to work".

I can do that, I just want to agree on a direction :)

**Comment by josegonzalez** [comment]
What is the *actual* url in this case? Does it persist as what used to be the hostname?

**Comment by 1player** [comment]
I do not understand your question -- the example is from a fresh VM with a fresh installation of dokku.

To recap: hostname = ubuntu, no /home/dokku/VHOST file exists, the app is deployed to `http://node-js-app.ubuntu`

Which is wrong.

**Comment by josegonzalez** [comment]
My question is: When you first setup dokku and do not use a VHOST file, what would the url for an app end up being?

**Comment by 1player** [comment]
This: **http://node-js-app.ubuntu**
Basically: http://`appname`:`hostname`

**Comment by michaelshobbs** [comment]
I'll see if I can get better testing around this area. 

@josegonzalez To be clear, we want the default to behavior if there is no `$DOKKU_ROOT/VHOST` to be the same as if NO_VHOST was set. Correct?

**Comment by josegonzalez** [comment]
I think so. That makes sense to me (though we should document this clearly as well)

**Comment by michaelshobbs** [comment]
@1player would you mind banging around on #880 in your env? It seems to do what we're discussing here but want to double check.

**Comment by 1player** [comment]
@michaelshobbs I just tried and works beautifully.

**Comment by michaelshobbs** [comment]
The problem here is that if `/home/dokku/HOSTNAME` is not an IP we use it as the global VHOST. Right?

**Comment by michaelshobbs** [comment]
Ok I just submitted a patch to #880 that was less aggressive in the case of no global VHOST
