### ISSUE TITLE
Default PHP buildpack problems

### ISSUE THREAD

**Issue by klaussilveira** [progrium/dokku#882]
I'm running the default PHP buildpack with the following custom nginx configuration:

```
location / {
    try_files $uri @rewriteapp;
}

location @rewriteapp {
    rewrite ^(.*)$ /app.php/$1 last;
}

location ~ ^/(app|app_dev)\.php(/|$) {
    try_files @heroku-fcgi @heroku-fcgi;
    internal;
}

```

This is exactly the same as the sample used in the buildpack documentation. The same app works on heroku, but not with dokku. The error is:

```
[error] 88#0: *2 could not find named location "@heroku-fcgi"
```

Any ideas?

**Comment by josegonzalez** [comment]
Do you have a custom nginx config on heroku?

**Comment by klaussilveira** [comment]
Yes, exactly the same one.

**Comment by josegonzalez** [comment]
What is the name of the file? Is it in your repository?

**Comment by michaelshobbs** [comment]
This seems to refer to an internal heroku config 'thing'?

https://devcenter.heroku.com/articles/custom-php-settings

**Comment by josegonzalez** [comment]
@klaussilveira Were you able to figure out the issue? Sorry for getting back to you so late.

**Comment by klaussilveira** [comment]
Yes, i did. Dokku is using the PHP heroku buildpack v44. I manually updated my buildpack to the latest dev-master and it worked flawlessly.

**Comment by mattions** [comment]
@klaussilveira how did you update to the latest buildpack?

I'm having the same problem when I'm trying to get it going

**Comment by michaelshobbs** [comment]
@mattions include a `.env` file with `export BUILDPACK_URL=https://github.com/heroku/heroku-buildpack-php`

docs here: http://progrium.viewdocs.io/dokku/application-deployment
