### ISSUE TITLE
Modifying nginx.conf when installing hangs

### ISSUE THREAD

**Issue by MatthewMueller** [progrium/dokku#886]
When upgrading Dokku and running `sudo make install`. This is consistently hanging for me

```
Configuration file '/etc/nginx/nginx.conf'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** nginx.conf (Y/I/N/O/D/Z) [default=N] ? Y
```

I'm not sure this is a Dokku thing, but it's weirdly consistent. If I say `N` for this option it's fine. Not really sure what's going on.

**Comment by michaelshobbs** [comment]
Can you turn tracing on with `dokku trace on` and reproduce this? Would like to see which plugin is causing thing.

**Comment by josegonzalez** [comment]
I think this is actually dokku core. We modify the file and *then* install plugins-install. Weird though, haven't seen this in Virtualbox on 1.4.04.

**Comment by MatthewMueller** [comment]
it's a bit hard to reproduce, i've just noticed it every time i spin up a new digitalocean box and try to upgrade:

```
cd ~/dokku
git pull origin latest
rm -rf /var/lib/apt/lists/*
sudo make install
```

**Comment by josegonzalez** [comment]
We do not recommend installing via the digitalocean dokku box. I'll make that explicitly clear in the docs.

**Comment by MatthewMueller** [comment]
Honestly, I think that's how dokku is getting most of it's traffic. There's so many articles on how to get Dokku up and running on digital ocean. In general it's extremely easy, just when you are looking to upgrade.

If we're looking for as many people on the platform as possible (more plugins, more bugfixes, etc), I think making sure that pipeline runs smoothly is critical.

**Comment by josegonzalez** [comment]
Looks like we might be able to avoid this by not templating out the `/etc/nginx/nginx.conf` and instead customizing everything in `/etc/nginx/conf.d/dokku.conf;` ? Haven't tested it to be honest.

**Comment by josegonzalez** [comment]
We had to override the config file for #799. Not really sure what the correct choice is here - new nginx installs appear to have `server_names_hash_bucket_size` uncommented.

We'll be updating the default dokku image soon, but for now the best option is to simply choose `N` during an upgrade.

**Comment by MatthewMueller** [comment]
sounds good. thanks for investigating!

**Comment by scientist1642** [comment]
@josegonzalez Just for the record on dokku 0.2.3(DO image) after installing dokku-pg-plugin something changed /etc/nginx/nginx.conf and I had to uncomment:   
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_prefer_server_ciphers on;
because they were duplicates of etc/nginx/conf.d/dokku.conf. Any idea why this happened?
