### ISSUE TITLE
Dokku fails with large filenames

### ISSUE THREAD

**Issue by rchrd2** [progrium/dokku#889]
I am able to recreate a bug where dokku fails with really large filenames. I broke down the steps to confirm that it is this one file (with a crazy long name) that is breaking it. 

In my case the file name is `oKmauz-dLaAke3cUDynMnMGs2QiQJeBQVb_8QEyGvrJfenCffFHN4UJLFRbh52jhWD9DwcjUjhItZQsKw24K5ewDFQIU5QwowsTyiaiaO1ZyjhB0ieZyScunjkoRdhXCicBRjAoXZcBkdAlROcFzdPUhjAFyd1scjW4l-hw0SaBujW48Sagyjh90jhNlOfG0icBRjAoXZcBkdAlRO1FUiABkZWF3jAF8OcFzdPJwSY4zpe8ljPu0daZyJ68c.js`.

Example steps to reproduce the bug in gist: https://gist.github.com/rchrd2/76d439ad07bd87d556f2.
Dokku trace output: https://gist.github.com/rchrd2/76d439ad07bd87d556f2#file-trace-output-txt

@michaelshobbs points out that the problem probably lies in the git-receive hook.

I originally brought up this issue in this thread. https://github.com/progrium/dokku/issues/841#issuecomment-69694453

**Comment by michaelshobbs** [comment]
What is this output of the docker container?

In your example from the gist you can see the container logs with `docker logs 3661d783eb8d0ea537b4b288c80c344603e98ba6582a613b2288d9a15469917d`

**Comment by rchrd2** [comment]
Sorry, but I deleted my test app after finding a workaround. I recreated the test app with the offending file. The output of `docker logs` is minimal:
```
root@sandbox:/var/lib/dokku/plugins# docker logs 512db5a45cab

> embed-examples@0.0.0 start /app
> node index
```

**Comment by michaelshobbs** [comment]
Yeah that's not the correct container. We need to see the exited container that ran `/bin/bash -c 'mkdir -p /app && tar -xC /app`

ex:
```
root@dokku:~/dokku# docker ps -a --no-trunc
CONTAINER ID                                                       IMAGE                       COMMAND                                          CREATED              STATUS                          PORTS               NAMES
909e6fbe8dd994f582edf8c3a5125b9ac7961899e58dad189c5ed1543335876a   progrium/buildstep:latest   "/bin/bash -c 'mkdir -p /app && tar -xC /app'"   About a minute ago   Exited (2) About a minute ago                       determined_jang
```

I ran a deploy locally with that file name. Here are the results:
```
root@dokku:~/dokku# docker logs -f determined_jang
tar: ./public/oKmauz-dLaAke3cUDynMnMGs2QiQJeBQVb_8QEyGvrJfenCffFHN4UJLFRbh52jhWD9DwcjUjhItZQsKw24K5ewDFQIU5QwowsTyiaiaO1ZyjhB0ieZyScunjkoRdhXCicBRjAoXZcBkdAlROcFzdPUhjAFyd1scjW4l-hw0SaBujW48Sagyjh90jhNlOfG0icBRjAoXZcBkdAlRO1FUiABkZWF3jAF8OcFzdPJwSY4zpe8ljPu0daZyJ68c.js: Cannot open: File name too long
tar: Exiting with failure status due to previous errors
```

**Comment by michaelshobbs** [comment]
#890 should solve this issue by using cpio instead of tar

**Comment by rchrd2** [comment]
That's awesome! Thanks for fixing this.

**Comment by michaelshobbs** [comment]
@rchrd2 Unfortunately we arrived at https://github.com/docker/docker/issues/1413

My cpio solution was a red herring anyway.

**Comment by michaelshobbs** [comment]
From what I've gleaned from the Internetz, btrfs might solve this....
