### ISSUE TITLE
dokku config:set but without restart (in a pre-release hook)

### ISSUE THREAD

**Issue by vincentfretin** [progrium/dokku#908]
Hi,
I need to be able to call dokku config:set but without restarting the application, because I'm already in the process of restarting the application. I'm in a pre-release hook, see:
https://github.com/vincentfretin/dokku-elasticsearch-plugin/blob/master/pre-release#L37
How can we modify the config:set code to handle this case?
For now the application restarts twice if the elasticsearch container is not started.

**Comment by michaelshobbs** [comment]
@josegonzalez thoughts on this?

**Comment by josegonzalez** [comment]
Yeah, that seems like a reasonable request. Not sure on the best implementation, as it would need to work over ssh as well. Also, afaik no normal heroku plugin has the same requirements - when linked, a plugin sets configuration, it doesn't mount a container.

**Comment by michaelshobbs** [comment]
Should we just decouple the restart from config:set? That's probably reasonable since we now have a simple restart command.

**Comment by mmerickel** [comment]
Yes please. I think the current behavior of restarting is not desirable. Especially since the "auto-restart" only does a redeploy and not a rebuild. It'd be nice to have a rebuild command.

**Comment by josegonzalez** [comment]
Well config:set follows what heroku does - redeploy after configuration change. I'm still not sure as to why  the pre-release hook for that mongo plugin is setting configuration - shouldn't that go in a link step or something?

**Comment by michaelshobbs** [comment]
I suppose you could just interface with `$DOKKU_ROOT/$APP/ENV` directly but that kind of breaks the api boundary...

From https://devcenter.heroku.com/articles/config-vars: "Whenever you set or remove a config var, your app will be restarted."

Given that we're complying with Heroku's API, I don't think we should change `config:set`. Perhaps we can provide a "protected" function that does config setting/unsetting without restart that is only exposed via pluginhook?

**Comment by josegonzalez** [comment]
Why is that mongo plugin running config:set during a deploy?

**Comment by michaelshobbs** [comment]
You mean elasticsearch, right? I don't see mention of mongo here.

**Comment by josegonzalez** [comment]
Sorry yeah elasticsearch

**Comment by michaelshobbs** [comment]
That's a good point though. This could be done with a container link instead and bypass the entire `config:set` api. The deployed app would just use the standard docker env vars for linked containers.

**Comment by michaelshobbs** [comment]
This seems to be the agreed upon plugin to do this sort of thing. https://github.com/rlaneve/dokku-link

**Comment by josegonzalez** [comment]
Well we do have the plugin-spec issue, as well as a PR for plugins as addons...

**Comment by michaelshobbs** [comment]
Closing as there seems nothing to be done for this particular issue at this time. Feel free to reopen if there's anything else to discuss here.

**Comment by sekjun9878** [comment]
I am requesting that this issue be re-opened. At least a flag or option on config:set that does not redeploy is needed. I am already using Dokku Link, however config:set is needed to provide applications with a quick method of connecting to the plugin (URL format instead of host and port).

**Comment by josegonzalez** [comment]
@sekjun9878 would you mind submitting a PR for this?

**Comment by michaelshobbs** [comment]
I have something in a dev branch. Let me clean it up and submit the PR for review.

**Comment by josegonzalez** [comment]
@vincentfretin this has been fixed and documented in the plugin development section of the docs. Let us know if it works for you!

**Comment by sekjun9878** [comment]
:D thanks!

**Comment by vincentfretin** [comment]
@josegonzalez Thanks, I'll try it.
