### ISSUE TITLE
"pre-receive hook declined"

### ISSUE THREAD

**Issue by csu** [progrium/dokku#911]
When I try to use a custom buildpack in `.env` to serve a static site (I've tried the nginx one and `lorianheinemann/buildpack-nginx`), I get this: ` ! [remote rejected] gh-pages -> master (pre-receive hook declined)`.

**Comment by josegonzalez** [comment]
Can you paste the deploy logs? We can't really tell whats going on without you showing us more than just the error line. If possible, deploy after running `dokku trace on` and gist those logs.

[gist]([https://gist.github.com) is a good place to place gists.

**Comment by michaelshobbs** [comment]
> gist is a good place to place gists.

:+1: :wink:

**Comment by josegonzalez** [comment]
That was meant to be a link!

**Comment by RickCarlino** [comment]
I've been running a dokku box for months without issues and got the same problem today, too.

https://gist.github.com/RickCarlino/ab311c05244be1ff32a8

**Comment by josegonzalez** [comment]
So then it's a networking issue, no? If it's been working for a while and you didn't upgrade dokku, the issue must lie elsewhere. Not the greatest response, I know, but it's all I have. We've been talking of setting up google as the default dns which may or may not help things.

**Comment by csu** [comment]
Sorry I haven't followed up on this. I've been swamped by other work but will post logs as soon as I can.
