### ISSUE TITLE
PHP + Nginx unix socket permission problem

### ISSUE THREAD

**Issue by Epigene** [progrium/dokku#912]
Testing vanilla wordpress deployment with added procfile, composer.json and .lock and nginx.conf with the contents:

```text
location / {
    try_files $uri $uri/ /index.php?$args;
}
location ~ .php$ {
    try_files $uri =404;
    include fastcgi_params;
    fastcgi_pass unix:/tmp/heroku.fcgi.5000.sock;
}
```

Deploy finishes fine, however, visiting the app url gives me 502 gateway error.
Querying logs returns:

```text
root@apps:/home/dokku# dokku logs wp
Booting on port 5000...
Starting php-fpm...
Starting nginx...
2015/01/21 11:49:39 [crit] 92#0: *1 connect() to unix:/tmp/heroku.fcgi.5000.sock failed (13: Permission denied) while connecting to upstream, client: 172.17.42.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/tmp/heroku.fcgi.5000.sock:", host: "wp.apps.gs"
172.17.42.1 - - [21/Jan/2015:11:49:39 +0000] "GET / HTTP/1.1" 502 574 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.99 Safari/537.36"
```

Has anyone else ran into this and how do I fix it?

**Comment by ploddi** [comment]
Its selinux related. 

http://stackoverflow.com/questions/23948527/13-permission-denied-while-connecting-to-upstreamnginx

**Comment by Epigene** [comment]
Definitely not SELinux 
```text
root@tools:/var/log/nginx# sestatus
SELinux status:                 disabled
```text
And there are no SELinux log files either in messages or audit paths.

From what I have gathered reading similar issues elsewhere it is either nginx or php-fpm. Specifically, the users with which they are executed.

**Comment by michaelshobbs** [comment]
What is ownership/perms on that file? What user is exec'ing both processes?

**Comment by Epigene** [comment]
I am not sure the file at `/tmp/heroku.fcgi.5000.sock` exists either in the app container or the droplet filesystem.

From what I gather the problem might be arising from nginx executing under "www-data" user, but php-fpm under "nobody" user.

Truth be told, the location and configuration of the php-fpm process as it pertains to a php app container is completely unknown to me.

I am not sure on what port php-fpm is serving and what port nginx should be listening on.

**Comment by michaelshobbs** [comment]
Do you see anything when you run `docker ps`?

**Comment by Epigene** [comment]
I do - everything I have successfully deployed (the sample node app for example).

**Comment by michaelshobbs** [comment]
Grab the container id of the container running the start cmd.

Try these two commands
`docker exec -ti <container-id> ps auxwww`

`docker exec -ti <container-id> /bin/bash -c "ls -l /tmp/heroku.fcgi.5000.sock"`

**Comment by josegonzalez** [comment]
@Epigene any luck?

**Comment by Epigene** [comment]
The php-deploy-with-dokku project got shelved, and I have switched priorities, this problem will have to be solved by someone else.

Thanks for all the help, close the issue.

**Comment by mattions** [comment]
I have the same problem here. 
Should I open another bug, or shall we re-open this one?

**Comment by mattions** [comment]
For the time being I'll add it here

these are the results of the commands:
```
dokku@carrier:~/blog$ docker exec -ti  ab20644ee0788a9f6e5614466cab584150f1378c97bb13984080a82751d15c04 ps auxwww
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0  17976   252 ?        Ss   08:03   0:00 /bin/bash /start web
u29564      10  0.0  0.0  18028   376 ?        S    08:03   0:00 bash vendor/bin/heroku-php-nginx -C nginx_app.conf
u29564      73  0.0  0.0  18028   288 ?        S    08:03   0:00 bash vendor/bin/heroku-php-nginx -C nginx_app.conf
u29564      74  0.0  0.0  18028   272 ?        S    08:03   0:00 bash vendor/bin/heroku-php-nginx -C nginx_app.conf
u29564      75  0.0  0.0  18028   292 ?        S    08:03   0:00 bash vendor/bin/heroku-php-nginx -C nginx_app.conf
u29564      77  0.0  2.0 200264 10364 ?        Ss   08:03   0:00 php-fpm: master process (/app/vendor/heroku/heroku-buildpack-php/conf/php/php-fpm.conf)                                                           
u29564      79  0.0  0.0   4384   224 ?        S    08:03   0:01 tail -qF -n 0 /tmp/heroku.php-fpm.5000.log /tmp/heroku.php-fpm.www.5000.log /tmp/heroku.nginx_access.5000.log
u29564      80  0.0  0.0  18032   268 ?        S    08:03   0:00 bash vendor/bin/heroku-php-nginx -C nginx_app.conf
u29564      82  0.0  0.0  10976   260 ?        S    08:03   0:00 sed -u -E s/^\[[^]]+\] WARNING: \[pool [^]]+\] child [0-9]+ said into std(err|out): "(.*)"$/\2/
u29564      85  0.0  0.1  15664   756 ?        S    08:03   0:00 nginx: master process nginx -g daemon off; include /app/vendor/heroku/heroku-buildpack-php/conf/nginx/heroku.conf;
u29564      86  0.0  0.3  16504  1736 ?        S    08:03   0:00 nginx: worker process                                                                       
u29564      88  0.0  7.5 283364 37836 ?        S    08:05   0:11 php-fpm: pool www                                                                                                                                 
u29564     136  0.1  6.6 282652 33252 ?        S    11:11   0:04 php-fpm: pool www                                                                                                                                 
u29564     139  0.1  7.0 283076 35328 ?        S    11:12   0:03 php-fpm: pool www                                                                                                                                 
root       158  0.0  0.2  15568  1136 ?        Rs+  12:07   0:00 ps auxwww
```

and the second one:

```
dokku@carrier:~/blog$ docker exec -ti ab20644ee0788a9f6e5614466cab584150f1378c97bb13984080a82751d15c04 /bin/bash -c "ls -l /tmp/heroku.fcgi.5000.sock"
srw-rw---- 1 u29564 u29564 0 May 13 08:03 /tmp/heroku.fcgi.5000.sock
```

**Comment by mattions** [comment]
When I deploy I alos get this output:
```
       [13-May-2015 08:03:40] NOTICE: [pool www] 'user' directive is ignored when FPM is not running as root
       [13-May-2015 08:03:40] NOTICE: [pool www] 'user' directive is ignored when FPM is not running as root

```

**Comment by michaelshobbs** [comment]
You are seeing the same `crit` message? It looks like it started up. Just want to make sure we're debugging the same issue. Can you look at the nginx logs when attempting to hit this site? There is no error in what you posted; just an informational warning.

**Comment by mattions** [comment]
if I deploy the site with just
```
location / {
    try_files $uri $uri/ /index.php?$args;
}
```
everything seems to work ok (permalinks included), however if I add the specific block for the php bit I get an empty white page.

It basically goes and the site is live and responsive. (admin/xmlrpc/normal post are all responding.)

**Comment by michaelshobbs** [comment]
What does the access log show with the php block in? What about the error log? Also make sure `nginx -t` passes with that in place.

**Comment by michaelshobbs** [comment]
It sounds like you have a different issue btw

**Comment by mattions** [comment]
Hi, no logs are generaed when load the pages.

Just a white page.

Honestly I'm not sure this is anymore required with the latext heroku buildpack (May 2015), because it actually works ok.

**Comment by michaelshobbs** [comment]
Meaning it works without the additional nginx config?

**Comment by mattions** [comment]
yep, it works with just the bit I've uploaded above

**Comment by michaelshobbs** [comment]
Excellent
