### ISSUE TITLE
level="fatal" msg="cannot enable tty mode on non tty input" 

### ISSUE THREAD

**Issue by pdxbmw** [progrium/dokku#913]
The `dokku run` command executes the `docker run` command in interactive mode, which causes remote commands to terminate with the error: 

level="fatal" msg="cannot enable tty mode on non tty input" 

(I was trying to setup a cronjob to run nightly). The only way I could get this to work was to manually execute `docker run` without the -i switch instead of executing `dokku run`. 

Cronjob:

Doesn't work: 
`0 15 * * * bash -c ': | PATH="$PATH:/usr/local/bin" dokku run www python main.py' > /tmp/main.output`
Works:
 `0 15 * * * bash -c ': | PATH="$PATH:/usr/local/bin" docker run -t dokku/www /exec python main.py' > /tmp/main.output`

**Comment by michaelshobbs** [comment]
Perhaps related to #552 or new in the latest docker version. Not sure of the right solution here. Perhaps we can detect when we have a TTY and pass `-i` or not.

**Comment by pdxbmw** [comment]
Hmm, the only reference I see in the Docker release notes is back in [version 1.3.1](http://docs.docker.com/v1.3/release-notes/#version-131), but it's not clear to me what they fixed. For what it's worth, the first command worked before I upgraded Dokku (I believe I was on 0.2.0).

**Comment by michaelshobbs** [comment]
@pdxbmw #914 seems to solve your issue. can you confirm?

**Comment by pdxbmw** [comment]
Yes, I resorted back to my original command it worked perfectly.
