### ISSUE TITLE
Deploy always fails when using a custom buildpack

### ISSUE THREAD

**Issue by FWeinb** [progrium/dokku#919]
I am using the standard digitalocean droplet (dokku `v0.3.13`) and trying to use [this](https://github.com/florianheinemann/buildpack-nginx) custom buildpack to host a static WebApp. I read the troubleshooting guide and enabled tracing. Using `dokku trace on`. 

Every time I deploy there is the same bug when fetching a custom buildpack.  
```
-----> Fetching custom buildpack
remote: + exit_code=128
```

And after that the push ends with:

```
 ! [remote rejected] master -> master (pre-receive hook declined)
```

I verified that docker has an internet connection as described [here](http://progrium.viewdocs.io/dokku/troubleshooting)

**Comment by michaelshobbs** [comment]
How are you defining the custom buildpack? Can you share the contents of that method?

**Comment by FWeinb** [comment]
I have this `export BUILDPACK_URL=https://github.com/florianheinemann/buildpack-nginx.git` in an `.env` file in the root of my project and an additional `.static` file which is [required](https://github.com/florianheinemann/buildpack-nginx#usage) by the buildpack.

**Comment by josegonzalez** [comment]
Can you show the full deploy log?

**Comment by FWeinb** [comment]
[Here](https://gist.github.com/FWeinb/542a13dc3269ebbba5d7) it is.

**Comment by josegonzalez** [comment]
Odd, exit_code 128 means that it's an invalid exit code that is being sent to exit...

**Comment by FWeinb** [comment]
Anything I could try to make it work? Do you need some more information?

**Comment by michaelshobbs** [comment]
It's failing inside the `/build/builder` (i.e. build phase) container. I just added some troubleshooting steps to the docs regarding this. If you haven't already, you may try the those steps listed under the section labelled `I get the aforementioned error in the build phase (after turning on dokku tracing)`. 

Let us know what happens when you attempt to download that buildpack from inside the build container.

**Comment by FWeinb** [comment]
I did everything listed there. I also run `git clone https://github.com/florianheinemann/buildpack-nginx.git` from within the docker container without any issue.

**Comment by michaelshobbs** [comment]
Stupid question perhaps, but do you get the error if you try deploying again?

**Comment by michaelshobbs** [comment]
My hypothesis is that git exits with 128; which can mean all sorts of things based on the source code. Basically the checkout failed for some reason but the [script](https://github.com/progrium/buildstep/blob/091eafdad7ccf5f4584aa21704397fd1dc1fd208/builder/compile.sh#L54) hides the output...

**Comment by FWeinb** [comment]
I did it nearly 50 times now.

**Comment by michaelshobbs** [comment]
Well we're going to need to dig into the build container more and understand what is failing with exit code 128. 
Is there any additional configuration (volume/network) that we should know about? I'm not too familiar with DO. 

Alternatively you might want to try spinning up a new droplet to see if the problem persists.

**Comment by FWeinb** [comment]
I tried it with a new project (completely empty, just requiring the custom buildpack).
Without the custom buidpack everything is working fine.

**Comment by michaelshobbs** [comment]
Yeah without the custom buildpack just bypasses the problem. Did the new empty project that required the custom buildpack also fail?

Another thing to try is including a different buildpack. You might try deploying https://github.com/heroku/node-js-sample and including a `.env` file that has `export BUILDPACK_URL=https://github.com/heroku/heroku-buildpack-nodejs.git` in it. Would be interesting if it fails in the same manner.

**Comment by FWeinb** [comment]
That is working. Strange.

**Comment by michaelshobbs** [comment]
I'm not sure this is primary use case of dokku. However, the way you are attempting to host a static site is exactly how we do so in our test suite.

https://github.com/progrium/dokku/tree/master/tests/apps/static

**Comment by michaelshobbs** [comment]
@FWeinb were you able to debug this any further? Feel free to hop on irc if you'd prefer more real time assistance.

**Comment by michaelshobbs** [comment]
@FWeinb from the looks of it on IRC, you got sorted out?

**Comment by FWeinb** [comment]
@michaelshobbs Thanks for your help. I just created a new repo and first committed just the `.env` and  `.static` file, adding the application files afterwards (after the first push to the server)

**Comment by marothstein** [comment]
I am having this issue now. Would either @FWeinb or @michaelshobbs be willing to explain what the resolution was?

Having the ```.env``` and ```.static``` files committed to the repo did not fix it for me.

**Comment by josegonzalez** [comment]
@marothstein can you open another issue with the full output of your deploy (after running `dokku trace on`) in a gist?

**Comment by marothstein** [comment]
@josegonzalez I ended up getting passed this by re-adding my SSH keys properly, but I'm still having quite a bit of trouble running a static application. 

Current error is: 

```bin/nginx: error while loading shared libraries: libcrypto.so.0.9.8: cannot open shared object file: No such file or directory```

**Comment by alex88** [comment]
I'm having the same issue:

.env:
```
export BUILDPACK_URL=https://github.com/ddollar/heroku-buildpack-multi.git
```

deploy:

```
Pushing to dokku@146.185.xx.xx:test
Counting objects: 4391, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (1630/1630), done.
Writing objects: 100% (4391/4391), 2.56 MiB | 308.00 KiB/s, done.
Total 4391 (delta 2576), reused 4371 (delta 2561)
-----> Cleaning up...
-----> Building databoard from buildstep...
-----> Adding BUILD_ENV to build environment...
-----> Fetching custom buildpack
To dokku@146.185.xx.xx:databoard
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'dokku@146.185.xx.xx:test'
```

**Comment by mattberther** [comment]
@alex88: I was able to make mine work by removing the .env file and doing

```
dokku config:set <appname> BUILDPACK_URL=https://github.com/ddollar/heroku-buildpack-multi.git
```
