### ISSUE TITLE
app scripts

### ISSUE THREAD

**Issue by leonardodino** [progrium/dokku#923]
are there any build time scripts that are triggered early on? (on the core?)
epecially in this steps would be awesome (as they are before the tests)
```
 V -----> Preparing runtime environment...
 | -----> Discovering process types
 |        Procfile declares types -> web
 |        Default process types for PHP -> web
 | -----> Releasing php ...
 | -----> Deploying php ...
 ^ -----> Running pre-flight checks
 ? -----> Running post-deploy
```
and is post-deploy only accessible via plugins?

I know this feature probably departs the heroku default, but it seams that node.js apps have it, it should be nice to have this feature across the board.

**Comment by josegonzalez** [comment]
What do you mean by app scripts?

**Comment by michaelshobbs** [comment]
I had similar requirements (I think) and ended up writing the predeploy-tasks plugin here (michaelshobbs/dokku-app-predeploy-tasks).

**Comment by josegonzalez** [comment]
You can write your own custom plugin to have hooks for different settings. For instance, I think with PHP apps you can use the `extra.compile` key in your composer.json.

For the pluginhook, you'll want to hook into `pre-deploy`.
