### ISSUE TITLE
Redirects as a built-in feature

### ISSUE THREAD

**Issue by marvinroger** [progrium/dokku#924]
Hey,

Thanks for this great tool! I just saw that domain management is now a built-in feature of dokku, no need to use dokku-domains-plugin anymore. That's great to hear. But one important feature I think pretty much websites implement is redirect: non-www <-> www is required these days. We can do it using dokku-redirects-plugin, but as you implemented domains I thought you could also implement redirects.

Cheers.

**Comment by josegonzalez** [comment]
How does it work for that plugin? I don't see this as a bad feature myself, just want to have a good implementation...

**Comment by marvinroger** [comment]
How does it work ? It basically loops through set redirects ($source, $destination) and for each one adds an nginx directive like so:

```
server {
    listen [::]:80;
    listen 80;
    server_name $source;
    return 301 http://$destination\$request_uri;
}
```

It would obviously also add a directive on :443 if using HTTPS.
Unfortunately, I can't help much about implementing this feature, my skills are limited on bash. :disappointed:

**Comment by josegonzalez** [comment]
What if a user wants the www version?

**Comment by josegonzalez** [comment]
Ah I see what it's doing. [Plugin](https://github.com/Mordred/dokku-redirects-plugin) for reference.

**Comment by marvinroger** [comment]
I indeed forgot the link, I apologize. Thank you for having had a look!

**Comment by marvinroger** [comment]
https://github.com/dokku-alt/dokku-alt already implemented this feature, maybe that might help.

**Comment by josegonzalez** [comment]
Is there a similar solution for heroku somewhere? If so, we could probably copy it's ui and provide an official plugin, or at least modify that above plugin and make sure it works with dokku.

**Comment by Flink** [comment]
@josegonzalez it seems heroku doesn’t have an official redirect plugin/command. However we could have something like this:
```shell
dokku redirect:set <app> <domain-from> <domain-to>
dokku redirect:unset <app> <domain>
dokku redirect (to list all redirects)
```
SSL redirects are already handled I think.

**Comment by josegonzalez** [comment]
@Flink An official plugin could work here if you want to take a stab at it :)

**Comment by Flink** [comment]
@josegonzalez no problem, I’ll do that.

**Comment by Flink** [comment]
Just created https://github.com/dokku/dokku-redirect if anyone wants to test it :)

**Comment by josegonzalez** [comment]
@Flink nice. One thing we might want to do is note that the redirects are currently only domain-based.

**Comment by Flink** [comment]
Yes, you’re right, I’ll modify the README

**Comment by josegonzalez** [comment]
Also, add it to our list of official plugins and close this issue with that commit :)

**Comment by Flink** [comment]
done :)

**Comment by marvinroger** [comment]
Thanks!
