### ISSUE TITLE
HTTPS config issue - documentation says ok to use PEM, but didn't work for me.

### ISSUE THREAD

**Issue by MichaelJCole** [progrium/dokku#930]
Hi, this page says it's ok to use a .pem file.

http://progrium.viewdocs.io/dokku/nginx

I uploaded a pem and key with SCP, and nginx was ok with the configuration, but Dokku didn't use them to configure my deployed apps.  

So I think that's a bug in the docs at least.  I had to rename the pem to a crt and it worked.  Maybe worth a note.

Also, thanks for this cool tool!  

Here's documentation I wrote for myself on how to configure a new Dokku server at DigitalOcean - if you're into that sort of thing:

## Setup Dokku/Docker container

  1. Create a Droplet on DigitalOcean 
    - name it after the root domain.  E.g. example.com
    - Select Image -> Applications -> Dokku v0.3.13 on 14.04
    - Select one of your SSH keys
  2. Configure DNS to point to the new IP.
    - Login to DNSimple (or wherever) and make 2 records
      - A       [Hostname]      [Droplet IP address]
      - A       *.[Hostname]    [Droplet IP address]
  3. Get a SSL wildcard cert for domain.  Save in private location [servername].key and .pem
  4. Visit the droplet in a browser.  http://example.com
     - Replace the IP with the domain name:  example.com
     - Select virtualhost checkbox
     - Ok
  5. Configure the Droplet:
     - Turn on some swap: ssh root@example.com
```
dd if=/dev/zero of=/swapfile bs=1024 count=512k
mkswap /swapfile
swapon /swapfile
echo "/swapfile       none    swap    sw      0       0" | sudo tee /etc/fstab
echo "10" | sudo tee /proc/sys/vm/swappiness
echo "vm.swappiness = 10" | sudo tee -a /etc/sysctl.conf
sudo chown root:root /swapfile 
sudo chmod 0600 /swapfile
```

     - Add SSL Certs:
       - Run these from your local computer - where you saved the certs
       - Notice the pem is copied as a crt.  Pem does not work.

```
ssh root@example.com 'mkdir -p /home/dokku/tls/'
scp example_com.key root@example.com:/home/dokku/tls/server.key
scp example_com.pem root@example.com:/home/dokku/tls/server.crt
```
       - ssh into box:
```
echo "ssl_certificate /home/dokku/tls/server.crt;" | sudo tee -a /etc/nginx/conf.d/dokku.conf
echo "ssl_certificate_key /home/dokku/tls/server.key;" | sudo tee -a /etc/nginx/conf.d/dokku.conf
```
       - reboot the server through DigitalOcean console.  "Power Cycle"
       - deploy your app.

**Comment by josegonzalez** [comment]
Interesting. We handle it with `nginx:import-ssl` now - so the docs are a bit outdated - but we should def at least update the docs.

**Comment by MichaelJCole** [comment]
Hi Jose, 

I think import-ssl only works for an individual app.  The above method adds a wildcard cert for the whole server.

```
nginx:import-ssl <app>                          Imports a tarball from stdin; should contain server.crt and server.key
```

The bug is this:  

1) The docs say it's ok to use .pem/.crt
http://progrium.viewdocs.io/dokku/nginx

2) When deploying an app, the deploy code only makes the app https if a .crt is present.
