### ISSUE TITLE
How to configure environment variables for multiple apps?

### ISSUE THREAD

**Issue by MichaelJCole** [progrium/dokku#931]
Hi, I have a group of related apps.

I keep an 'ops' repo separate from my code repos.  It has all my apps secrets.

Ideally, I'd like to set the config environments for all my apps to be the same, by loading one file.

The only way I see to do it is one app at a time, by scp'ing a file into /home/dokku/<app>/ENV, then restarting.

Setting them one-by-one would be kinda tedious.

What's the smartest way to set all these apps environment variables to be the same?

Also, how can I configure the environment *before* the app is run?

Thanks!

Mike

**Comment by josegonzalez** [comment]
- You can create an app using `dokku apps:create`. 
- You can have global - but override-able - environment configuration in your `/home/dokku/ENV` file. This is prepended to the app-specific config before the build process. Note that users may still configure environment variables and override the global ones.
- You need to restart an app in order to ensure the env vars in the instance are the same as those on disk. The `ps:restart` command - due for the upcoming `0.4.0` release - should take care of this I blieve. It's in master atm.

**Comment by MichaelJCole** [comment]
Ah!  I saw `/home/dokku/ENV` but didn't do the restart, so the changes didn't take.  Thanks!  Looking forward to 0.4 :-)

**Comment by MichaelJCole** [comment]
Hey, I tested this and got this behavior:
1) Upload file to /home/dokku/ENV
2) Print env vars during container "build" - saw my new vars.
3) Print env vars during container "run" - didn't see them.
4) Rebooted server.
5) Print env on 'run' - didn't see them

As a workaround, I ssh'd into box and ran this:
`rm ENV && ln -s ../ENV `

Then rebooted, then deployed new code to my app.  

*Then* saw the env in was set correctly for the app.

I'm using 0.3.13

**Comment by vincentfretin** [comment]
@MichaelJCole You need to source /app/.profile.d/app-env.sh inside your container to see your env variables. This is done by the /start or /exec script.

**Comment by michaelshobbs** [comment]
That's odd though because we use `/exec` in run.

https://github.com/progrium/dokku/blob/2dad1afa572d379d840696773072e3aea467bc78/plugins/00_dokku-standard/commands#L54

**Comment by michaelshobbs** [comment]
Ah! `$DOKKU_ROOT/ENV` is only used in the the `pre-build` environment. @josegonzalez does it makes sense to include those env vars in all app envs?

**Comment by josegonzalez** [comment]
So long as heroku does it, +1

**Comment by michaelshobbs** [comment]
It does not seem to do so.

**Comment by michaelshobbs** [comment]
@MichaelJCole if you'd like to see these env vars in your app, you'll need to place/symlink and env file to `$DOKKU_ROOT/$APP/ENV` and ensure you are including the `export` command for each variable.

Also, to clarify, when you say "Print env on 'run' - didn't see them", do you mean `dokku run` or app run? If app run, how are you printing them?

**Comment by MichaelJCole** [comment]
Ok, I'll make symlinks or upload individual files.  I was looking for a global config, one-by-one will work.

"Print env on 'run' - didn't see them" - by this I mean testing when the app automatically restarted after reboot.  Sorry, it wasn't very clear :-)

Thanks for working on this!

Mike

**Comment by josegonzalez** [comment]
@michaelshobbs wait, are `$DOKKU_ROOT/$APP/ENV` vars available in pre-build?

**Comment by michaelshobbs** [comment]
Yep

**Comment by josegonzalez** [comment]
I thought you said the global ones aren't? They seem to be as well though...

**Comment by michaelshobbs** [comment]
The global and app-specific are available in `pre-build` but only the app-specific envs are available at deploy/run.

**Comment by josegonzalez** [comment]
That seems bizarre, and unexpected behavior to me. Would it not make more sense to have global *also* available at deploy/run?

**Comment by michaelshobbs** [comment]
It's kind of a semantics issue, right? We currently use `$DOKKU_ROOT/ENV` to define the build-env but here we are expecting that to be a global configuration for all apps. 

However, this assumption does not line up with the documentation. In fact, we call out the danger in defining truly global config vars in the docs. We just didn't implement that. 

I'll take a look at including the global ENV file in deploy and run.

**Comment by josegonzalez** [comment]
Right, we make it hard to configure that global env on purpose, but I believe we should be able to provide that functionality for those brave/silly/poor souls that would like to use it. We can still document the fact that it is not recommended unless you know what you are doing.

**Comment by MichaelJCole** [comment]
I don't think it's better to make it hard to use.  Global configuration fits my use case.  One developer, 5 apps that all use the same configuration for external services (Papertrail, Cloudinary, etc).

**Comment by michaelshobbs** [comment]
#941 should take care of this. Looks like I need to rebase it though.
