### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by pmvieira** [progrium/dokku#934]
I was trying to deploy an app but I started to get this error:

-----> Ruby app detected
       !
       !     Command: 'set -o pipefail; curl --fail --retry 3 --retry-delay 1 --connect-timeout 30 --max-time 30 https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/bundler-1.6.3.tgz -s -o - | tar zxf - ' failed unexpectedly:
       !
       !     gzip: stdin: unexpected end of file
       !     tar: Child returned status 1
       !     tar: Error is not recoverable: exiting now
       !

The interesting is that if I run " set -o pipefail; curl --fail --retry 3 --retry-delay 1 --connect-timeout 30 --max-time 30 https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/bundler-1.6.3.tgz -s -o - | tar zxf - ' " from the server terminal, It runs fine...

But if I run this, it fails: 

root@localhost:~# docker run -t -i progrium/buildstep bash
root@53ec89d0d159:/# set -o pipefail; curl --fail --retry 3 --retry-delay 1 --connect-timeout 30 --max-time 30 https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/bundler-1.6.3.tgz -s -o - | tar zxf - 

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now

**Comment by michaelshobbs** [comment]
try running `curl -s -S -O https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/bundler-1.6.3.tgz` inside that container. We need to see where in the stack it's failing inside the container.

**Comment by pmvieira** [comment]
looks it might be dns? it's odd... because in the box works fine... 
root@263e6f777985:/# curl -s -S -O https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/bundler-1.6.3.tgz
curl: (6) Could not resolve host: s3-external-1.amazonaws.com

**Comment by pmvieira** [comment]
Thanks for the help Michael, Ihis is a DO box and I'm actually noticing some considerable latency on this box, so it might be related?

**Comment by michaelshobbs** [comment]
It's possible. I haven't used DO before but I have seen these issues pop up in the project before. The troubleshooting doc references `resolvconf -u` may help if somehow the instance has switched networks. Also, using a 3rd party DNS resolver like Google can help. See: https://github.com/progrium/dokku/issues/841#issuecomment-69527122

**Comment by pmvieira** [comment]
This was due to an issue with the DO and was sorted with a reboot. Thanks Michael for all your help! closing this now.
