### ISSUE TITLE
PHP: Failed to resolve runtime requirements.

### ISSUE THREAD

**Issue by intellent** [progrium/dokku#939]
Hey everyone,

just installed Dokku v0.3.13 on Ubuntu 14.04 (w/ Docker 1.4.1) and tried to deploy my first PHP app. This is, what I get:

    $ git push deploy_production master:master
    Counting objects: 52, done.
    Delta compression using up to 4 threads.
    Compressing objects: 100% (45/45), done.
    Writing objects: 100% (52/52), 18.02 KiB | 0 bytes/s, done.
    Total 52 (delta 25), reused 15 (delta 4)
    -----> Cleaning up ...
    -----> Building my-php-app ...
    -----> Adding BUILD_ENV to build environment...
    -----> PHP app detected
       
           !     ERROR: Failed to resolve runtime requirements.
           If the issue persists, please contact support.
       
    To dokku@my-host.com:my-php-app
     ! [remote rejected] master -> master (pre-receive hook declined)
    error: failed to push some refs to 'dokku@my-host.com:my-php-app'

It’s a simple app with an index.php in its root. I tried to add a composer.json, but the error persists:

    {
        "require": {
            "php": ">=5.5.10"
        },
        "extra": {
            "heroku": {
                "index-document": "index.php"
            }
        }
    }

Did I miss anything during installation? Do I need to compile PHP beforehand?

**Comment by michaelshobbs** [comment]
I also noticed that the composer.json you posted is not valid and yields the following error when I deploy in my dev env. When I remove the trailing comma, my deploy completes successfully. Is there additional json that might be causing issues?

```
-----> PHP app detected

       !     ERROR: Could not parse composer.json; make sure it's valid!

To dokku@dokku.me:test-php-12351
 ! [remote rejected] master -> master (pre-receive hook declined)
```

**Comment by intellent** [comment]
Ahh, yeah, sorry. The composer.json I use, is valid. Just a copy/paste error when creating this issue. I added the "silex/silex": "~1.1" requirement to the composer.json just to get a composer.lock and tried to redeploy. Still no success, though.

**Comment by michaelshobbs** [comment]
Are you on Digital Ocean?

**Comment by michaelshobbs** [comment]
The error you are getting is coming from a line similar to this one:

```
echo -n "{"lock": {"stability-flags": [], "platform": {"hhvm": null, "php": ">=5.5.10"}, "prefer-stable": false, "minimum-stability": "stable"}, "json": {"platform": {"hhvm": null, "php": ">=5.5.10"}, "prefer-stable": null, "minimum-stability": null}, "packages": ["hhvm-3.2.0", "php-5.5.11", "php-5.5.12", "php-5.5.13", "php-5.5.14", "php-5.5.15", "php-5.5.16", "php-5.6.0", "php-5.6.1"]}" | curl --silent --location --fail -HContent-Type: application/json -d @- http://php-runtime-version-selector14.herokuapp.com/resolve?default_runtime=php
```

You'll want to test this inside of a container on this host. So run something like:

```
root@dokku:~/dokku# docker run -ti progrium/buildstep bash
root@2b04d80b02cb:/# echo -n "{"lock": {"stability-flags": [], "platform": {"hhvm": null, "php": ">=5.5.10"}, "prefer-stable": false, "minimum-stability": "stable"}, "json": {"platform": {"hhvm": null, "php": ">=5.5.10"}, "prefer-stable": null, "minimum-stability": null}, "packages": ["hhvm-3.2.0", "php-5.5.11", "php-5.5.12", "php-5.5.13", "php-5.5.14", "php-5.5.15", "php-5.5.16", "php-5.6.0", "php-5.6.1"]}" | curl --silent --location --fail -HContent-Type: application/json -d @- http://php-runtime-version-selector14.herokuapp.com/resolve?default_runtime=php ; echo ""; echo ""

php|default|*|

root@2b04d80b02cb:/#
```

**Comment by intellent** [comment]
Yes, I am on DigitalOcean. And the cause was IPv6 [1]! If I create the droplet without IPv6 support, everything works. This wasn’t a PHP specific problem, after all. Other buildpacks didn’t work, too.

Thanks for pointing me in the right direction!

[1]: https://www.digitalocean.com/community/questions/pre-receive-hook-declined-on-dokku-image

**Comment by michaelshobbs** [comment]
Glad it got sorted out.

**Comment by josegonzalez** [comment]
@michaelshobbs any chance we can add IPv6 testing to CircleCI? I'll screw around with IPv6 boxes on my DO account and see if I can replicate this issue as well.

**Comment by michaelshobbs** [comment]
I'll take a look.

**Comment by michaelshobbs** [comment]
From CircleCI:

```
we're running in EC2 which doesn't support IPv6 traffic (to the best of my knowledge) and our firewalls explicitly drop all IPv6 traffic inbound and outbound.
If you limit what you're testing to inside the container then it shouldn't be filtered by the firewall, but I'm afraid you're out of luck using regular IPv6 to the outside world.
```

**Comment by mc0e** [comment]
Whether there is network support for ipv6 is beside the point.  Things break if support for ipv6 is turned on inside the VM that docker runs on.

I've mostly been ok with just setting ipv6 forwarding on (`sysctl -w net.ipv6.conf.all.forwarding=1`) , but after updating to docker 1.5, things have broken again.

**Comment by maethor** [comment]
I seem to have the same problem, and I really don't understand what to do.

@michaelshobbs test fails after 60 seconds.

```
test-dokku01% sudo docker run -ti progrium/buildstep bash
root@3f70bf19f4d6:/# echo -n "{"lock": {"stability-flags": [], "platform": {"hhvm": null, "php": ">=5.5.10"}, "prefer-stable": false, "minimum-stability": "stable"}, "json": {"platform": {"hhvm": null, "php": ">=5.5.10"}, "prefer-stable": null, "minimum-stability": null}, "packages": ["hhvm-3.2.0", "php-5.5.11", "php-5.5.12", "php-5.5.13", "php-5.5.14", "php-5.5.15", "php-5.5.16", "php-5.6.0", "php-5.6.1"]}" | curl --silent --location --fail -HContent-Type: application/json -d @- http://php-runtime-version-selector14.herokuapp.com/resolve?default_runtime=php ; echo ""; echo ""


root@3f70bf19f4d6:/#
```

But I don't understand why. I don't have any public IPv6 address configured on the host. So why is it trying to connect on IPv6 ? And why is it not falling back on IPv4 ?

**Comment by michaelshobbs** [comment]
I'm not sure I have enough info to help you out but let me see what I can do. Depending on your hosting provider, the kernel of the instance could be configured with IPv6 even though there is no 'public' address. Hence you would see same behavior as you did when running `ping6 google.fr`. Also, I'm not sure how to configure IPv4 "fallback" with docker containers.

This article talks about disabling IPv6 on Ubuntu. You might try that?
http://askubuntu.com/questions/440649/how-to-disable-ipv6-in-ubuntu-14-04

**Comment by maethor** [comment]
Indeed, disabling IPv6 on the host fixes the bug. But I should not have to do that. I'm new to docker and dokku. Do you think it's a bug in dokku, or in docker ?

**Comment by josegonzalez** [comment]
It's a docker bug. Dokku is just a bunch of shell code :).

**Comment by mc0e** [comment]
@maethor do you actually have working routable ipv6?  

I'm thinking that the 'bug' is simply that ipv6 looks like it's available and somewhere between docker and the container, and the app in the container, a decision is made to use that.  In my case I'm not surprised that fails because routing is not set up.  I'd be interested in what happens when ipv6 is actually operational.

**Comment by maethor** [comment]
@mc0e nope, the IPv6 routing is not set up on this host. But I will configure it and keep you informed.

**Comment by maethor** [comment]
@mc0e I have setup the IPv6 on the host, with a routed ipv6, and I still have the same problem :(

**Comment by josegonzalez** [comment]
@maethor what hosting platform are you using?

**Comment by mc0e** [comment]
@maethor Do you have ipv6 forwarding turned on?  I.e. what's the output of `sudo sysctl -a | grep 'net\.ipv6\.conf.*forwarding'`.

As @josegonzalez is probably alluding to, most people who report this problem are on DigitalOCean with IPv6 turned on.  However I'm also seeing it in Vagrant environments with the official Ubuntu 14.04 box.

**Comment by josegonzalez** [comment]
@mc0e I don't see the issue with our current vagrant setup :(

This is definitely a docker issue, but I'm game for figuring out how we can help our users avoid it :(.

**Comment by mc0e** [comment]
Actually after playing with it tonight in Vagrant, I'm 100% sure it's not a docker issue.  Docker just demonstrates a fault in libcurl which I think has been fixed upstream, but that hasn't made it into Ubuntu's packaging.

https://bugs.launchpad.net/ubuntu/+source/curl/+bug/1457192

**Comment by josegonzalez** [comment]
Ha great, so whats the fix for us?

**Comment by mc0e** [comment]
Well for some reason the bug doesn't manifest on the bare metal, so presumably there's a way to change the network environment such that libcurl doesn't behave that way.

The easier immediate solution is going to be to download the gpg key a different way (e.g. wget) and pipe it into gpg, or perhaps to put the gpg directly into the dokku install script.  If you're hard-coding the keys ID, why not the key's content?

However, libcurl is widely used and this will just pop up somewhere else if not fixed properly.

**Comment by josegonzalez** [comment]
The "bug" in this case isn't the GPG key, it's that libcurl in the container is unable to retrieve the buildpack (or similar). So not that simple.

All we can do is document it I think? Unless we can patch the buildstep/buildkit image we use.

**Comment by mc0e** [comment]
hmm.  Actually yes, this is one of those 'somewhere else' spots that the bug pops up from my current point of view.  I've been primarily focussed on the problem of installing docker in some environments, including Vagrant and Digital Ocean droplets with ipv6 enabled.

**Comment by maethor** [comment]
@josegonzalez @mc0e I'm not using a cloud plateform, my servers are hosted by the french company Online.net. It's a KVM virtual machine running on a private Ganeti cluster.

I have IPv6 turned on, and I can't ping6 anything from inside the container.

```
test-dokku01% ping6 google.fr                            
connect: Network is unreachable
```

If I disable ipv6 with sysctl, I don't have the problem anymore.

**Comment by josegonzalez** [comment]
Right, what I'm saying is that it appears that libcurl or something else is broken under ipv6.

**Comment by maethor** [comment]
Just to clarify, when you say libcurl (or something else), you say libcurl (or something else) in the pogrium/buildstep container, right ? 

It would explain everything, indeed.

**Comment by josegonzalez** [comment]
Right (which is basically the same as on the instance hosting the container, depending upon the source of 14.04 being installed).

**Comment by mc0e** [comment]
libcurl on any currently existing version of ubuntu is old enough that it has bugs which means that if the dns info it receives includes ipv6 it will attempt an ipv6 connection, and if that fails, it will not fall back to attempting to use ipv4.  I suspect there is some sort of decision on whether to request ipv6 info (AAAA), but I haven't dug into it far enough to be sure how that goes.  I suspect the answer is in [this fix](https://github.com/bagder/curl/commit/9081014c2c467077723d5ae1d0081003b3eb3504).

I've mostly pursued this in a different context.  I expect this bug also involves libcurl, but haven't verified that.  If you want to check on that, I'd suggest using ltrace.  And yes, I expect the command that's failing is inside the buildstep container.

libcurl problems  would not affect ping6.  That's more likely an actual problem in your ipv6 network setup.

**Comment by maethor** [comment]
`ping6` works fine. The container doesn't have a routable IPv6, so it returns "Network unreachable". That OK.

The problem with `libcurl` (if that's libcurl, I don't know) is that it doesn't fallback on IPv4 after trying to connect in IPv6.
