### ISSUE TITLE
Fresh install of dokku using DO's image

### ISSUE THREAD

**Issue by Trickierstinky** [progrium/dokku#944]
I've just done a fresh install of the Digital Oceans' image for dokku, followed the setup on ```[ip]:2000``` and when I come to push the Node js sample package.

I get **! [remote rejected] master -> master (pre-receive hook declined)**

This is the verbose output from the push : https://gist.github.com/Trickierstinky/ab7741b964bb6fe481d5

I've also tried a basica rails app, and also custom build pack for a static site all resulting in the same issue.

Any ideas?

Thanks
Matt

**Comment by josegonzalez** [comment]
Setup on `:2000` ?

**Comment by Trickierstinky** [comment]
Sorry It seems I messed up on some syntax it should have been  ```[ip]:2000```

**Comment by josegonzalez** [comment]
As far as I know, we don't do any setup on port `2000`. What guide did you follow?

**Comment by Trickierstinky** [comment]
Sorry this is my fault I'm getting totally mixed up here I did that process a couple of hours ago and couldn't remember which guide or url I used, so I just did a quick google and came across the dokku-alt instructions which is where I just copied and pasted the url which uses port 2000. 

Let me clarify I didn't actually use this guide just as a reference when typing this issue up, the guide I actually used was https://www.digitalocean.com/community/tutorials/how-to-use-the-dokku-one-click-install-image-to-deploy-your-app

Once again sorry for the confusion, I'm just getting myself confused!

**Comment by josegonzalez** [comment]
Ha great. So you used the web installer for setting up dokku or no?

**Comment by Trickierstinky** [comment]
yeah I used the web installer and chose to use virtual host for the apps.

**Comment by josegonzalez** [comment]
@Trickierstinky any chance you can go on IRC so we can debug your issue? We're #dokku on freenode :)

**Comment by michaelshobbs** [comment]
@Trickierstinky did we wind up sorting this out?

**Comment by Trickierstinky** [comment]
Afraid I didn't, I needed something up so I had to ditch the box and boot another one where I could just manually host my rails / node projects.

I do have a backup of the dropplet that I could boot up if you think it could be down to a bug or anything. But if you just think it's down to human error then I'm ok I'll leave it thanks :+1:

**Comment by michaelshobbs** [comment]
@Trickierstinky just to clarify here, are you sure you are using dokku and not dokku-alt?

**Comment by Trickierstinky** [comment]
Yeah I was using dokku, in fact it was the image that Digital ocean provides.

**Comment by michaelshobbs** [comment]
Ok cool. So this looks like nodejs.org potentially being the issue in the buildpack. There was a recent patch that attempts to circumvent this recurring theme by grabbing node from their s3 repository.

You might try adding a `.env` file to the root of your repo with the following contents and deploying again. 

```
export BUILDPACK_URL=https://github.com/heroku/heroku-buildpack-nodejs
```

**Comment by josegonzalez** [comment]
@Trickierstinky Any luck with @michaelshobbs's suggestion?

**Comment by Trickierstinky** [comment]
Hi sorry for the delay I just quickly booted a droplet up managed to test this out and this worked for the node.js, I haven't tried republishing a rails one but at least the node.js one works now thanks.

I'm going to close this issue as i only really have a need for node applets now so this has manage to solve my issue.

Thanks a bunch guys!
