### ISSUE TITLE
Upgrading from 0.2.3 to latest

### ISSUE THREAD

**Issue by angusfretwell** [progrium/dokku#946]
This is for my own reference and for anyone who has similar issues. Perhaps some of these issues can be mitigating by changing the way the install scripts work.

When upgrading from 0.2.3 using [these instructions](http://progrium.viewdocs.io/dokku/upgrading) I get:

```
wget -qO /usr/local/bin/sshcommand https://raw.github.com/progrium/sshcommand/master/sshcommand
chmod +x /usr/local/bin/sshcommand
sshcommand create dokku /usr/local/bin/dokku
User 'dokku' already exists
wget -qO /tmp/pluginhook_0.1.0_amd64.deb https://s3.amazonaws.com/progrium-pluginhook/pluginhook_0.1.0_amd64.deb
dpkg -i /tmp/pluginhook_0.1.0_amd64.deb
(Reading database ... 88899 files and directories currently installed.)
Preparing to unpack .../tmp/pluginhook_0.1.0_amd64.deb ...
Unpacking pluginhook (0.1.0) over (0.1.0) ...
Setting up pluginhook (0.1.0) ...
lsmod | grep aufs || modprobe aufs || apt-get install -qq -y linux-image-extra-`uname -r` > /dev/null
aufs                  202783  2285 
apt-get install -qq -y curl
Setting up docker.io (1.0.1~dfsg1-0ubuntu1~ubuntu0.14.04.1) ...
addgroup: The group `docker' already exists and is not a system group. Exiting.
dpkg: error processing package docker.io (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 docker.io
E: Sub-process /usr/bin/dpkg returned an error code (1)
make: *** [docker] Error 100
```

I can fix this by running `delgroup docker`. The installer then appears to run fine but eventually cuts out with:

```
Start building buildstep
time="2015-02-05T00:39:37-05:00" level="fatal" msg="Error response from daemon: client and server don't have same version (client : 1.16, server: 1.12)" 
FATA[0005] Error: client and server don't have same version (client : 1.16, server: 1.12) 
make: *** [stack] Error 1
```

I can fix this by running `service docker restart`. The installer now completes, but after restarting docker all my apps have of course stopped, so I need to restart them with `dokku ps:restartall`.

Next up, I need to restart my database containers ([dokku-md-plugin](https://github.com/Kloadut/dokku-md-plugin)). I run `docker ps -a` to find the IDs of the stopped containers, and then run `docker start CONTAINER_ID` on each.

The process isn't too difficult, but it was a little confusing and took a bit of working out the first time I went through it.

**Comment by josegonzalez** [comment]
@michaelshobbs anything here you think we can document/fix in dokku? I'm thinking we could auto-restart docker before building buildstep at least.

**Comment by michaelshobbs** [comment]
That's odd because when updated docker the last time, it did restart the daemon....Perhaps the system was in an unknown state due to the first failure?

In fact, it's even stranger that the version that is attempting to be installed is 1.0.1. My guess is that the  master branch was updated in the directory where `git pull` was run but for whatever reason, the current state was on another branch or tag. Point being you didn't actually update. We can validate this by running the following:

```
root@dokku:~/dokku# docker version
Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 5bc2ff8
OS/Arch (client): linux/amd64
Server version: 1.4.1
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 5bc2ff8
```

and

```
root@dokku:~/dokku# dokku version
v0.3.14
```

I've seen this many times on IRC. I think we should probably update the git portion of the upgrade doc to ensure the user is on the correct tag or just have them use `bootstrap.sh` again.

**Comment by josegonzalez** [comment]
Docs now say you should run bootstrap.sh twice. It's a weird interaction between output redirection, ssh and bash, though moving to debian packages should assuage the issue going forward. Closing.
