### ISSUE TITLE
The old "pre-recieve hook declined" strikes back after updating Dokku to latest

### ISSUE THREAD

**Issue by angusfretwell** [progrium/dokku#947]
Not sure what's causing this guy. Have removed all third-party plugins.
https://gist.github.com/angusfretwell/c73208e056187594efcc

**Comment by michaelshobbs** [comment]
It looks like it's failing to fetch the custom buildpack. First, is this DO? If so, turn off IPv6. We've also seen folks have issues with DNS. So try the `resolvconf -u` trick from the troubleshooting docs. Sometimes rebooting the damn thing resolves whatever networking non sense is happening there. That's all in the case your on DO. 

If not, try downloading the buildpack url you're using from inside a container on that box. See if there is an error. There's reference steps in the troubleshooting docs if you need an example.

**Comment by petewwa** [comment]
Hello I am new to this projects. I have experimented with dokku in the past week extensively and have also encounter this issue. Firstly the buildpack detection mechanism seems to be far off from what I would expect. When pushing some laravel apps Dokku would take them as node.js. 

Only later I learned to use the dokku config set command
dokku config:set <app_name> BUILDPACK_URL=https://github.com/CHH/heroku-buildpack-php

Then later one other thing I noticed is that Dokku .env file where one can specify the BUILDPACK has a potential conflict with laravel 5 new .env files which are not meant to be git imported. Or am I wrong ?

**Comment by josegonzalez** [comment]
You didn't encounter the same error, you encountered a different error. You need a Procfile for PHP support, exactly the same as how heroku works.  See [this test](https://github.com/progrium/dokku/tree/master/tests/apps/php) app for an example.

All of our buildpacks are pretty much the heroku buildpacks. As for laravel .env files, you can always rename them to `.env.local` and then source the file in locally, which should have the same effect as having it named .env.

**Comment by michaelshobbs** [comment]
@angusfretwell did you get any resolution on this?

**Comment by stepri** [comment]
Same issue on a fresh install at Digital Ocean, no IPv6 enabled. Logs with ```dokku_trace=1```:
https://gist.github.com/stepri/9e28e9e21d01da0ffe2b

**Comment by michaelshobbs** [comment]
@stepri you seem to be having a different issue than the OP. Please open a new issue so we may track the resolution there. 

Thanks.

**Comment by angusfretwell** [comment]
@michaelshobbs, It started working for me after disabling the `build-env` and `checks` plugins. I haven't had a chance to look into it further yet, but I will do so at some point today.

**Comment by josegonzalez** [comment]
@angusfretwell any idea what the issue could be? Neither of those should cause issues if you:

- Don't have checks set
- Don't set invalid config

Maybe you had one or the other?

**Comment by josegonzalez** [comment]
Closing as there hasn't been feedback from op. Let us know if you found anything useful for debugging :)
