### ISSUE TITLE
Port 5000 not open

### ISSUE THREAD

**Issue by dallas** [progrium/dokku#948]
I'm having major trouble getting a Ghost app (an Express.js app running on node) to work on my dokku (version 0.3.13-88-g2dad1af) running on a Digital Ocean droplet. I've added the config variable to set `NODE_ENV=production` and the app logs tell me:

```
Ghost is running...
Your blog is now available on http://dallasandnicole.com
```

In the nginx `error.log` file I just see lines like this when I try to access the site:

```
2015/02/04 23:27:51 [error] 25746#0: *15 connect() failed (111: Connection refused) while connecting to upstream, client: 24.117.148.163, server: dallasandnicole.com, request: "GET / HTTP/1.1", upstream: "http://172.17.1.84:5000/", host: "www.dallasandnicole.com"
24.117.148.163 - - [05/Feb/2015:11:25:52 -0500] "GET /favicon.ico HTTP/1.1" 502 568 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.94 Safari/537.36"
```

I was quite frustrated and tried so many things at this point. I updated all my `apt-get` packages, I updated dokku, I rebooted my system, I repeatedly deleted and recreated the dokku app in question, I rebuilt its nginx config, I threw my hands up in the air and said a prayer.

Then I ran `nmap -p1-10000 172.17.1.84` (the port we're looking for is `5000`) and got these results:

```
Starting Nmap 6.40 ( http://nmap.org ) at 2015-02-04 23:57 EST
Nmap scan report for 172.17.1.84
Host is up (0.000023s latency).
All 10000 scanned ports on 172.17.1.84 are closed
MAC Address: 02:42:AC:11:01:54 (Unknown)

Nmap done: 1 IP address (1 host up) scanned in 3.70 seconds
```

When I ran the same thing on another node app I have successfully running using the [abhishekmunie/heroku-buildpack-static](https://github.com/abhishekmunie/heroku-buildpack-static) buildpack, I get:

```
Starting Nmap 6.40 ( http://nmap.org ) at 2015-02-04 23:58 EST
Nmap scan report for 172.17.0.185
Host is up (0.000024s latency).
Not shown: 9999 closed ports
PORT     STATE SERVICE
5000/tcp open  upnp
MAC Address: 02:42:AC:11:00:B9 (Unknown)

Nmap done: 1 IP address (1 host up) scanned in 3.38 seconds
```

So obviously it can work, so I'm not sure where the problem lays.

Running `dokku logs` for the app gives me nothing but smiles and rainbows:

```
> ghost@0.5.8 start /app
> node index

Migrations: Database initialisation required for version 003
Migrations: Creating tables...
Migrations: Creating table: posts
Migrations: Creating table: users
Migrations: Creating table: roles
Migrations: Creating table: roles_users
Migrations: Creating table: permissions
Migrations: Creating table: permissions_users
Migrations: Creating table: permissions_roles
Migrations: Creating table: permissions_apps
Migrations: Creating table: settings
Migrations: Creating table: tags
Migrations: Creating table: posts_tags
Migrations: Creating table: apps
Migrations: Creating table: app_settings
Migrations: Creating table: app_fields
Migrations: Creating table: clients
Migrations: Creating table: accesstokens
Migrations: Creating table: refreshtokens
Migrations: Populating fixtures
Migrations: Populating permissions
Migrations: Creating owner
Migrations: Populating default settings
Migrations: Complete
Ghost is running...
Your blog is now available on http://dallasandnicole.com
Ctrl+C to shut down
```
Which is the same output that I get if I run `docker logs` with the container ID stored in `/home/dokku/dallasandnicole.com/CONTAINER`.

And I'm sure that inside that box it is available at the Ghost default port (`2368`). Do I need to configure that port to point to something else? `80` for example? Can it not open up port `5000` on the Docker box if there's not actually anything running on whatever expected port inside the box?

I'm such a noob. Please forgive me for my ignorance. But I'm also rather frustrated and confused. Any help would be greatly appreciated. Thanks!

**Comment by michaelshobbs** [comment]
Yeah that was my original concern. I'm sure there is a way to make ghost bind to a different port. Check the docs and set it to 5000 and you should be good to go.

**Comment by dallas** [comment]
Oh  my word. If that works, I'm going to be blessing and cursing at the same time.

**Comment by dallas** [comment]
Okay, so I changed it to the Ghost `config.js` documentation suggested `process.env.PORT` and got the same no open ports and same `(111: Connection refused)` nginx error. I'm not sure how to check the ports that are open inside the box, maybe that would help debug this some, nor am I sure what `process.env.PORT` would be. 

Then I tried it with explicitly setting the port value to `"5000"`. Same exact outcome :cry: 

Then I tried setting it to port 80. I still get a `502 Bad Gateway` in my browser, but the nginx error logs give me a new error (progress?):

```
2015/02/05 12:44:44 [error] 11147#0: *307 connect() failed (113: No route to host) while connecting to upstream, client: 24.117.148.163, server: dallasandnicole.com, request: "GET / HTTP/1.1", upstream: "http://172.17.0.67:5000/", host: "dallasandnicole.com"
2015/02/05 12:44:47 [error] 11147#0: *307 connect() failed (113: No route to host) while connecting to upstream, client: 24.117.148.163, server: dallasandnicole.com, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.17.0.67:5000/favicon.ico", host: "dallasandnicole.com"
```

Or … maybe not progress. Looks like there was an actual error this time with booting up the Ghost app. `dokku logs` gives me:

```
ERROR: (Code: EACCES)
 There was an error starting your server.
 Please use the error code above to search for a solution.


npm ERR! ghost@0.5.8 start: `node index`
npm ERR! Exit status 255
npm ERR!
npm ERR! Failed at the ghost@0.5.8 start script.
npm ERR! This is most likely a problem with the ghost package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index
npm ERR! You can get their info via:
npm ERR!     npm owner ls ghost
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.0-39-generic
npm ERR! command "/app/vendor/node/bin/node" "/app/vendor/node/bin/npm" "start"
npm ERR! cwd /app
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /app/npm-debug.log
npm ERR! not ok code 0

> ghost@0.5.8 start /app
> node index

Migrations: Database initialisation required for version 003
Migrations: Creating tables...
Migrations: Creating table: posts
Migrations: Creating table: users
Migrations: Creating table: roles
Migrations: Creating table: roles_users
Migrations: Creating table: permissions
Migrations: Creating table: permissions_users
Migrations: Creating table: permissions_roles
Migrations: Creating table: permissions_apps
Migrations: Creating table: settings
Migrations: Creating table: tags
Migrations: Creating table: posts_tags
Migrations: Creating table: apps
Migrations: Creating table: app_settings
Migrations: Creating table: app_fields
Migrations: Creating table: clients
Migrations: Creating table: accesstokens
Migrations: Creating table: refreshtokens
Migrations: Populating fixtures
Migrations: Populating permissions
Migrations: Creating owner
Migrations: Populating default settings
Migrations: Complete
```

And trying to do an `nmap -p1-10000 $(cat /home/dokku/dallasandnicole.com/IP)` can't find it:

```
Starting Nmap 6.40 ( http://nmap.org ) at 2015-02-05 12:49 EST
Note: Host seems down. If it is really up, but blocking our ping probes, try -Pn
Nmap done: 1 IP address (0 hosts up) scanned in 0.62 seconds
```

So perhaps using port 80 isn't a good idea :stuck_out_tongue: 

What docs were you suggesting that I check? I'll put the port back to 5000 so we can be somewhat assured that the app is running on that `127.0.0.1:5000` inside of the box. I'm assuming that that should help with nginx trying to hit port 5000 on the box's IP and I'm assuming that Docker/dokku is all set up to just forward 5000 outside the box to 5000 inside the box. :fingers_crossed: :knock_on_wood: :smile:

**Comment by dallas** [comment]
Here is my Ghost `config.js` for whatever it is worth (the relevant bits, anyway):

```js
// # Ghost Configuration
// Setup your Ghost install for various environments
// Documentation can be found at http://support.ghost.org/config/

var path = require('path'),
    config;

config = {
    // ### Production
    // When running Ghost in the wild, use the production environment
    // Configure your URL and mail settings here
    production: {
        url: 'http://dallasandnicole.com',
        mail: {},
        database: {
            client: 'sqlite3',
            connection: {
                filename: path.join(__dirname, '/content/data/ghost.db')
            },
            debug: false
        },

        server: {
            // Host to be passed to node's `net.Server#listen()`
            host: '127.0.0.1',
            // Port to be passed to node's `net.Server#listen()`, for iisnode set this to `process.env.PORT`
            port: '80'
        }
    },
    // …
}
```

**Comment by michaelshobbs** [comment]
I believe you'll want to set the `host:` attribute to `0.0.0.0`

**Comment by dallas** [comment]
Alright, I will give that a shot. Thank you for sticking this out with me :smiley:

**Comment by dallas** [comment]
:tada: :smile: :laughing: 

You sir, are a gentleman and a scholar. 

THANK YOU!!

Now to go complain to some Ghost + dokku + Digital Ocean tutorial authors…

**Comment by michaelshobbs** [comment]
Glad to help.

**Comment by sebastiaandegeus** [comment]
How would this be done in Rails? i have the same error.

**Comment by dallas** [comment]
I think the preferred way to handle it is with a file named `Procfile` in the root of your rails app. In it you simply put the name of the process, `web` in this case, a colon `:`, and then the command to run to get the web server going:

    web: bundle exec rails server -p 5000

**Comment by chaseadamsio** [comment]
I know this is an old thread but the `0.0.0.0` recommendation also helped me on a `node` + `hapi` app. Thanks @michaelshobbs for the awesome protip.
