### ISSUE TITLE
Failed to push some refs

### ISSUE THREAD

**Issue by stepri** [progrium/dokku#958]
I can't push my code to the server, I receive the following error:
```! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'dokku@[IP ADDRESS]:socialwidgetco'```

See the complete logs here:
https://gist.github.com/stepri/9e28e9e21d01da0ffe2b

I run the server on Digital Ocean, IPv6 disabled

**Comment by michaelshobbs** [comment]
Can you confirm what version of dokku you're running? Also what plugins are you running?

`dokku version` and `dokku plugins` will yield this info.

**Comment by stepri** [comment]
Okay, I had some corrupted environment variables. It's working now, thanks for your help!
