### ISSUE TITLE
Consistent use of bash shebang

### ISSUE THREAD

**Issue by josegonzalez** [progrium/dokku#959]
Sometimes we use:

```shell
#!/usr/bin/env bash
```

And sometimes we use:

```shell
#!/bin/bash
```

I prefer the former, though we should at least stick to one convention throughout the codebase. I believe the tests use the latter, though there is at least one example of it's usage in the main codebase.

**Comment by michaelshobbs** [comment]
Agreed. I can make that PR in the morning unless you'd like to.

**Comment by josegonzalez** [comment]
Feel free to do so, I only noticed as I was going through the pluginhook docs I'm writing.
