### ISSUE TITLE
Installation instructions are a bit confusing

### ISSUE THREAD

**Issue by ineu** [progrium/dokku#961]
In README and http://progrium.viewdocs.io/dokku/installation it is proposed to run installation command this way:
```sh
$ wget -qO- https://raw.github.com/progrium/dokku/v0.3.14/bootstrap.sh | sudo DOKKU_TAG=v0.3.14 bash
```
Dollar sign and sudo shows that this command should be run as non-root user. At the same time it is proposed to install dokku on fresh ubuntu box, i.e. with no explicitly created users.
When I followed documentation first time, I've manually created user 'dokku' because of these considerations, and tried to run installation command as this user, which is definitely not correct. As whole script is fed to sudo, it is the same as running everything as root.
So I'd propose to either modify this line to
```
# wget -qO- https://raw.github.com/progrium/dokku/v0.3.14/bootstrap.sh | DOKKU_TAG=v0.3.14 bash
```
or explicitly specify under which user it should be run.
Thank you.

**Comment by josegonzalez** [comment]
You can/should run the command as whatever the existing user is. On Digital Ocean, that is just the `root` user, while on AWS that is the `ubuntu` user. The bootstrap script is meant to be run by the root user, so piping the script input to sudo is quite fine.

**Comment by ineu** [comment]
Then there shouldn't be `$` sign in the command, as by common convention it means non-root user.

**Comment by josegonzalez** [comment]
Running it as the root user doesn't break things. I run it as a non-root user - albeit one with sudo access - and that is quite fine. Was that not the case for you?

**Comment by ineu** [comment]
@josegonzalez I just had no non-root user directly after VPS setup, so was wondering if I should create some non-root user to run this command. Thank you for the commit!
