### ISSUE TITLE
Tail logs not working 

### ISSUE THREAD

**Issue by stepri** [progrium/dokku#963]
When I do ```dokku logs myapp -t``` I get the following output:
https://gist.github.com/stepri/25e057f96a84a1ef6f99

With ```DOKKU_TRACE=1``` https://gist.github.com/stepri/31085d4592d97b788654

Normal logs (without -t) are working.

Dokku version: v0.3.14
Dokku plugins: 
```/var/lib/dokku/plugins/00_dokku-standard/
/var/lib/dokku/plugins/apps/
/var/lib/dokku/plugins/backup/
/var/lib/dokku/plugins/build-env/
/var/lib/dokku/plugins/checks/
/var/lib/dokku/plugins/common/
/var/lib/dokku/plugins/config/
/var/lib/dokku/plugins/domains/
/var/lib/dokku/plugins/git/
/var/lib/dokku/plugins/nginx-vhosts/
/var/lib/dokku/plugins/ps/
```

**Comment by josegonzalez** [comment]
Are you running this over ssh?

**Comment by stepri** [comment]
Yes, I login to my server over ssh

**Comment by michaelshobbs** [comment]
Does it run locally?

**Comment by michaelshobbs** [comment]
Looks like this is due to the args parser...

**Comment by djelic** [comment]
It seems that -t flag is used ambiguously for tracing dokku and tailing logs.

**Comment by michaelshobbs** [comment]
@djelic good catch there. i forgot we already allowed short args in plugins. the commit referenced above only parses long args in the global namespace allowing short args to exist in plugins. it a bit naive yes, but it at least gets `logs -t` working now.

would love to see a better arg parsing implementation. i'll noodle on it but if anyone else wants to have a go, that'd be great!
