### ISSUE TITLE
Fresh install ubuntu 14.0.4 not working with nginx and app urls

### ISSUE THREAD

**Issue by sebastiaandegeus** [progrium/dokku#969]
Hello,

I've installed ubuntu 14.0.4 and installed dokku on it. So far I got the following working:
- can completely deploy a rails apps
- can use dokku, containers get created, nginx is running (welcome page)

But what doesn't work:
- apps are not available on subdomains
- nginx.conf are completely missing after a new app is pushed to the server
- url is wrong. It's myservername.colo.hostingcompany.net:4212
- /home/dokku/VHOST file is missing (what should be in here?  mydomain.com?
- /home/dokku/HOSTAME is `myservername.colo.hostingcompany.net`  is that correct?

I've tried to use the domains plugin to no avail. I only get the nginx welcome page on every domain and subdomain (I send the main domain and wildcard to the server IP)

I tried to add /home/dokku/VHOST and add this in it: `mydomain.com` 

When I deploy an app now the url will be: `http://mydomain.com` it completely ignores the appname for a subdomain. No matter how many times I destroy the container and try again. Server reboot doesn't help.

I'm lost :(

**Comment by josegonzalez** [comment]
How did you setup dokku?

**Comment by sebastiaandegeus** [comment]
I ran: `$ wget -qO- https://raw.github.com/progrium/dokku/v0.3.14/bootstrap.sh | sudo DOKKU_TAG=v0.3.14 bash`

I had to run it twice by the way because the first time there was no dokku user.

**Comment by josegonzalez** [comment]
And did you create a VHOST file in your `/home/dokku` directory?

What hosting provider are you on? If possible, you should be able to run the following bash commands to install on a fresh VM via debian packages: https://gist.github.com/josegonzalez/834b9e585b752e5b95f4

**Comment by sebastiaandegeus** [comment]
transip.nl

I still don't get it. dokku seems completely confused about the url. 

At the end I get:
```
=====> Application deployed:
       http://myappsdomain.com
```

Which should be `appname.myappsdomain.com`


I have a `/home/dokku/VHOST` that contains `myappsdomain.com`

(I masked the real name btw, but it's also a fully qualified .com domain pointing to the server)

**Comment by josegonzalez** [comment]
What about the contents of `/home/dokku/HOSTNAME`?

**Comment by sebastiaandegeus** [comment]
`boomer.colo.transip.net`

**Comment by asm89** [comment]
Can you gist the log of a push of a new app? (fresh name)

**Comment by sebastiaandegeus** [comment]
I think something is up with the version of ubuntu 14.04 that was installed on that VPS. I reinstalled everything completely and it's still broken.

Today I created a ubuntu 14.04 droplet on digital ocean and even though the HOSTNAME was `dokku` and the VHOST was missing I managed to add them and put my main domain inside both like so: `mydomain.com`

Then the app urls were actually starting to be correct. for instance: `http://sampleapp.mydomain.com`

Today I could not get through the deploys on the VPS because of some other pipe error or something. Weird. Because before the reinstall I could deploy successfully all the time. I will try to run everything with trace enabled and post the gist somewhere in the coming days.

**Comment by josegonzalez** [comment]
Closing as it appears you opened a separate issue for your issues in #972.

**Comment by sebastiaandegeus** [comment]
Sort of. I never managed to get this working on that VPS. I just moved over to digital ocean. And it also didn't work out of the box with the `HOSTNAME` and `VHOST` missing but the steps to create those manually fixed the problem on digital ocean but it did not fix in on the other VPS.

I think some of the standard resolving of `VHOST` and `HOSTNAME` is not working on ubuntu 14.04. I may be worth it to look into that or make a not in the docs about it.

**Comment by josegonzalez** [comment]
How didbyou install on DO?

**Comment by sebastiaandegeus** [comment]
By selecting the ubuntu 14.0.4 + dokku droplet.

**Comment by josegonzalez** [comment]
Interesting. I'll go through the install again tomorrow, but that should work just fine.
