### ISSUE TITLE
wildcard certificate

### ISSUE THREAD

**Issue by punund** [progrium/dokku#971]
If I have a wildcard certificate installed (*.example.com), I end up with

    listen 80;
    return 301 https://.*.example.com$request_uri;

in the nginx.conf, which is obviously wrong.

**Comment by michaelshobbs** [comment]
I'm having a difficult time recreating this. Can you post a `git push` with DOKKU_TRACE on?

**Comment by punund** [comment]
https://gist.github.com/punund/2ef95c7dc6ef6525fadd

**Comment by michaelshobbs** [comment]
What are the contents of `/home/dokku/www/VHOST`?

**Comment by punund** [comment]
Whatever I set it to, after deploy it becomes

    config.ly
    .*.config.ly

**Comment by michaelshobbs** [comment]
What version of dokku?

**Comment by punund** [comment]
0.3.13

**Comment by michaelshobbs** [comment]
Hrm. Ok I can't recreate this for whatever reason, but I do see where the potential issue is coming from. I have a PR (#975) open now.

Can you remove the errant line from `/home/dokku/www/VHOST` and test out the branch from the aforementioned PR?

**Comment by josegonzalez** [comment]
@punund The changes @michaelshobbs made are in master, can you upgrade to master and let us know if it works?

**Comment by josegonzalez** [comment]
@punund I'm closing this issue. I think @michaelshobbs fixed this. Feel free to comment if that's not the case.
