### ISSUE TITLE
Rails 4 nginx error. connection refused

### ISSUE THREAD

**Issue by sebastiaandegeus** [progrium/dokku#972]
```
2015/02/11 17:28:13 [error] 5619#0: *26 connect() failed (113: No route to host) while connecting to upstream, client: 82.204.98.143, server: pagetide.coderepeat.com, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.17.0.14:5000/favicon.ico", host: "pagetide.coderepeat.com"
```

deploy gist
https://gist.github.com/sebastiaandegeus/03121c478ed7dbe849a6

Procfile
```
web: bundle exec thin start -p $PORT -e $RACK_ENV
```

**Comment by sebastiaandegeus** [comment]
I did some more research. It seems the container is not running at all:
```dokku ps pagetide```

```FATA[0000] Error response from daemon: Container b24c46eb05a23d889f5af99d04ea8adfc38fc464e37417420fff9c81132ab756 is not running```

But restarting it gives no error. It looks like everything is in perfect order:

```
/home/dokku/pagetide# dokku ps:restart pagetide
-----> Releasing pagetide ...
-----> Release complete!
-----> Deploying pagetide ...
-----> Running pre-flight checks
       check-deploy: /home/dokku/pagetide/CHECKS not found. attempting to retrieve it from container ...
       CHECKS file not found in container. skipping checks.
-----> Running post-deploy
-----> Configuring pagetide.coderepeat.com...
-----> Creating http nginx.conf
-----> Running nginx-pre-reload
       Reloading nginx
-----> Shutting down old container in 60 seconds
=====> Application deployed:
       http://pagetide.coderepeat.com
```

**Comment by josegonzalez** [comment]
What happens if you do:

```
docker start -a CONTAINER_ID
```

Where the CONTAINER_ID is in the output of `docker ps -a`

**Comment by josegonzalez** [comment]
@sebastiaandegeus bump

**Comment by sebastiaandegeus** [comment]
I finally managed to resolve my issues. My Rails app was crashing but non of those errors bubbled back up to dokku. So dokku said everything was fine. The container itself was completely broken. I mounted my container and fixed the errors by checking the logs in there.

**Comment by josegonzalez** [comment]
Hmm okay. Yeah you can check that an app is running by using the `CHECKS` feature, which would have failed the deploy. 

Side-note, I wouldn't be surprised if your app also failed on heroku :)
