### ISSUE TITLE
dokku logs: follow conflicts with trace

### ISSUE THREAD

**Issue by jaysh** [progrium/dokku#990]
The `-t` flag is used for both following, and tracing:

    $ dokku logs --help
        logs <app> [-t]                                 Show the last logs for an application (-t follows)

    $ dokku --help
    Usage: dokku [-q|--quiet|-t|--trace|--rm-container|-rm] COMMAND <app> [command-specific-options]

I'm not sure what the best solution is. To me, it's more useful to be as similar to Heroku as possible, so perhaps dropping the `-t` tracing shortcut is easiest fix?

**Comment by josegonzalez** [comment]
What version of dokku are you running? This is fixed in 0.3.15 via [this](https://github.com/progrium/dokku/pull/964) PR.

**Comment by jaysh** [comment]
Indeed, I'm on v0.3.14.

I did search, but I probably should have checked I was on the latest before filing and issue anyway. Sorry about that.

**Comment by josegonzalez** [comment]
No worries! Let us know if you have any issues going forward.

**Comment by jaysh** [comment]
Shall do. `-t` works perfectly to follow the log stream in 0.3.15. Thanks!
