### ISSUE TITLE
Allow to take internal port from a Dockerfile

### ISSUE THREAD

**Issue by mahnunchik** [progrium/dokku#993]
Allow to take internal port from a Dockerfile.

if I'm not mistaken it should be here: https://github.com/progrium/dokku/blob/master/dokku#L73-L81

**Comment by josegonzalez** [comment]
We've traditionally made it so that the port is *always* 5000, though I can see why you might want to customize that for a dockerfile.

**Comment by mahnunchik** [comment]
Hi @josegonzalez 

It became necessary for me when I tried to run already dockerized application. It exposes not 5000 port.
Of course I could:
* to do some kind of proxy docker layer from 5000 to different port
* to change port of application

But it would be much easier if `dokku` could take already exposed port.

**Comment by vbauer** [comment]
:+1:

**Comment by michaelshobbs** [comment]
@mahnunchik @vbauer 

What are the expected outcomes here? When I deploy a Dockerfile with `EXPOSE 3000`, nginx still proxies correctly. 

Are you just looking for this when not deployed using nginx-vhosts?

**Comment by michaelshobbs** [comment]
Scratch that. My test app has this:

```
app.set('port', (process.env.PORT || 5000))
```

**Comment by michaelshobbs** [comment]
As a principle, I think the app should be modified to allow the deployment environment to tell it on what port to listen and include a sane default. This falls into line with the Heroku paas mentality.

**Comment by michaelshobbs** [comment]
Also, what do we do if a Dockerfile exposes multiple ports? Which one do we pick to proxy to?

**Comment by mahnunchik** [comment]
Hi @michaelshobbs 

My opinion:
* Heroku ideology is well suited for `normal` applications that are assembled from the source code on deploy.
* Dockerized applications are already built (image) or contain all the information to build themselves (Dockerfile)

We have two options:
* Specify in the documentation that all applications (including Dockerized) should take the PORT variable
* Make an assumption for Dockerized applications and read port from the image.

> Also, what do we do if a Dockerfile exposes multiple ports? 

I think we should pick first port (like it in Deis)

If we allow to take internal port from Dockerized app that we will give users ability to run already packed (maybe not their) applications without modification.

**Comment by michaelshobbs** [comment]
Good points. 

@josegonzalez any additional thoughts here?

**Comment by josegonzalez** [comment]
I would do the following:

- Highly suggest users take the PORT variable in all apps (buildstep/dockerfile)
- Highly suggest users use 5000 as something hardcoded if they need to hardcode in all apps (buildstep/dockerfile)
- Document that if they expose a port in a dockerfile, we will take the first port from the container, regardless of what port that is, and use that when proxying requests.

**Comment by mahnunchik** [comment]
@josegonzalez It will be great!

**Comment by michaelshobbs** [comment]
sounds good to me. i can work on this shortly
